### ISSUE TITLE
FFmpeg crash on channel switch

### ISSUE THREAD

**Issue by Logout22** [kodi-pvr/pvr.iptvsimple#106]
The crash happens with both 16.1 and 17.0 versions of Kodi and is easily reproducible: After two or three times switching the channel in full-screen mode, Kodi crashes with one of the attached core dumps.

[kodi_crashlog-16_1.txt](https://github.com/kodi-pvr/pvr.iptvsimple/files/744975/kodi_crashlog-16_1.txt)
[kodi_crashlog-17_0.txt](https://github.com/kodi-pvr/pvr.iptvsimple/files/744976/kodi_crashlog-17_0.txt)

**Comment by afedchin** [comment]
this isn't related to the addon itself. please create a ticket on http://trac.kodi.tv/
