### ISSUE TITLE
settings.xml - UTC Offset slider doesn't cover full range of possible UTC offsets

### ISSUE THREAD

**Issue by themitchnz** [kodi-pvr/pvr.iptvsimple#107]
Currently using the addon settings slider we can adjust UTC offset between -12 and +12. Wikipedia states the range as -12 to +14 https://en.wikipedia.org/wiki/List_of_UTC_time_offsets

Hopefully an easy fix?

(I'm in New Zealand which is currently +13 due to daylight savings)

**Comment by phunkyfish** [comment]
In #269

**Comment by phunkyfish** [comment]
And #275
