### ISSUE TITLE
build for kodi 15.2

### ISSUE THREAD

**Issue by kapralVV** [kodi-pvr/pvr.iptvsimple#109]
Hi, 

Could you please help me to build the add-on for kodi-15.2 . 
The instruction from master branch works , but add-on cannot be loaded , seems due to this dep: 
addon="xbmc.pvr" version="... (xbmc.pvr 1.9.6 is installed on kodi 15.2) 
I did 
`git checkout origin/Isengard `
And could not found the useful instruction for kodi-15.2
Please assist

**Comment by Jalle19** [comment]
I think it's best if you search the forum for some old guide or tutorial. This version hasn't been supported for some time so the best course of action would be to update to at least 16.0.

**Comment by kapralVV** [comment]
Oh, I've just found the way how to compile the plug-in. 
Just for history , maybe help someone: 
```
# git clone https://github.com/xbmc/xbmc.git
# # Checkout to 15.2
# git clone https://github.com/kodi-pvr/pvr.iptvsimple.git
## Checkout to 15.2
# cd pvr.iptvsimple && mkdir build && cd build
# cmake -DADDONS_TO_BUILD=pvr.iptvsimple -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/project/cmake/addons
# make
# mv ../../xbmc/addons/pvr.iptvsimple/ /usr/share/kodi/addons/
```
Thanks. Closing
