### ISSUE TITLE
Need assistance

### ISSUE THREAD

**Issue by ykamchi** [kodi-pvr/pvr.iptvsimple#115]
Hi,

I wonder if it is possible to query the pvr information, like url from the addon?

If it is, can you please share a code example of how to get a list of channels with information like: channel name, URL, icon etc. 

... after searching, I managed to find the channels, but how do I get the URL that it runs, can someone someone assist?

Here is my code:

ret = json.loads(xbmc.executeJSONRPC('{"jsonrpc": "2.0", "id": 1, "method": "PVR.GetChannelGroups", "params":{"channeltype":"tv"} }'))
channelgroups = ret['result']['channelgroups']
for channelgroup in channelgroups:
#Get Channels
ret = json.loads(xbmc.executeJSONRPC('{"jsonrpc": "2.0", "id": 1, "method": "PVR.GetChannels", "params":{"channelgroupid" : ' + str(channelgroup['channelgroupid']) + '} }'))
channels = ret['result']['channels']
for channel in channels:
#Get Channel Details
ret = json.loads(xbmc.executeJSONRPC('{"jsonrpc": "2.0", "id": 1, "method": "PVR.GetChannelDetails", "params":{"channelid" : ' + str(channel['channelid']) + '} }'))
utils.write_log('service', str(ret))Confused
(This post was last modified: 2017-03-15 16:03 by ykamchi.)
PM FIND

**Comment by afedchin** [comment]
please use https://forum.kodi.tv for assistance.

**Comment by ykamchi** [comment]
Thx,
Yohay


On Mar 21, 2017, at 12:16, Anton Fedchin <notifications@github.com> wrote:

Closed #115.

**Comment by ykamchi** [comment]
Well,  I did try, but I guess no one know the answer there since there is no reply for a week or more.

Please assist me


Thx,
Yohay


On Mar 21, 2017, at 12:16, Anton Fedchin <notifications@github.com> wrote:

Closed #115.
