### ISSUE TITLE
M3U playlist download interval

### ISSUE THREAD

**Issue by mcallegari** [kodi-pvr/pvr.iptvsimple#116]
Hi, I have a usage case where there is an IP streamer that exposes a M3U playlist that can change in time.

It would be fantastic if there was an option in the addon configuration page, where I can set an interval (in minutes would be OK) to periodically download the playlist at the provided URL.

Also, I noticed that when a playlist changes, Kodi doesn't do a "full" update (meaning: clean and write again), but instead it performs a "merge" with the previous channel list. So if a channel gets removed from a playlist, it remains forever in Kodi, as if it was still there. I need to manually reset the channel list and start over.
Don't know if this can be handled by the simple iptv addon or if it's in the Kodi guts.

Well, thanks in advance !

**Comment by dbowles1975** [comment]
I could definitely use this as well.

**Comment by dbowles1975** [comment]
I found a workaround for the dynamic m3u8 issue. I posted instructions here:

https://www.reddit.com/r/kodi/comments/67vd6e/restart_pvr_on_schedule/

**Comment by AgileHumor** [comment]
Please add a refresh of M3U stream URL's and XMLTV guide. Thanks!!

**Comment by vasildev** [comment]
I need this too.

**Comment by phunkyfish** [comment]
I will add this to Matrix version of the addon.

**Comment by phunkyfish** [comment]
The channel cleanup is already fixed in matrix but only when settings are changed.

**Comment by phunkyfish** [comment]
Added in: https://github.com/kodi-pvr/pvr.iptvsimple/pull/281
