### ISSUE TITLE
Playing YouTube Live streams

### ISSUE THREAD

**Issue by noquierouser** [kodi-pvr/pvr.iptvsimple#124]
I'm building a custom list based on many different TV channels that have open streams available to the public, but I'm seeing many of them are moving into YouTube or Facebook Live. So far, **I have no interest** in Facebook Live streams, as they don't seem to provide HLS URLs, or any endpoint to access Facebook Live streams outside of Facebook.

In the other hand, YouTube Streams **do provide** HLS URLs and API endpoints to get them, and are quite accesible to get, at least using a bit of code and regexp. But there's a catch: playlists URI change over time, so it isn't reliable to get the playlist URL manually. I've been trying to make a solution based on PHP and a web server, but the redirection to the HLS playlist doesn't seem to work. Testing manually in mplayer and VLC throws a HTTP 403 error.

So, I think maybe YouTube support might be in this side of the fence, where the plugin should retrieve the playlist file based on the YouTube's video data, and play that. So far, I know of some players that allegedly support YouTube videos in IPTV playlists, but I don't know how do they implement this.

**Comment by back-to** [comment]
@noquierouser 
you can get 360p hls streams from **facebook** with
`https://www.facebook.com/video/playback/playlist.m3u8?v=VIDEO_ID`

example
`https://www.facebook.com/rtlnieuws/videos/10156515475969852/`
url for kodi
`https://www.facebook.com/video/playback/playlist.m3u8?v=10156515475969852`

---

for **youtube**, you could use this addon [primaeval/plugin.video.pvr.plugin.player](https://github.com/primaeval/plugin.video.pvr.plugin.player)

it will allow you to use plugin links in your playlist

example
`https://www.youtube.com/watch?v=K59KKnIbIaM`
url for kodi
`http://localhost:60666/?plugin://plugin.video.youtube/?action=play_video&videoid=K59KKnIbIaM`

**Comment by naijaping** [comment]
@back-to , just to let you know that your suggestion for playing Facebook live video in Kodi has stopped working this week.  may be something has changed. any hint will be appreciated.

thanks

**Comment by Jalle19** [comment]
Closing this one since there's not much that can be done at the moment. The plugin URL workaround sounds like your best option for now.
