### ISSUE TITLE
import m3u_plus format stop when tvg-logo is wrong

### ISSUE THREAD

**Issue by badgeling** [kodi-pvr/pvr.iptvsimple#132]
A wrong format from m3u export (from my provider). I got something like 

tvg-logo="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxASEhUQERIVFRUXFR4XGBcYFRkVFhgVGR4WIBoXGRcYHCkgJBolHRUdITMiJSktLjouIx8zODMtNygtMSsBCgoKDg0OGxAQGi0lHyYtLS0tKy0wLS0tLS8tLy0tLS0tLS0rLS0tLS0tLS0tLS4tLS0tLS0tLS0tLS8tLS0tLf/AABEIAGAAoAMBEQACEQEDEQH/xAAcAAABBAMBAAAAAAAAAAAAAAAHAAEFBgIDCAT/xABLEAACAQMBBQMECwwJBQAAAAABAgMABBESBQYHITETQVEiYXGBCBcyNFR0kZKhstEUFkJiZXKTlKSzw+MjQ1JTVXOCsdMVJDWDwf/EABsBAAEFAQEAAAAAAAAAAAAAAAABAgMEBgUH/8QAOxEAAQMCAwQGBwcEAwAAAAAAAQACAwQRBSExEhNBUQYyYXGRwSI0U3KBseIUFRYzoaLRQ2OS4UJi8P/aAAwDAQACEQMRAD8AONCExpChVPeXiHs6yJSSbXIP6uMa2yO488A+kiulS4TU1IuxthzOSY6RoVKueOkYYiOxZl7i04Rj6VEbAfKa7DOi7relKL9gv5hR77sT2vHSMsBLYsq95SYSN81kUfTQ/ou8D0ZQT2i3mUb7sV43a392dfEJDNiQ/wBW40PnwAPI+omuLVYXU02b25cxmP8AXxUjZGuVoBqgnp6EJUITGkQqnvJxE2bZEpJNrkGcxxjW2R3E9AfSRXSpcKqakXa2w5nJMdI0Kl3fHSINiKxdl8XmEbfNVGH012I+i77elIL91/MfJR77sW3ZPGnt54oPuHT2sqR6vunOnWwXOOy54z0qOp6ObmJ0m8vYXtb6kolubWRaFZpTKu7yb77PsTpnmGv+7Ty39YHT11dpcNqKnONuXM6JpeAqJe8c4Q2IbJ3XHV5VjOfzVVx9NduPoxIR6cgB7AT+pIUW+7FoHHb8n/tP8mn/AIXPtf2/Ujf9itGw+LWzLg6WZ4Gzy7VQFP8AqUkfLiubUYDVwi4AcOz/AGntlaVeopFYBlIZSMgg5BHiCO6uMQQbEKRbKELCRwASSABzJPIADxPhQBnkhAbiPxQknZraxcpAOTSDk8v5p6hPpNbLCcEaxu9nHpcBy/2qz5L5BC/NaZRJUqEqEJUmuqEWOG/FJ42W1v3LxHkszHLIe4Oe9fxuo8/dl8WwMEGWnGfEcPgpmScCjkDWOVhOaEIK8W+Ijh32fZvpC+TNKp8ot3xqR0A7z6uWOeswTCA5onm+A81BJJwCDxNa1QJqVClt0/f1p8ai/eJVLEfVZPdPyTmdYIs8WOI7ws1hZNhxyllB5rn8BPxvE93p6ZnBsHEo30wy4Dn2lSvksLBBN3JJJJJPMk8ySepJrYhoAsoFjTkJqEJxSFCuG4e/txs5wvOS3J8uLwz1ZCejd+Oh83WuTimEx1Y2hk/gf5T2PLV0nYXsc0aTRMGR1DKw6EGvP3scxxa4WIVsG6GXHPehoYUsIjhpgTIfCIcguPxjn1A+PLQdH6ASyGV2jdO9QyutkgSTW2VdNSoSoQlQhKhCcGkQugOCW9LXNu1pKcyW4Gknq0R5L61Ix6NNYXHqEQS7xgyd81ZidcWV83gvvue2mn744mYekA4+muNBHvJWs5lSE2C5EdyTkkknmSeZJPUk+NeosaGiwVJY09CVCFvsrlopElTkyOHU+DKQQflFRyxtlYWO0KAbLXJIWJZiSSckk5JJ6knxp7WhosELGlQmoQlQhKkQnzRZCM3APeEntdnuRgDtYvHr/SL9Ib51ZDpHSBrhOOORU8LuCofE7aPb7TuWzkK/ZL5hHyI+cDXawaHdUje3NRyG5VVrq6JiQo0uhF/cvg+k0K3F9I66wGWKPAIU8xrYg8yO4AY8aytd0iLHlkABtxPkFM2K4uVo364SLbwtdWcjuqDU8b4LaR1ZWAHQdxHjz7qdh/SAyyCOcDPQjzQ+KwuEJ61A0uFClSoV04QX5h2pAB0k1Rt6CCR9KiuNjsO3SOPLNPjNijdxQl07LuvPHj5SKx+FC9XH3qw/qrl016SqaahKtkMTOwRQSzEKAOpJOAB5yTTHvDGlx0CArJvjuXNs1IDO6F5g50Lk6NGjOWPU+X3eFc6hxSOse4MBsOJT3MLdVV66iYnpEK78NdwjtNneR2jhjIDFQCzsQfJUnkMciSQeo8eXGxbFvsdmtF3Hwsnxx7Ste93B6GG3eezmkLRqXZJNJDKoydLKBggAnnn1Vy6PpG98oZM0WPEXyUjobDJB01rQbqBNSoVt4V3hi2pbHVpDMUPnDKRj1nFcjG49ujebaZp8Zs5RO9qkX13n4TL9dqs4b6ozuCR/WUTV4pqR6U12bULsSwvI5okmjbUjqGUjvB6V5VIxzHFrtQrwzWjbt9HDbyzSkaEjYtnvGDy9fSpKeN0kjWt1JSO0XIVeoN0AVJKnE2QrBw/iZtpWgXr2yn1DmfoFc/FSG0b78k5mqLXHXb8cdqLJWzLKwJAPNY0IOT6TgY9PhWX6P0bpJ96dB81NK4WsgLW4VdNSoVv4T2nabUtweYUlz/pU4+kg1yMbk2aR3anxj0ldfZFe6sfRN/ArjdGOtJ8PNSTcEG62CgT0IR89j+P+wm+NH6kVYbpH6y33fMqzD1UTXXIIPPlXABsVKuNhXqrOqFRTU9Clt0vf1p8ai/eJVLEfVZPdPyTmaq0caNkmDaTyc9M6iQHuyAFYfKo+WudgFQJKUMOrcvNOlFiqFXeUaVIhWbdjfu/sFMcEgMZOdDrqUHvK+GfNXOrMKpqo7Ujc+YyTmvI0WG9G+99fgLcSeQOYjQaUz4kd59NLSYXTUpvG3Pmcyhzy7VVwmuimpUIW61unjYSRuyOOjKSrDPLkRzHI0x8bXizwCDzzRosJpWYlmJZickkkknxJPfStaGizRYIWFOQmoQinwB2bru5rgjlFEFB/GkP2IazHSWYCJsfEm6lhGd1IeyK91Zeib+BVbox1pPh5p03BBytgoE4oQj77H/3hN8Zb6kVYbpH60Pd8yrMXVRONZ9SLjMV6uzqjuVJKnIUtul7+tPjUX7xKpYj6rJ7p+SczULoXibuj/wBRtdKY7ePLxE95ONSZ8GAHrArC4VXmkm2j1TkVZkbtBc0TRlSVYEMCQQRggjqCD0INeitcHAEG6qaLXTkJUISoQlQhbrS2eV1jjUs7HSqjmST0AqOSRsbS9xsAgC6lt7932sJxbO2pxGjN4BmGSB5hVSgrftbDIBYXsE5zbKDq+mp6ELKOMsQqgkkgAAZJJ6AAd5prnBrdp2QQun+G+7P/AE+ySJsdq/8ASS/nnHk58wGK84xOs+1Tl400HcrbG2CoHsivdWXom/gV2ujHWk+Hmo5uCDla9QJxQhH32P8A7wm+Mt9SKsN0j9aHu+ZVmLqonGs+pFxmK9XZ1R3KklTkKW3S9/WnxqL94lUsR9Vk90/JOZqF1qa8yVxULiFw3h2hmeIiK4x7rHkyY6BwO/8AGrs4Zi8lJ6Ds2/LuUb49pAreHdm7sm03MLJzwGxmNvzXHI9OnWtrS10FS28Tr9nL4KsWkaqHq4kSFCFObubp3t82LaEsucGQ+TGPSx5eoZNUarEIKUXkdny4pWtJ0R44f8O4NnDtXIluCOcmMKg/soP/AL1Pm6VisSxaSsOyMm8v5VlkeyhPxs/8o/8Alp/sa0nR31X4qKXVUOu92KJSGxtiXN2/Z20LyN36RyH5zdB6zVeoqoYG3kcAlAJ0Ry4c8MksiLm6KyXH4IHNIvHB728/d3VjMVxo1Q3ceTP1P8KwyK2ZRJFcJSoLeyK91Zeib+BWq6MdaT4eagmQcrXqBOKEI++x/wDeE3xlvqRVhukfrQ93zKsxdVE41n1IuMxXq7OqO5UkqchS26Xv60+NRfvEqliPqsnun5JzNQuts15mriRpChYyIGBVgCD1BGQR5xSg2NxqhQV3uXsyQ5ezhJ8yBfq4q4zEapgs2Qj4ppY3kns9zNmxHKWcAPnQN9bNJJiFVILOkJ+KAxo4KcRQBgDAHcOQqmTc3Kcss0IUHtPdLZ9zIZp7aORyACzAk4HQVbhrqiFuxG8gJpYDqmtNzdmxnKWcA/8AWG/3pX4hVPFnSO8UbDeSmoY1QBVAUDoAAAPUKqlxJzOacs80iEqRCjNsbv2l1pNzAkujOnWM6dWM49OkfJU8FTLB+U4juTS0HVR33h7J+AwfMqz961ntXeKTYbyT/eHsn4DB8yj71rPaHxRsN5KU2Tse3tVMdtEsSltRVRgFuQz6cAVVnqJZnbUji49qcABoveahSqtjcPZPwGD5tXxilYP6h8U3dt5JfeHsr4DB8yl+9az2p8Um7byWcG5OzEZZEs4VZWDKwXmGByCPOCKZJiVU8bLpDYpQxo4IOcStq3dxtZrITsiCWOGNQ7KgLafKYA9cuefhWpwqGCCi35bc2JPw5eCgeSXWUt7UG1Ph0fz5fsqE9IaT2R/RLunc1L7q8Ptr2Vwky30bJqHaIWlIdM8xgjGrBOD41TrsVo6mIs3RB4HLLwTmxuB1Vk4l7H2hdQxLs+UxushLkSmLK6SMZXrzPSqGE1FNBITOLi3K6dICdEP/ALxt5/hkn67J9td370wn2Y/wCi3b+aht6dl7e2fEs1zeTaGfQCt1Ix1EE8+fTyat0k+HVTtiOMX1zaAkc17dUWtwd4pZtlLeXB1OiSFj0Ldlq5nzkLWUxClZFWOiZpcfqp2klt0FrO72vti5KJNIznL6RI0cSL5gDgDnjxrYPjosOhBc0eFyVX9JxU77We3/AO+H6y1VPvrDh/x/aE7dPUVsTeHaWy75YZ5ZCFkCSxO5dCrEZK5JA5HIIqeppKStpjJG0aZECyRpLXWKMPEvY20LmGJNnytG6yEuRK0WV0kYyvXn3VlsKqKaGQmobcWyyBU0jSdEPvvG3n+GSfrsn213vvPCfZj/AACj2HqG3o2Xt+wiE9xeTaC4QabuRjqIJGRnp5NWaSpw2qfsRxi9uLQE1wc3Uor7i7Vub7ZHaO2ZykkYYHSSy6lVsjoenMVlq+GOnrC1vVBCnYSWobXm6u8sUbyvdTBUUs2LxycKMn8LzVo2V+FOIaGC/uBQ7DwoPdg7a2g7x215cFkXU2q6kXkTjvartZ9gpADLG3P/AKj+E1u0dEWeF+w9qWzTnaMjuGCdnqmMuCC+rGScdRWWxaopJtn7M0DnZoHyU8bXDVDTejad3tLaz2qztEvbmCNWkIjXQSucDvYr4Z5gVoKKOGkoRMW3NrnLPNQvuXWU97UG1Ph0fz5fsqt+IaT2R8Anbp3NT+5m4m1rG4WU3qSRZxJFqkIZT3gMpGodc+qufiOJ0dVFsiMh3A2H8pzY3A6rDfnhvbXl21yt9HA7AdojKr5YDGr3akcsciKdhmMTU0Ij3ZcOBFx5FD4wTqq97TkX+Kw/ox/y1fHSF4H5B8fpTd12qpz20mydpRrDOsxjZDqjOA6tjVGQCeo5Y510N43EKNxewt7/AJ8Ey2y5FzjPt+6sreB7WUxM0xViApyuknHlA94rNYFSw1EzmytuLKaVxAyQ/wBmbc3ouIxNA80iHowSLBxyP4NdyWmwiJxY8NB73KIOeVq2xsrea9QRXMU0ihtQUiNRqAIzkY7iadBUYTTO24iAfiUEPOqKmwd35LLY0lq5DSCCYtp5jU4c6Qe/GcZrLVVSKms3rdCQpwLNshXwU21b215J90SLGJIdCsxwurUpwT3ZxWmx+nkmgaY23sbnwUMRAOaOrbwWXwq3/TJ9tY77LP7N3gVY2hzXPG/20YrvazSQNrQvGqkdGI0jl5snFbnDonwUVpMiqzjd2SK/Gfb91Z28MlrKYmaYqxAU5XSTjyge8VnMCpYaiVzZW3FlLKSBkqBs3be9NxGJoHmdD0YJFg4/013JabCInbDwARwu7+VEC8qH3zutuGJE2l2vZl8rqVAusA96DrgnkfP4VaoI6APJpbbVuBOnxKRxdxRq4UJbjZkIt2dl8okuArdpqOsYBIHPzmsdi5kNW7eDNWI7WU1vZ7yuvi8n1TVSm/Ob3hOdohD7Hr3zc/5K/WFanpL+Uzv8lBDqjniserCFG+PDS2u7qS5S/jhLnLxlVbDjkSCJB1x0x1z41pcPxmWCERGIuA0P/gVC6ME3uoT2nYv8Vh/Rj/lq9+IXn+gfH6U3c9qrGxY32dtmKGGZZNNwkRdPcukhQMMA+DdMnmKu1cjaugdI5tsibcrJrRsusitvrwqgv5zcpO0EjY1+QJFbAxnGpSG6d+OXSs3h2OSUse7LdocM7H5KV8Qcbqu+0T+UP2b+dXR/FH9r930pu47VKbt8HIra4juJbozdmwdUEXZDWpypJ1tkAjOBj01UrekL6iIxtjDb8b38gnNhsb3Vp383OXacUcTTGLs315Chs8iMcyPGudh2IGjeXht7juT3s2l79z93xYWqWiyGQIWOorpJ1EnoCfGoayqNTMZSLXQ1uyLKaxVVOTMKRCFW2eCdvLIXt7loFJJ0GMSqM9ynWpC+Y5rSU3SSWNmzIzaPO9vIqEwg6FR/tFflD9m/nVZ/FP8Aa/d9KTc9qnN1OEVtaTLcTTtcOjakHZiNAR0JXUxLA8xzA81Ua3H5aiMxtaGg68T5JzYrG6sW/m567TijieUxaH15Chs8iMcyPGqOHYgaN5eG3unPaHZL37pbBWxtUtVkMgTPlEaScknoD56grKk1MrpbWvwStbsiy8e/m6S7TgSBpTEEkEmQobJCsMYJH9qpcPrjRyGQNvcWSPZtL07m7ujZ9qtqshkCszaiuk+UScYBPjUddVGqmMpFr9qVrbCyktq2fbQywE6e0jZM4zjUCM49dV437Dg7knEXVT3B4epsuSSVbhpe0QJgoExg5zyY108RxU1rWtLbW7UxjNlXY1yU9DXe7hHBeTtcxXBgZzl17MSIW5cwNSkE9TzNd+hx6Smj3bm7QGmdvIqJ0QJuoP2ifyh+zfzqvfij+z+76U3c9qmt0+EUNncLcy3BnKHUi9l2ahv7R8ts46jpzqlXdIH1MZiazZvrnfyCc2Kxuv/Z"

but kodi stop import @ this line

**Comment by badgeling** [comment]
in fact if some off value had more than 3991 char it's break 

But why 3991 char

**Comment by Jalle19** [comment]
The code assumes that no line is longer than 4000 characters or something like that, that's why it breaks here.

**Comment by johanson** [comment]
> no line is longer than 4000 characters

Is there a reason for it?

**Comment by Jalle19** [comment]
https://github.com/kodi-pvr/pvr.iptvsimple/pull/133 would remove the line length limit

**Comment by Jalle19** [comment]
Fixed in master
