### ISSUE TITLE
Switching channels only works using EPG

### ISSUE THREAD

**Issue by erikdrenth** [kodi-pvr/pvr.iptvsimple#134]
I'm using your great plugin with a m3u of Dutch public stations. When switching channels using the guide, all is fine. When I'm switching using the channels OSD or channels up/down buttons, the image stands still, though sound is fine.

I've tested this on Kodi 17.3 on Android TV and Windows with the same m3u. As the streams I am using require a temporary token, the streams are loaded via a Raspberry Pi that runs a homemade script to redirect to a working url: https://bitbucket.org/erikdrenth/npocumulusstreams

Hope you can help!

**Comment by Jalle19** [comment]
This sounds like a bug in Kodi, not in this addon. If you're still having this issue you can open a ticket on trac.kodi.tv.
