### ISSUE TITLE
tvg-id casesensitive

### ISSUE THREAD

**Issue by sinned130** [kodi-pvr/pvr.iptvsimple#135]
Some .m3u files has the "tvg-id" tag written in uppercase like "tvg-ID". Please make it possible to use both. All IPTV Projects that are managed with the xtream-codes cms system version 2 will generate m3u files with "tvg-ID" so in future many will have that problem.

sorry for bad language not my main language.

**Comment by Jalle19** [comment]
Shouldn't whatever system out there that generates these invalid tags be updated instead?

**Comment by sinned130** [comment]
Yes of course it should but they wont do it. i asked allready the support of xtream codes. So for a programmer its nothing to make a if statement and this will fix the problem too AND makes PVR Simple Client more compatible now is the request not so big but in few month :).

**Comment by Jalle19** [comment]
I can't seem to reproduce this. I tried all combinations of upper/lower case and the guide data still loads just fine.
