### ISSUE TITLE
Mini Guide bug if selected during playback

### ISSUE THREAD

**Issue by newbie1235** [kodi-pvr/pvr.iptvsimple#154]
Hello,

I have noticed an issue with the guide if the mini guide option is selected during playback.

the guide goes blank, no XMLTV EPG info, times or channel logos.

It is a great feature within the Add-On and a bug is causing it, it seems to go back to normal after a while (around 90 - 120 minutes later), but then i press guide on the player and its blank again, I havent had time to check out the source code but i wanted to let you know.

Thank you.

**Comment by Jalle19** [comment]
The addon has nothing to do with how the EPG is displayed in Kodi, you should open a ticket on trac.kodi.tv instead.

@ksooo right?

**Comment by ksooo** [comment]
> @ksooo right?

 Right. Although I have no idea what the "mini guide option" is. Which Kodi version? Which skin? How (step-by-step) do I activate the "mini guide option"? ...

**Comment by Jalle19** [comment]
@ksooo I think he means the OSD guide window
