### ISSUE TITLE
when iptv stream stops simply client could crash PC

### ISSUE THREAD

**Issue by NiekN** [kodi-pvr/pvr.iptvsimple#159]
when i watch IPTV , them i  have almoste ones a day,  a system crash
It looks like it is caused by a stream that stops, when server is overloaded
Normal it should not be a problem that teh stream stops , it should recover automatically . 
But in my case, when this happons , stream stops ans will not recover automatically. i can do 1 or 2 clicks and then system hangs . .  Could this be a Addon problem

**Comment by afedchin** [comment]
It's not an issue if the addon. Seems it's related to Kodi VideoPlayer.
