### ISSUE TITLE
Limited bandwith fixes

### ISSUE THREAD

**Issue by vk496** [kodi-pvr/pvr.iptvsimple#160]
Hello,

Would be nice to have some config parameters for people who have limited Internet speed.

Things like adjust the buffer size when playing some channel. 

Also, in Kodi, when the play bar reach the end of the buffer, the channel exit. VLC has the option "loop mode" to avoid that, but there's no way to do that on IPTVsimple.

Salu2

**Comment by Jalle19** [comment]
You should be able to control some buffer settings from Kodi. Either way the addon has no control over any of this so there's nothing we can do here.
