### ISSUE TITLE
Support plugin:// URLs

### ISSUE THREAD

**Issue by dh4rry** [kodi-pvr/pvr.iptvsimple#161]
There are a lot of kodi video-plugins (written in python) which provide Live-Streams. 
It would be very nice if we could simply add something like "plugin://plugin.video.xyz?play=livestream" to a m3u playlist and iptvsimple would play it.
I know there workarounds/hacks (e.g. running a http-server which is called by iptvsimple which redirects to the korrekt URL). But that dosen't work for more complex cases with inputstream-mpd.

**Comment by afedchin** [comment]
It's not possible without a huge VideoPlayer changes.

**Comment by michaelarnauts** [comment]
@a1rwulf is this still the case, or are there changes made in the meantime to support this?

**Comment by michaelarnauts** [comment]
@afedchin  is this still the case, or are there changes made in the meantime to support this?

**Comment by phunkyfish** [comment]
I know users do this with the YouTube plugin. Have you tried it?

**Comment by michaelarnauts** [comment]
I've noticed that it might be possible after all. This seems to be an addon that does this: https://github.com/snoopyjoe/service.psvue.epg/blob/master/resources/lib/globals.py#L130

I haven't tested this, but I will now :)

**Comment by phunkyfish** [comment]
I think this may work without that addon.

**Comment by phunkyfish** [comment]
Example:

```
#EXTM3U

#EXTINF:-1 tvg-logo="https://i.ytimg.com/vi/_82sV2LQP6g/maxresdefault.jpg",Relaxing Sleep Music
plugin://plugin.video.youtube/play/?video_id=_82sV2LQP6g
```

**Comment by michaelarnauts** [comment]
Thanks @phunkyfish this actually works just fine!

**Comment by phunkyfish** [comment]
Excellent, you're welcome.
