### ISSUE TITLE
Multiple epg sources...[Suggestion]

### ISSUE THREAD

**Issue by murrayf** [kodi-pvr/pvr.iptvsimple#162]
Hello,

I'd like you to implement multiple epg guide sources in the addon epg section option. 
Could it be possible?

Thanks, and congratulations for iptvsimple.
Alberto.
:)

**Comment by matthuisman** [comment]
@murrayf 

There is already a pull request for this:
https://github.com/kodi-pvr/pvr.iptvsimple/pull/52

That add's multiple playlists and EPG sources.

**Comment by murrayf** [comment]
Thanx.

**Comment by MCTyler** [comment]
Year and 1/2 Later...Abandoned?

**Comment by murrayf** [comment]
You can close it if you want.

**Comment by murrayf** [comment]
I'd like to see this feature in the official iptvsimple addon, but it's 
only a suggestion. Yes it's true, a year ago I tried this fork without 
sucess. It's not vital for me that's why I told you to close the issue.
-- Alberto --
