### ISSUE TITLE
Suggestion - Perform case insensitive search of markers and attributes

### ISSUE THREAD

**Issue by Shtutnik** [kodi-pvr/pvr.iptvsimple#164]
Hi,
Could you consider changing this line:

> std::string PVRIptvData::ReadMarkerValue(std::string &strLine, const char* strMarkerName)
> {
>   int iMarkerStart = (int) strLine.find(strMarkerName); <==
>   if (iMarkerStart >= 0)
>   { ...

 https://github.com/kodi-pvr/pvr.iptvsimple/blob/master/src/PVRIptvData.cpp#L1106 so that the function will perform a case insensitive search instead? 
Also, maybe consider changing all of the `xml_node` calls (such as `xml_node::first_node`) to use `case_sensitive=false` instead of using the default value of `case_sensitive=true`
 (see http://rapidxml.sourceforge.net/manual.html)

I think it will make the addon even more user friendly and flexible :)

**Comment by phunkyfish** [comment]
Why?

You don't give any examples.

**Comment by Shtutnik** [comment]
@phunkyfish Some time has passed since, but if I remember correctly, I ran upon an iptv xml that was generated incorrectly in terms of case sensitivity. I think it was the 'id' or the 'name' of the channel that was problematic. 
In general, don't you think that the addon should not be strict regarding case sensitivity of keys and elements?

**Comment by phunkyfish** [comment]
There is a DTD for the XML which explicitly specifies the format and case for a valid file. So in the case of the XML I don't think case insensitivity is required.

Case insensitive searching is more expensive than normal searching so why have the overhead if it's not required?

The only instance I have seen is the use of tvg-ID instead of tvg-id in M3U files. I've explicitly added that case but unless users have raised multiple instances with examples of this happening its probably not worth the engineering or performance overhead.

**Comment by Shtutnik** [comment]
Could you kindly refer me to the DTD?

Regarding performance - Case sensitivity searches can be performed in a very efficient way since the difference between the cases is a single bit. Also, I don't think that performance is at all an issue here. There are some examples of inefficiency in the existing code which is a sign that performance on operations with strings isn't a main concern. As such, case insensitive searching wouldn't impose any new performance issues, IMO.

I just wanted to point out that since this addon is a core addon then I think that it would be better to make it as user friendly as possible to minimize non-tech user frustration. Even if there is a DTD, why assume that each and every application will follow it? What is the real cost of supporting both upper and lower case, despite the DTD? An example for this logic can be seen in implementation differences between browsers. In some cases the RFC is very strict and yet in the specific implementation, a different approach is sometimes chosen to favor wider support of external components. 

Of course, this is all just my opinion and you can just discard it all :) No harm done.

**Comment by phunkyfish** [comment]
http://wiki.xmltv.org/index.php/XMLTVFormat

https://github.com/XMLTV/xmltv/blob/master/xmltv.dtd

**Comment by phunkyfish** [comment]
I don't think this should cause any further issues since the recent changes. If you notice any new cases just open a new issue. Ty
