### ISSUE TITLE
end of buffer 

### ISSUE THREAD

**Issue by NiekN** [kodi-pvr/pvr.iptvsimple#165]
This weekend i heb testen kodi again with IPTV
I had totally of 8 times a frozen image(in 4 soccer games), i think buffer empty (server problem)
I used Aeon Nox skin , and i cannot see what  the buffer does(no hourglass, nothing)

The video player kills the stream  between 10 and 20 sec.  
After that i can startup again the stream. If i start the stream directly after the image is forzen , it will crash kodi.
- Is there a way i can set the stream, on continue when the buffer will fill again, so the stream will continue automatically
- or is there a way if buffer is empty, that it will kill directly the videostream(parameter)
- or is there a way i can seen on the screen the buffer status? or when it will kill teh videostream ?

**Comment by afedchin** [comment]
the issue isn't related to the add-on. please visit Kodi forum and try to find a solution.
