### ISSUE TITLE
Kodi Log

### ISSUE THREAD

**Issue by willbrow** [kodi-pvr/pvr.iptvsimple#166]
Hi

In my kodi log i am seeing that often pvr.iotvsimple is downloading epg and this is causing issues when i am playing back video causig buffeeing.

Is there anyway to reduce how often the epg is uodated or to prevent this from happening when playback is happening.Can this be done in settingw.xml ?

I have tried changing in kodi livetv settings but the changes are not taking effect.

Thanks

**Comment by afedchin** [comment]
The add-on downloads EPG only when Kodi PVR manager requests data. Kodi settings must affects on EPG request frequency.

> Is there anyway to reduce how often the epg is uodated or to prevent this from happening when playback is happening.Can this be done in settingw.xml ?

enable caching of EPG in add-on settings. If a source of EPG supports `Last-Modified` header it will work. You can also try to play with settings in as.xml, see http://kodi.wiki/view/Advancedsettings.xml#epg

Please move the conversation to the forum https://forum.kodi.tv/
