### ISSUE TITLE
Ubuntu/Kodi17/pvr-iptvsimple not show on addons

### ISSUE THREAD

**Issue by Grabasimo** [kodi-pvr/pvr.iptvsimple#168]
Hi
I have instaled kodi and iptvsimpleclient on ubuntu 17.10. This addon didn't show on setings/myaddons/Pvr clinet.

How to enable this package 

>sudo apt install kodi-pvr-iptvsimple 
kodi-pvr-iptvsimple is already the newest version (2.4.14-1~artful)

thanks

**Comment by afedchin** [comment]
please ask the question at the forum https://forum.kodi.tv
