### ISSUE TITLE
BIG crash when the tvg-logo is a data:image

### ISSUE THREAD

**Issue by gordielachance** [kodi-pvr/pvr.iptvsimple#173]
Hi !
I'm trying to make the plugin work but it makes KODI crash on startup.  BIG crash :)
I had to disable WIFI to be able to run KODI again, because it keeps crashing each time it starts.

From what I see, it seems that it is related to the tgv-logo in the m3u file, which is a data:image.

**Disabling channel logos does not help**, I guess it crashes when the m3u file is parsed on startup.

Could you fix this ?

Thanks !

> #8  0x00007fb7052d8714 in ___vsprintf_chk (s=0x7fb6c6dc9e90 "Read line: '#EXTINF:-1 tvg-ID=\"\" tvg-name=\"Maya Koningin Voor Een Dag\" tvg-logo=\"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxISEhUSExMVFhUXFxgWGBgYGBcVGBoYGB8XFxUaGBcYHSggGBolHRcXITEh"..., flags=1, slen=16384, format=0x7fb6ac3ee0ab "Read line: '%s'", args=0x7fb6c6dc9e70) at vsprintf_chk.c:82

**Comment by gordielachance** [comment]
Seems weird but if I change the m3u url from **&type=m3u_plus** to **&type=m3u** (as suggested [here](https://forum.kodi.tv/showthread.php?tid=323312&pid=2686211#pid2686211)), it doesn't crash anymore (altough I don't have any channel logo)

**Comment by afedchin** [comment]
inline encoded logos are not supported.

**Comment by gordielachance** [comment]
Ok, but then they should be ignored instead of crashing KODI.
Users don't always have control on the input feed sent to the plugin...

**Comment by Jalle19** [comment]
Can you post the full crashlog to pastebin and link it here?

**Comment by gordielachance** [comment]
[kodi_crashlog-20180102_232353.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/1604454/kodi_crashlog-20180102_232353.log)

Not mine, but same problem

**Comment by Jalle19** [comment]
Seems to be this line that crashes: https://github.com/kodi-pvr/pvr.iptvsimple/blob/master/src/PVRIptvData.cpp#L340.

Why people make playlists containing features that aren't supported is completely beyond me though.

**Comment by a-reda** [comment]
> Why people make playlists containing features that aren't supported is completely beyond me though.

These playlists are provided by third parties, and are intended to work on multiple devices (that may support inline encoded logo)

**Comment by Jalle19** [comment]
Well, if they want to make playlists that work with this plugin they should stick to supported features.

**Comment by a-reda** [comment]
As @gordielachance  said, they should be at least ignored.

**Comment by Jalle19** [comment]
Someone would have to make a pull request, I don't have time to work on this.

**Comment by palinek** [comment]
From the logs/backtraces there seems to be only problem with the log/debug print. The solution should be trivial... I can make PR for it.
