### ISSUE TITLE
Colors for xml categories [Feature Request]

### ISSUE THREAD

**Issue by Netuddki** [kodi-pvr/pvr.iptvsimple#176]
Is it possible to get a feature, where we can read category items from xml files and assign different colors to them?

That would be cool.

**Comment by jangeador** [comment]
I saw this on the change log but I dont know what it means "map xmltv genre to Kodi genre via genres.xml" where is genres.xml

**Comment by Netuddki** [comment]
I don't know how one would use a separate genres.xml
What I meant was reading the category tag from the EPG'S XMLTV file.

<category lang="fr">Jeu</category>

**Comment by phunkyfish** [comment]
This is supported in the Matrix version of the addon.
