### ISSUE TITLE
HTTP headers not passed on to FFmpeg demux

### ISSUE THREAD

**Issue by bocki** [kodi-pvr/pvr.iptvsimple#177]
Starting with Leia, at least in builds dating back to [December 6](https://forum.kodi.tv/showthread.php?tid=325139), HTTP headers specified in the M3U playlist are correctly set for cURL. However, they are not picked up by the FFmpeg demux.

Loading the M3U via Files in Kodi the behaviour is as expected.

Log output from regular M3U loading:
```
VideoPlayer::OpenFile: https://foobar|X-Forwarded-For=foo.bar
CurlFile::ParseAndCorrectUrl() adding custom header option 'X-Forwarded-For: foo.bar'
CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput() adding custom header option 'X-Forwarded-For:foo.bar'
```

Log output using PVR iptvsimple:
``` 
AddOnLog: PVR IPTV Simple Client: Read line: ' https://foobar|X-Forwarded-For=foo.bar'
AddOnLog: PVR IPTV Simple Client: Found URL: 'https://foobar|X-Forwarded-For=foo.bar' (current channel name: 'Foo Bar')
CurlFile::ParseAndCorrectUrl() adding custom header option 'X-Forwarded-For: foo.bar'
```

This leads to being able to read a m3u8 playlist, for example, but not picking up the individual segments.

Any help would be appreciated :)

**Comment by afedchin** [comment]
this issue isn't related to the addon. please create a ticket at trac.kodi.tv
