### ISSUE TITLE
browse/store epg history for 4 days

### ISSUE THREAD

**Issue by paprastavisai** [kodi-pvr/pvr.iptvsimple#179]
Hi, it's possible change settings to browse epg history for 4 days.
Now is only show 1 day back

**Comment by Jalle19** [comment]
You can change how many days Kodi shows in Kodi itself. Obviously this also depends on how much data your EPG source has, i.e. if it only has one day of data then that's all you're going to get.

**Comment by paprastavisai** [comment]
yes I can change how many days in future show.
I my epg.xml is minus 4 days from today and plus 4 in futurebut in guide view I can see only minus 1 day.

maybe exists trigger for removing older epg data when updating

**Comment by Jalle19** [comment]
Google for "kodi epg lingertime", I think there's an advancedsetting for this.

**Comment by paprastavisai** [comment]
Thanks

**Comment by ksooo** [comment]
It's an advanced setting in v17 and before and a regular setting in v18.
