### ISSUE TITLE
Add recording support and live stream pause

### ISSUE THREAD

**Issue by omribahumi** [kodi-pvr/pvr.iptvsimple#18]
This feature is really missing. Any chance it could be implemented?

**Comment by decryptedchaos** [comment]
I Second this.  

I use the addon with a custom slingbox setup,  and need each client to be able to record independently

**Comment by afedchin** [comment]
this requires a backend, the addon has no backend, ie. there is no way to implement this.

**Comment by omribahumi** [comment]
@afedchin is there an equivalent addon that has a software backend?
Perhaps a software backend (a daemon running alongside with kodi, pretty much like Pulsar is working) is suitable here as well?

**Comment by mariofenech** [comment]
@decryptedchaos  How did you manage to view your slingbox with pvr iptvsimple?
