### ISSUE TITLE
Drop off to menu, when channel is not found

### ISSUE THREAD

**Issue by anshlv** [kodi-pvr/pvr.iptvsimple#181]
When I switch channels in the playlist sequentially (not by selecting from the list. I need this "dumb" behavior for an elderly person), and one of channels is not available, PVR drops either to Kodi's main menu or to the channel list. Is it possible to rather show a picture or message - "Channel is not available" and let the user switch to the next, available one? This is also critical, when there is an Internet connection drop off - which requires someone to manually restore the playing channel, instead of just auto-retrying.

**Comment by afedchin** [comment]
It's just not possible in the add-on.
