### ISSUE TITLE
Logos not downloading from remote peer

### ISSUE THREAD

**Issue by maughanorama** [kodi-pvr/pvr.iptvsimple#184]
so as a for instance 
 ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://example.com/tvlogos/BBC2 HD

im assuming this is because of the space in the name, is there a way of adding " " to the string ?

**Comment by palinek** [comment]
> im assuming this is because of the space in the name, is there a way of adding " " to the string ?

Why isn't it URL encoded? [wiki](https://en.wikipedia.org/wiki/Percent-encoding)

**Comment by phunkyfish** [comment]
Addressed in #269

**Comment by phunkyfish** [comment]
And #275
