### ISSUE TITLE
Kodi 18 Leia - PVR client broken using TVHeadend

### ISSUE THREAD

**Issue by msj33** [kodi-pvr/pvr.iptvsimple#185]
Latest Kodi 18 Alpha2 Nightly breaks the PVR functionality in KODI.

Using TVHeadend as backend ends in a HTTP 405 error using in PVR IPTV Simple Client version 3.4.3

20:44:30.915 T:13472  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/All channels/pvr.iptvsimple_1921639412.pvr
20:44:30.915 T:988  NOTICE: Creating InputStream
20:44:34.715 T:988   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 405
20:44:34.715 T:988   ERROR: CCurlFile::Open failed with code 405 for http://USERNAME:PASSWORD@x.x.x.x:9981/stream/channelname/channel1:
20:44:38.762 T:988   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 405
20:44:38.762 T:988   ERROR: CCurlFile::Open failed with code 405 for http://USERNAME:PASSWORD@x.x.x.x:9981/stream/channelname/channel1:
20:44:38.762 T:988   ERROR: XFILE::CFileCache::Open - failed to open source <http://USERNAME:PASSWORD@x.x.x.x:9981/stream/channelname/channel1>
20:44:38.762 T:988   ERROR: CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/All channels/pvr.iptvsimple_1921639412.pvr]
20:44:38.762 T:988  NOTICE: CVideoPlayer::OnExit()

Playlist entry:
#EXTM3U
#EXTINF:-1,DR1
http://USERNAME:PASSWORD@x.x.x.x:9981/stream/channelname/channel1

Works perfectly in Kodi 17.6 - But have no clue if root cause is KODI or PVR client

**Comment by phunkyfish** [comment]
Closing as I assume this was fixed before Leia release. If not please reopen.
