### ISSUE TITLE
IPTV Radio Streams not launching via remote in Kodi 18

### ISSUE THREAD

**Issue by drspy00** [kodi-pvr/pvr.iptvsimple#192]
Audio Streams not launching by kodi remote, have tried multiple remotes. They play when launched from kodi screen, or flicked through as channels, and DVB audio Radio channels work by launching from remote aswell as IPTV TV channels and DVB channels with NextPVR addon launched from the remote apps. The problem does not exist in earlier versions of Kodi so I am unsure if this is an issue with Kodi 18, or something with IPTV simple Client.

**Comment by phunkyfish** [comment]
Have you raised this issue against the remote repo (either android or iOS)???

**Comment by drspy00** [comment]
Hi, this was reported over a year ago, Issue no longer apparent.

**Comment by phunkyfish** [comment]
Great, thanks for responding.
