### ISSUE TITLE
ignore order of tvg-chno tag - request

### ISSUE THREAD

**Issue by Netuddki** [kodi-pvr/pvr.iptvsimple#193]
It would be cool if there would be an option where you could ignore the tvg-chno tag's order.

I would like to number my channels 1 and 2 and I want to display 2 first and then 1.

In the current version the channels will be ordered by channel number if there is a tvg-chno tag, not by the order of the channel list in the m3u.

**Comment by palinek** [comment]
Shouldn't this be changeable in Kodi's settings? (Settings -> PVR & Live TV -> General -> Channel Manager)

**Comment by Netuddki** [comment]
Actually you are right.
I didn't think of that.
However if you used an m3u editor where you can sort the channels in a custom order and then you have to do it again, just because Simple Client ignores the channel order in the m3u file, it is very frustrating. And if you have hundreds of channels to reorder, it's even more frustrating.

It is namely so: if you switch on the option "use channel order from backend" then the order of the channels in the m3u file will sort your channels in Simple Client.
If you have tvg-chno tags, then those tags will determine the order.
Why does it have to be either this or that, why can't it be both?

You could add an option "sort by tvg-chno" beside the "use channel order from backend" option.

**Comment by phunkyfish** [comment]
This would need to be added to the addon. The backed setting you are referring to is kodi core so we can't change that for the purpose of this addon.

**Comment by phunkyfish** [comment]
Are you using channel groups @Netuddki?

Do you want the numbers to be as you set but the order they appear in the groups to be the order from the M3U?

**Comment by Netuddki** [comment]
> Do you want the numbers to be as you set but the order they appear in the groups to be the order from the M3U?

Yes. and yes.
My channels are in groups, but it doesn't matter actually.
Numbers should be displayed as they are set in tvg-chno but the order of channels should be based on the list inside the m3u file.

If the channel is the third row in the m3u file, then it should be displayed as the 3rd channel in KODI, even if the channel number is 50.

**Comment by phunkyfish** [comment]
I see the problem. If you open up the left bars there are 3 options to sort by:

Name, Number and Last played

There is no sort option for original order. So it’s an issue in kodi and not the addon. I created a bug for it: https://github.com/xbmc/xbmc/issues/16546

**Comment by Netuddki** [comment]
Cool!

**Comment by hoshsadiq** [comment]
@Netuddki I've got an [m3ufilter](https://github.com/hoshsadiq/m3ufilter) application. If you don't mind running a small application on a raspberry pi or similar, feel free to raise it as a feature request and I'd be happy to implement it.

**Comment by Netuddki** [comment]
@hoshsadiq Thank you, but I am not sure if that would help.
Actually I am running a website with an online m3u editor myself (http://iptv-epg.com) and our users and I can do all the things we want with an m3u file, but no matter what we do, KODI simply displays it wrongly.

This request was made over a year ago. Since then we developed our own IPTV app where all the things work how they should work.

I actually don't use KODI anymore for IPTV.

**Comment by phunkyfish** [comment]
This has been added to kodi Matrix.

**Comment by Netuddki** [comment]
Cool! Thank you!

**Comment by phunkyfish** [comment]
There is now a 4th sort option for 'Backend order' in the left nav on the
channels and guide UIs on Matrix.

**Comment by phunkyfish** [comment]
Implemented in: https://github.com/xbmc/xbmc/pull/16558 and #275
