### ISSUE TITLE
EPG data not shown if Kodi is configured to Play TV on startup

### ISSUE THREAD

**Issue by alexheinz** [kodi-pvr/pvr.iptvsimple#194]
Hello,

I use the option to download an .XML file with EPG data.

I have installed pvr.iptvsimple and changed the Kodi configuration:

Settings/Interface - Startup: Perform on startup: Play TV
Settings/Interface - Startup: Startup window: TV channels

The problem is that the EPG data is not shown unless I stop the stream once. After stopping the stream, the .xml file is downloaded and I do see the EPG data.

Is this a bug of pvr.iptvsimple?
Is there a way to work around this behavior (except deactivating "Play TV" on startup)?

Thank you for your help!

information about my setup:
Raspberry Pi 3 running the latest milhouse builld, see [https://forum.kodi.tv/showthread.php?tid=298461](url)

**Comment by Alecto28** [comment]
I had the same problem, you must allow kodi to update Guide during playback.
Go to Settings - PVR & Live TV - Guide, then turn off "Prevent updates during playback"

Regards!

**Comment by alexheinz** [comment]
Thank you very much!
