### ISSUE TITLE
Epg not loading because of tvg-id

### ISSUE THREAD

**Issue by Alecto28** [kodi-pvr/pvr.iptvsimple#195]
Hello,

when trying to use an .xml epg file iptvsimple looks for "tvg-id", but most m3u providers only make lists with "tvg-ID".
The fact that this comes in uppercase letters makes it so that iptvsimple can´t read the label.

I tried to manually change the uppercase "ID" to lowercase "id" and immediately iptvsimple loads the epg.
the problem is that I can only make it work by downloading and editing the .m3u file, so I lose all channel updates.

I saw this post about the same issue:

https://github.com/kodi-pvr/pvr.iptvsimple/issues/135

in the last post, "jalle19" says he can´t reproduce the issue, but the problem happens to me too.

Is it possible to make iptvsimple read the "tvg-ID" tag?

Regards.

**Comment by tiagoagre** [comment]
I also have this issue.

Tried different kodi versions, all have the same problem.

When m3u comes with "tvg-ID", it wont parse the EPG. Like @Alecto28 said, changing "tvg-ID" to "tvg-id" directly on the m3u will solve the issue.

Looking on the source code, something simple like this, will work?

```
#define TVG_INFO_ID_MARKER      "tvg-id="
#define TVG_INFO_ID_MARKER_UPPERCASE      "tvg-ID="
```

```
strTvgId      = ReadMarkerValue(strInfoLine, TVG_INFO_ID_MARKER);
strTvgID      = ReadMarkerValue(strInfoLine, TVG_INFO_ID_MARKER_UPPERCASE);	

```
```
        if (strTvgId.empty())
        {
			if(!strTvgID.empty())
			{
				strTvgId = strTvgID;
			}
			else
			{
	                      char buff[255];
			      sprintf(buff, "%d", atoi(strInfoLine.c_str()));
			      strTvgId.append(buff);			
			}
        }
```

**Comment by Znuff** [comment]
Could probably be fixed by a `tolower()` or a `transform()` on the string/line before looking for the value.

**Comment by phunkyfish** [comment]
Case sensitivity is fixed in #269

**Comment by phunkyfish** [comment]
And #275

**Comment by aydnyldrm** [comment]
Hi
I still got the problem exist PVR IPTV simple Client version 3.8.7 and  Kodi 18.5

**Comment by phunkyfish** [comment]
Please give example M3U and XMLTV data where this is not working. Please also supply a full debug log.

**Comment by phunkyfish** [comment]
Actually, no need, this is a bug.

**Comment by phunkyfish** [comment]
PR: https://github.com/kodi-pvr/pvr.iptvsimple/pull/316
