### ISSUE TITLE
SAT>IP Stream Support: [rtsp] method DESCRIBE failed: 404 Not Found

### ISSUE THREAD

**Issue by Cybolord** [kodi-pvr/pvr.iptvsimple#196]
Dear Dev Team,

spent a lot of time in trying to use IPTV Simple Addon for Kodi 17.6 to connect to a Panasonic SAT>IP TV Server via M3U playlist in this format:

```
#EXTM3U
#EXTINF:0,1. Das Erste HD
rtsp://sat.ip:554?src=1&freq=11491.77&pol=h&msys=dvbs2&mtype=8psk&ro=0.35&plts=off&sr=22000&fec=23

```

Kodi Logfile offers:
```
16:46:53.006 T:1906307840 ERROR: ffmpeg[719FF300]: [rtsp] method DESCRIBE failed: 404 Not Found
16:46:53.007 T:1906307840 DEBUG: Error, could not open file rtsp://192.168.100.146/?src=1&freq=11494&pol=h&ro=0.35&msys=dvbs2&mtype=8psk&plts=on&sr=22000&fec=23&pids=0,17,18,5100,5101,5102,5104
16:46:53.007 T:1906307840 ERROR: OpenDemuxStream - Error creating demuxer
```

...meanwhile I found out via Wireshark that the used method could be the culprit in here:

IPTV Simple Client Request:
-------------
**OPTIONS** rtsp://sat.ip:554/?src=1&fe=1&freq=11494&pol=h&msys=dvbs2&mtype=8psk&ro=0.35&plts=on&sr=22000&fec=23&pids=0,17,18,5100,5101,5102,5104 RTSP/1.0\r\n
**DESCRIBE** rtsp://sat.ip:554/?src=1&fe=1&freq=11494&pol=h&msys=dvbs2&mtype=8psk&ro=0.35&plts=on&sr=22000&fec=23&pids=0,17,18,5100,5101,5102,5104 RTSP/1.0\r\n
...404 not found

e.g. VLC or DVB Viewer Request:
------------
**SETUP** rtsp://sat.ip:554/?src=1&fe=1&freq=11494&pol=h&msys=dvbs2&mtype=8psk&ro=0.35&plts=on&sr=22000&fec=23&pids=0,17,18,5100,5101,5102,5104 RTSP/1.0\r\n
**PLAY** rtsp://sat.ip:554/stream=14 RTSP/1.0\r\n
...Stream started

Thank you very much for your assistance.

Kind Regards,
Paule

**Comment by palinek** [comment]
The IPTV Simple doesn't handle the stream URLs anyhow. It just forwards the URL to Kodi, see:
- for `Krypton` (17.*): https://github.com/kodi-pvr/pvr.iptvsimple/blob/2.4.14-Krypton/src/PVRIptvData.cpp#L474 and https://github.com/kodi-pvr/pvr.iptvsimple/blob/2.4.14-Krypton/src/PVRIptvData.cpp#L592
- for `Leia` (18.*): https://github.com/kodi-pvr/pvr.iptvsimple/blob/master/src/client.cpp#L347

... so for finding a solution to your problem, you need to report/contact Kodi core devs.

**Comment by phunkyfish** [comment]
Closing as from v17

**Comment by tmm1** [comment]
@Cybolord did you find any solution?
