### ISSUE TITLE
PLAYLIST_TYPE_MARKER    "#EXT-X-PLAYLIST-TYPE:"

### ISSUE THREAD

**Issue by gregoir3** [kodi-pvr/pvr.iptvsimple#197]
I saw this being added in the code. I think this should make it possible to pause a VOD movie or series. Question is; how do I apply this in the m3u file? I added it on the top of the file but with no results.

**Comment by phunkyfish** [comment]
Duplicate of the better phrased #273

**Comment by gregoir3** [comment]
I forgot about this. It's been a year now. But thanks for reminding me. Do you want me to close this topic?

**Comment by phunkyfish** [comment]
Yes please. We can use the other issue to track.

**Comment by gregoir3** [comment]
Issue closed.
Track at #273
