### ISSUE TITLE
EPG download every 5 minutes

### ISSUE THREAD

**Issue by lama18** [kodi-pvr/pvr.iptvsimple#202]
I have EPG data on my own server and I do not understand why Kodi (IPTV simple) downloads a TVXML file that contains data for 3 days ahead every 5 minutes and twice in a row?

Log in attachment:
![hfghfg](https://user-images.githubusercontent.com/20426629/47439621-fcc64880-d7ac-11e8-8cfa-51814d6ee2e2.png)

**Comment by lama18** [comment]
![image](https://user-images.githubusercontent.com/20426629/50059059-6ac23700-0182-11e9-8a35-5bfa28c6100d.png)

Some news? RC3 is still the same, so it's probably a addon thing.

**Comment by AnonTester** [comment]
Somewhat related to this, I also noticed this addon trying to load the EPG file extremely frequently, even though I set the update interval to a high level.
This is on the current Kodi 18.1RC1 nightly of 4/Feb/2019.
IPTV Simple addon v3.5.7

In my case, I do not have an EPG URL configured. Apart from the high frequency of the updates, if nothing is configured, there should be a single warning when the plugin and channels get initialised and then the EPG update check should be skipped as it will not automagically appear when checking over and over again.

Log entries showing the frequency:
.kodi/temp/kodi.log:17:44:53.816 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:17:49:53.874 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:17:54:53.943 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:17:59:54.000 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:18:04:54.055 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:18:59:54.629 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:19:04:54.704 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:19:09:54.754 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:19:14:54.810 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:19:19:54.863 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:19:24:54.924 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:19:29:54.979 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:20:04:54.361 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:20:19:54.519 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:20:24:54.568 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:20:29:54.615 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:20:34:54.673 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:20:39:54.734 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:20:44:54.794 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:20:49:54.847 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:21:04:54.011 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:21:29:54.279 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:21:49:54.497 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:21:54:54.551 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:21:59:54.602 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:22:04:54.658 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:22:09:54.719 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:22:19:54.822 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:22:24:54.871 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
.kodi/temp/kodi.log:22:29:54.918 T:140384285185792  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.

**Comment by afedchin** [comment]
the addon downloads EGP by request from Kodi, if Kodi requests it every 5 min then the addon will do it every 5 min there is nothing to fix in addon's code base

**Comment by wombat01** [comment]
React from https://forum.kodi.tv/showthread.php?tid=340357&pid=2818268#pid2818268

Probably it's really a bug in PVR IPTV Simple

**Comment by ksooo** [comment]
I did not say it’s a bug. It works as it is, but implementation has potential for optimization as it wastes network resources.

BTW: do you have an idea what “simple” in “pvr.iptvsimple” stands for?

**Comment by wombat01** [comment]
Simple, unnamed, unnecessarily burdening the network and resources.

**Comment by ksooo** [comment]
@lama18 Go ahead, come up with fix!

**Comment by wombat01** [comment]
yes, we are currently working on the way it works and it would be good to get the best solution.

**Comment by ksooo** [comment]
C'mon if you really feel this needs to be fixed, come up with a fix. For me, this is not more than a glitch - no high priority, really. I'm not even using pvr.iptvsimple. Why should I invest my free time to deal with something I don't even need? I feel I have already invested to much time into this and therefore for me this discussion ends at this point.
