### ISSUE TITLE
Suggest -> Take some info from http

### ISSUE THREAD

**Issue by macamba** [kodi-pvr/pvr.iptvsimple#203]
Hi all,

I'll try to explain my case, I can access to the epg from my internet provider (Spain - Movistar), they send data epg by multicast (channel_id, title, episode, series_id, starttime, endtime, genre) but the rest info can be taken by server http one by one program (synopsys,  director, actors, country, year...). If I take the second information by http server to do the xmltv I would subject the servers of my provider to a lot of load (so crazy, non-viable).

To avoid it the only solution I see is that the addon only requests the second group information when I put my cursor over the program then the addon get the information in this moment by attribute src "http://program_id.txt" which contains synopsys,  director, actors, country, year...

I hope to have explained and as you see this possibility that would give much dynamism

Thanks

**Comment by Jalle19** [comment]
This not possible with the current architecture.
