### ISSUE TITLE
Xbox One Kodi 18 Beta 4 Breaks IPTV Simple Client

### ISSUE THREAD

**Issue by themodfatherinc** [kodi-pvr/pvr.iptvsimple#204]
after auto updating to Beta 4, the IPTV Simple Client addon has totally disappeared from the PVR Clients section. Apparently its a known issue with no timeframe for a fix on the kodi end (have to wait for the next update as of now) I'm wondering if there's a way to manually add it to the xbox build at this point as I rely on this wonderful addon for all my live tv viewing and am pretty bummed i cant watch tv anymore haha

**Comment by i3boy** [comment]
anyone know a workaround or even a temporary replacement for Simple Client until this is fixed? i need  to watch tv again dammit!

**Comment by ksooo** [comment]
dammit, no.

**Comment by AlMa18** [comment]
For me it’s working

**Comment by felipeng** [comment]
Exactly same problem here
