### ISSUE TITLE
Kodi Xbox - "tvg-ID" tag is case sensitive

### ISSUE THREAD

**Issue by sergiolepore** [kodi-pvr/pvr.iptvsimple#208]
Hello,

I'm subscribed to a paid IPTV service. Their m3u file contains the tag `tvg-id` and cannot be read by `PVR IPTV Simple Client`. It seems that the addon only matches `tvg-ID`, not `tvg-id`. The file works just fine with other IPTV apps on an LG Smart TV.

I'm not able to change those tags and make it work with Kodi because it's not a custom list I made.

---

Platform: Xbox One
Kodi version: 18.0-BETA5
Addon version: 3.5.4

**Comment by palinek** [comment]
Duplicate of #195 and #135 ?

**Comment by sergiolepore** [comment]
Oh, missed those. Thanks!
