### ISSUE TITLE
IGMP version

### ISSUE THREAD

**Issue by lvalero** [kodi-pvr/pvr.iptvsimple#21]
Hello,

Is it possible to change the IGMP version the client is using ? Actually i see that an IGMPv3 is sent, and then after a few seconds an IGMPv2 (which works for me).

I am also wondering if it linked to the add-on or to Kodi, or it is an OS managed parameter (i think that's the answer)

Regards

**Comment by afedchin** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi

**Comment by Jalle19** [comment]
Try this: http://www.sheepguardingllama.com/2009/11/forcing-red-hat-linux-to-igmp-version-2/

**Comment by lvalero** [comment]
Hello Jalle19,

Actually i noticed that sometimes (i do not know why) on certain platforms (windows, macosx), the igmp membership report is not sent, under linux i had no problem so far (wireshark igmp protocol on interface)

So i assume the igmp capability is linked to the OS ip stack.

Regards

**Comment by lvalero** [comment]
I found a solution for MacOSX 

sysctl net.inet.igmp.sendra=0
