### ISSUE TITLE
Builds failing as a result of PR15321

### ISSUE THREAD

**Issue by StormTrooper** [kodi-pvr/pvr.iptvsimple#215]
Running nightly builds on OSMC is now failing due to PR15321. 

https://github.com/xbmc/xbmc/pull/15321

With explicitly writing a patch file and then executing it, the patch step doesn't fail if a command (e.g. patch apply) from the patch file fails.

Previously on pvr.iptvsimple the 01-fix-windows.patch would fail but the build would continue. 

With the above PR it now causes it to fail. 

01-fix-windows.patch is failing:

```
[  7%] Performing patch step for 'rapidxml'
(Stripping trailing CRs from patch; use --binary to disable.)
patching file rapidxml.hpp
Hunk #1 FAILED at 382 (different line endings).
Hunk #2 FAILED at 549 (different line endings).
Hunk #3 FAILED at 634 (different line endings).
3 out of 3 hunks FAILED -- saving rejects to file rapidxml.hpp.rej
CMakeFiles/rapidxml.dir/build.make:101: recipe for target 'rapidxml/src/rapidxml-stamp/rapidxml-patch' failed

```

patch -v
GNU patch 2.7.5

**Comment by mkreisl** [comment]
Same here, XBian build of Kodi 18.0 final!

Why did you guys (especially @Rechi) made such changes a few days before 18.0 final will be released ???

It is soooo ridiculous, that makes the RC state ad absurdum, falling back to ALPHA state

Sorry, but I can't understand that

**Comment by thepasto** [comment]
Same here too, on archlinux

**Comment by knedlyk** [comment]
Is there any way to avoid patching rapidxml.hpp ?

**Comment by fdonv** [comment]
> Is there any way to avoid patching rapidxml.hpp ?

dirty temp fix, after cmake command and just before make : in your addon build directory (ex /pvr.iptvsimple/build), edit file "CMakeFiles/rapidxml.dir/build.make" and remove line 103. make should work now.

**Comment by knedlyk** [comment]
Confirmed.

**Comment by phunkyfish** [comment]
Fixed by https://github.com/kodi-pvr/pvr.iptvsimple/pull/216
