### ISSUE TITLE
Kodi 18 Libreelec - not working

### ISSUE THREAD

**Issue by frobali** [kodi-pvr/pvr.iptvsimple#218]
Error opening streams

My iptv list is http://xxx.xxx.xxx:25461/xxxxxx  (tried as local or as url), in the Kodi log i see ;

Error failed to open source http://xxx.xxxx.xxx:8080/xxxx

It seems its changing the port, 25461 to 8080

Tks

**Comment by ksooo** [comment]
This is a dev space, not a user support forum.
