### ISSUE TITLE
tvg-name takes priority over tvg-id if it's present

### ISSUE THREAD

**Issue by Znuff** [kodi-pvr/pvr.iptvsimple#221]
The wiki/docs mention:

```
- tvg-id is value of channel id in EPG xml file. If the tag is absent then addon will use tvg-name for map channel to EPG;
- tvg-name is value of display-name in EPG there all space chars replaced to _ (underscore char) if this value is not found in xml then addon will use the channel name to find correct EPG.
```

This leads me to believe that `tvg-id` has priority over `tvg-name` for EPG data, but unfortunately this does not seem to be the case.

I have tried the following:

```
#EXTM3U
#EXTINF:1 tvg-id="Antena1.ro" tvg-name="Antena 1" tvg-logo="https://[redacted].eu/logo/antena1hd.png" group-title="ROMANIA",Antena 1
https://[redacted]/6406
```
And with the following XMLTV:
```
  <channel id="Antena1.ro">
    <display-name lang="ro">Antena 1</display-name>
  </channel>
```

This unfortunately does not seem to match the `id` from the XMLTV with the `tvg-id`, as I would normally expect.

In this case, I had to completely remove the `tvg-name` attribute completely from the EXTINF line in order for `tvg-id` to be considered. 

Further more, having a blank `tvg-name` attribute (ie: `tvg-name=""`) also breaks the matching.

**Comment by phunkyfish** [comment]
This is a valid bug. What happens is that each channel is checked for tvg id first then tvg name. If tvg name matches on the first channel then no other channels are checked for tvg-id.

It's not easy to fix, will probably only try to fix on Matrix.

EDIT: Fix was easier than I thought. It might not be the most efficient but it works. In #269

**Comment by phunkyfish** [comment]
And #275
