### ISSUE TITLE
Add some attributes

### ISSUE THREAD

**Issue by xmha97** [kodi-pvr/pvr.iptvsimple#223]
Hello, This addon doesn't support some attributes. (For example channel fanart)
See all attributes from the below link:
https://github.com/Cigaras/IPTV.bundle/wiki/Playlist

**Comment by phunkyfish** [comment]
The addon now supports all the fields available in the API after: #269 

Any others, such as channel fanart would be kodi-pvr requests and not specific to the addon.

**Comment by xmha97** [comment]
Now, Is the addon supports fanart? (Using playlist.m3u file)

**Comment by phunkyfish** [comment]
No, the addon cannot support this. It would need to be added to kodi-pvr before it would be possible.

**Comment by phunkyfish** [comment]
I.e. the core of kodi.

**Comment by phunkyfish** [comment]
If there are specific features you would like to see in kodi-pvr you can post you request on the forum and see if other users are looking for the same things.

**Comment by xmha97** [comment]
In Kodi forum? (https://forum.kodi.tv/)

**Comment by phunkyfish** [comment]
Yes, it’s a good place to start.

**Comment by phunkyfish** [comment]
Here is the the feature requests section: https://forum.kodi.tv/forumdisplay.php?fid=9

**Comment by xmha97** [comment]
https://forum.kodi.tv/showthread.php?tid=346687

**Comment by phunkyfish** [comment]
Closing this issue as request should be to xbmc repo instead.
