### ISSUE TITLE
there is no pvr / pvr.iptvsimple in kodi 18.1 for ios

### ISSUE THREAD

**Issue by pofer** [kodi-pvr/pvr.iptvsimple#226]
there is no pvr / pvr.iptvsimple in kodi 18.1
there is no pvr / pvr.iptvsimple in kodi 18.1 for ios

**Comment by daveamato** [comment]
Any existing reference to this issue would be helpful, but I too am unable to locate pvr.iptvsimple in the ios64 build of the distributable (.deb) or the official Kodi repo (+ mirrors)... Not sure if they're related but, I am aware of a WiFi networking issue on Kodi18 for iOS, and see that  it's being worked-on as there is an active test-build that seems to resolve my connectivity issue; just missing my simple pvr!

**Comment by daveamato** [comment]
FTR, I was able to copy an older 18.0 RC build's 'pvr.iptvsimple' addon folder into the latest build.  Then I repackaged the IPA, resigned and reinstalled.  All works well, not sure if they have just forgotten about us iOS users

**Comment by ksooo** [comment]
This is a dev space, not a user support forum.
