### ISSUE TITLE
how can i change stream cache in kodi 18.1 for tv？

### ISSUE THREAD

**Issue by qwertccc** [kodi-pvr/pvr.iptvsimple#227]
I want to increase the cache，because my network is not good，video is not smooth……

Buffer for X seconds，maybe 10s is enough，maybe 5s？so i want to adjust it 

：）

**Comment by qwertccc** [comment]
https://kodi.wiki/view/HOW-TO:Modify_the_video_cache

advancedsettings.xml this file is no help here…

**Comment by ksooo** [comment]
This is a dev space, not a user support forum.
