### ISSUE TITLE
missing #EXTM3U descriptor on line 1, attempting to parse it anyway

### ISSUE THREAD

**Issue by fswaria** [kodi-pvr/pvr.iptvsimple#229]
I am using kodi-18.1-Leia-x86 with PVR IPTV Simple Clients.

For more than 4 months I have been watching IPTV without any problems. Sinds the last update when trying to access IPTV server with my login I am presented with the following Error:
Kodi Log is showing...
ERROR: AddOnLog: PVR IPTV Simple Client: URL 'http://xxxxx.live:8080/get.php?username=Xxxxxxxxxxx&password=XxXxXxXxX&type=m3u_plus&output=ts ' missing #EXTM3U descriptor on line 1, attempting to parse it anyway.

The IPTV Server Administrator says login is fine and #EXTM3U is not missing and used with correct syntax.
Can anyone please help me?

**Comment by phunkyfish** [comment]
Do you have a sample M3U that is generated when you visit the URL in a browser?

**Comment by Tech127x** [comment]
I am having the same issue.  Here is a sample of M3U:

#EXTM3U
#EXTINF:-1 tvg-id="" tvg-name="###### EXCLUSIVE VIP ######" tvg-logo="http://vod-gate.sytes.net/files/t20.png" group-title="EXCLUSIVE",###### EXCLUSIVE VIP ######
http://landiptv.live:8080/username/password/246967
#EXTINF:-1 tvg-id="animaux.fr" tvg-name="VIP: FR - ANIMAUX HD" tvg-logo="http://xtools.landiptv.live/manage/stream_pool/data/picon/2884eb7d4ef8351becf8e366cadba9e7.png" group-title="EXCLUSIVE",VIP: FR - ANIMAUX HD
http://landiptv.live:8080/username/password/198616

**Comment by phunkyfish** [comment]
It looks valid.

Can you try to download the m3u file using a curl command like this:

`curl --user username:password -o playlist.m3u8 http://my.iptvprovider.com/mym3u` in case there are any unexpected characters. The `-o playlist.m3u8` is the file that will contain the content. Omitting it will display of the file on the screen.

Please also provide a full debug log, without that we won't solve this.

**Comment by Tech127x** [comment]
Thanks for the reply!

I tried this:
`curl --user username:password -o playlist.m3u8 http://landiptv.live:8080/landiptv.live.m3u`

and all it returns is:
```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
I am also trying out Swoop which is working very well it's just more expensive.  I tried the same curl command with their url and it yielded the same result.  I'll get a debug log link up shortly.

**Comment by phunkyfish** [comment]
You need to substitute your username and password (assuming you use a username and password, if not you can drop that part).

**Comment by Tech127x** [comment]
I do and I did. I should have mentioned that.  I just didn't want to post them publicly so I change the actual info to 'username" and 'password' before posting.  Everything else is exact though.

EDIT:  I had the name of the m3u incorrect on Swoop.  Once I corrected that, one downloaded there but like I said before, that one works fine.  Nothing from the landiptv with any of the variations I have tried.

**Comment by phunkyfish** [comment]
Strange. Let see what the debug log tells us.

**Comment by Tech127x** [comment]
[kodi.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/3575946/kodi.log)

**Comment by phunkyfish** [comment]
Ok, looks like you are inputting an iptvstream URL instead of a URL that returns an M3U file.

`grep “AddOnLog: PVR IPTV Simple Client:” kodi.log” 

To see all the binary data being sent.

**Comment by phunkyfish** [comment]
Closing this issue as wrong URL used.
