### ISSUE TITLE
Setting Rytec EPG Downloader

### ISSUE THREAD

**Issue by waikna** [kodi-pvr/pvr.iptvsimple#23]
Good morning folks.. I am a new kodi user and I was wondering is someone could assist me with an issue I am having everytime l login on kodi. I keep getting a pop-up window: " Setting Rytec EPG Downloader" I keep hiting ok but it keeps coming back. How can I stop this window from popping again next time I loging to Kodi... Thanks in advance 

Ivan

**Comment by afedchin** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
