### ISSUE TITLE
Takes more than 10 minutes to parse everything 

### ISSUE THREAD

**Issue by lattice0** [kodi-pvr/pvr.iptvsimple#230]
Everytime I open my OSMC (latest raspberry pi), this add on takes 10 minutes to load everything. My IPTV link has 16.000 channels. 

Is there something that can be done to increase the speed?

Anyways, thank you so much, it's a very useful add on

**Comment by ksooo** [comment]
Works as designed. ;-)

Nobody on this planet legally has 16K channels and we do not support piracy in any form, so this is not a bug.
