### ISSUE TITLE
UDP multicast support...

### ISSUE THREAD

**Issue by siliconhippy** [kodi-pvr/pvr.iptvsimple#233]
I am on an Amlogic 905* TV Box running LibreElec/CoreElec 9.0.0.*

How can we stream from the multicast udp formats eg, UDP://@ip:port in an m3u file with Kodi setup for IPTV Simple PVR here?

The m3u format should look like:

http://192.168.1.1:4000/udp/ip:port

But how do I configure the http part in Kodi? Is udpxy auto configured in Kodi or PVR Simple ?

Is there a way the http ip:port are kept static?

Edit: Just saw this:
https://github.com/afedchin/xbmc-addon-iptvsimple/wiki/IPTV-Simple-Home

Seems to say that the native UDP://STREAMURL format works. No need for above http conversion?

Can someone confirm? I seem to have trouble with the native format.

Thanks 👺

**Comment by afedchin** [comment]
m3u file can contain any supported stream urls (unicast or multicast).
