### ISSUE TITLE
Multiple ts files: m3u8 file works fine in VLC

### ISSUE THREAD

**Issue by jariojose** [kodi-pvr/pvr.iptvsimple#234]
Hello, @all 

I don't know what is the problem with the URL: https://www.skyiptv.com.br:25463/live/Tai/Oie/9.m3u8

When I use it on VLC, is possible to see the video. 

Could I help me, please?

Thanks!

**Comment by afedchin** [comment]
Kodi's PVR isn't designed to using m3u8 as PVR stream url.
