### ISSUE TITLE
Use ffmpeg to check if channels are online

### ISSUE THREAD

**Issue by gabriellluz** [kodi-pvr/pvr.iptvsimple#241]
Hi there.

I'm not using IPTV Simple anymore because I have paid TV now. The thing is: I was testing IPTV Simple and I think it would be even better if there was a way to check for online/offline channels and remove them from the list.
An option like this would do: Check if streams are online

Using that option would use ffmpeg to check every channel and remove it if it doesn't work.

That script below checks for every stream for online or offline channels and generate a valid m3u8 file:

```
#!/bin/bash

#+==========================================================+#
# m3u8-link-checker check m3u8 - m3u files for working links #
#+==========================================================+#

# exit status and error codes
SUCCESS=0      # success exit code
E_WRONGARGS=65 # wrong number of arguments passed to script
E_WRONGFILE=66 # wrong file passed to script

# script usage
script_usage="Usage: $(basename "$0") [m3u8 or m3u file]"

#+========================================================+#
# check arguments passed to scripts                        #
#+========================================================+#

# check number of arguments passed to script and exit if not correct
[[ $# -eq 1 ]] || { printf "%s\n" "$script_usage"; exit "$E_WRONGARGS"; }

if [[ "$1" =~ \.m3u8?$ ]]; then        # + m3u8 file passed as first argument to script
    file="$1"                          # - filename is first argument passed to script
    outfile="${file%%.*}-checked.${file##*.}" # - get filename and extension
else
   printf "%s\n%s\n" "'$1' invalid input" "$script_usage" # + no arguments are passed to the script
   exit "$E_WRONGFILE"                 # - exit with E_WRONGFILE error code
fi

#+========================================================+#
# while read file check links with ffprobe                +#
#+========================================================+#

printf "%s\n" "Checking $file for working links"

while IFS= read -r line               # while read m3u8 or m3u file check links with ffprobe
do 
  link=$(printf "%s\n" "$line" | grep -Eo '(http|https)://[a-zA-Z0-9:0-9./?=_@&%|()[:blank:],;-]*' | grep -vP '(http|https|rtmp)://[a-zA-Z0-9:0-9./?=_@&%|()[:blank:],;-]*\.[(jpg|png|gif|svg)]$')
  [[ $? -eq 0 ]] && $HOME/bin/ffprobe -hide_banner "$link"
  [[ $? -eq 0 ]] && grep -B 1 "$link" "$file" 2>/dev/null | sed -e '/--/d' >> "$outfile"
done <"$file"

# check if any working links are found
[[ -f "$outfile" ]] && sed -i '1i #EXTM3U' "$outfile" || printf "%s\n" "No working links found"

exit "$SUCCESS" # exit 
```

[This script is available here:
https://raw.githubusercontent.com/NapoleonWils0n/kodi-playercorefactory/9c1881a541c7ef1ba3207fbf2005eccb879d18c1/bash-scripts-macosx/m3u8-link-checker](This script is available here:
https://raw.githubusercontent.com/NapoleonWils0n/kodi-playercorefactory/9c1881a541c7ef1ba3207fbf2005eccb879d18c1/bash-scripts-macosx/m3u8-link-checker)

[This script is available here:
https://raw.githubusercontent.com/NapoleonWils0n/kodi-playercorefactory/9c1881a541c7ef1ba3207fbf2005eccb879d18c1/bash-scripts-macosx/m3u8-link-checker](https://github.com/NapoleonWils0n/kodi-playercorefactory/blob/9c1881a541c7ef1ba3207fbf2005eccb879d18c1/bash-scripts/m3u8-link-checker)

**Comment by afedchin** [comment]
**Simple** is a keyword. if you want a checking availability of channels use tvh

**Comment by gabriellluz** [comment]
Lol you're really arrogant. Thanks anyway.
