### ISSUE TITLE
Kodi crashing with group manager

### ISSUE THREAD

**Issue by Dumua1312** [kodi-pvr/pvr.iptvsimple#246]
Hello,
The problem started with the latest version of Kodi 18.2 on my xbox one, android and windows 10. As i add a new group in the client and i click one the first channel kodi crashes.Here is my debug logs from android [https://pastebin.com/00Vz5Cgh](url) and this is my debug log from windows 10 [https://pastebin.com/QF2vqnAb](url)

thank you in advance

**Comment by ksooo** [comment]
Not an addon issue. Please open an issue for xbmc. Thanks.
