### ISSUE TITLE
[Feature Request] - Support EPG-tag season/episode

### ISSUE THREAD

**Issue by Goldsucher** [kodi-pvr/pvr.iptvsimple#258]
Hi,
I would really appreciate, if iptv simple would support more epg tags like season/episode, star rating or credits. For example:

<episode-num system="xmltv_ns">3 . 7 . </episode-num>

  <star-rating system="IMDb">
  <value>7.1/10</value>
  </star-rating>

  <credits>
    <director>Gary Halvorson</director>
    <actor>Charlie Sheen</actor>
    <actor>Jon Cryer</actor>
    <actor>Angus T. Jones</actor>
    <actor>Melanie Lynskey</actor>
    <actor>Jane Lynch</actor>
    <actor>Melanie Abramoff</actor>
    <actor>Kelly King</actor>
    <actor>Bruno Amato</actor>
    <actor>Stefan Umstead</actor>
    <actor>Shane Woodson</actor>
  </credits>

thanks in advance!

**Comment by ghost** [comment]
I make PR for this, but without episode-num, added some pictures https://github.com/kodi-pvr/pvr.iptvsimple/pull/261

**Comment by phunkyfish** [comment]
Done in #269

**Comment by phunkyfish** [comment]
And #275
