### ISSUE TITLE
Kodi 19 matrix nightly. Pvr iptv simple client will not install

### ISSUE THREAD

**Issue by mattyspurs76** [kodi-pvr/pvr.iptvsimple#260]
Clean install of kodi 19 nightly on nvidia shield. 
Tried to install this addon on a clean kodi build, nothing else installed on it yet.
4.0.2 will not install at all. Message saying unable to install.
Thought I'd try and copy source folders from 18.3 to kodi 19 and see if it would automatically update....nope, again message saying this addons not made for this version of kodi. 3.5.8.   It would not update to 4.0.2

**Comment by phunkyfish** [comment]
Can you provide a full debug log from when are are trying to install?

**Comment by phunkyfish** [comment]
Will close in a couple of days as no replay in nearly a month.

**Comment by phunkyfish** [comment]
This is really a forum question anyway.
