### ISSUE TITLE
Crash when loading epg data

### ISSUE THREAD

**Issue by skydrome** [kodi-pvr/pvr.iptvsimple#264]
Matrix Nightly 20190816 - arm64-v8
addon versions 4.1.0 4.2.0 both crash / **4.0.2 works**

kodi log: https://paste.debian.net/plain/1096352
logcat: https://paste.debian.net/plain/1096353

Crashes after playlist is loaded and epg starts to load
Everything works normally until I add an epg file

Logfile doesnt show anything that stands out so im not sure how else to debug it

I also tested on win64 with version 4.2.0 and it works on windows

**Comment by phunkyfish** [comment]
Do you have the kodi crash log?

**Comment by skydrome** [comment]
android doesnt produce crash dumps, just what logcat CrashDescriptorUtil gives

**Comment by phunkyfish** [comment]
I think I've found the issue referenced above. Update to v4.2.1 once it’s out.

**Comment by skydrome** [comment]
Thanks! That fixed it
