### ISSUE TITLE
[Feature Request] add support for EPG tag <star-rating> and <date>

### ISSUE THREAD

**Issue by augustas2** [kodi-pvr/pvr.iptvsimple#267]
Hi,

As I understand right now this addon does not support `<star-rating>` and `<date>` tags from XML.

Maybe there are some plans to introduce these tags? :)

**Comment by phunkyfish** [comment]
The API supports those fields so it's possible. Do you have example M3U's containing this data?

**Comment by augustas2** [comment]
Yep I got EPG XML file ready with these tags here: https://github.com/augustas2/iptv/blob/master/epg.xml

**Comment by phunkyfish** [comment]
Fixed in #269

**Comment by phunkyfish** [comment]
And #275
