### ISSUE TITLE
Issues with newly added credit tags (actor, director, writer)

### ISSUE THREAD

**Issue by augustas2** [kodi-pvr/pvr.iptvsimple#268]
Here is the file where the tags for xml is described: https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_epg_types.h

According to line 91, field `strCast` can be multiple actors separated by comma or any other separator. So by current Addon code, only first actor tag is taken...

Also XMLTV format states, that every actor must be specified in every new `<actor>First Last Name</actor>` tag. XMLTV format example here: http://wiki.xmltv.org/index.php/XMLTVFormat

So current code is buggy, as you need a loop threw all `<actor/>` XMLTV tags and append them into one string.
Same rule for `director` and `writer`, as the XMLTV file may contain multiple writers and directors.

**Comment by phunkyfish** [comment]
Example here: https://github.com/kodi-pvr/pvr.iptvsimple/pull/269

@2small will use something like this to fix it.

**Comment by Sorien** [comment]
some samples
http://xmltv.xmltv.se/hbo.si_2019-09-07.xml
http://xmltv.xmltv.se/disneychannel.dk_2019-09-09.xml

**Comment by phunkyfish** [comment]
Fixed in #269

**Comment by phunkyfish** [comment]
And #275
