### ISSUE TITLE
How do I install this on Android?

### ISSUE THREAD

**Issue by hmiah101** [kodi-pvr/pvr.iptvsimple#27]
Hi,

I have an issue with version 1.11.2 of IPTV Simple Client - it isn't loading up channel logos at all both from a local folder and remote path. I wanted to install the Github version to see if it would work but don't know which folder to paste the files into. Would really appreciate it if you or someone else can guide me as to where the IPTV Simple Client folder is located so I can install the Git version. I've tried downloading the zip and installing from zip but it says the structure is incorrect.

Thank you.

Running Isengard 15 RC1.

**Comment by Jalle19** [comment]
There is no newer versiom than what's in Isengard. Please open a thread on the forums if you have general issues with an addon.
