### ISSUE TITLE
VERSION 3.7.2 NOT WORKING

### ISSUE THREAD

**Issue by Nathcloud9** [kodi-pvr/pvr.iptvsimple#274]
Hi, my kodi on windows auto updated to simpleclient 3.7.2 and now it does not load any channels or anything.

**Comment by phunkyfish** [comment]
Did you have version 3.7.1 before this and did that work?

Also could you upload a full debug log?

**Comment by Nathcloud9** [comment]
Yes I did and that worked but have tried downloading a copy from here and it wont install.

**Comment by phunkyfish** [comment]
You can’t download it from here as it’s a binary addon. You need to downgrade from the update button in addon settings. But please supply a debug log first so we can fix the issue.

**Comment by phunkyfish** [comment]
@AlwinEsch any ideas? 3.7.2 was all build related so I don’t see how it causes an issue.

**Comment by Nathcloud9** [comment]
[kodi.old.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/3543269/kodi.old.log)
[kodi.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/3543270/kodi.log)

I have no idea about this sort of stuff in this depth.

**Comment by Nathcloud9** [comment]
i cant downgrade because the only version i see in kodi repo is 3.7.2

**Comment by phunkyfish** [comment]
I see this error in your log file:
```
2019-08-26 21:56:57.699 T:1744   ERROR: AddOnLog: PVR IPTV Simple Client: Unable to load channels from file 'E:\NathsM3U.m3u':  file is corrupted.
```

Can you check the file to make sure it’s ok?

**Comment by phunkyfish** [comment]
Here’s the thing. There was no code changed in 3.7.2. The only changes were with how the addon is built.

**Comment by Nathcloud9** [comment]
yes ever so sorry somehow my file seems to be corrupt, have just downloaded a fresh copy and it works. Don't understand how it could have happened. Damn i deleted my whole setup without a backup.

**Comment by phunkyfish** [comment]
No worries 😉

**Comment by Nathcloud9** [comment]
Sorry just assumed it must have been down to the update as was working before. Very strange timing lol.

**Comment by phunkyfish** [comment]
It usually is!
