### ISSUE TITLE
Update addon home urls in addon metadata

### ISSUE THREAD

**Issue by allixx** [kodi-pvr/pvr.iptvsimple#279]
Obsolete urls linking to non-existing github wiki page in pvr.iptvsimple/addon.xml.in should be replaced with current https://kodi.wiki/view/Add-on:IPTV_Simple_Client and/or https://github.com/kodi-pvr/pvr.iptvsimple

**Comment by phunkyfish** [comment]
This will happen the next time transfix is run. Currently it’s only correct for en_GB

**Comment by phunkyfish** [comment]
But this is only for Matrix build.

**Comment by allixx** [comment]
Thanks, I totally forgot about the centralized localization service.
