### ISSUE TITLE
Delay startup when Kodi boots

### ISSUE THREAD

**Issue by lsilva97** [kodi-pvr/pvr.iptvsimple#285]
Hi everyone,

Is this possible insert a field like "_Wait for X seconds after Kodi starts_" in config? 
This would be great, because sometimes my VPN starts after the IPTV addon loads the EPG and M3U channels list.

I am using Kodi Leia in LibreELEC and Raspberry PI 3 B+.

Regards,

**Comment by phunkyfish** [comment]
LibreElec already has a wait for network setting in Settings->LibreElec->Network.

This is not something that should be added to the addon anyway.

**Comment by ksooo** [comment]
> This is not something that should be added to the addon anyway.

 This is correct.

**Comment by phunkyfish** [comment]
Closing.

**Comment by P-a-d-r-a-i-g** [comment]
Wait for network is not the same as waiting for VPN to connect and is not provided for as incorrectly stated by someone above.

The OP wants to give Kodi time to load, then fire up the VPN plugin, then kick off the PVR plugin after X seconds from startup.
Thus, I don't believe this ticket should be closed based on the above incorrect understanding of the issue.

**Comment by phunkyfish** [comment]
It’s still not something that should be part of the addon.

If the VPN addon has this requirement it should be changed.

**Comment by P-a-d-r-a-i-g** [comment]
Is it that you mean the VPN plugin should kick off the PVR plugin?
Wouldn't that mean that the PVR plugin need an auto-start type option set to false in this case.

**Comment by phunkyfish** [comment]
No, there would be no change to this. I have no idea how another addon might make this happen. I’m not a python dev but I’m sure it’s possible.
