### ISSUE TITLE
[feature request] udpxy playlist change support

### ISSUE THREAD

**Issue by aztech-azza** [kodi-pvr/pvr.iptvsimple#286]
Is there any possibility to add support for on-the-fly altering loaded m3u's with udpxy links? For iptv in lans over wifi...

**Comment by phunkyfish** [comment]
You will need to provide way more information than that 😉

Examples would be a good start.

**Comment by aztech-azza** [comment]
OK, I'll try )...
The original M3U comes this way [part]:
`#EXTINF:0,Russian MusicBox HD`
`udp://@239.239.3.38:5239`

The modified M3U for udpxy support looks like this:
`#EXTINF:0,Russian MusicBox HD`
`http://192.168.1.1:4000/udp/239.239.3.38:5239
`
where 192.168.1.1:4000 - is the IP/Port of the device running udpxy (Asus router in this example), so IP and PORT are the parameters that should be set up in IPTV Simple Client settings. Thanks in advance!

**Comment by phunkyfish** [comment]
Ok, thanks. Solution details make sense.

But can you describe the use case, i.e. the problem you are trying to solve. The more context the better.

I assume currently you just do the substitution yourself.

**Comment by aztech-azza** [comment]
It's all about distribution of UDP multicasted IPTV traffic over wifi connections in lans. It causes systematic packet loss and freezing. When over wired connection everything is ok (or definitely better). So the udp-to-http proxy (udpxy) is the solution, but inconvenience is that you shoud alter the m3u manually every time it is charged by the iptv provider.

**Comment by phunkyfish** [comment]
So you run the proxy locally which converts to http on the local network?

But is the proxy supplied by your provider or is it something you have set up yourself?

**Comment by aztech-azza** [comment]
The UDP proxy is a component that can be run on several devices (routers - it is often included in router's firmware, NASes, *berry pi, etc). It is not supplied by the iptv provider. The only configuration option in device is the casting port (as far as it is in my Asus router).

**Comment by phunkyfish** [comment]
Ok, this doesn’t look too difficult, I will add it to the Matrix version when I have the time to do so.

**Comment by phunkyfish** [comment]
Question, are you able to build the addon from a PR for testing purposes? Or do you run Libreelec on intel or a raspberry Pi?

**Comment by phunkyfish** [comment]
Hey, if I provide you a test build can you test this?

**Comment by aztech-azza** [comment]
I'll try)

**Comment by phunkyfish** [comment]
What platform do you run kodi on?

**Comment by aztech-azza** [comment]
Android TV

**Comment by phunkyfish** [comment]
https://github.com/kodi-pvr/pvr.iptvsimple/pull/292

**Comment by phunkyfish** [comment]
Matrix addon builds are here: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-292/8/artifacts
You can choose which build is correct for your Android TV.

Let me know if it works as expected. On Kodi Matrix go to the addon settings, change the settings level to Advanced or higher and you'll see the values there.

Kodi Matrix nightlies can be found here: https://mirrors.kodi.tv/nightlies/android/
Choose a Matrix nightly from October 10th or earlier otherwise you will pick up the python 3 changes.

**Comment by aztech-azza** [comment]
Can't get installed. CAddonInstalljob says that required addon kodi.binary.global.main version 1.1.0 not found. Kodi 18.4 with kodi.binary.global.main ver 1.0.14. I've tried to alter addon.xml to lower 1.1.0 to my 1.0.14, but after putting the xml back to zip kodi addon installer fails to read it from the zip...

**Comment by phunkyfish** [comment]
You need to be running kodi matrix, I.e. Kodi 19. It won’t work on Kodi 18.4.

**Comment by aztech-azza** [comment]
Well, it works pretty fine, thanks! Is Matrix a must? It's quite buggy, crashes from time to time

**Comment by phunkyfish** [comment]
Ya. Afraid so, there has been a lot of work done on the matrix version of the addon to make it easier to make changes.
