### ISSUE TITLE
Android not working.

### ISSUE THREAD

**Issue by Rihy** [kodi-pvr/pvr.iptvsimple#287]
Not load, no display list.
It works nomally on a PC.

Android log
[Androidlog](https://drive.google.com/open?id=1Dv7fZp2u_WDBfVSzy9omCLleM0zBMvnZ)

PC log
[PClog](https://drive.google.com/open?id=1JFXOFNRQxOIbAF5u_Q9f27H0BoO8u1xl)

**Comment by phunkyfish** [comment]
```
2019-10-04 08:30:15.335 T:17840   ERROR: AddOnLog: PVR IPTV Simple Client: pvr.iptvsimple - GetXMLTVFileWithRetries - Unable to load EPG file 'http://192.168.1.101:8888/api/iptv/epg.xml?days=2':  file is missing or empty. After 3 tries.
```

**Comment by Rihy** [comment]
Can I read it on my PC but not Android?

**Comment by phunkyfish** [comment]
Can you curl the file from the android box?

**Comment by Rihy** [comment]
Probably because it was made in some previous versions.(Kodi 18.1 old)

It has been impossible for quite some time.

**Comment by phunkyfish** [comment]
Can you add as a source and find the file in filemanger?

**Comment by Rihy** [comment]
Can not.  Because have to use api.
I want you to fix it because it can be read normally on a PC.

And in the forum it looks like this.  Probably the same as me.
https://forum.kodi.tv/showthread.php?tid=343010

**Comment by phunkyfish** [comment]
Why can't you add as a regular source and see if the file is accessible? What happens when you try?

I am asking you these questions so I can try and figure out why it's failing.

**Comment by phunkyfish** [comment]
What is the API that you use?

Do you have a browser on your Android device? What happen if you visit this API in the browser: `http://192.168.1.101:8888/api/iptv/epg.xml?days=2`

**Comment by Rihy** [comment]
I Don't know. Sorry.

Adding to source error massage
"Remote shere Couldn't connect to network server"

Android browser result.
https://i.imgur.com/y2HtjUm.png

**Comment by phunkyfish** [comment]
And a screenshot if you visit the URL from a windows browser?

**Comment by Rihy** [comment]
![無題](https://user-images.githubusercontent.com/34890492/66261157-66473780-e803-11e9-95ca-2005181b1158.png)

**Comment by phunkyfish** [comment]
This could be that the API is not compatible with Android.

**Comment by phunkyfish** [comment]
It’s not loading the M3U file either:

`2019-10-04 08:29:35.950 T:17841   DEBUG: AddOnLog: PVR IPTV Simple Client: pvr.iptvsimple - GetChannels - channels available '0', radio = 0`

**Comment by Rihy** [comment]
Where can I find previous version builds?

Prove that it worked with the previous version.

**Comment by Rihy** [comment]
I tried it with an krypton version. It works.

https://i.imgur.com/yF5HReu.png

**Comment by phunkyfish** [comment]
Ok, but krypton is very different to Matrix. The addon is the same but kodi core is very different.

If you set a network location can you navigate to the directory locally?

**Comment by phunkyfish** [comment]
It feels like a networking issue, something that happens on kodi ok android Matrix+. Is the api on the same device or a different one?

**Comment by Rihy** [comment]
It was not possible to use it from the middle of Leia.

How can I move to a local directory?

The API is on a different device.

**Comment by phunkyfish** [comment]
Leia should almost be the same as Matrix, I would expect it to the same there.

As a test can you try this to test it locally:

1) visit the M3U url on Windows and copy the output to a text file called channels.txt.
2) visit the EPG url on Windows and copy
the output to a text file called epg.txt

Copy both files to your kodi android box and setup the addon to use these local files.

Let me know I if that works.

**Comment by Rihy** [comment]
Playback failed.

https://i.imgur.com/YVg9fYd.png

**Comment by phunkyfish** [comment]
Can you pastebinit the two files that would created and a debug log?

**Comment by Rihy** [comment]
epg
https://paste.fedoraproject.org/paste/jdq9nY4~-e~5YBMPGZXa3A
channel
https://pastebin.com/6AngUb6d
log
https://pastebin.com/kKXGTT2k

**Comment by phunkyfish** [comment]
Ok, this means the problem is just that kodi Matrix running on android receives no data from your api. We know this as it correctly loads the files when supplied locally.

This means this is not an addon issue but a kodi core issue.

Without being able to run curl on your Android device it’s very hard to debug.

Is the behaviour the same on Leia?

**Comment by Rihy** [comment]
It worked in the early version of Leia.

**Comment by phunkyfish** [comment]
Which version?

**Comment by phunkyfish** [comment]
Addon version or Leia version?

**Comment by Rihy** [comment]
I don't remember it, so I want to verify it.

Has the built-in add-on been uploaded?

**Comment by phunkyfish** [comment]
What do you mean? Afraid I don’t use android so I don’t know how the addon updates works for it.

**Comment by Rihy** [comment]
I want you to upload the Leia add-on in various versions in zip format.

@armv7a

**Comment by phunkyfish** [comment]
I can’t. Can you try going to addon settings and update and see if you can choose older versions?

**Comment by phunkyfish** [comment]
I have no way to build for android.

**Comment by Rihy** [comment]
Leia 18.0 worked.
18.1 RC-1 worked
18.1 not worked.

addon ver 3.8.3　
This is the only add-on version.

**Comment by phunkyfish** [comment]
So same addon version each time?

**Comment by Rihy** [comment]
Yes.

**Comment by phunkyfish** [comment]
Ok, so it’s not the addon.

**Comment by Rihy** [comment]
How can I contact Kodi?

**Comment by phunkyfish** [comment]
Ok, so let me pull down those two branches and see can I spot the difference.

**Comment by Rihy** [comment]
Thank you.  We'll be expecting you.

**Comment by phunkyfish** [comment]
Commit List of 18.1rc1: https://github.com/xbmc/xbmc/commits/18.1rc1-Leia

Commit List for 18.1: https://github.com/xbmc/xbmc/commits/18.1-Leia

There are 10 commits difference.

**Comment by phunkyfish** [comment]
You can create an issue on https://github.com/xbmc/xbmc for kodi.

**Comment by phunkyfish** [comment]
I can’t see why these commit cause this problem.

**Comment by Rihy** [comment]
Thank you. I'll try.

**Comment by Rihy** [comment]
There seems to be no reply.
Is there anything I can do?
