### ISSUE TITLE
channel order  is incorrect

### ISSUE THREAD

**Issue by sand-max** [kodi-pvr/pvr.iptvsimple#288]
I have playlist.m3u8 with 200 channels, but in kodi channel order is other.
I don't understand how to player is sorting ones

**Comment by phunkyfish** [comment]
Are you running on Kodi Leia or Matrix?

**Comment by phunkyfish** [comment]
On Matrix you can number by the M3U order, and order by the M3U order (you just need to change the sort order in the left nav).

**Comment by sand-max** [comment]
> Are you running on Kodi Leia or Matrix?
 Kodi Leia

Found article https://forum.kodi.tv/showthread.php?tid=319036 and it's helped me
