### ISSUE TITLE
support for Radio Data System (RDS) Radiotext Plus via IPTV Simple  #Feature Request

### ISSUE THREAD

**Issue by ou-li** [kodi-pvr/pvr.iptvsimple#299]
Add support for RDS information (embedded programme information in DVB streams).

@ksooo has added this for Tvheadend pvr.hts a while ago:
https://github.com/kodi-pvr/pvr.hts/commit/5d8f1728c74ec2833192b84a05c26d18ce43d887#diff-fef2d0bddcacd34c8df38f91e0d19a38

It would be nice to have this available for streaming from external DVB-Receivers (Dreambox, Vu+ etc.) via IPTV Simple.

As Kodi's internal player can already handle this information, this seems to me just a matter of signalling its availability to the player, correct me if I'm wrong here.

I can provide access to such streams for testing purposes.

(Just in case: Yes, the RDS information is definitely available in these streams, which can be tested by adding them as an IPTV souce via Tvheadend's web interface)

**Comment by phunkyfish** [comment]
pvr.hts uses its own demuxer to make this possible. For iptvsimple the stream URL is just passed to kodi so any processing of RDS (assuming it’s embedded in the stream) would need to be done by the core.

FYI, if you are streaming from dreambox/VU+ etc why not use the dedicated Enigma2 addon instead?

**Comment by ou-li** [comment]
Ok, I can see why this doesn't make make sense to implement for IPTV Simple at this stage.Thanks for the insight! I will close this.

I liked the flexibility of syncing my playlist from different sources with several scripts but I will give the Enigma addon another shot to see how it handles RDS

**Comment by phunkyfish** [comment]
you can run the Enigma2 and iptvsimple addons at the same time. 

With the Enigma2 addon you can pause live tv and use a lot of other features.

**Comment by ou-li** [comment]
Thx!
