### ISSUE TITLE
reload playlist without reboot

### ISSUE THREAD

**Issue by efirshik** [kodi-pvr/pvr.iptvsimple#301]
this possible?

**Comment by phunkyfish** [comment]
Yes, this is implemented in the Kodi matrix version of the addon.

**Comment by skydrome** [comment]
is this supposed to be a button in the settings? or is there a command that we can send using jsonrpc to reload epg?

**Comment by phunkyfish** [comment]
There is a setting to do this on an interval of your choosing. 

There is no JSOn RPC command.
