### ISSUE TITLE
Error when loading the m3u list

### ISSUE THREAD

**Issue by susobaco** [kodi-pvr/pvr.iptvsimple#304]
Hello, configuring the following list of channels in m3u format, 
**https://gitlab.com/susobaco/iptv_spain/raw/master/iptv_spain.m3u**
gives me the following error in the log:
**ERROR: CCurlFile::Open failed with code 429 for https://gitlab.com/susobaco/iptv_spain/raw/master/iptv_spain.m3u:
2019-11-07 20:46:26.246 T:140206036408064   
ERROR: Open - failed to open source <https://gitlab.com/susobaco/iptv_spain/raw/master/iptv_spain.m3u>
2019-11-07 20:46:26.246 T:140206036408064   
ERROR: AddOnLog: PVR IPTV Simple Client: Unable to load playlist file 'https://gitlab.com/susobaco/iptv_spain/raw/master/iptv_spain.m3u':  file is missing or empty.**

Is it curl problem, kodi problem?, Addon problem? I use kodi 17.4 on trisquel flidas (version gnu-linux of ubuntu xenial)

**Comment by phunkyfish** [comment]
You would need to run at least kodi 18 and provide a full debug log.

**Comment by phunkyfish** [comment]
And quick google of code 429 gives you: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

**Comment by susobaco** [comment]
I'm sorry, but I don't understand. I may explain myself wrong. The version of kodi I have is:

~$ kodi -v
18.4 Git:20190831-3ade758 Media Center Kodi
Copyright (C) 2005-2019 Team Kodi - http://kodi.tv

(I misspelled the data, sorry) I need to activate the full debug log somewhere, right?

With the mistake, you say that I make many requests? sorry but I do not understand much.

Thank you and apologies.

**Comment by phunkyfish** [comment]
HTTP code 429 means that you have made too many requests to the URL you are trying to access and are being rate limited.

This is why kodi cannot read the file.

If you want to supply a debug log follow these instructions: https://kodi.wiki/view/Log_file/Easy

I don’t think this is bug though so the kodi forum is probably a better place for support.

**Comment by susobaco** [comment]
Hello, I attach a log, I don't know if I did it right.
[kodi_iptvsimple.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/3848411/kodi_iptvsimple.log)

**Comment by phunkyfish** [comment]
Ok, nearly.

You need to post the full log from after a restart of kodi. What you posted is a partial log.

**Comment by susobaco** [comment]
[kodi.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/3854433/kodi.log)
The new log

**Comment by phunkyfish** [comment]
Ok, you are being rate limited, http code 429.

I'd recommend you save the file locally and load it from there.

**Comment by susobaco** [comment]
Yeah, that's what I've been doing so far, thanks.

**Comment by phunkyfish** [comment]
I think many users must be hitting that URL in your region so GitHub is rate limiting requests originating from kodi.

**Comment by Roland2020** [comment]
Any one has any m3u albanian.

**Comment by phunkyfish** [comment]
@Roland2020 this is a GitHub issue board for bugs found in this addon. It’s not a place to request M3U files or anything like that.
