### ISSUE TITLE
Support EXTM3U x-tvg-url for reading EPG data

### ISSUE THREAD

**Issue by khimaros** [kodi-pvr/pvr.iptvsimple#306]
An example can be found here: https://github.com/iptv-org/iptv/blob/master/channels/au.m3u

**Comment by phunkyfish** [comment]
The way the addon works playlist and epg urls are added separately in the addon config.

If you add them separately does it work as expected?

**Comment by phunkyfish** [comment]
Added in PR #305 commit: https://github.com/kodi-pvr/pvr.iptvsimple/pull/305/commits/66970f6af46cb33a209194bbb714c8f28ced57af
