### ISSUE TITLE
I can watch only 5 sec and stop

### ISSUE THREAD

**Issue by melmel0101** [kodi-pvr/pvr.iptvsimple#309]
I have load my m3u playlist in local.
I can see the list of the channel.
I'm choosing one.
I can watch the TV during only 5 sec.
After i'm come back on channel list.

in vlc, the channels work well.

Do you have a idea ?
Thanks
(i'm on windows 18.4 and also android 18.4)

**Comment by phunkyfish** [comment]
VLC supports http reconnect. Kodi does not.

Therefore vlc works better with low quality streams.

**Comment by melmel0101** [comment]
ok thank

**Comment by phunkyfish** [comment]
There is one thing to try. I will post back here in a few days if you can test it.

**Comment by melmel0101** [comment]
i have done the test with stable m3u playlist et all it's ok now.
thanks

**Comment by phunkyfish** [comment]
Cool, feel free to close the issue.
