### ISSUE TITLE
Playback stutter 

### ISSUE THREAD

**Issue by prydda** [kodi-pvr/pvr.iptvsimple#318]
Is there anything weird going on with my IPTV logs? 
http://ix.io/24Ip
Could be the provider aswell. 
Very often my stream keeps buffering and I need to quit the channel and choose a lower quality. 
HW: Amlogic S922x with 1Gbit network.

**Comment by phunkyfish** [comment]
Buffering will usually be due to provider. A good way to see if it's your hardware or provider is to run kodi on linux/windows/mac and see do you get the same buffering,

If you do it most likely your provider. If not a hardware/platform issue.

Either way it's unlikely it's the addon.

**Comment by prydda** [comment]
Alright I figured, definitely not hardware - diffrent channel, higher quality and no issues.  I'll ask the provider instead. 

Thanks.
