### ISSUE TITLE
I hope create a network protocol that support p2p -- p9p & vjms & tvbus & mitv

### ISSUE THREAD

**Issue by oncebeloved** [kodi-pvr/pvr.iptvsimple#320]
For example, these live lists.
vjms://58.215.133.185:8500:3502/live/cid=3
mitv://198.255.74.87:9906/5dc08f05000df9b701b7a09b8365395a.ts
P2p://190.2.146.92:18912/5c7249f7000966361d58752a73813a0e.ts
p8p://0198.02686.cc:16871/5d1a69da000a2acf11be734ba3f44eda.ts

**Comment by Evandro1975** [comment]
I think is a kodi feature and not PVR client.
The PVR pass the link to kodi player as is

**Comment by phunkyfish** [comment]
That’s correct. Any feature requests for Kodi should be raised on the forum.
