### ISSUE TITLE
channel order resets on m3u update

### ISSUE THREAD

**Issue by bam80** [kodi-pvr/pvr.iptvsimple#322]
Every time my IPTV provider updates it's .m3u playlist - my carefully crafted channel ordering fully resets.
Channels get added, changed, etc. on the provider side, so I need to set Location for my M3U as Remote path (URL), so it updates unattended and might ruin my hard work on channel ordering at any time (unfortunately, it happened many times already).

Can we have an option to preserve channel numbering for the channels which didn't change their names on M3U update?

**Comment by phunkyfish** [comment]
No, this wouldn’t be possible I’m afraid. Many providers allow you to generate a list of channels yourself so the M3U doesn’t change.

Maybe switch to a provider that has this functionality.

**Comment by bam80** [comment]
I can choose the channels for M3U too, as well as other parameters of the playlist, but still, actual channel URLs can change, since CDN (content delivery network) can change itself (or I might want to change it myself), etc. so I think this feature would be useful rather common.

For now, I end up hacking PVR database manually, which is inappropriate for average user.

**Comment by phunkyfish** [comment]
If the M3U list stays the same and only the URL changes then the channel numbers won’t change.

**Comment by bam80** [comment]
I'm afraid they will.
In my case only URLs seem have changed, and still it cased complete ordering reset..

**Comment by phunkyfish** [comment]
Running Leia or Matrix version?

**Comment by phunkyfish** [comment]
In Matrix you can choose to use the file order so they won’t change.

**Comment by bam80** [comment]
It's Leia. I saw Matrix has ability to preserve M3U order, but it's not what this issue about.
I'm talking about preserving the order set from Kodi itself..

**Comment by phunkyfish** [comment]
You mean if you customise the order after loading the M3U?

You can’t have it both ways. Either you control the order and manually update entries or you leave the backend manage it and it can change as the backend does. In the case of IPTV Simple the backend is the M3U file.

**Comment by bam80** [comment]
I know. Yes, I mean managing the order from within Kodi after m3u was loaded. I'm not interested in m3u's channels order at all.

**Comment by phunkyfish** [comment]
If you load an M3U and update that M3U it will override any customisations you have made in kodi.

The customisation feature is for users who don’t update there channel lists automatically they instead do it by hand.

**Comment by bam80** [comment]
I come to conclusion it's just import algorithm that needs to be adjusted. There is no need to screw up channels ordering with the same name, for sure - unconditionally..

**Comment by phunkyfish** [comment]
IPTV Simple is simple by nature. It does not add new channels instead it reloads an M3U from scratch. It also identifies each channel by uniquely combining the name and the URL to create an ID. 

A feature could be designed to only add new channels at the end but only using name would not be sufficient for the reasons you have seen, there is no way to know which `channelx` is which if you have several of them.

**Comment by bam80** [comment]
As a temporary workaround, I made following script to restore the order from backed-up TV db:
```sql
sqlite3 .kodi/userdata/Database/TV32.db  --column -header '
ATTACH ".kodi/userdata/Database/TV32.db~" AS "good";

/*
update map_channelgroups_channels         
set iChannelNumber = (
select good.map_channelgroups_channels.iChannelNumber
from                
channels join           
good.channels join good.map_channelgroups_channels
on main.channels.idChannel = main.map_channelgroups_channels.idChannel
and main.channels.sChannelName = good.channels.sChannelName
and good.channels.idChannel = good.map_channelgroups_channels.idChannel
);
*/

select
main.channels.idEpg,
main.channels.idChannel,
main.map_channelgroups_channels.iChannelNumber,

good.channels.idEpg,
good.channels.idChannel,
good.map_channelgroups_channels.iChannelNumber,
main.channels.sChannelName                     

from                      
channels join map_channelgroups_channels join
good.channels join good.map_channelgroups_channels
on                                                                    
main.channels.idChannel = main.map_channelgroups_channels.idChannel
and good.channels.idChannel = good.map_channelgroups_channels.idChannel
and main.channels.sChannelName = good.channels.sChannelName            

order by good.map_channelgroups_channels.iChannelNumber
limit 10'

**Comment by phunkyfish** [comment]
Closing as not possible in this addon due to the nature of how it works.
