### ISSUE TITLE
Can't find

### ISSUE THREAD

**Issue by ghost** [kodi-pvr/pvr.iptvsimple#324]
Can't find kodi.binary.global.main 1.1.0？

**Comment by phunkyfish** [comment]
There is no context or debug log with this issue. Please give more details?

**Comment by ghost** [comment]
2020-02-10 21:59:54.300 T:15896   ERROR: CAddonInstallJob[pvr.iptvsimple]: 对版本 1.1.0 的 kodi.binary.global.main 依赖无法满足。

**Comment by ghost** [comment]
正在使用发音

I don't know how to catch the log. I don't know if these are what you want to read

**Comment by phunkyfish** [comment]
There is an issue with the current downloaded kodi 18.5 install. Please use nightly builds (pre release) of 18.6 as we wait for actual 18.6 to be released.

I assume you run on OS X.

**Comment by ghost** [comment]
I use Android version org.xbmc.kodi-19.0-alpha1. Do you have a download address for version 18.6? Can you solve the update problem?

**Comment by phunkyfish** [comment]
Kodi 18.6 is available now if you want to download it.

**Comment by phunkyfish** [comment]
Closing as 18.6 is released
