### ISSUE TITLE
Catchup: add common types into settings

### ISSUE THREAD

**Issue by SerhiyRomanov** [kodi-pvr/pvr.iptvsimple#326]
The main idea is to have common catchup types in settings.
I mean, to add an option like "Catchup type" with values "default", "append", "flussonic", "xc", shift", ..., "Custom format string". So, users will be able to choose one from common types OR to provide their custom format string if select "Custom format string".

As @phunkyfish mentioned on https://github.com/kodi-pvr/pvr.iptvsimple/issues/325#issuecomment-586636544 we should assume that all channels from the list use a certain type of catchup by default. If not then we always can adjust it using supported M3U catchup tags.

The use case for this: I have a playlist from my IPTV provider, and I know that for channels is present archive support in "flussonic" format. So I simply add remote playlist URL, enable Catchup and select appropriate catchup type. 
If needed catchup type is not present in the list, I can select the option "Custom format string" and input my custom "Query format string" (this functionality already implemented). 
And one more case: if I have a playlist from different sources, so each entry supports different catchup types, I can adjust it using supported M3U catchup tags. So this means, that tags from M3U file should have highest priority.

Let's discuss it together.

**Comment by phunkyfish** [comment]
Ok, so instead of `all channels support catchup` which is true/false instead that option should be changed to `Assume channels are catchup type`. Then each a drop down with each item. And if custom is selected it uses the query string from settings?

**Comment by SerhiyRomanov** [comment]
@phunkyfish yes, this is what I mean. Please describe details if I don't know or don't understand something related to this topic

**Comment by Mr-Groch** [comment]
Now `timeshift="x"` tag is equal to `catchup="shift" catchup-days="x"`. But this behaviour should be changed. `timeshift` is obsolote tag indroduced by SIPTV when there was only **shift** type supported and it can not be equal to `catchup="shift"` in all situations currently. 

Now some providers use `timeshift="x"` only to tell how many days in catchup is available and catchup type can be something different than **shift**. IMHO this is not correct, but we must handle it. So still `timeshift="x"` should be equal to `catchup-days="x"` (`catchup-days="x"` can have bigger priority).

But `timeshift="x"` should be equal to `catchup="shift"` only when:
1. There is no `catchup` tag for that channel in m3u list that overrides that
2. **All channels support catchup using mode** is set to **disabled**

**Comment by phunkyfish** [comment]
Added in #327

**Comment by SerhiyRomanov** [comment]
**Thank you all for implementing this feature!**
