### ISSUE TITLE
Catchup: when watching live - resuming from pause doesn't start catchup

### ISSUE THREAD

**Issue by Mr-Groch** [kodi-pvr/pvr.iptvsimple#329]
When watching live stream if I press pause, and after a while resume - few seconds will play from buffer and then stream will skip to current live stream. It should resume from catchup url from time when paused.

**Comment by Mr-Groch** [comment]
If I can suggest priority for catchup issues, then from highest to lowest:

1. This
2. #332 
3. #333 
4. #330

**Comment by Mr-Groch** [comment]
This issue also happens when playing from catchup on TS streams if catchup URL is based on offset. When I resume from pause watching catchup stream will jump forwards. So restarting from new catchup url after pause should occur both - in live and catchup

**Comment by phunkyfish** [comment]
I hope to get back to this over the next 2 weeks. I think both are related to how skipping happens, It needs to correctly close and open the format context in ffmpeg which it doesn't do in the current version.

**Comment by phunkyfish** [comment]
Fixed in: https://github.com/xbmc/inputstream.ffmpegdirect/pull/27

Requires kodi API change

**Comment by phunkyfish** [comment]
Can you test again. This should work now, v1.8.0 or v1.8.1 of ffmpegdirect and the latest kodi.

**Comment by Mr-Groch** [comment]
I have tested with `catchup="xc"` **TS** and `catchup="timeshift"` **HLS**. Worked fine in both. Thanks. Will close this issue after testing with more stream types.

**Comment by Mr-Groch** [comment]
Fixed
