### ISSUE TITLE
Error compiling on Arch Linux :(

### ISSUE THREAD

**Issue by BytEvil** [kodi-pvr/pvr.iptvsimple#33]
Error log here: http://pastebin.com/2xSUGEcH

**Comment by hudokkow** [comment]
You need to update your system to a Kodi 16 J***** build.

file xbmc_pvr_dll.h changed and the one present on your system is outdated.

**Comment by BytEvil** [comment]
:)) 16.0-ALPHA1 Git:2015-07-24-5e04ca9-dirty. from kodi.log

**Comment by BytEvil** [comment]
Compiling from Isengard branch - same error ;)

**Comment by BytEvil** [comment]
Compiling from this commit :353cb28 ... All ok. Thanks!

**Comment by hudokkow** [comment]
This is master only. It won't work against Isengard.

Anyway, something is not right with your system.Have a look at: 
https://github.com/xbmc/xbmc/pull/7079/files#diff-e73115cc4e6a02ef7029ee04f8ddd2a8R381
and compare with https://github.com/kodi-pvr/pvr.iptvsimple/blob/master/src/client.cpp#L473
