### ISSUE TITLE
Catchup: back from timeshift to live issue

### ISSUE THREAD

**Issue by Mr-Groch** [kodi-pvr/pvr.iptvsimple#332]
Currently to go back from timeshift to live, I must press stop and play same channel again. When I'm playing timeshifted stream and try to seek forward to live time it should switch to live channel url, not catchup url, because catchup url in result is not correct. For **XC** or **shift** cachup type, it will stop itself (because `{utc}` and `{lutc}` is the same and/or `{duration}` is zero). For flussonic, it will play, but not correctly, because of using catchup url with offset 0

**Comment by phunkyfish** [comment]
If you press the next button on the OSD the catchup URL should switch to live URL. Are you saying it still uses the catchup URL?

If it's not it should be a hard fix.

**Comment by Mr-Groch** [comment]
Yes, the same behaviour when I press next button on OSD. It try to play from catchup url and this fails - my XC provider gives no data for duration = 0 and player exits.

**Comment by phunkyfish** [comment]
Ah, I remember this now. Originally I wanted to just switch to the live URL but the stream hit an EOF but that didn’t work so instead I used the catchup URL to go 10 seconds off live.

**Comment by phunkyfish** [comment]
Can you check this PR: https://github.com/xbmc/inputstream.ffmpegdirect/pull/27

It should not use the live URL instead of catchup.

**Comment by Mr-Groch** [comment]
Unfortunately I see an regression - timeshift stoped working - for live and archive, so I can't test back to live issue. Currently there is no possibility to seek forward/backward - KODI UI allows only to STOP.
Tested with HLS XC and Timeshift catchup lists.

**Comment by phunkyfish** [comment]
Ah, I think this is combined with another issue. PVR let’s us send 20 stream properties but an inputstream only allows us to receive 8. So inputstreams would need an API update to get this to work.

**Comment by phunkyfish** [comment]
Can you test again. This should work now, v1.8.0 or v1.8.1 of ffmpegdirect and the latest kodi.

**Comment by Mr-Groch** [comment]
I have tested with `catchup="xc"` **TS** and `catchup="timeshift"` **HLS**. Worked fine in both. Thanks. Will close this issue after testing with more stream types.

**Comment by Mr-Groch** [comment]
Fixed
