### ISSUE TITLE
Catchup: short time timeshifting from live problem - stream stopping

### ISSUE THREAD

**Issue by Mr-Groch** [kodi-pvr/pvr.iptvsimple#333]
There is a problem with cacthup types that uses `{duration}`, `{utcend}` or `{lutc}` (like **XC** or **shift**) after timeshifting backwards small amount of time from live. For example if I seek 30 seconds backwards from live, it will play from catchup url with just 30 second duration, so after 30 seconds stream will stop.

How we can resolve that? Maybe we should restart catchup over and over after stream ends from time when it ends to current `now`?

**Comment by phunkyfish** [comment]
It’s possible to do something like this in ffmpegdirect but I’m not sure it’s a good solution as we would have to restart the stream every 30 seconds. It would be a horrible viewing experience.

There must be a better shift/xc API for this.

**Comment by Mr-Groch** [comment]
I'm trying to get some more info from XC team, but currently with no luck. Maybe there will be other API for XC, but currently Google says there is not... For other types - like **append**, **default** or **shift** there will be no other API. **Shift** is just URL query standard, no specific backend.

I have tested my **XC** and **Shift** lists in other players - OTT Navigator on Adnroid and SS-IPTV on my Smart TV. In both players, when I rewind from live 30 seconds, then after every 30 seconds I can see _"bufering"_. Moreover after first buffering for XC - some time was skipped (XC accuracy is minutes not seconds) but next buffering was smooth. Similarly when I rewinded from live 3 minutes (SS-IPTV allows only seek 3 minutes minimal) - then buffering occurs every 3 minutes.

So if other players do that - I think there's no other way...

**Comment by phunkyfish** [comment]
Ok, I’m not sure how smooth the buffering can be but it’s worth a try. This actually an ffmpegdirect fix. Nothing to do with PVR.

Which makes it more tricky as up to now the inputstream addon doesn’t know anything about the catchup mode, just a URL it populates.

**Comment by Mr-Groch** [comment]
I think there is no need to know catchup type - cacthup query URL should be sufficient. Just when catchup stream ends, reconnect using stream end time as start time.

If I'm right, such reconnection is made in live stream mode with live url? If yes, then this will be consistent.

**Comment by phunkyfish** [comment]
We can just check for a `{duration}` specifier in the catchup url. But if any other stream type ever uses `duration` and unlike xc/shift does not have this problem we would break a working provider.

It’s safer to only do this for xc/shift where we know this is required.

**Comment by Mr-Groch** [comment]
`{duration}` is not enough. Same problem will occur when there is `{lutc}` or `{utcend}` placeholders (and their variants).

I don't think reconnection can break anything. If stream ends, it could be connection problems just like timeshifting issue, so reconnecting is expected behaviour. 

`{utc}`, `${start}`, `{Y}`, `{m}`, `{d}`, `{H}`, `{M}`, `{S}` - those placeholders should always be updated to time of stream end when reconnecting
`{lutc}`, `${timestamp}` - obvious - always `now`
`{utcend}`, `${end}` - it should be updated to `now` when when they previously has been capped to `now`
`${duration}` - it can be treated the same way as usual - recalculated if needed
`{offset:X}`, `${offset}` - no need to change, offset always will be the same (but maybe should be updated if it is connection problem and first reconnection attempt fails, otherwise we would skip some time after reconnecting)

**Comment by phunkyfish** [comment]
It will break things. In the case of flussonic reconnecting will cause a jump like a timeshift when it’s not required.

So this functionality can’t be generic. If the catchup url is inspected on stream start we could tell if this special mode needs to be enabled or not. As to how to get it to change I don’t know yet.

So if an xc/shift stream is running does that mean no value can be set that is greater than now? I.e. is capping duration now a problem?

**Comment by Mr-Groch** [comment]
Hmm.. But flussonic stream will reconnect only when there are some problems. Without reconnection functionality it will just stop, and there will be need to manually play channel again and seek place where I was watching. I rather prefer this jump instead of searching place where I was watching :)

I'm still having vision that this can be generic also for handling other issues when stream stops unexpectedly :)

Currently you are capping duration/end to `now`, I'm correct? Thats why I have mentioned that capping.

**Comment by phunkyfish** [comment]
This will be based on the current time approaching the original now time and seeking to a new position. There will be zero reconnection logic, if there is ever a disconnect there is no way to reconnect as the inputstream is destroyed. 

Essentially a disconnect stops any further action from being taken.

I don’t even know if the seek will work as it could mess up where the video player believes it is.

**Comment by Mr-Groch** [comment]
Oh, I thought it will be based on kind of "stream stpped" event... I'm understanding now, why this should not be used for `{offset}` based catchup. So it should work for catchup having `{duration}`, `{lutc}` or `{utcend}` placeholders (and their variants like `${timestamp}`, etc).

There really isn't any other way to detect stream end? I have been using tvheadend pvr client in KODI and I remember if there was some problem with stream, it did not stop playing - just _"No signal"_ hint was displayed. After stream came back playback continued. This can't be adopted here?

**Comment by phunkyfish** [comment]
TV Headend has its own demuxer, so it can be customised to do anything. FFmpegdirect uses ffmpeg's built in engine so it owns the stream. We have some control but not of everything. We would need some extra API functionality in kodi to be able to detect a stream stop.

If the addon owned the reading of the stream we could pass empty packets to keep the stream running and in the background do a reconnect, but it doesn't. 

Let's see can we solve the basic case first, something like duration. Then we can look at others.

In your tests what happen (let's say using vlc) if you set `{lutc}` or `{duration}` past now for xc/shift streams?

**Comment by Mr-Groch** [comment]
When I passed `{lutc}` or `{duration}` past now, stream has stopped when play time reached time of making request. So it behaves as if `{lutc}` or `{duration}` was set to `now`.

**Comment by phunkyfish** [comment]
Cool, thanks

**Comment by phunkyfish** [comment]
I'll look at this one next.

**Comment by phunkyfish** [comment]
How about this. ffmpegdirect needs to decide if this is a stream that can stop before it reaches live.

First thing to be decided is how close to live we want to enable this feature? Within 5 mins, 10 mins or default programme duration (4 hours).

Second is to know when to enable it. Is it sufficient to check for `{duration}`, `{lutc}`, `{end}, or`{utcend}` in the catchup format string to know that this mode can be enabled?

**Comment by Mr-Groch** [comment]
In my opinion:
1. Programme duration
2. When catchup type is set to `XC` or `shift` (also when there is just `timeshift` tag in m3u) or when catchup type is `default` or `append` and catchup URL has `{duration}`, `{lutc}`, `${timestamp}`, `{utcend}`, `${end}`

**Comment by phunkyfish** [comment]
> In my opinion:
> 
> 1. Programme duration
> 2. When catchup type is set to `XC` or `shift` (also when there is just `timeshift` tag in m3u) or when catchup type is `default` or `append` and catchup URL has `{duration}`, `{lutc}`, `${timestamp}`, `{utcend}`, `${end}`

For 1) programme duration it will be that or default duration because we may not know it explicitly if we seeked to live (only the first duration is known by ffmpeg direct).

For number 2 why care if it's XC or shift? Why not just base it on the format specifiers, remember that ffmpegdirect has no idea what the backend is.

**Comment by Mr-Groch** [comment]
OK, I agree, **shift** has `{lutc}`, **xc** has `{duration}` so it can be based just on placeholders

**Comment by phunkyfish** [comment]
How close to the end does it need to be to the end? It's a bit tricky with the minute granularity.

**Comment by Mr-Groch** [comment]
I think the end must be exactly the time defined by {lutc}, etc or start time + {duration}. XC with minute precission will timeshift always to full minute, KODI player UI will show incorrectly, but this need to be ignored.

For example:
It is 12:04:20, will timeshift back 3 minutes, KODI UI will show 12:01:20 (-3 minutes) but XC backend will play from 12:01:00. When catchup playtime reach start time +3 minutes (real time 12:07:20) it should restart stream with new catchup start time. So it will request to play from 12:04:20, but XC backend will serve from 12:04:00 - and this will be OK, becouse we previosuly watching from 12:01:00 from XC backedn.

**Comment by phunkyfish** [comment]
So the backend will play for 3 mins and 20 secs? It won’t round to 3 mins?

This part is important if it is to work properly.

**Comment by Mr-Groch** [comment]
In my example play time will be exactly 3 minutes, not 3 mins 20 sec. 

Actual 12:04:20 (1), shift -3 mins, so catchup from 12:01:20 (2). Then real time reaches 12:07:20 (3) - then restart catchup from 12:04:20 (4) (previous start time +3 minutes)

In XC corresponding times will be:
1. 12:04:00 2. 12:01:00 3. 12:07:00 4. (12:04:00)

There just always will be 20 second shift between XC server stream and KODI

I think there will be no problem with XC when timeshifting more than 1 minute - there will be problem when timeshifting less than 1 minute... It can be blocked in KODI by plugin?

**Comment by phunkyfish** [comment]
That is very hard to calculate as the minute granularity is only known in the format string.

**Comment by phunkyfish** [comment]
Blocking timeshift for less than one minute should be possible. Although i think it will just make it the previous minute boundary which is probably fine.

**Comment by phunkyfish** [comment]
Ok, to close this?

**Comment by Mr-Groch** [comment]
Yes, it can, thanks :)
