### ISSUE TITLE
(howto) build for krypton / debian

### ISSUE THREAD

**Issue by mrkapqa** [kodi-pvr/pvr.iptvsimple#335]
Hello ,

i am using Devuan Beowulf and the repository does not offer kodi-addon-iptvsimple or similar

how could i install iptvsimple addon ontop of Kodi 17.6 provided by Devuan repository?

Downloaded the branch 
`pvr.iptvsimple-Krypton`.zip

but don't know how to enable it. installing from zip inside kodi fails.

Thank you very much

**Comment by phunkyfish** [comment]
This is a binary addon, it must be compiled. You cannot install from zip. 

I’m afraid I don’t know how to compile the addon for kodi 17.

**Comment by svyaznoy362** [comment]
Good evening. I have installed spmc 17.6 version of iptv simple pvr 2.4.14, how do I upgrade to version 4.11.6

**Comment by mrkapqa** [comment]
me too would have another issue to be commented on:

have several single board computers,

and older ones running (raspberry pi) 

openelec (based on kodi 16, and also newer with 17) function well with iptvsimple -addon - channels get loaded when inserted the playlist.url from local eyetv iptv server running on macmini with macos 10.6 (samba v.1+2)

newer ones (rockchip and allwinner based) however, starting with kodi18+,
running libreelec instead of openelec, would still start iptvsimple add-on (included in libreelec repository), however, the channels would not load from the local eyetv iptv server resulting in zero channels.

This software i have installed on MacMini 
https://kodi.wiki/view/EyeTV_IPTV_Server

I can confirm with several Versions i tried on Libreelec that the channels do not get loaded when inserted with remote url via iptvsimple;
have not yet tried with manual m3u playlist insertion, but this should function also via url i think.

this has been tried with Libreelec (Kodi 18, 18.2 and 19 alpha) on both Rock64 and PineA64.


Maybe this is related with older samba on MacMini 10.6 i don't know, maybe there is error in the add-on?

If you show me how to i can try to create logfile to see where the error could lie?

Thank you.

**Comment by phunkyfish** [comment]
https://kodi.wiki/view/Log_file/Easy

This is probably something to do with security on the Mac. It’s probably not correctly setting something. But let’s see the log file first.

But please create your own issue. It’s not the same as this one.

**Comment by mrkapqa** [comment]
i am still investigating, considering opening a separate topic if nothing found

http://ix.io/2gPK

**Comment by mrkapqa** [comment]
as suspected, when i load manually .m3u file (got it from webinterface via bonjour on mac for netstream dtt), the channels get loaded.
problem is due to netstream4sat having no webinterface and therefore not able to export channel list as m3u playlist (so they state at geniatech), so i am able only to get the channels from DVB-T, which is ok, as long as the signal lasts.
