### ISSUE TITLE
Catchup: issue with playing from EPG for SIPTV lists (timeshift tag)

### ISSUE THREAD

**Issue by Mr-Groch** [kodi-pvr/pvr.iptvsimple#337]
When there is only `timeshift="x"` tag on list there is problem with playing from EPG when choosing current live programme. It will play using catchup URL from the beginning (start time of current programme), but on UI it will display prgress bar as like playing live.

**Comment by phunkyfish** [comment]
Could you email me a test M3U Entry?

**Comment by phunkyfish** [comment]
I assume the channel has an EPG?

**Comment by Mr-Groch** [comment]
email send and yes - it has EPG

**Comment by phunkyfish** [comment]
Do you have a screenshot. I used the example you sent and created two entries from it. One as `timeshift="x"` and one as `catchup="shift" catchup-days="5"`.

Both appear to function as expected.

**Comment by Mr-Groch** [comment]
After some more testing I have steps to reproduce this:

1. Chose programme from EPG and play from the beginning.
2. Stop playing and play same channel but as live
3. Notice that every time you try to play as live - stream will play from beginning of the current programme, but KODI player UI will show current live progress

**Comment by phunkyfish** [comment]
Testing across both examples the generated timestamps for both are correct as far as I can tell.

But on the second the programme length is way off if I choose an older EPG entry. This is very strange.

**Comment by phunkyfish** [comment]
On the second stream it's not opening the stream with ffmpegdirect as it doesn't know what format the video is in. Is this stream supposed to be opened by ffmpegdirect?

**Comment by phunkyfish** [comment]
If you add this prop:
`#KODIPROP:mimetype=video/mp2t`

That will tell it that's it's a TS stream and it will work.

With the next PR you could also add:
`#KODIPROP:inputstream.ffmpegdirect.mime_type=video/mp2t`

https://github.com/kodi-pvr/pvr.iptvsimple/pull/338

**Comment by phunkyfish** [comment]
Do you think the mime type can default to TS for shift type if it can't be determined?

**Comment by Mr-Groch** [comment]
No, SIPTV has no standard for streaming format. I have seen HLS and TS lists using SITPV timeshift tag. Maybe there should be possibility to manually choose stream type in plugin options - it will be used if stream type can't be detected or there is no `#KODIPROP` in m3u?

**Comment by phunkyfish** [comment]
HLS and dash can always be detected. It’s just that TS can not be. In this case choosing TS makes sense to me.

**Comment by Mr-Groch** [comment]
I've checked #338 - PR fixes this issue for me, thanks. I will close issue after it get merged :)
