### ISSUE TITLE
Base URL/path required for logos

### ISSUE THREAD

**Issue by Forst** [kodi-pvr/pvr.iptvsimple#34]
There are playlists that have full URLs in `tvg-logo`:
```
#EXTM3U
#EXTINF:0 tvg-logo="http://example.com/logo.png",Example
udp://@233.252.0.1:1234
```
 For those, there is no need to specify a base URL in settings. In that case however, the logos are not processed, since the plugin requires a base URL to be present (`src/PVRIptvData.cpp`, lines 970-971):
```c++
if (m_strLogoPath.empty())
    return;
```
I'm guessing that this requirement should either be less general or removed altogether.

**Comment by afedchin** [comment]
fixed in #64 and #65
