### ISSUE TITLE
Unable to load playlist file.

### ISSUE THREAD

**Issue by kodirovshchik** [kodi-pvr/pvr.iptvsimple#344]
https://paste.kodi.tv/ujiwijowew.kodi

I have the same problem with ubuntu, arch and debian builds. 

For me there is only one build where iptvsimple works - Flatpack build.

BTW, there is a 
strange note https://github.com/flathub/tv.kodi.Kodi in README.md

> Kodi flatpak build notes
> The following binary plugins do not compile, and are excluded:
> pvr.iptvsimple: requires rapidxml, which is only headers

[kodi.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/4399636/kodi.log)

**Comment by phunkyfish** [comment]
You are trying to run an old version of the addon in a later version of kodi I think.

EDIT: The M3U url appears unconnectable. Please delete you old addon data and reconfigure the addon it’s trying to load an old format settings.xml

**Comment by kodirovshchik** [comment]
I think I have have 3.9.8 iptvsimple from ppa:team-xbmc/ppa
> Package: kodi-pvr-iptvsimple
Priority: extra
Section: libs
Installed-Size: 598
Maintainer: Anton Fedchin <anightik@gmail.com>
Architecture: i386
Version: 3.9.8-1~bionic
Depends: libc6 (>= 2.17), libgcc1 (>= 1:4.2), libp8-platform2 (>= 1.0.10), libstdc++6 (>= 5.2), zlib1g (>= 1:1.1.4)
Filename: pool/main/k/kodi-pvr-iptvsimple/kodi-pvr-iptvsimple_3.9.8-1~bionic_i386.deb
Size: 183728
MD5sum: e85f6cf98d9891474d917bf3e381f1f9
SHA1: 168cd7d42e4164719d778f9d02e50d42be35fe85
SHA256: 223695de352c6f943d57d3e3d134e8b7ebb7066526c8133309ac860bde4ebe87
Description-en: Simple IPTV PVR for Kodi
 Simple IPTV PVR for Kodi
Description-md5: de335f773b0308282442ff1ef2515974

I deleted my old addon data. Here is log just after data was deleted (during reconfiguration):
https://paste.kodi.tv/atemosusup.kodi
[kodi.old.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/4399893/kodi.old.log)
Here is log after restart:
https://paste.kodi.tv/amalayeqez.kodi
[kodi.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/4399897/kodi.log)

Still not working. btw http://192.168.1.102:8085/m3u8 is a valid link, it works right now with iptvsimple addon from flatpak kodi build.

**Comment by phunkyfish** [comment]
If you save the content of the link locally and set it up as a local file instead what happens?

**Comment by kodirovshchik** [comment]
It works with a local file
https://paste.kodi.tv/eyoyefaviv.kodi
[kodi.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/4402470/kodi.log)

edit: 
I made a typo in the epg address. Fixed.
https://paste.kodi.tv/irebotijik.kodi
[fixed.kodi.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/4402500/fixed.kodi.log)

**Comment by phunkyfish** [comment]
Can you retrieve the file from the server using curl and see if the headers are the same?

This must be a nuance of a Linux flavour and some incompatibility with http.

**Comment by phunkyfish** [comment]
You could also try https

**Comment by kodirovshchik** [comment]
https doesn't work for me. I use https://www.hls-proxy.com/ to manage my iptv and http is how it is set. 

```
curl http://192.168.1.102:8085/m3u8 > test.m3u8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 64326    0 64326    0     0   190k      0 --:--:-- --:--:-- --:--:--  190k
```
[test.txt](https://github.com/kodi-pvr/pvr.iptvsimple/files/4403090/test.txt)
[playlist.txt](https://github.com/kodi-pvr/pvr.iptvsimple/files/4403091/playlist.txt)
I was unable to upload files as .m3u8, so i change it to .txt

there is a difference, but its a difference in links inside, so I assume its ok, and test.m3u8 works with vlc in windows.
![diff1](https://user-images.githubusercontent.com/62853236/77918683-e5926100-72a4-11ea-9cc8-c06b8a425733.png)
![diff2](https://user-images.githubusercontent.com/62853236/77918695-e88d5180-72a4-11ea-87a8-345ae1a6cda0.png)

**Comment by phunkyfish** [comment]
Can you show the headers from curl? So a curl -l?

**Comment by phunkyfish** [comment]
But why not just use the flat pack version?

**Comment by kodirovshchik** [comment]
> Can you show the headers from curl? So a curl -l?

Sorry. I was thinking about a file header =)
```
curl -I http://192.168.1.102:8085
HTTP/1.1 200 OK
Set-Cookie: userId=1585584294520; Max-Age=31536000; Path=/; Expires=Tue, 30 Mar 2021 16:04:54 GMT; HttpOnly
Content-Type: application/x-mpegURL; charset=UTF-8
Content-Disposition: attachment;filename=playlist.m3u8
Transfer-Encoding: chunked
Connection: close
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
Date: Mon, 30 Mar 2020 16:04:54 GMT
```
```
curl -I http://192.168.1.102:8085/epg
HTTP/1.1 200 OK
Set-Cookie: userId=1585584320548; Max-Age=31536000; Path=/; Expires=Tue, 30 Mar 2021 16:05:20 GMT; HttpOnly
Content-Type: application/octet-stream
Content-Disposition: attachment;filename=epg.xml.gz
Content-Length: 6503363
Date: Mon, 30 Mar 2020 16:05:20 GMT
Connection: keep-alive
```
```
curl -I http://192.168.1.102:8085/m3u8
HTTP/1.1 200 OK
Set-Cookie: userId=1585584329488; Max-Age=31536000; Path=/; Expires=Tue, 30 Mar 2021 16:05:29 GMT; HttpOnly
Content-Type: application/x-mpegURL; charset=UTF-8
Content-Disposition: attachment;filename=playlist.m3u8
Transfer-Encoding: chunked
Connection: close
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
```

> But why not just use the flat pack version?

Yes, i'm using it for about half of a year, but i was want to try an official build. 
Edit: And flatpak build has iptvsimple 3.7.2 and kodi 18.4. And if they can`t (as mentioned in their readme) compile iptvsimple for a new builds i'll have a huge problem =)

Edit2: Ok, this http link works for me (XXXXXXXX - edited key)
```
curl -I http://spacetv.in/playlist/XXXXXXXX/m3u
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 30 Mar 2020 19:51:38 GMT
Content-Type: audio/mpegurl; charset=UTF-8
Connection: keep-alive
X-Powered-By: PHP/5.4.16
Access-Control-Allow-Origin: *
Content-Disposition: attachment; filename=playlist.m3u
```

What is the difference?

**Comment by phunkyfish** [comment]
Not sure. Can you change the file name used  on your local server? I wonder is it setting the wrong content type or something like that.

**Comment by kodirovshchik** [comment]
> Can you change the file name used on your local server?

It takes a while, but now I can =) I changed "playlist.m3u8" to "testedchange.m3u"
```
curl -I http://192.168.1.39/m3u8
HTTP/1.1 200 OK
Set-Cookie: userId=1586186567110; Max-Age=31536000; Path=/; Expires=Tue, 06 Apr 2021 15:22:47 GMT; HttpOnly
Content-Type: application/x-mpegURL; charset=UTF-8
Content-Disposition: attachment;filename=testedchange.m3u
Transfer-Encoding: chunked
Connection: close
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
Date: Mon, 06 Apr 2020 15:22:47 GMT
```
It looks like nothig have changed for me.

https://paste.kodi.tv/iboxinujav.kodi

[kodi.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/4439321/kodi.log)

**Comment by phunkyfish** [comment]
What is the application that is serving the playlist?

**Comment by kodirovshchik** [comment]
> What is the application that is serving the playlist?

https://www.hls-proxy.com/

Option to edit playlist name was enabled yesterday in v6.2.0 =)

**Comment by phunkyfish** [comment]
So does it work now?

**Comment by kodirovshchik** [comment]
> So does it work now?

Yes. Issue was in my hls proxy app (only for 32 bit version). It was fixed couple hours ago =)
