### ISSUE TITLE
EPG Timeshift doesn't work

### ISSUE THREAD

**Issue by timkhadnevich** [kodi-pvr/pvr.iptvsimple#351]
Hi,
I couldn't manage to make EPG timeshift to work on following verisons:
Kodi 1.8.6 Leila
PVR iptv simple client 3.9.8

I tried both on Windows and Android.

I followed advice like to clear cache and reinstall client. I even tried to set timeshift inside the m3u8 playlist, but it still doesn't work.

**Comment by phunkyfish** [comment]
What do you mean by timeshift? You mean just changing the time zone of the EPG data?

**Comment by timkhadnevich** [comment]
Yes. The time shift in epg settings for epg data.

**Comment by phunkyfish** [comment]
Which timeshift value are you trying to use? I.e what time zone is your epg in and what timezone are you in?

Have you cleared the EPG data in PVR settings in kodi?

**Comment by timkhadnevich** [comment]
This is the epg Im using:
http://epg.it999.ru/edem.xml.gz

It should be GMT +3 (Moscow). I use it from Australia GMT +10. I set slider
to -7 in settings but effect is the same as 0.

**Comment by phunkyfish** [comment]
Should that not be +7 for austailia?

**Comment by timkhadnevich** [comment]
Yes, you are right. it should be +7, my mistake, however, it seems that it still not working as time for programs doesn't shift at all if I set +7, 0 or -7. Restarted kodi and cleaned cache.

**Comment by phunkyfish** [comment]
How exactly are you cleaning the cache?

**Comment by timkhadnevich** [comment]
I clear the cache using Settings -> PVR&Live TV -> Guide - > Clear Data

I just tried again to set 0 and cleared the cache. Somehow this time it fixed the issue. I did it on Windows. I'll do the same on Android later today.

**Comment by timkhadnevich** [comment]
I have tried on Android. Setting it to 0 and "Clear Data" afterwards eventually  did the trick.
Thank you so much for your assistance.
