### ISSUE TITLE
XML/tag - How to set Rating Age?

### ISSUE THREAD

**Issue by macamba** [kodi-pvr/pvr.iptvsimple#362]
Hi all,

I would like to set the Rating Ages but I didn't see any information about

These are the values I have;

infantile
all audiences
> 7 years old
> 12 years old
> 16 years old
> 18 years old

Regards

**Comment by macamba** [comment]
Ok I saw that this option is disable in code, EpgEntry.cpp "left.iParentalRating     = 0;     /* not supported */"

**Comment by phunkyfish** [comment]
That might be that the addon does not support it or Kodi PVRs implementation doesn’t match the XMLTV spec.

I think XMLTV only support text ratings but kodi’s is a number if I recall.

**Comment by macamba** [comment]
> That might be that the addon does not support it or Kodi PVRs implementation doesn’t match the XMLTV spec.
> 
> I think XMLTV only support text ratings but kodi’s is a number if I recall.

What do you mean exactaly? Is there some way to add parental age?

**Comment by phunkyfish** [comment]
The parental rating in kodi pvr is an integer. XMLTV uses a text rating which I just checked in the DTD.

Do you have an example piece of XML?

**Comment by macamba** [comment]
Hi phunkyfish,

I'm not expert but I'm trying to organize all the provider information to show correctly in Kodi pvr but I  don't get all them are shown

You can find here 24hr example m3u, xmltv and screen-shots how is shown in my kodi
https://drive.google.com/drive/folders/13Eu9RSYnAvWqA9aWZ7fbn2j5oBxLsi87?usp=sharing

This is an example code and these are the tags no shown;
- date. I only have year not month and day
- episode-num system="onscreen". It's show in other skin
- star-rating
- rating system="es"

https://pastebin.com/Jy9VbkcD


I hope you know how to get set correctly the xml, if not then I'll have to put all the information in Description

Thanks

**Comment by phunkyfish** [comment]
I think this is a skin problem. Those values need to be displayed by the skin.

Please try estuary (but it does not show star rating either).

**Comment by macamba** [comment]
Well I tried already and only shows episode-num system="onscreen" all the rest are not shown
