### ISSUE TITLE
EPG genre colours 

### ISSUE THREAD

**Issue by macamba** [kodi-pvr/pvr.iptvsimple#364]
Hi all,

I checked the way the addon let set the colours in epg by category and it's good for the people have the same o similar categories like standard but for all the rest it doesn't make much sense.

Standard Genres Kodi -> https://pastebin.com/QCA0gpPz
My provider List -> https://pastebin.com/WiH4MSdD

If I try to map my list repect the kodi one then I'll missing the exactly information of my provider, besides, it would be very tedious to try to adjust my list with kodi one.

So, it would be easier give the posibility to set the color in TvGuide.xml directly in tag with some reference color id list;
List colors:
16 - Red
32 - Green
64 - ...

**`<category colorId="16">Cine / Acción</category>`**

Could be posible implement something like this in addon?

Regards

**Comment by phunkyfish** [comment]
I’m afraid not. The XMLTV has a DTD and we obey it and any inferred standards.

There is already a mechanism to configure the EPG colours in the addon.

**Comment by macamba** [comment]
It's a shame, because really help to users define their own list and colors, it'd do so much best the addon adding one way more to set it.


If I try to set by the current way I'll missing genres/subgenres descriptions and details likes these;

Series / Adventures and fantastic
Short film
Suspense
Animation
TV soaps
animation
Erotic
Motorcycling
Cycling
Golf
Hunting
fishing
Travels
....and a long etc

**Comment by phunkyfish** [comment]
what’s wrong with the feature in the addon right now? You can set a category and customise the text.

**Comment by macamba** [comment]
Oh yes?
Well, I'm going to explain you what I'm doing

I created a genres.xml in ..\user\AppData\Roaming\Kodi\userdata\addon_data\pvr.iptvsimple like this;

```
<genres>
<name>My List</name>
<genre type="16" subtype="0">Deportes / Automovilismo</genre>
<genre type="32" subtype="0">Documentales / Ciencia y tecnología</genre>
</genres>
```
And I set the genres in my tvGuide.xml like this

`<category lang="es">Deportes / Automovilismo</category>`
or
`<category lang="es">Documentales / Ciencia y tecnología</category>`

But the result is that https://drive.google.com/open?id=1SQS8UR-n4jHiLOTCZOtG33MVTwIoT4Di

What am I doing wrong?

Thanks

**Comment by phunkyfish** [comment]
Which version of kodi are you using?

**Comment by macamba** [comment]
I'm testing in this version

Kodi (18.5 Git:20191116-37f51f6e63). Platform: Windows NT x86 64-bit
Kodi compiled 2019-11-16 by MSVC 191627034 for Windows NT x86 64-bit version 10.0 (0x0A000006)

**Comment by phunkyfish** [comment]
I think custom colours will only work in Matrix.

**Comment by macamba** [comment]
I passed to Kodi matrix but the result is similar
https://drive.google.com/open?id=1dihszXCbl5vP_VAyW1ZBXBZSIggpUJ5X
I removed the tilde to recognize the second one and atribute lang

```
<category>Deportes / Automovilismo</category>
or
<category>Documentales / Ciencia y tecnologia</category>
```

Really what am I doing wrong? or are you sure that I can show my custom genre text?

Thanks

**Comment by phunkyfish** [comment]
If you send me an M3U (it doesn't need to play), genres.xml and an XMLTV
that will be still valid on Monday I will take a look then and see if I can
figure out what's wrong with it.

**Comment by macamba** [comment]
Thanks for support, I'll do it

**Comment by phunkyfish** [comment]
Can you send this to me?

**Comment by macamba** [comment]
Hi phunkyfish,

Sorry I was going to send it to you later because I'm working anyway I've just updated and uploaded the files here;
genres.xml
ChannelDetails_Local.m3u
EPGDetailsTvGuide_1_Local.xml

https://drive.google.com/drive/u/2/folders/13Eu9RSYnAvWqA9aWZ7fbn2j5oBxLsi87

Thanks

**Comment by phunkyfish** [comment]
Your files work perfectly for me on the estuary skin.

![Screenshot 2020-04-27 at 14 34 47](https://user-images.githubusercontent.com/4601187/80378248-486f1c00-8894-11ea-8294-fc06a999b9d9.png)

**Comment by phunkyfish** [comment]
In Matrix you need to enable this in the addon settings

**Comment by macamba** [comment]
You're right, I have to active the flag to using mapping genres.
Thanks so much phunkyfish for your help and patience :)

**Comment by phunkyfish** [comment]
No problem. You’re welcome.
