### ISSUE TITLE
Issue installing add-on on Ubuntu 20.04

### ISSUE THREAD

**Issue by Neelix57** [kodi-pvr/pvr.iptvsimple#366]
After upgrade to Ubuntu 20.04 (at least with Xubuntu), when installing Kodi from kodi's ppa, I couldn't install kodi-pvr-iptvsimple.
Got the error :

" packages have unmet dependencies: kodi-pvr-iptvsimple : Depends: kodi-api-pvr (= 5.10.3)"

**Comment by phunkyfish** [comment]
The PVR api was recently updated. It may take a day or so for the PPA to get updated.

**Comment by appsjohn** [comment]
I got the same issue where i was not able to install some of the Kodi add-ons

(Edited by moderator)

**Comment by phunkyfish** [comment]
Please don’t mention of the use of piracy services nor ask for any support if you use them.

**Comment by confusionists** [comment]
same problem here. after upgrading to xubuntu 20.04 i cannot install kodi-pvr-iptvsimple. Please fix.

**Comment by phunkyfish** [comment]
See here: https://forum.kodi.tv/showthread.php?tid=353985&highlight=ubuntu+focal

In short, your repo is messed up, or it's not trying to install the package from the Kodi PPA.

BTW, these kinds of questions should be asked on the forum. We try to keep github for bugs.
