### ISSUE TITLE
Archive/Catchup play from beginning

### ISSUE THREAD

**Issue by Sorien** [kodi-pvr/pvr.iptvsimple#368]
maybe it's not right tracker but there seems to be missing PVR feature in Kodi/IPTVsimple, many users are asking me all the time how can they play current live programme from the beginning.

now when there is archive support it should be pretty straightforward to implement.

**Comment by phunkyfish** [comment]
That is already supported. Just disable  **Catchup only available on finished programmes** in addon settings.

I think you asked for that setting originally. 

Then from the guide just use play programme to play the current live programme from the start.

**Comment by Sorien** [comment]
oh, but I remember that there was some problem with that, something like that live URL was different from catchup URL and catchup URL was used for LiveTV playback, to solve that I asked for that settings.

or maybe not, hard to remember, will try it, sorry for the noise.

**Comment by phunkyfish** [comment]
It should all work as you expect now.

**Comment by phunkyfish** [comment]
If not let me know.
