### ISSUE TITLE
Channels not loading / EyeTV IPtv-server + libreelec client

### ISSUE THREAD

**Issue by mrkapqa** [kodi-pvr/pvr.iptvsimple#372]
Hello ,

i use a MacMini 09 as a IPTV Server (and with AFP, FTP, Samba Shares enabled)
for EYETV Netstream DTT (DVB-T(2)) and Netstream 4Sat (DVB-S2)
and noticed the following behaviour:

with **OpenELEC** 7 as a client, PVR-Iptvsimple loads correctly all channels when inserted URL (tested on Raspbery Pi1,2,AppleTV1)
With **Kodi** as client, on Windows 7, PVR-Iptvsimple loads correctly the channels, but with newer IPTVsimple (like on Kodi 18.6) zapping through channels is very slow.
With **LibreELEC** newer builds (Libreelec 9.2.1 for Raspberry Pi2, Rock64) (Libreelec NIghtly for Pine A64) there the channels won't load at any rate when inserted an URL, unless i would load channel list from a M3U file.

How could i enable the Libreelec build to load the channel list from URL?

I noticed some other behaviour on Libreelec (like problem accessing Samba Share on A64 NightBuild and failure to playback DVD-Folders from complete DVD Rips)

If there is a way i would also like to enable the playback on newer Kodi for IPTVsimple with Layout like on Jarvis - this seems much more intuitive for playing back the TV CHannels and changing channels on the fly.

Thank you

**Comment by phunkyfish** [comment]
Full debug log please? You may need to ask this question on the LibreElec forum though. But let’s see the log first.

Regarding looking like Jarvis I am afraid not and that has nothing to do with the addon anyway. That’s Kodi 😉

Also, please use the forum if you have general kodi questions. This project is for the addon only.

**Comment by mrkapqa** [comment]
Yes, thank you, i am asking also in the LibreElec Forum!

https://paste.ubuntu.com/p/FKJWMQmxfV/

**Comment by mrkapqa** [comment]
this is the log for the same device (raspi2 b+) now with openelec 7

https://paste.ubuntu.com/p/CkcXV7j7JN/

**Comment by mrkapqa** [comment]
This is the log for Kodi 18.6 on Windows 7 (which is also loading correctly the channels from URL using Pvr Iptvsimple 3.9.8)

http://paste.kodi.tv/muyajodili

**Comment by mrkapqa** [comment]
> Regarding looking like Jarvis I am afraid not and that has nothing to do with the addon anyway. That’s Kodi 
> 

Thanks, as suggested by someone @LibreElec Forums, changing the Skin to "confluence" enable the TV like Style that i found more comfortable.

**Comment by phunkyfish** [comment]
You have a bad install. It's not loading the addon at all.

Can you try installing the kodi 19 version of LibreElec and see does that work:

https://forum.kodi.tv/showthread.php?tid=343068

**Comment by mrkapqa** [comment]
Thanks, i tried to update via .tar file ,
however,

the pvr-iptvsimple update included would not update due to missing
dependency.

also, the mac-discovery via wake-on-lan is not functioning:

the error i get is:


MAC discovery failed for 192.168.1.84,


however, my Mac Network IP is 192.168.1.204?

**Comment by phunkyfish** [comment]
What tar file did you use? Can you provide the link?

**Comment by mrkapqa** [comment]
http://milhouse.libreelec.tv/builds/master/RPi2/LibreELEC-RPi2.arm-9.80-Milhouse-20200412210522-%230412-g0365c1e.tar


also i noticed the same behaviour as with Allwinnner A64 Nightly image
(Matrix based) >

Samba Share from MacMini would no longer function (error inside Zeroconf
is "software caused connection abort")

**Comment by phunkyfish** [comment]
That’s a old image. Why not a more recent one? Maybe try the first version from May tomorrow.

You will probably also need to set the samba compatibility version to SMB1 in LibreElec settings.

**Comment by mrkapqa** [comment]
Thanks, i tried the most recent one first, with the same result.

Will check again and report.

**Comment by phunkyfish** [comment]
That is strange. I have an RPi3 and it works ok. Do you have a log?

**Comment by mrkapqa** [comment]
I tried to "refresh" Kodi with FreshStart from dimitrology repo but that
did not function either (missing xbmc.python2 somewhat dependency)

https://www.wirelesshack.org/how-to-clear-old-data-from-kodi-and-have-a-fresh-start-install.html

**Comment by phunkyfish** [comment]
LibreElec already lets you do this. You do not need any extra addons. Just go to the LibreElec setting and it will let you fully reset.

**Comment by mrkapqa** [comment]
Thanks, i will try.

https://paste.kodi.tv/oxexipukar.kodi

**Comment by mrkapqa** [comment]
Thanks, with the Re'Set now the PVR Iptvsimple now loads in the newer version, however the channels do not load.
Also, the Kodi Log'File Uploader does not upload the Logs (around 100 to 150 kb)

The Version of PVR Iptvsimple however states Version 999.4.11.6 and when i click "update" it would show "4.11.1.1" but the update would not succeed.

**Comment by mrkapqa** [comment]
now i could upload .log of the latest version .430 for raspi2 with pvr-iptvsimple apparently installed and functioning

https://paste.kodi.tv/xavexagebu.kodi

**Comment by mrkapqa** [comment]
one thing to add: on the macmini running the eyetv iptvserver, i disabled "IPv6" but that should not make a difference regarding this error?

Also: setting the Samba to v1. for minimum and v2. for maximum did not solve the problem with SAMBA Shares (as noticed previously);
the Samba Shares would show up in Zeroconf browser, but clicking on the "macmini (SAMBA)" would result in "Software caused connection abort".
On LibreElec v.9.2.1 this would still function.
@libreElec it was suggested to set up a different approach but that seems a bit tedious to me; would be nice if it could still function 
https://forum.libreelec.tv/thread/21717-jarvis-libreelec7-0-for-rock64/?postID=138820#post138820

**Comment by mrkapqa** [comment]
This is a log from A64 running LibreElec Nightly (Matrix 19) with PVR Iptvsimple 4.8.4.1

https://paste.kodi.tv/kolatiguce.kodi

**Comment by mrkapqa** [comment]
This is log from Rock64 running LibreElec 9.2.1 with PVR Iptvsimple 3.9.8.1 

https://paste.kodi.tv/ubuhajupem

**Comment by phunkyfish** [comment]
Your server is not returning anything:

```
2020-05-02 11:45:46.911 T:2873    INFO: easy_acquire - Created session to http://192.168.1.204
2020-05-02 11:45:46.914 T:2873   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
2020-05-02 11:45:46.914 T:2873   ERROR: CCurlFile::Open failed with code 0 for http://192.168.1.204:9898/playlist.m3u8:
2020-05-02 11:45:46.914 T:2873   ERROR: Open - failed to open source <http://192.168.1.204:9898/playlist.m3u8>
2020-05-02 11:45:46.915 T:2873   ERROR: AddOnLog: PVR IPTV Simple Client: pvr.iptvsimple - LoadPlayList - Unable to load playlist cache file 'http://192.168.1.204:9898/playlist.m3u8':  file is missing or empty.
2020-05-02 11:45:46.915 T:2873    INFO: AddOnLog: PVR IPTV Simple Client: Start Starting separate client update thread...
```

**Comment by mrkapqa** [comment]
yes, however when i change SDcard back to OpenElec 7 (Raspi 2) it is functioning normally, channels do load. No change at all needed on MacMini Serverside.

**Comment by mrkapqa** [comment]
`
12:33:34  15.273273 T:1886585760   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
12:33:34  15.273549 T:1886585760   ERROR: CCurlFile::Open failed with code 0 for http://feeds.openelec.tv/news
12:33:34  15.551482 T:1786770336  NOTICE: AddOnLog: PVR IPTV Simple Client: Loaded 854 channels.
12:33:35  15.776573 T:1674572704  NOTICE: Start - EPG thread started
12:33:36  16.808987 T:1592779680  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
12:33:41  22.277174 T:1886585760   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
`

**Comment by mrkapqa** [comment]
this is log with OpenElec 7 on Raspi

https://paste.kodi.tv/ihicakotel.kodi

12:33:34  15.273273 T:1886585760   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
12:33:34  15.273549 T:1886585760   ERROR: CCurlFile::Open failed with code 0 for http://feeds.openelec.tv/news
12:33:34  15.551482 T:1786770336  NOTICE: AddOnLog: PVR IPTV Simple Client: Loaded 854 channels.
12:33:35  15.776573 T:1674572704  NOTICE: Start - EPG thread started
12:33:36  16.808987 T:1592779680  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
12:33:41  22.277174 T:1886585760   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)

**Comment by phunkyfish** [comment]
Did you get this working eventually?

**Comment by mrkapqa** [comment]
it would function on openelec 6, or jarvis, but not with newer versions (eg. krypton onwards)
i don't know why, but havent tried some time now.
have a functional matrix on rock64, might wanna try and let you know. happy easter!

**Comment by phunkyfish** [comment]
Ok, I will close this issue. Please reopen if you find out anything new.
