### ISSUE TITLE
(appleTV1/openelec6.0.1) pvr iptvsimple not installing

### ISSUE THREAD

**Issue by mrkapqa** [kodi-pvr/pvr.iptvsimple#374]
Hello ,

i wanted to ask if it is possible to download a functional 

PVR Iptvsimple add-on for AppleTV1?

I do have OpenElec 6.0.1 installed but the bundled PVR Iptvsimple would not install.
OpenElec 6.0.1 corresponds to Kodi 15.2 Isengard.

Thank you very much.

**Comment by kekukui** [comment]
OpenELEC is not being maintained.  And I do not see any builds of OpenELEC for iOS on their web site.  Where did you get this from???  The official Kodi web site has current iOS builds, and OSMC has one that specifically claims to support the first generation Apple TV.  Why are you not using one of those???

https://kodi.tv/download
https://osmc.tv/download

**Comment by phunkyfish** [comment]
@mrkapqa please don’t use GitHub for support questions. It should be used for bugs only.
