### ISSUE TITLE
(ubuntu20.04) pvr-iptvsimple not showing up

### ISSUE THREAD

**Issue by mrkapqa** [kodi-pvr/pvr.iptvsimple#375]
Hello ,

i have a Computer running Ubuntu 20.04 and installed Kodi + Kodi-Pvr-Iptvsimple via terminal command.

When i start Kodi however, no Pvr-Iptvsimple does show up in the add-ons folder.

Where could i possibly find it?
I know it should be posted in the Ubuntu forum but i'll try my luck here first.

Thank you very much.

**Comment by mrkapqa** [comment]
found, but add-on couldn't be loaded?

**Comment by kekukui** [comment]
> **installed Kodi-Pvr-Iptvsimple via terminal command... Where could i possibly find it?**

https://kodi.wiki/view/PVR/Basics

> **I know it should be posted in the Ubuntu forum**

No, it should be posted in the Kodi forum: https://forum.kodi.tv
