### ISSUE TITLE
Edit Style of tag Description

### ISSUE THREAD

**Issue by macamba** [kodi-pvr/pvr.iptvsimple#377]
Hi all,

I didn't see any to edit the style font. for example is it possible to do something like this?

```
<programme channel="717" start="20200503030000 +0200" stop="20200503034500 +0200">
 <title lang="es">The game show</title>
 <desc><strong style="color: #FC9CF9;">Presentador:</strong> Gemma Manzanero, Cristina Porta
Espacio conducido por Cristina Porta, Gemma Manzanero y Aitor Fernández en el que se repasan las mejores estrategias de juego para la Ruleta, el Black Jack y el Poker.</desc>
 <category>Documentales / Ciencia y tecnologia</category>
 <icon src="http://192.168.1.53:21583/Land-5040/50400648.jpg"/>
</programme>
```

As appearance this https://raw.githubusercontent.com/guiniguada/Guiniguada-EPG/master/Files/Imagenes/4.png

Regards

**Comment by phunkyfish** [comment]
You cannot do this. The addon reads text only from fields and passes it to kodi. How the text is displayed is up to the skin being used and nothing to do with the addon.

**Comment by macamba** [comment]
ok, thanks
