### ISSUE TITLE
Ability to pause  and navigate back the live timeshift stream

### ISSUE THREAD

**Issue by basilgello** [kodi-pvr/pvr.iptvsimple#378]
My paid IPTV provider has two types of TV streams: live and timeshift.

Live stream is the HLS stream with 60 second sliding window:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:821075
#EXT-X-TARGETDURATION:4
#EXTINF:4.000,
tv-821075.ts
#EXTINF:4.000,
tv-821076.ts
#EXTINF:4.000,
tv-821077.ts
#EXTINF:4.000,
tv-821078.ts
#EXTINF:4.000,
tv-821079.ts
#EXTINF:4.000,
tv-821080.ts
#EXTINF:4.000,
tv-821081.ts
#EXTINF:4.000,
tv-821082.ts
#EXTINF:4.000,
tv-821083.ts
#EXTINF:4.000,
tv-821084.ts
#EXTINF:4.000,
tv-821085.ts
#EXTINF:4.000,
tv-821086.ts
#EXTINF:4.000,
tv-821087.ts
#EXTINF:4.000,
tv-821088.ts
#EXTINF:4.000,
tv-821089.ts
```

Timeshifted stream is 3 hours (10800 seconds, 1080 segments * 10 seconds each):

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:8399660
#EXT-X-TARGETDURATION:11
#EXTINF:10.000,
tv-8399660.ts
#EXTINF:10.000,
tv-8399661.ts
...
#EXTINF:10.000,
tv-8400739.ts
```

How is it possible to go back and forth within the sliding window (3 hours) and switch to live broadcast (say, stream end minus 10 seconds if no separate URL for live stream declared, or to live stream if it is)?

**Comment by phunkyfish** [comment]
Do they provide a URL to jump to a time during that 3 hours? Or it is simply a delayed live stream or a VOD stream?

**Comment by basilgello** [comment]
> Do they provide a URL to jump to a time during that 3 hours? Or it is simply a delayed live stream or a VOD stream?

The latter. No jump specifying catchup urls (lutc, utc, h:m:s etc). 

The url is `https://xxx/timeshift.m3u8` accepting no parameters.

The goal is to detect the length of stream (maybe in ffmpegdirect or in iptvsimple) and update EPG played accordingly, but it is my attempt to derive a solution ;)

**Comment by phunkyfish** [comment]
If it’s a VOD stream try loading it in regular IPTV simple and see if you can seek.

I have not added VOD support to ffmpegdirect yet. But when it’s added it should be possible to supply an offset so you can align it with an EPG programme.

**Comment by basilgello** [comment]
It is a delayed live stream. Connection to Github is unstable tonight, so sorry for possible double-posting in advance.

**Comment by basilgello** [comment]
> If it’s a VOD stream try loading it in regular IPTV simple and see if you can seek.
> 
> I have not added VOD support to ffmpegdirect yet. But when it’s added it should be possible to supply an offset so you can align it with an EPG programme.

It is a delayed live stream. Catchup streams played from EPG window are seekable just fine, but there is catchup-id and they are loaded by Kodi's built-in ffmpeg, not ffmpegdirect or adaptive.

Delayed live streams can not be even paused using ffmpegdirect but can be using adaptive for HLS.
But no seeking back using adaptive. Plus another couple of bugs I am gonna fix in the next few days in adaptive :)

**Comment by phunkyfish** [comment]
If you can’t seek back then it’s not VOD.

But hold on. It’s works in kodi?

**Comment by basilgello** [comment]
That is the question. The same stream seeks well using ffplay and vlc, as well as exoplayer from the provider's website.
I can send you the stream getter by email.

**Comment by phunkyfish** [comment]
Ok, so maybe I can just copy what they do in ffplay and that should work.

**Comment by basilgello** [comment]
Check your private email please. The stream getters are in your inbox (or spam folder, if I am unlucky) :)

**Comment by phunkyfish** [comment]
Got them, thanks.
