### ISSUE TITLE
[IMPROVEMENT] Treat VOD entries in M3U playlist as recordings not live TV channels

### ISSUE THREAD

**Issue by basilgello** [kodi-pvr/pvr.iptvsimple#379]
## Rationale

VOD videos should be treated as recordings, not live channels to solve two issues:

1. In playlists the number of VOD videos is significantly greater than the number of live TV channels. If VOD videos are treated as live TV channels, the EPG update logic tries to get EPG entries for them all for every moment and such slows down the overall Kodi experience.

2. The VOD video is, by nature, a video, so it has only one EPG tag describing the video, not the set of sequential EPG tags describing the EPG for a live channel during the day. The user can watch VOD at any time, while EPG tags are bound to `start` and `stop` attributes.

That's why treatng M3U entries with `#EXT-X-PLAYLIST-TYPE:VOD` as recordings would greatly improve the user experience (either with Kodi leanback UI or remotes like Kore / Yatse) and offload the EPG tag parsing logic from unnecessary parsing EPG tags for all VODs found.

**Comment by phunkyfish** [comment]
Good idea. We have the C++ API coming in soon. Let me see when that is. It might be easier to get that in before adding this.
