### ISSUE TITLE
Incorrect time in EPG

### ISSUE THREAD

**Issue by mark-veenstra** [kodi-pvr/pvr.iptvsimple#38]
If I am correct an incorrect time is displayed in the EPG.

For example. I have generated an EPG XMLTV as follows: http://epg.cheapwhisky.nl/guide.xml. You can see that for the most program information there is a UTC offset displayed:

```
<programme start="20150811133000 +0200" stop="20150811143000 +0200" channel="Sky Sport 1 HD">
```

All the information with a offset `+0200` are grabbed from the source `tvgids.tv` which is in a UTC offset of +0200. Which is correct. I am also located in UTC offset +0200 (CEST). So my Kodi will show me that the starttime/stoptime would not change.

I also grab some information from the source `tvguide.co.uk`, like:

```
<programme start="20150811140000 +0100" stop="20150811150000 +0100" channel="YESTERDAY">
```

This source site is in UTC offset +0100. Which is one hour behind my local time. So the EPG should be added 1 extra hour to display it all correct. It seems like the IPTV Simple Client isn't adding this extra hour.

**Comment by goyney** [comment]
Have you tried setting the time shift at the top of your M3U file?

    #EXTM3U tvg-shift=1

The number is the amount of hours your want to shift your EPG data.

**Comment by mark-veenstra** [comment]
That does the trick, but I am wondering if that would be the nicest thing to do from an user point of view?
Most user receive an M3U from their supplier and the EPG data can be grabbed from anywhere of the internet. So you never now upfront if the `tvg-shift` should be `1` or `5` or even `-7`.

Would it be possible to add this to the M3U based on the EPG? For example. If the local time zone is UTC +0200 and in the EPG data it is UTC +0100, then you know that `tvg-shift=1` should be added.

**Comment by krogsbell** [comment]
#EXTM3U tvg-shift=1

Worked for me with Kodi 17

I used to have a setting of timeshift -1 which do not work anymore

**Comment by nerijus** [comment]
#EXTM3U tvg-shift=1 does not work anymore with Kodi 17.3.

**Comment by Jalle19** [comment]
Closing this since there seems to be some sort of solution
