### ISSUE TITLE
WARNING: ActiveAE - large audio sync error and crash

### ISSUE THREAD

**Issue by Serrous** [kodi-pvr/pvr.iptvsimple#380]
Hello, friends

I use the kodi-pvr-iptvsimple (3.8.8-1~buster) and I face with periodical problem; during 
while watching tv channels sometimes a lot of errors occur in the logs such as: 

<...>
WARNING: ActiveAE - large audio sync error: -89410.650957
WARNING: ActiveAE - large audio sync error: -89440.703156
WARNING: ActiveAE - large audio sync error: -89442.816636
NOTICE: CVideoPlayerAudio::Process - stream stalled
NOTICE: CVideoPlayer::OnExit()
NOTICE: VideoPlayer: eof, waiting for queues to empty
NOTICE: Closing stream player 1
NOTICE: CDVDMessageQueue(audio)::WaitUntilEmpty
NOTICE: Waiting for audio thread to exit
ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
NOTICE: thread end: CVideoPlayerAudio::OnExit()
NOTICE: Closing audio device
ERROR: CActiveAEStream::Drain - timeout out
NOTICE: Deleting audio codec
NOTICE: Closing stream player 2
NOTICE: CDVDMessageQueue(video)::WaitUntilEmpty
NOTICE: waiting for video thread to exit
ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
NOTICE: thread end: video_thread
NOTICE: deleting video codec
NOTICE: CVideoPlayer::CloseFile()
<...>

These errors occur at different intervals and sometimes this leads to the termination of the channel or, in special cases, to constant synchronization of the stream and freezing. 

I couldn’t find a clear compilation of this behavior anywhere - what is the reason for this error? Is this due to some problems on the server side or do I need to configure something on my server to avoid this? 

I tried to increase the buffer through advancedsettings.xml, but this did not any result. I use kodi 18.6, IPTV Simple PVR add-on 3.8.8. The problem occurs with local or remote m3u(8) files. OS: ArchLinux and Raspbian (Raspberry 4 model B). 

I would be grateful if you explain the cause of this error and tell me how to fix it.

With best regards

**Comment by phunkyfish** [comment]
It’s usually as a stream is not of of high enough quality or you have a poor connection.

**Comment by Serrous** [comment]
> It’s usually as a stream is not of of high enough quality or you have a poor connection.

Thank you for quick reply. I tested this theory - I watched the network on my router + logs + other devices - my internet channel is stable - i have 350 Mbps (I think this is enough :) ). At the same time I open the same playlist and the same channel in the VLC-player and there are no problems - no brakes, no freezes. (sometimes, however, a break occurs anyway, but this is rare and the reason is clear here - the broadcast server may be unavailable for a short time). 

I noticed one thing: vlc player plays the video with a delay of 3-5 seconds, unlike the kodi pvr simple client. One gets the feeling that it "slows down" the playback of the stream in order to put more data in the buffer, thereby avoiding constant synchronization during playback (it seems to me that the PVR client plays the stream faster than it manages to receive the data - the audio stream does not have time to transmit the whole ) Is it possible to “slow down the playback” so that when the connection from the broadcast server is slow, it is possible to put more data into the buffer?

**Comment by phunkyfish** [comment]
I’m not sure on this. Kodi will try to play this live, so as close to real-time as possible. It’s not your bandwidth is the issue it’s the speed at which the stream is served. So the provider is not sending it fast enough. 

I wonder if the provider is sending this data in bursts so the gaps are apparent in kodi but not in VLC.

**Comment by Serrous** [comment]
Yes, you are right. I changed my IPTV provider (from free to paid, for tests) and now the error in the logs is gone - the stream has become stable. Current bandwidth between server and Kodi for channel with HD quality about 20 Mbps. In some cases, the error still occurs, but here I clearly see a low reception rate in network monitor.

What about:
>I wonder if the provider is sending this data in bursts so the gaps are apparent in kodi but not in VLC.

Can I find out for myself? In other words, will this information be useful for further improvements in PVR IPTVsimple or KODI? I think it would be great if KODI could work with gaps at a low transfer rate from the content server.

**Comment by phunkyfish** [comment]
This would be a feature that doesn't exist in kodi today, I don't know what would be inolved in adding it. Generally though if you pay for a good service you get it.

There is some reconnection logic in the Matrix version of the addon but that's for reconnecting if a stream drops. It will deal with a disconnection of less than 4 seconds.

**Comment by Serrous** [comment]
OK, thanks a lot for information. I got an answer to my question, the discussion can be closed.
