### ISSUE TITLE
I don't get install addon

### ISSUE THREAD

**Issue by macamba** [kodi-pvr/pvr.iptvsimple#383]
Hi,

I tryed to update the addon but it returned error dependancy so I uninstalled the kodi and removed folder "C:\Users\USER\AppData\Roaming\Kodi" but it doesn't let me install it.

Only see this reference in Kodi.log respect this issue:

2020-05-08 22:04:42.193 T:948     ERROR <general>: CAddonInstallJob[pvr.iptvsimple]: No se puede satisfacer la dependencia de kodi.binary.instance.pvr versión 6.5.0.

Regards

**Comment by SerhiyRomanov** [comment]
Which version of the addon are you trying to install? And which version of Kodi do you use?

**Comment by macamba** [comment]
Thanks SerhiyRomanov,  I was checking it seems that the issue come from Kodi Matrix windows version, several thing don't work
