### ISSUE TITLE
Channels not loading / RPI3 LibreElec

### ISSUE THREAD

**Issue by barti** [kodi-pvr/pvr.iptvsimple#384]
I have been using add on for several months. Recently went into general troubles with Kodi and ended up with fresh new installation on RPI3 / LibreElec (same setup I was using earlier). Unfortunately, my m3u file (with 7k+ entries) does not load anymore. Kodi crashes or channel list is blank. I tried with smaller files and after going back and forward, rebooting, etc. I managed to see my very short list loaded.
Kodi + add-on seem to be buggy, now. I thought maybe LibreElec does not provide the newest add-on version (nightik - 3.9.8.1) so I tried to install it manually. Here are my pain points:
1. How to figure out the newest IPTV SIMPLE add-on version on github?
2. How to install it manually form github? I followed build instructions for Linux but than got stuck.
3. If you ask me for a log, how to get it?
Thanks in advance.
PS
Issue might be similar to #372

**Comment by phunkyfish** [comment]
Can you try a kodi 19 libreelec build? For LibreElec it must be bundled with the release. As it's a binary addon you can't just install it.

Here are the official kodi 19 builds for Rpi:
https://forum.kodi.tv/showthread.php?tid=343068

If that doesn't work please supply a full debug log. I doubt it is the same as the linked issue unless you are loading your M3U from 10+ year old mac mini.

**Comment by barti** [comment]
Thanks, that worked. Was not aware LibreElec is so far behind Kodi.
