### ISSUE TITLE
Channel groups are not created

### ISSUE THREAD

**Issue by fonini** [kodi-pvr/pvr.iptvsimple#385]
I'm using a remote IPTV list, both on Raspberry PI and Windows and the channel groups are not being created. 
The same list on SS IPTV cause the groups to be created.

Sample of the M3U list: (ommited the URL)

```
#EXTM3U
#EXTINF:-1 tvg-id="" tvg-name="Canal do Cliente" tvg-logo="https://nnn" group-title="Canais Abertos",Canal do Cliente
http://aaa

#EXTINF:-1 tvg-id="" tvg-name="Show ao Vivo" tvg-logo="https://nnn" group-title="Canais Abertos",Show ao Vivo
http://bbb

#EXTINF:-1 tvg-id="" tvg-name="TV Diário Fortaleza" tvg-logo="http://nnn" group-title="Canais Abertos",TV Diário Fortaleza
http://aaa
```

**Comment by phunkyfish** [comment]
Please post a full debug log using a paste site.

Are you sure the channel groups are not being created or maybe they are not enabled in your PVR settings?

**Comment by Silhouette2022** [comment]
> Are you sure the channel groups are not being created or maybe they are not enabled in your PVR settings?

How do you check if they are enabled?
In my case it does create grouts with group-title="xyz" but does not create for playlists with

#EXTGRP:Entertainment

Any suggestions?

**Comment by phunkyfish** [comment]
That is because #EXTGRP is not supported in Leia.

What version of kodi are you running?

**Comment by Silhouette2022** [comment]
You're right. It's Leila. Unfortunately it doesn't state anywhere in wiki or readme.
And what's the reason to dropping that feature? Thanks
