### ISSUE TITLE
Catchup: different catchup-type tags in m3u

### ISSUE THREAD

**Issue by SerhiyRomanov** [kodi-pvr/pvr.iptvsimple#388]
Hello @phunkyfish and thank you again for implementing catchup for this addon. It works nice!
But recently I find out the playlists from some IPTV providers, which use a slightly different way to point out archive URL in a playlist.
The use next for HLS:
```
#EXTINF:-1 timeshift="7" catchup-days="7" catchup-type="flussonic" group-title="Group 1",Canal 1
http://str04.ottg.tv/9195/video.m3u8?username=login&password=pass&token=token&ch_id=70&req_host=key
```

And next for MPEG-TS
```
#EXTINF:-1 timeshift="7" catchup-days="7" catchup-type="flussonic-ts" group-title="Group 1",Canal 1
http://str04.ottg.tv/9195/mpegts?username=login&password=pass&token=token&ch_id=70&req_host=key
```

As you see, is present new tag ```catchup-type="flussonic"``` or could even be ```catchup-type="fs"``` which means the same. Also, ```flussonic-ts``` appears. 

I asked, why do they use exactly such format, and the answer was "because format works with such players as OTT-Play, Tivimate, Televizo, OTT Navigator, and many others". As I see, all these applications are popular on Android TV, hence is used by many users.

But, I have no idea, what is the standard way to point out catchup tags in m3u. So, I've created this issue to discuss it. 

Also, if it okay, could we have support such format by this addon?

**Comment by phunkyfish** [comment]
So I short they use `catchup-type` instead of just `catchup` and have 3 different names for flussonic?

**Comment by SerhiyRomanov** [comment]
Yes, exactly.

**Comment by phunkyfish** [comment]
Can you test?

https://github.com/kodi-pvr/pvr.iptvsimple/pull/389

**Comment by SerhiyRomanov** [comment]
Thank you @phunkyfish for your work. I've tested #389 and it resolves this issue. 

Some small notices, that I've found during testing:
1. For HLS - catchup works, but small timeshift (or forward up/back)  for 3, 5, 10 seconds are not even available. For TS all this stuff works correctly.

2. For TS the EPG Catchup URL looks like` http://str04.ottg.tv/6482/mpegts?username=login&password=pass&token=token&ch_id=181&req_host=pkjX3BL&utc=1590733440&lutc=1590759254` It's weird that its works with Flussonic, I have no idea why. 

3. While I'm watching a programme from the archive the EPG data (title and description) aren't depicted to Kodi UI in fullscreen mode. So I still see info about the programme which are current on TV, not for an archived one.

**Comment by phunkyfish** [comment]
Would you mind closing this issue and opening new issues for these?

Also please state if these are new issues or have always been there.

**Comment by phunkyfish** [comment]
When did these issues start to occur?

**Comment by SerhiyRomanov** [comment]
I close this issue. New issues have been created. Let's go continue the discussion there

**Comment by SerhiyRomanov** [comment]
I close this issue. New issues have been created. Let's go continue the discussion there
