### ISSUE TITLE
icon-src ignored in Kodi 15.1

### ISSUE THREAD

**Issue by mark-veenstra** [kodi-pvr/pvr.iptvsimple#39]
I just noticed that the `<icon-src>` from the XMLTV isn't working anymore in Kodi 15.1. IT did work in 15.0, but since 15.1 it doesn't work. I don't have any error output, but my settings are correct:

http://i.imgur.com/2uyA1SG.png
http://i.imgur.com/jcCH3yV.png

**Comment by Jalle19** [comment]
Please try again with the latest stable version of Kodi
