### ISSUE TITLE
A good idea to put a file to choose the custom groups ?

### ISSUE THREAD

**Issue by marcosemiao** [kodi-pvr/pvr.iptvsimple#390]
I saw the following ticket on the Enigma 2 PVR plugin:

https://github.com/kodi-pvr/pvr.vuplus/pull/215

this evolution allows to position an xml file "customTVGroups-example.xml"
and this displays only the groups the user wants.

What do you think for the simple client iptv plugin?

Good or Bad idea ?

**Comment by phunkyfish** [comment]
There are already tools such as IPTV merge that allow you to do this so I’m not sure this makes sense.

In addition a channel does not need to be in a group for it to loaded in iptvsimple. That’s not the case with vuplus/Enigma2.

**Comment by phunkyfish** [comment]
Or is that all channels will still be in the all channel list it’s just the groups would be omitted?

**Comment by marcosemiao** [comment]
I just thought of a better idea because deleting a group does not manage all cases.
Maybe the best idea is to add a regex expression?

I explain, in France, the internet provider offers a m3u with these channels in sd, hd and low speed format, example:

> #EXTM3U
> #EXTINF:0,2 - France 2 (standard)
> rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=201&flavour=sd
> #EXTINF:0,2 - France 2 (bas débit)
> rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=201&flavour=ld
> #EXTINF:0,2 - France 2 (auto)
> rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=201
> #EXTINF:0,2 - France 2 (HD)
> rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=201&flavour=hd

In my case, it is not practical to have the same channels several times.

A regex on the name of the channel
example:

> ^.*\(HD\)$

or then on the url

example:

> ^.*flavour=hd$

**Comment by phunkyfish** [comment]
You could easily write a cron job to download the file and run a regex on it.

It doesn’t feel like it should be a feature the addon.

**Comment by SerhiyRomanov** [comment]
@marcosemiao You can use an online m3u playlist editor to manage your channels, for instance, https://m3u.in

**Comment by phunkyfish** [comment]
This has not been added in the Matrix version of the addon. Closing the issue.
