### ISSUE TITLE
Catchup: Progress bar and textual info about duration seem don't work correctly

### ISSUE THREAD

**Issue by SerhiyRomanov** [kodi-pvr/pvr.iptvsimple#391]
A progress bar and text info about duration seem don't work correctly.

![image](https://user-images.githubusercontent.com/11770485/83273742-89c95300-a1d5-11ea-9167-59b55dfad352.png)

I start the programme from the archive, but it shows that duration starts from about 18:00 and pointer not started from begin (see point 1 on screenshot).

Then I rewind to some time (point 2) but progress bar and text info don't change.

Also, I'm watching a programme from the archive the EPG data (title and description) aren't depicted to Kodi UI in fullscreen mode. So I still see info about the programme which are current on TV, not for an archived one (Point 3)
This is a new issue. 

Versions:
Starting Kodi (19.0-ALPHA1 Git:20200529-376cca988c). Platform: Linux x86 64-bit
kodi.binary.instance.pvr v6.5.1 installed
pvr.iptvsimple v5.1.0 installed

**Comment by phunkyfish** [comment]
What was the previous version you were running that worked?

**Comment by SerhiyRomanov** [comment]
It was addon version 4.14.2 and Kodi nightly build from near 20 May or previous, it's hard to say exactly now.

**Comment by phunkyfish** [comment]
Is there a way you can switch back to the old version and prove that one still works?

I need to try and track down the issues. Between kodi and the addon. So any reference points will help.

**Comment by SerhiyRomanov** [comment]
> Is there a way you can switch back to the old version and prove that one still works?

As I see, there is no old build on repo, that I use. Only two last builds are present: today's
and from yesterday. So, there is only one way - build Kodi from sources. But I haven't installed any tools for it still, because I've never developed something for Kodi. I guess you can do it much faster than me.

**Comment by phunkyfish** [comment]
I can’t build for Ubuntu. Just for Mac but it’s very hard to rewind a dev env to a prior version.

Ah, sure we’ll figure it out 😉

**Comment by phunkyfish** [comment]
I cannot reproduce this issue.

**Comment by SerhiyRomanov** [comment]
The problem was in missing ffmpegdirect addon when installing it from Ubuntu PPA. We figured it out, so I close this issue
