### ISSUE TITLE
Catchup: IPTV Manager handling

### ISSUE THREAD

**Issue by michaelarnauts** [kodi-pvr/pvr.iptvsimple#393]
## Background info

I'm trying to fit in the use case of IPTV Manager with the new catchup feature in Matrix. Note that I'm not using an IPTV provider, but I use locally installed Add-ons that are able to play legally available live streams, have access to EPG data and are able to play programs on demand.

See https://github.com/add-ons/service.iptv.manager for more information.

## Current implementation

So, I construct a m3u playlist with a list of channels, and an xmltv file with the epg data for these channels. Every channel has a `plugin://` url to play the channel live. For some programs, I have a `plugin://` url that I can use to play the program on-demand, but not for all programs. I can even have a `plugin://` url for programs in the future when they are already available (when it's a re-run for example).

I have added the catchup tags to configure catchup on the channel, and I use `catchup-id` as the full URL. This is not the intended usage for `catchup-id`, but it fits my purpose nicely, and seems to work fine.

Currently, I have added the following fields to a channel in the playlist:
* catchup="default"
* catchup-source="{catchup-id}" 
* catchup-days="10"

```
#EXTINF:-1 tvg-name="VTM" tvg-id="vtm.be" tvg-logo="special://home/addons/plugin.video.vtm.go/resources/logos/vtm.png" tvg-chno="3" group-title="VTM GO" catchup="default" catchup-source="{catchup-id}" catchup-days="10",VTM
plugin://plugin.video.vtm.go/play/catalog/channels/d8659669-b964-414c-aa9c-e31d8d15696b
```

Then, in the xmltv file, I have the following:

Currently, I have added the following fields to a channel in the playlist:
* catchup-id="plugin://plugin.video.example/play/12345678999"

```
<programme start="20200530202000 +0200" stop="20200530214500 +0200" channel="vtm.be" catchup-id="plugin://plugin.video.vtm.go/play/catalog/episodes/ff2f3192-d9b9-4ab3-80f3-70c2bf2d23fb">
 <title>Lego Masters</title>
 <desc>In deze finale is de opdracht: geen! Brickmaster geeft de finalisten maar liefst 28 uur om hun masterbuild te bouwen. Welk duo wint de 25.000 euro en de titel: LEGO Masters van Nederland en België?</desc>
 <icon src="https://images0.persgroep.net/rcs/1nhbgq1R4nu-zLEGsaZCLJEjqxk/diocontent/170840181/_fill/600/400?appId=da11c75db9b73ea0f41f0cd0da631c71"/>
</programme>
```

## Problems

* This allows me to play a program on demand from the past, but not a program from the future. Even if there's a `catchup-id` on the EPG program.
* `catchup-days` should not limit the catchup, but the existence of a `catchup-id` in the EPG should.
* It also doesn't prevent to play a program without a `catchup-id` in the EPG program.

## Possible solution

I think it's best to define a new `catchup` type, something like `iptv`. This automatically sets `catchup-source` to `{catchup-id}`. `catchup-days` doesn't matter here, since we can just look at the epg programs with a `catchup-id`.

I think this solution is generic enough so it can also be used for other services besides IPTV Manager.

What do you think of this solution? Do you have a better idea?

**Comment by phunkyfish** [comment]
It should be ok to just omit the requirement for the catchup-days check if there is only a catchup id. I don’t think we need a new type.

Why would would you want to play a programme from the future? I would need to understand that use case better. I’m not even sure kodi would let you do that even if programmatically the addon did.

**Comment by michaelarnauts** [comment]
This can be useful when programs are re-broadcasted at a later time, or when a whole season is put online in the catalog, but it's still aired linear. This allows you to watch those episodes from the EPG.

**Comment by phunkyfish** [comment]
You’ll need to keep explaining I’m afraid. I still don’t get it.

Are you try to use PVR for a purpose it’s not designed for?

**Comment by michaelarnauts** [comment]
I'm using the PVR to show the linear broadcast schedule of a network, allow live playback and stream "recordings". I guess that's about what it's designed for.

## Example 1:
```
MONDAY
13:00 Some drama serie S05E45
14:00 News magazine
15:00 Other programs
...
21:00 News magazine
22:00 Documentary
23:00 Some drama serie S05E45 (rerun)
```
Now, when viewing the EPG at 21:00 for example, you could see that the drama serie from 23:00 is already available (since it has been aired before at 13:00 and is available in the video on demand catalog).


## Example 2:
```
SUNDAY
...
21:00 Game of Thrones S08E01
...

MONDAY
...
21:00 Game of Thrones S08E02
...

TUESDAY
...
21:00 Game of Thrones S08E03
...

```
Say you want to watch GoT, the network has bought the rights for the full season, and they've put it in their video on demand catalog. The EPG guide on their website has a direct link to these programs, so you can watch them already before they are aired. On Sunday, after having views S085E01, you could scroll to Monday and play the episode already from there. You can also use the "Find similar programs", and get a list of all the episodes that will be aired in the coming days.

I hope this makes it more clear. The playback from future episodes off course depends on how Kodi handles this. If Kodi doesn't allow this, I'm fine with it, but it would be a nice touch if it was supported.

**Comment by phunkyfish** [comment]
I have a feeling you will only be able to add a reminder or set a timer (not on iptvsimple obviously) for anything in the future. But let’s see once restriction on days is removed.

**Comment by phunkyfish** [comment]
Ok, what do you think of this.

We have a `catchup="iptv"` mode. In this mode if `catchup-source` is not provided it is set to `{catchup-id}` and if `catchup-days` is not provided its requirement is removed.

This would then also solve a problem with defaults for some non timeshifting catchup streams while still supporting streams that cannot play future EPG entries (assuming this will work as we would like it to).

**Comment by michaelarnauts** [comment]
We also need the check that catchup-id is present on the epg program itself. Basicly, a program is playable if it has the a `catchup-id` tag on the EPG.

I tried to modify `IsEPGTagPlayable()` to remove the time checks as a test, and Kodi handles it just fine. Future programs also get a green dot, and the context menu gets a "Play program". The "Smart selection" feature of the EPG will ask to play live or record it however, that will need to be changed in Kodi itself.

**Comment by phunkyfish** [comment]
Don't worry about the playable part there is already code for that.

How do you mean the smart selection feature? As IPTV Simple does not support recordings I don't see why it would ask about recording (unless that's just a bug).

**Comment by michaelarnauts** [comment]
The playing works, I'm not worrying :)

I have enabled the "Smart Selection" option when selecting a program. For past programs, this plays the recording, for live programs this plays the channel live, for future programs, this pops up the dialog to ask if the user wants to watch live, or add a recording.

**Comment by michaelarnauts** [comment]
I just noticed that it actually created a reminder instead of a scheduled recording. I think could be improved to also check for the hasArchive flag, but is definitely something for another PR to the kodi repo.

**Comment by michaelarnauts** [comment]
The one thing that might need a bigger change is that in `IsEPGTagPlayable()`, you'll need access to the `catchup-id` of the epg program defined in the xmltv file. That will define if it's playable or not, not the time.

**Comment by phunkyfish** [comment]
Ok to close @michaelarnauts ?

**Comment by michaelarnauts** [comment]
Indeed!
