### ISSUE TITLE
Slow channels zapping with some IPTV providers

### ISSUE THREAD

**Issue by ugoviti** [kodi-pvr/pvr.iptvsimple#40]
Hi,

I'm using pvr.iptvsimple with Kodi 15.0 and I'm experiencing long timeouts when changing channels (10/12 seconds).

The problem is the same as reported here:

http://trac.kodi.tv/ticket/15918

I understand that fixing the IPTV server would be the correct way to fix that problem, but would be great if pvr.iptvsimple can have some override options configurable as reported in the kodi ticket:

b) pvr.iptvsimple should have a global option (that can potentially be overridden per playlist item using tags) for the MIME type, which could even default to video/mp2t since that's what real TV streams use. If someone wants to use the addon with any random collection of streams from the internet that are not MPEG-TS then that's their problem.

let me know if you need anything else

With kind regards

**Comment by armando-basile** [comment]
+1

**Comment by skest3qc** [comment]
+1

**Comment by mariokovac** [comment]
+1

**Comment by saqebakhter** [comment]
was there a fix for this ?
