### ISSUE TITLE
Timeshift should not be enabled when using catchup-source only for stream URL as an option

### ISSUE THREAD

**Issue by phunkyfish** [kodi-pvr/pvr.iptvsimple#402]
@puenktchen

Is what you mean that for a channel if played live use timeshift but if it's played using the catchup-source of that channel don't use timeshift?

**Comment by phunkyfish** [comment]
Just thinking, any reason why the catchup-source should ever have timeshift applied to it? Maybe we don't need an option and we just never allow it.

I guess that depends on whether or not a catchup stream could be a delayed live stream. In that case a setting would be needed.

**Comment by puenktchen** [comment]
> Just thinking, any reason why the catchup-source should ever have timeshift applied to it? Maybe we don't need an option and we just never allow it.

That would make sense to me, because from a logical standpoint if i can jump through the timeline of a catchup stream,
then for sure i can also pause it. But it's your decision. If you vote for a setting, then it should default to "off" i think.

**Comment by phunkyfish** [comment]
And you only use catchup using `catchup-id`,  correct?

**Comment by puenktchen** [comment]
Correct.

**Comment by phunkyfish** [comment]
Testbuilds here: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-404/1/artifacts
PR: https://github.com/kodi-pvr/pvr.iptvsimple/pull/404

All you should need to do is set `catchup="vod"` in your M3U and it should never enable timeshift.

**Comment by puenktchen** [comment]
Working after i disabled "Allways enable timeshift stream mode if missing" in the addon.
Obviously the addon setting takes precedence, which makes sense after thinking about it.
So issue can be closed. Thank you!

**Comment by phunkyfish** [comment]
In the latest version you don’t need to disable that option if you use the `vod` catchup mode.

**Comment by puenktchen** [comment]
> In the latest version you don’t need to disable that option if you use the `vod` catchup mode.

Oh i did set "vod" like here:
```
#EXTINF: -1 catchup="vod" catchup-source="http://192.168.0.2:8096/emby/VirtualTV/StaticStream?ItemId={catchup-id}" tvg-id="VirtualTV0" tvg-chno="14.1" tvg-name="80's Thriller" tvg-logo="http://192.168.0.2:8096/emby/VirtualTV/ChannelImage?ChannelId=1240281",80's Thriller
#KODIPROP:inputstream=inputstream.ffmpegdirect
http://192.168.0.2:8096/emby/VirtualTV/Stream?ChannelId=1240281&User=Kodi&Playback=Restream
```
but with "Allways enable timeshift stream mode if missing" enabled, timeshifting is active.

**Comment by phunkyfish** [comment]
Ok, that’s a bug so. For VOD there should never be timeshift. I will fix that.
