### ISSUE TITLE
Add "lock" support to #EXTINF section of playlist

### ISSUE THREAD

**Issue by Sheredeka** [kodi-pvr/pvr.iptvsimple#407]
Please add "lock" tag support in M3U playlist, to make channel as locked in channel-list.
It must limit viewing of 18+ channels for children!

**Comment by phunkyfish** [comment]
What is a lock tag?

**Comment by Sheredeka** [comment]
To make channel as "parental locked"
![parental_locked](https://user-images.githubusercontent.com/59475072/87923400-1a116f00-ca86-11ea-92ef-f6d0b6f505fd.png)

**Comment by phunkyfish** [comment]
I think this is a feature of the skin you are using. There is no parental lock option available on a channel in kodi.

**Comment by Sheredeka** [comment]
"Parental lock" it's standart Kodi option:
![1](https://user-images.githubusercontent.com/59475072/87948602-99feff80-caad-11ea-85e5-416d4d8df8a9.png)

Activate PIN on Parental locked channels:
![2](https://user-images.githubusercontent.com/59475072/87948743-c286f980-caad-11ea-8232-bac76920b940.png)

In TV-database (kodi/userdata/Database/TV32.db) table "channels" row "bIsLocked" = 1 for Parental locked channels

Please add tag support for Parental lock in #EXTINF m3u list

**Comment by phunkyfish** [comment]
But this in Kodi. It is not something the addon has access to. Closing the issue.
