### ISSUE TITLE
New, Live, Finale and Premiere for EPG

### ISSUE THREAD

**Issue by fernandoalonzo** [kodi-pvr/pvr.iptvsimple#413]
Any chance to implement New, Live, Finale and Premiere for EPG as described here: https://github.com/xbmc/xbmc/pull/17515

**Comment by phunkyfish** [comment]
There would need to be XMLTV fields that signify these attributes. I didn’t see any in the XMLTV DTD.

**Comment by fernandoalonzo** [comment]
There are [New](https://github.com/XMLTV/xmltv/blob/master/xmltv.dtd#L506) and [Premiere](https://github.com/XMLTV/xmltv/blob/master/xmltv.dtd#L469) tags; no Live and Finale though. Can you add at least those two?

**Comment by phunkyfish** [comment]
`new` is there: https://github.com/kodi-pvr/pvr.iptvsimple/blob/0e30a88aac3685191253d53b73b0f14e54ee7edb/src/iptvsimple/data/EpgEntry.cpp#L66

**Comment by phunkyfish** [comment]
Ah, but it’s only populated based on the first  aired date being the same as EPD date.

Do you have some sample XMLTV data for these? 

I think we would only populate premiere. New does not mean the same thing that it means in kodi.

**Comment by phunkyfish** [comment]
I've added premiere in this PR: https://github.com/kodi-pvr/pvr.iptvsimple/pull/410

Testbuilds of the addon are here: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-410/4/artifacts 

Let me know if it works ok.

**Comment by fernandoalonzo** [comment]
> Ah, but it’s only populated based on the first aired date being the same as EPD date.
> 
> Do you have some sample XMLTV data for these?
> 
> I think we would only populate premiere. New does not mean the same thing that it means in kodi.

Oh I see that was the problem, my EPG data doesn't have first aired date.
Did a quick search and found this example:
```
<programme start="20200729080000 -0500" stop="20200729083000 -0500" channel="beIn.us">
  <title>This Is Paris</title>
  <category>Sport</category>
  <desc>An all-access look at Paris Saint-Germain.</desc>
  <new />
  <rating>
    <value>TV-G</value>
  </rating>
</programme>
```
What does New mean in Kodi?
Thanks for the PR, will take a look later today.

**Comment by phunkyfish** [comment]
New in kodi means this is a first airing of any episode of a show. I.e. air date equals epg date. Premiere on the other hand mean the first time a show is playing on a channel. But really the ensign of premiere is epg specific. 

New in XMLTV means the first showing of a show. But is only for the first time episode 1 is showing and never again.

We could add the new flag if it’s new in xmltv or epg date matches air date.

**Comment by phunkyfish** [comment]
Ok, can you test this @fernandoalonzo?

Testbuilds are here: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-410/5/artifacts

It will use both air date equal to the epg date and the new tag to detect something new. Premiere will only use the premiere tag.

**Comment by fernandoalonzo** [comment]
I generated some test data because I couldn't find any premiere tag in my current EPG.
Both, new and premiere, work great. I tested two premiere tags:
```
<premiere />
```
and
```
<premiere lang="en">
  First showing on national terrestrial TV
</premiere>
```
The latter doesn't show the paragraph text anywhere, which is probably due (Esturay) skin doesn't support it.
Another thing I noticed is that there's a bracket in front of Première label (this may be a bug in the skin):
![Screen Shot 2020-08-08 at 11 38 55 AM](https://user-images.githubusercontent.com/2417136/89715643-a79cfc00-d96c-11ea-9b1c-2d240dd34182.png)
I'm closing this issue, thanks for all your help!

**Comment by phunkyfish** [comment]
Yes, any premiere text would not be supported. The skin would not matter as it’s not supported in PVR.

Hmmm, let me take a look at the bracket.

**Comment by phunkyfish** [comment]
@fernandoalonzo do you have the sample EPG data for where the extra `[` appears? With my data it does not reproduce the issue. 

So if you have the data that matches a screenshot that would be great. Thanks

**Comment by phunkyfish** [comment]
Nevermind, I found the issue.

Fix: https://github.com/xbmc/xbmc/pull/18263
