### ISSUE TITLE
Unstable addon?

### ISSUE THREAD

**Issue by VuzzyM** [kodi-pvr/pvr.iptvsimple#415]
![image](https://user-images.githubusercontent.com/66425682/89695845-29196d80-d91e-11ea-8081-4683c7323976.png)

Why under the addon seems unstable, the other older addon was unstable. If it is stable, remove this description, thanks.

**Comment by phunkyfish** [comment]
I would say this text has been in each PVR addon by default since they were created. I can remove the first part in the next PR.

**Comment by VuzzyM** [comment]
> I would say this text has been in each PVR addon by default since they were created. I can remove the first part in the next PR.

Ok, thanks
