### ISSUE TITLE
Bug - cache

### ISSUE THREAD

**Issue by VuzzyM** [kodi-pvr/pvr.iptvsimple#416]
Why does my epg update every time I open Kodi?  I set it to be in cache and auto reload and that's it.

**Comment by phunkyfish** [comment]
The EPG will always update even if from a local cache when you start kodi. The cache is specific to the iptvsimple addon.

Are you using the Leia or Matrix version of the addon?

**Comment by VuzzyM** [comment]
> The EPG will always update even if from a local cache when you start kodi. The cache is specific to the iptvsimple addon.
> 
> Are you using the Leia or Matrix version of the addon?

Matrix
