### ISSUE TITLE
Bug - Icons remain active on all channels

### ISSUE THREAD

**Issue by VuzzyM** [kodi-pvr/pvr.iptvsimple#417]
![image](https://user-images.githubusercontent.com/66425682/89711684-76d0bd00-d994-11ea-9658-994a4f3da225.png)

After I change the m3u link and if I leave the same epg or change another one, the last logos from another playlist remain.

In settings the epg is set to ignore, you can check this bug.
The logos come from old playlist m3u, a strange thing is that it was set to ignore in the epg settings, but the logos were still put automatically.

**I cleared data from pvr & Live TV settings and epg and m3u and the same problem remains.**

**Comment by phunkyfish** [comment]
It’s because the icons are saved in the textures db when loaded. After this displaying them is not a function of PVR.

Try this and see if they are cleared up: https://github.com/kodi-pvr/pvr.vuplus/issues/252

**Comment by VuzzyM** [comment]
> It’s because the icons are saved in the textures db when loaded. After this displaying them is not a function of PVR.
> 
> Try this and see if they are cleared up: [kodi-pvr/pvr.vuplus#252](https://github.com/kodi-pvr/pvr.vuplus/issues/252)

is work, thanks
