### ISSUE TITLE
Now Playing info missing or not displaying on IP Radio Channels

### ISSUE THREAD

**Issue by wisegeeksrules** [kodi-pvr/pvr.iptvsimple#422]
I can see the "Now Playing" info when using Radio addon or VLC Media Player when streaming Live Radio streams but when using this IPTV addon all I see is the channel number and name like this (9) ReggaeFM.
I'm kindly requesting if you could add support for the "Now Playing" info display.

**Comment by phunkyfish** [comment]
Are you using the Leia or Matrix version of kodi?

**Comment by wisegeeksrules** [comment]
using Leia on OSMC

**Comment by phunkyfish** [comment]
Do you have a way to try it on Matrix? I remember some RDS changes being merged that may fix it.

**Comment by wisegeeksrules** [comment]
On OSMC I'm not sure if there's a way. I will check on the OSMC forum.

**Comment by phunkyfish** [comment]
Might be simpler to run kodi on a laptop of some sort to check it.

**Comment by wisegeeksrules** [comment]
I tested the PVR IPTV addon on different skins, Estuary (Kodi's default), OSMC, Embuary and it worked well with the Xperience1080 skin only as seen below:

![screenshot048](https://user-images.githubusercontent.com/10378575/90919039-fe331d00-e3e5-11ea-9369-0281f014347e.png)
![screenshot051](https://user-images.githubusercontent.com/10378575/90919199-50743e00-e3e6-11ea-80bb-3a8a548dcca1.png)
On OSMC skin it's not working, I gotta open an issue in the OSMC forum.

![screenshot053](https://user-images.githubusercontent.com/10378575/90919477-cd9fb300-e3e6-11ea-8f81-679e5a90b132.png)

**Comment by wisegeeksrules** [comment]
Finally managed to get the issue fixed for OSMC skin
