### ISSUE TITLE
Radio playback stops after less then a second [version 3.9.8 for Kodi 18.x]

### ISSUE THREAD

**Issue by Martin1995** [kodi-pvr/pvr.iptvsimple#423]
I have the following problem, after tagging radiostations with radio="true" in the m3u for the channel list, radiostations play only less then a second and then the player stops.  it was working before, when radio stations were still tagged like the TV-channels.

I'm using KODI 18.8 on Arch Linux as the client and an AVM FritzBox6660Cable as the SATIP server.

i provide my m3u as plain-text sample (it only features internal network paths)
[channellist-cleaned.m3u.txt](https://github.com/kodi-pvr/pvr.iptvsimple/files/5112920/channellist-cleaned.m3u.txt)

i retagged all radiostations like this `#EXTINF:-1 radio="true",` and rest is still the autogenerated part exported from the satip server of my cable modem router

I installed the addon yesterday via the package manager which downloaded it from github and compiled it locally

If somebody (developer or not) could point me in to the right direction of solving my issue, i would be very grateful.

**Comment by phunkyfish** [comment]
Satip will only work with with Kodi 19.1 (not released) or Kodi 19.0 with inputstream.ffmpegdirect. But the protocol must be satip://

**Comment by Martin1995** [comment]
can i just replace "rtsp://" with "satip://"?

**Comment by phunkyfish** [comment]
Yes, but only on the latest nightly builds on Kodi 19 or by using ffmpegdirect.

**Comment by Martin1995** [comment]
Current version is now 19.0 so we can close this out because problem got solved with ffmpegdirect and Kodi19.0
