### ISSUE TITLE
How to install on windows

### ISSUE THREAD

**Issue by helgovic** [kodi-pvr/pvr.iptvsimple#424]
How can i install this addon on windows? I tried the linux approach under mingw, but i get the following error:

Determining if the _X86_ exist failed with the following output:
Change Dir: D:/Kodi/HomeDir/pvr.iptvsimple/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_57c06.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.26.28806 for x64

  CheckSymbolExists.c

  Copyright (C) Microsoft Corporation.  All rights reserved.

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_57c06.dir\Debug\\" /Fd"cmTC_57c06.dir\Debug\vc142.pdb" /Gd /TC /errorReport:queue D:\Kodi\HomeDir\pvr.iptvsimple\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c

D:\Kodi\HomeDir\pvr.iptvsimple\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c(8,24): error C2065: '_X86_': undeclared identifier [D:\Kodi\HomeDir\pvr.iptvsimple\build\CMakeFiles\CMakeTmp\cmTC_57c06.vcxproj]

File D:/Kodi/HomeDir/pvr.iptvsimple/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <Windows.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef _X86_
  return ((int*)(&_X86_))[argc];
#else
  (void)argc;
  return 0;
#endif
}

I also tried running prepare-binary-addons-dev.bat, but i get a load of errors.

Pls help, i would really like to have this addon on my htpc.

**Comment by phunkyfish** [comment]
Why not just install from repo?

You do not wed to build the addon to install it.

**Comment by helgovic** [comment]
What repo is that?

**Comment by phunkyfish** [comment]
The kodi repo. It’s built in on windows.

**Comment by playzino** [comment]
Kodi 18 has old version 3.9.8, Kodi 19 Matrix Alfa2 can't see this addon in repo :(

**Comment by phunkyfish** [comment]
Alpha3 has been released. Did you try that?

**Comment by playzino** [comment]
oh thx, got it
