### ISSUE TITLE
How to install PVR client in Debian Linux? (please, open yet)

### ISSUE THREAD

**Issue by claudiosa** [kodi-pvr/pvr.iptvsimple#428]
Hi everyone

I installed the Kodi in a Debian machine last version (I think that is 10). However, the PVR client is not include as well as this package is not official in this version as I can read.
Reading and following  the instructions from (https://github.com/kodi-pvr/pvr.iptvsimple/) for Linux installation,
all the compilation were OK, but as a Linux user is missing a "**make install**"

Everything was compiled in a directory where I had did the clone

Please, could you complete the  cocumentation to install the PVR client in Debian or Linux? 

thanks

claudio

**Comment by phunkyfish** [comment]
@basilgello should be able to help you.

**Comment by basilgello** [comment]
Thanks @phunkyfish !

@claudiosa please read my repository README: https://github.com/basilgello/kodi-nightly-debian-repo

It is unofficial Kodi repo featuring 19.0 with addons for Debian 10 / amd64. If you need i386 or other architecture, please let me know. Also, feel free to ask questions here or in email mentioned in the README file.

You can also upgrade Kodi 17.6 (the one from Debian 10 "buster") to my 19.0 build safely - I use it myself and welcome beta testers before 19.0 and all addons enter official Debian repositories.

**Comment by DaVukovic** [comment]
@claudiosa Hopefully I haven't misunderstood the questoin. But what about these instructions we have at core: 

https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md#5-build-binary-add-ons

I guess that's mostly everything you need to compile and install binary add-ons

**Comment by claudiosa** [comment]
Hi everyone: 

Initially thanks for your kindly.  Really, I was little hurried when I wrote my first issue,  but I am reinforcing some points about the described in [https://github.com/kodi-pvr/pvr.iptvsimple] (https://github.com/kodi-pvr/pvr.iptvsimple) for  Linux installation.

Let's explain better:

* Normally, any Linux installation has a file configuration, or it is generate by a "make config"
* Then, follow by a "make" (normally, a  local compilation)
* Finally, a "make install" did by root or su

In all these cases, it is indicate if a single user or root to do these steps, and all directory to download and install
are indicated.

Let's back to steps described in https://github.com/kodi-pvr/pvr.iptvsimple:

1. git clone --branch master https://github.com/xbmc/xbmc.git
2. git clone https://github.com/kodi-pvr/pvr.iptvsimple.git

Should be logged as user or root?
Where is the directory to be when I am doing this clone? 
For instance, I did in /home/my_name/Download (both them)

3. cd pvr.iptvsimple && mkdir build && cd build
No doubts ...

4. cmake -DADDONS_TO_BUILD=pvr.iptvsimple -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons
As this step runs fine, ... I think that all files are generate correctly

5. make
Probably,  with this make, it the addons were generated correctly also.

Well, where I will install the PVR-client addon?  
Where is "a make install" or equivalent?
Should be use it as root to do the installation?
Where and what files 

My doubts are about the documentation specifically.
my kodi was installed by an aptitute install kodi in  /usr/lib/x86_64-linux-gnu/kodi
ls -al  /usr/lib/x86_64-linux-gnu/kodi
total 21128
drwxr-xr-x  4 root root     4096 set  4 19:48 .
drwxr-xr-x 92 root root    73728 set  6 10:41 ..
drwxr-xr-x 11 root root     4096 set  6 17:19 addons
-rwxr-xr-x  1 root root 21417248 jan 28  2019 kodi.bin
-rwxr-xr-x  1 root root    56056 jan 28  2019 kodi-xrandr
drwxr-xr-x  3 root root     4096 set  4 19:48 system
-rwxr-xr-x  1 root root    72672 jan 28  2019 TexturePacker

So, whose  the files must be copied to "where"?
Well, with these difficuties I prefered a workaround

a) Add "deb http://ftp.de.debian.org/debian stretch main " in source.list (/etc/apt/sources.list)
b) aptitude update 
c)  aptitude install kodi-pvr-iptvsimple

Well, the live channels are working perfectly, **but just  under Catchup-UP**, but they are present in PVR-client,
except that by PVR-client the channels do not works ..... just searching and stop after some seconds ...
My status the "almost" is in this 

 https://github.com/claudiosa/CCS/blob/master/private/screen_PVR_CCS.jpg

Probably, some option or permission to watch TV using PVR client. Someone could be help me?
the channels are in PVR client ... but don't play.
Where is the option in KODI?

Thanks once in advance


Claudio

**Comment by basilgello** [comment]
@claudiosa you have to build addon and zip it to be able to install into Kodi (check https://www.google.com/search?channel=fs&client=ubuntu&q=kodi+installin+gaddons+from+zip+file). Before I migrated to 19.0, I built the addon with the following script:

```shell
#!/bin/sh

#
# Build Kodi addon
#
# Author: Vasyl Gello <vasek.gello@gmail.com>
# Release Date: 2020-03-25
#
# Requires: Kodi build environment, xmlstarlet
#

#
# Print usage
#

usage() {
	echo ""
	echo "Usage:"
	echo ""
	echo 'build-kodi-addon.sh \'
	echo '     -a "/path/to/addon/source/directory" \'
	echo '    [-k "/path/to/kodi/source/directory"] \'
	echo '    [-b <Krypton|Leia|Matrix>] \'
	echo '    [-o "/path/to/addon/zip/directory"] \'
	echo '    [-c "addon-configure-options"] \'
	echo '    [-m "addon-make-options"]'
	echo ""
}

#
# Start of script
#

# Get script directory and save current directory

SCRIPTDIR=$(readlink -f "$0")
SCRIPTDIR=$(dirname "$SCRIPTDIR")
_OLDPWD="$PWD"

# Parse command-line arguments

while getopts "ha:k:b:o:c:m:" arg; do
	case $arg in
	h)
		usage
		exit 1
		;;
	a)
		ADDON_SOURCE_DIR="$OPTARG"
		;;
	k)
		KODI_SOURCE_DIR="$OPTARG"
		;;
	b)
		KODI_BRANCH="$OPTARG"
		;;
	o)
		OUT_DIR="$OPTARG"
		;;
	c)
		CONFIGURE_ARGS="$OPTARG"
		;;
	m)
		MAKE_ARGS="$OPTARG"
		;;
	esac
done

# Validate command-line arguments and set defaults where needed

echo ""
echo "[?] Validating command-line arguments"

if [ -z "$ADDON_SOURCE_DIR" ]; then
	usage
	exit 1
fi

ADDON_SOURCE_DIR=$(readlink -f "$ADDON_SOURCE_DIR")

if [ ! -d "$ADDON_SOURCE_DIR" ]; then
	echo "[x] ERROR: Add-on source directory does not exist:"
	echo "[x] $ADDON_SOURCE_DIR"
	echo ""
	exit 1
fi

ADDON_XML_PATH=$(find "$ADDON_SOURCE_DIR" -name "addon.xml*" | head -n 1)

if [ -z "$ADDON_XML_PATH" ]; then
	echo "[x] ERROR: Add-on source directory has no addon.xml!"
	echo ""
	exit 1
fi

ADDON_ID=$(xmlstarlet fo --recover "$ADDON_XML_PATH" 2>/dev/null |
	xmlstarlet sel -t -v '/addon/@id')
ADDON_VERSION=$(xmlstarlet fo --recover "$ADDON_XML_PATH" 2>/dev/null |
	xmlstarlet sel -t -v '/addon/@version')

if [ -z "$KODI_SOURCE_DIR" ]; then
	KODI_SOURCE_DIR="$PWD/kodi"
fi

KODI_SOURCE_DIR=$(readlink -f "$KODI_SOURCE_DIR")

if [ -e "$KODI_SOURCE_DIR" ] && [ ! -f "$KODI_SOURCE_DIR/version.txt" ]; then
	echo "[x] ERROR: The Kodi source tree path specified"
	echo "[x] does not represent a valid directory:"
	echo "[x] $KODI_SOURCE_DIR"
	echo ""
	exit 1
fi

if [ -z "$KODI_BRANCH" ]; then
	KODI_BRANCH="master"
fi

if [ -z "$OUT_DIR" ]; then
	OUT_DIR="$PWD"
fi

OUT_DIR=$(readlink -f "$OUT_DIR")

# Checkout Kodi of selected branch if no path specified or path does not exist

if [ ! -d "$KODI_SOURCE_DIR" ]; then
	echo "[?] Checking out Kodi branch \"$KODI_BRANCH\" to directory:"
	echo "[?] $KODI_SOURCE_DIR"
	echo ""

	git clone https://github.com/xbmc/xbmc \
		"$KODI_SOURCE_DIR" \
		-b "$KODI_BRANCH" \
		--depth 1 \
		1>/dev/null 2>/dev/null
	_RET=$?

	if [ $_RET -eq 0 ]; then
		echo "[+] Successfully checked out Kodi"
		echo ""
	else
		echo "[x] ERROR: Can not clone Kodi $KODI_BRANCH to directory:"
		echo "[x] $KODI_SOURCE_DIR"
		echo "[x] (git exit code $_RET)!"
		echo ""
		exit 1
	fi
else
	# Update Kodi source tree

	echo "[?] Updating Kodi installation ..."

	cd "$KODI_SOURCE_DIR"

	git pull 1>/dev/null 2>/dev/null
	_RET=$?

	if [ $_RET -eq 0 ]; then
		echo "[+] Successfully updated Kodi source directory"
	else
		echo "[x] ERROR: Can not update the Kodi source directory:"
		echo "[x] $KODI_SOURCE_DIR"
		echo "[x] (git exit code $_RET)!"
		echo ""
		exit 1
	fi

	cd "$OLDPWD"
fi

# Create build sub-directory

echo "[?] Creating build sub-directory"

cd "$ADDON_SOURCE_DIR"

mkdir -p build
_RET=$?

if [ $_RET -eq 0 ]; then
	echo "[+] Successfully created build sub-directory"
else
	echo "[x] ERROR: Can not create build directory (exit code $_RET)!"
	echo ""
	exit 1
fi

cd build

# Build the add-on

echo "[?] Configuring add-on $ADDON_ID / $ADDON_VERSION"

cmake -DCMAKE_BUILD_TYPE=Debug \
	-DADDONS_TO_BUILD="$ADDON_ID" \
	-DADDON_SRC_PREFIX=../.. \
	-DCMAKE_INSTALL_PREFIX="$KODI_SOURCE_DIR/addons" \
	-DPACKAGE_ZIP=1 "$KODI_SOURCE_DIR/cmake/addons" \
	$CONFIGURE_ARGS

_RET=$?

if [ $_RET -eq 0 ]; then
	echo "[+] Successfully configured add-on $ADDON_ID / $ADDON_VERSION"
else
	echo "[x] ERROR: Can not build $ADDON_ID (exit code $_RET)!"
	echo ""
	exit 1
fi

echo "[?] Building add-on $ADDON_ID / $ADDON_VERSION"

make $MAKE_ARGS

_RET=$?

if [ $_RET -eq 0 ]; then
	echo "[+] Successfully built add-on $ADDON_ID / $ADDON_VERSION"
else
	echo "[x] ERROR: Can not build $ADDON_ID / $ADDON_VERSION (exit code $_RET)!"
	echo ""
	exit 1
fi

cd ..

# Package the addon

echo "[?] Creating output directory"

if [ ! -d "$OUT_DIR" ]; then
	mkdir -p "$OUT_DIR"
	_RET=$?

	if [ $_RET -eq 0 ]; then
		echo "[+] Successfully created output directory"
	else
		echo "[x] ERROR: Can not create putput directory:"
		echo "[x] $OUT_DIR"
		echo ""
		exit 1
	fi
fi

echo "[?] Zipping the addon $ADDON_ID / $ADDON_VERSION to:"
echo "[?] $OUT_DIR/$ADDON_ID-$ADDON_VERSION.zip"

cd "$KODI_SOURCE_DIR/addons"

zip "$OUT_DIR/$ADDON_ID-$ADDON_VERSION.zip" --symlink -r "$ADDON_ID"
_RET=$?

if [ $_RET -eq 0 ]; then
	echo "[+] Successfully zipped add-on $ADDON_ID / $ADDON_VERSION"
else
	echo "[x] ERROR: Can not zip the add-on (zip exit code $_RET)!"
	echo ""
	exit 1
fi

cd "$_OLDPWD"

# Clean up Kodi source tree

echo "[?] Cleaning up Kodi tree"

cd "$KODI_SOURCE_DIR"

git clean -f -d 1>/dev/null 2>/dev/null

_RET=$?

if [ $_RET -eq 0 ]; then
	echo "[+] Successfully cleaned up Kodi tree"
else
	echo "[x] ERROR: Can not clean up Kodi source tree (git exit code $_RET)!"
	echo ""
	exit 1
fi

cd "$_OLDPWD"

# Report success

echo "All done! Enjoy!"
```

Assume you are building iptvsimple for Kodi 18.8 "Leia". Then you do the following:

1. Create a directory for builds, like `$HOME/kodi-builds` and change working directory into that one
2. Save the script I posted as `build-kodi-addon-zip.sh` and make it executable:

`chmod 0755 build-kodi-addon-zip.sh`

3. Clone this repository:

`git clone https://github.com/kodi-pvr/pvr.iptvsimple -b Leia`

4. Invoke script:

`./build-kodi-addon-zip.sh -a pvr.iptvsimple/ -b Leia -o $PWD/ 2>&1 | tee build-pvr.iptvsimple.log`

5. If build fails, paste the log to pastebin.com and give the link.

**Comment by claudiosa** [comment]
Hi  @basilgello (basilgello)

Thanks for your attention, unfortunately the version that I am using  is Kodi 17.8 and
the aptitude install kodi-pvr-iptvsimple seems well installed.

However, I removed and executed your script that runs fine, here the log;
https://github.com/claudiosa/CCS/blob/master/private/kodi-pvr/build-pvr.iptvsimple.log

The error from pastebin.com I can not obtain, once, that my Kodi version was different.
I roll back the version  (aptitude install kodi-pvr-iptvsimple)   from Debian repository.

So, my error remains, the TV-live plays only under Cathup Addon, using the directly the 
Catchup (https://github.com/claudiosa/CCS/blob/master/private/kodi-pvr/screen_TV-live_only-as-addon-cathup.jpg). 

Before, I did a configuraion of PVR-Client to read the directories from Cathup addon,
seems that read (https://github.com/claudiosa/CCS/blob/master/private/kodi-pvr/screen_PVR_CCS.jpg)
the TV-Live does not play ....

How to do it play reading the Catchup M3U files? 
Anyway, I collected a log from my last try ... it is in:
 https://github.com/claudiosa/CCS/blob/master/private/kodi-pvr/kodi.log

any guess  @basilgello ?

I just follow all the steps trying pvr-client works reading the m3u directory from Cathup addon.
where is  my reasoning? 

I just follow the steps described in KODI wiki pages >>>>

Should be try to install Kodi 19 from scratch?
Why the pvr client is not integrated in Kodi reading some m3u valid files such Catucp does?

Claudio

**Comment by claudiosa** [comment]
@basilgello 

I just try to do works like describe here:
https://catch-up-tv-and-more.github.io/live_tv_installation/

thank you so much

Claudio

**Comment by basilgello** [comment]
Hi! @claidiosa!

So, did you solve your issue? If not, I will check the logs :)

**Comment by claudiosa** [comment]
Hi @basilgello 

Unfortunately, no progress.
Did you read cautiously my last issue?
I just watch TV live as described here: https://catch-up-tv-and-more.github.io/live_tv_installation/
using the PVR client, nothing anymore ....

Where is my fault or should be try a Kodi version 19.0 from your repository?
My error (or wish) come from many others users, see in the Forum of Kodi. Could you do a Kodi with Catchup and PVR pre-installed? 😀😀😀😀 It is should be great 😀😀😀👏 👏 👏 👏 
who is the author from 
https://catch-up-tv-and-more.github.io/live_tv_installation/ ??? Maybe an issue there?

My problem is the same in a TV-Box (android - MXQ Pro ... very slow), a Linux in a netbook (32 bits) and
in Debian 64 bits. Three installations with same problem ... very sad for a starter in Kodi.

Thanks once in advance


claudio

**Comment by basilgello** [comment]
Hi Claudio!

If you use Debian 10 aka buster on amd64, all you need is my repository of 19.0.
Basically, what you need can be automated in a script for total newcomers.

Once more: to be able to help you, I need the screenshot of Kodi Settings - System info - Overall info
from your current Kodi. Also please backup your Kodi profile (it is in your home directory, named ".kodi")
before you start upgrading to 19.0.
