### ISSUE TITLE
[Leia] Dependencies build error

### ISSUE THREAD

**Issue by thepasto** [kodi-pvr/pvr.iptvsimple#429]
Hi guys, just to report my build issues:

 `-- Generating done
-- Build files have been written to: /home/thepasto/Devel/kodi-addon-pvr-iptvsimple/src/pvr.iptvsimple-3.9.8-Leia/build
[  2%] Performing patch step for 'tinyxml'
[  4%] Performing update step for 'p8-platform'
[  8%] Performing patch step for 'zlib'
[  8%] Performing patch step for 'rapidxml'
patching file ''
Hunk #1 FAILED at 183.
Hunk #2 FAILED at 201.
Hunk #3 FAILED at 211.
/usr/bin/patch: **** Can't reopen file '' : No such file or directory
Error: Target (for copy_if_different command) "" is not a directory.
make[2]: *** [CMakeFiles/zlib.dir/build.make:122: build/zlib/src/zlib-stamp/zlib-patch] Errore 2
make[1]: *** [CMakeFiles/Makefile2:209: CMakeFiles/zlib.dir/all] Errore 2
make[1]: *** Attesa per i processi non terminati....
make[2]: *** [depends/CMakeFiles/tinyxml.dir/build.make:122: build/tinyxml/src/tinyxml-stamp/tinyxml-patch] Errore 1
make[1]: *** [CMakeFiles/Makefile2:346: depends/CMakeFiles/tinyxml.dir/all] Errore 2
Error: Target (for copy_if_different command) "" is not a directory.
make[2]: *** [CMakeFiles/rapidxml.dir/build.make:122: build/rapidxml/src/rapidxml-stamp/rapidxml-patch] Errore 1
make[1]: *** [CMakeFiles/Makefile2:236: CMakeFiles/rapidxml.dir/all] Errore 2`

Archlinux user, if you need more, just ask.

Thanks

**Comment by AlwinEsch** [comment]
Think you use cmake 3.18? There was brought a bug inside where in conflict within Kodi's addon build system.

There was here https://github.com/xbmc/xbmc/commit/8f714dcc7f1a1dfa9b57ef18c3f4accc62cb0652 a fix added to Kodi Leia.
But as them no more become a new release, you need to take this as patch and add to your related Kodi source byself.

**Comment by thepasto** [comment]
Thank you so much, it works like a charm!
For me it's closed
