### ISSUE TITLE
Catch Up from EPG - only 30 minutes

### ISSUE THREAD

**Issue by mariyanpv** [kodi-pvr/pvr.iptvsimple#431]
Hello, when I use catch-up feature from EPG I'm getting only 30 minutes video even if the TV program is 2 hours.

**Comment by phunkyfish** [comment]
Do you have an example catchup format string?

**Comment by mariyanpv** [comment]
This is the string from my playlist.

#EXTINF:-1 tvg-id="tivi.2" tvg-name="tivi.2" group-title="information" catchup="default" catchup-source="http://AAAAA:80/sc.php?stid=2&mac=AAAAAA&key=9837bff8&utc=${start}&lutc=${timestamp}" catchup-days="7" ch-number="2" ch-order="2",bTV

**Comment by phunkyfish** [comment]
Can you provide a debug log which covers the  period then the stream ends?

**Comment by mariyanpv** [comment]
`2020-09-18 09:51:31.697 T:5041    DEBUG <general>: CurlFile::Open(0x8594b700) http://AAAAAAA:80/sc.php?stid=12&mac=AAAAAAA&key=61c3a594&utc=1600383600&lutc=1600411891
2020-09-18 09:51:31.882 T:5041    DEBUG <general>: CCurlFile::Open - effective URL: <http://AAAAAAA:88/stalker_portal/storage/get.php?ch_id=12&duration=1800&start=0&filename=20200918-02.mpg&token=0289b308379e31890ab3d4acd07e7320>`

Now I see in the debug log a parameter "duration=1800". So my iptv provider is limiting the catch-up duration?

**Comment by phunkyfish** [comment]
Yes, or they set a default as you did not provide one. It’s possible there is something you could add to your catchup URL to provide the duration.

But that might be provider specific.

**Comment by mariyanpv** [comment]
I understand. Thanks for help.
