### ISSUE TITLE
Any chance for iPad 1 iOS 5.1.1 ? 

### ISSUE THREAD

**Issue by sadtango289** [kodi-pvr/pvr.iptvsimple#432]
Hi . Im have a old iOS device - iIpad 1 . It can play good Kodi 17.6 Krypton . But i can't find some thing about play IPTV with combo " iIpad 1 + Kodi 17.6" . Any tricks to sovle ?

**Comment by phunkyfish** [comment]
Sorry, I really don’t know. I only started to work on this since kodi 18/19.
