### ISSUE TITLE
Catchup on unfinished program - streaming finishes early

### ISSUE THREAD

**Issue by berkhornet** [kodi-pvr/pvr.iptvsimple#433]
When viewing an unfinished program (ie starting viewing before the live transmission is complete) via catchup the stream terminates early. Viewing the same program after live transmission is complete works fine. This happens on all channels/programs.

I have run some tests and established that in this use case, the duration is not calculated correctly. For example, the EPG lists a program scheduled to start at hh:00 and finish at hh:30. When using "play program" from the EPG context menu at hh:xx the duration is calculated as xx. I ran 10 tests at varying times using different channels and always the duration was calculated as xx.

As an example, in my last test, the program was scheduled from 08:00 to 08:30. I selected "play program" at 08:06 and the duration was calculated as 6. Start and End buffers both set to 0 in Simple IPTV client settings. Here is an extract from the debug log:

2020-09-26 08:06:27.089 T:4108     INFO <general>: AddOnLog: inputstream.ffmpegdirect: ffmpeg[0000000000000000X]: Input #0, mpegts, from 'http://xxxxx:25461/streaming/timeshift.php?username=xxxxx&password=xxxxx&stream=523&start=2020-09-26:08-00&duration=6':

All tests performed on Windows 10 version 2004, and Kodi 19 nightly for Windows 64 from KodiSetup-20200924-39d2a7bc-master-x64.exe.

**Comment by phunkyfish** [comment]
If you manually play the URL like what is above with a duration of 30 does it actually play until 30?

Most providers don’t allow a duration greater than now and either the stream won’t play or it will when now (in this case 8:06) is reached anyway.

Also, what kind of video is in the stream? There is some logic around restarting streams for some types. It means you get a frame skip when it’s close to. 8:06 but it should keeping.  Maybe provide a debug log from before the stream starts and I can take a look.

**Comment by berkhornet** [comment]
Hi

As suggested, I entered the URL Google Chrome, which downloaded a file called timeshift.php.

Can you advise the best way to play and check this file?

Thanks

**Comment by phunkyfish** [comment]
Just add a new ordinary channel to your M3U file with they as the stream URL.

Alternatively open the URL in vlc.

**Comment by phunkyfish** [comment]
You can also open a create a `.strm` file and open it in kodi from the video menu. The only thing in the file should be the URL.

**Comment by berkhornet** [comment]
Hi

I tested using VLC, and yes the playback terminated before the end of the show. So my provider doesn’t support catch-up until the program has finished live transmission.

I’ll fix my IPTV Simple Client settings accordingly.

Many thanks for your help

Regards Mick

________________________________

**Comment by phunkyfish** [comment]
As I said above there is logic to deal with this in ffmpegdirect but for some reason it is not working for your stream. If you can submit a debug log I can try and see why it's not working.

If it's possible for your stream type the following should happen.

1. You play the programme starting at 8:00 at 8:06.
2. Once you are almost 6 mins into the programme ffmpegdirect will make a new call to your provider and request the stream until the new now (8:12) and splice it into the current stream.

It does this by detecting the stream end and using that to make the new request. It might be that you have a new use case for this logic and a simple fix could get it working for you too.

**Comment by berkhornet** [comment]
Debug log. My latest test starts at line 5670. I've changed any passwords for security.
[kodi.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/5286544/kodi.log)

**Comment by phunkyfish** [comment]
Is this standard catchup or timeshifted catchup?

Do you have the M3U entry used for this?

**Comment by berkhornet** [comment]
Hi

I tried both standard and timeshifted catchup.

The m3u entry is in this format

#EXTINF:-1 catchup="default" catchup-source="http://xxx:25461/streaming/timeshift.php?username=xxx&password=xxx&stream=458&start={Y}-{m}-{d}:{H}-{M}&duration={duration:60}" catchup-days="7" tvg-chno="10" tvg-id="ITVBe.uk" tvg-name="ITVBe.uk" tvg-logo="" group-title="ENTERTAINMENT",ITVBE FHD
http://xxx:80/live/xxx/xxx/458.m3u8

Thanks


.

**Comment by phunkyfish** [comment]
Are you able to seek using timeshifted catchup?

**Comment by berkhornet** [comment]
Hi. No - i tried seek with CTRL-right arrow and the stream finished and kodi reverted to the EPG

**Comment by phunkyfish** [comment]
Can you seek backward? So by a few minutes or so. Just trying to understand if your provider allows timeshifting or not. Even on an earlier program that is finished

**Comment by berkhornet** [comment]
hi. yes, i can seek backward using timeshift for live tv, for catch up for programs that have finished and for catch up programs that have not finished. thanks.

**Comment by phunkyfish** [comment]
Ok, so you should when using ffmpegdirect supply a MIME type. I think yours in mpegts so maybe try this before one of the M3U entries to see if it works:

```
#KODIPROP:inputstream=inputstream.ffmpegdirect
#KODIPROP:mimetype=video/mp2t
#KODIPROP:inputstream.ffmpegdirect.is_realtime_stream=true
```

From what I can see in the log your stream seems to be opened as a standard stream and not a catchup stream and I'm not sure why that is.

**Comment by berkhornet** [comment]
I've just done a quick test and that seems to fix it. so although my streams have a .m3u8 extension they are  really .ts streams. I will confirm with my provider. Many thanks for you help with this.

**Comment by phunkyfish** [comment]
NP

**Comment by berkhornet** [comment]
just to let you know I tried setting the input stream and mimetype in the addon’s advanced settings and that also worked.

**Comment by phunkyfish** [comment]
Amazing, feel free to close the issue if you are happy it’s revolved 😃
