### ISSUE TITLE
Feature request: Setting buffering time.

### ISSUE THREAD

**Issue by TmpName** [kodi-pvr/pvr.iptvsimple#44]
Is there a way to increase the buffering even if cause a delay in live TV?

With the addon, the buffer is at 20% (see when pressing O)
On normal player with same url buffer is at 100%.

**Comment by afedchin** [comment]
It's not possible in the addon. Use minvideocachelevel and minaudiocachelevel in advacedsettings.xml (http://kodi.wiki/view/Advancedsettings.xml#pvr)

**Comment by TmpName** [comment]
Nice thx, I could not find this option, it 's perfect.
