### ISSUE TITLE
PSA: Cloudflare connection issue

### ISSUE THREAD

**Issue by Anuskuss** [kodi-pvr/pvr.iptvsimple#440]
My IPTV provider recently switched to Cloudflare and I wasn't able to download the playlist nor play the channels since. I did some debugging and it turns out Cloudflare doesn't handle the `Upgrade: h2c` header (switch to HTTP/2) at all (see also [here](https://community.cloudflare.com/t/http-h2c-upgrade-requests-result-in-connection-reset-by-peer/214761)).
To fix this you need Kodi 19 and you need to put this into your `advancedsettings.xml`:
```xml
<network>
  <disablehttp2>1</disablehttp2>
</network>
```

This was the log:
```
ERROR: CCurlFile::Open failed with code 0 for http://example.org:
ERROR: Open - failed to open source <http://example.org>
ERROR: AddOnLog: PVR IPTV Simple Client: Unable to load playlist file 'http://example.org':  file is missing or empty.
```

cURL shows:
```
curl: (56) Recv failure: Connection reset by peer
```

The Kodi log was very unhelpful while the cURL output would've been very useful in solving this quicker. But I don't know if there's even anything you guys could've done there.

P.S. I also saw that pvr.iptvsimple was using the Kodi User-Agent while fetching the M3U even though I specified a User-Agent in the addon settings. Has this been fixed since?

**Comment by wsnipex** [comment]
already fixed: https://github.com/xbmc/xbmc/pull/18577

**Comment by Anuskuss** [comment]
Dang, I've spent all day debugging this that I forgot to look if it has already been fixed in master. Anyway, this was supposed to be a sticky until it's fixed in stable because that's the place *I* went to first so it could still potentially help others.
