### ISSUE TITLE
m3u parsing: 'http' to 'https'

### ISSUE THREAD

**Issue by resetter** [kodi-pvr/pvr.iptvsimple#443]
Might be a good feature to add an option to the plugin that parses the downloaded m3u file, allowing the http streams to be converted to https. Would be fairly trivial, just changing the stream address from http to https and port 80 to 443.

**Comment by phunkyfish** [comment]
Why?

**Comment by resetter** [comment]
This would give a lot of streamers a layer of security.

**Comment by phunkyfish** [comment]
How can that be? You can’t just assume a URL is also available in https in all cases.

If your provider wanted you to use https the M3U would use it already.

**Comment by Jr7000750** [comment]
Thnkx i try it now

Verstuurd vanaf mijn iPhone
