### ISSUE TITLE
Cannot play rtmp://

### ISSUE THREAD

**Issue by qwerttvv** [kodi-pvr/pvr.iptvsimple#453]
Tested with：
sony x900f
kodi-19.0-Matrix_beta1Android-armeabi-v7a & kodi-20201123-f1ea0e47-master-armeabi-v7a
IPTV Simple PVR 7.0.0-Matrix
Latest Version inputstream-adaptive, inputstream-ffmpegdirect, inputstream-rtmp with autoupdate

VLC 3.0.11 x64 on windows can be played very well

**Comment by phunkyfish** [comment]
Do you have a full debug log?

**Comment by qwerttvv** [comment]
emmmm,,,,how can i get full debug log?

let me do some dig :P

**Comment by phunkyfish** [comment]
https://kodi.wiki/view/Log_file/Easy

**Comment by phunkyfish** [comment]
Did you figure this out?

**Comment by qwerttvv** [comment]
> Did you figure this out?

I have changed the source to http...and no more rtmp......

**Comment by phunkyfish** [comment]
Ok, closing.
