### ISSUE TITLE
Stream Stalled on Unfinished Catchup Program

### ISSUE THREAD

**Issue by ceekdp** [kodi-pvr/pvr.iptvsimple#462]
I have an issue where if I start catchup on an unfinished program then the stream stops after a time and then crashes Kodi.  I see this was an issue previously for another user which was solved.  The description of the issue is the same as the previous.  https://github.com/kodi-pvr/pvr.iptvsimple/issues/433.  

Eg.  If I watch a program scheduled from 18:00 - 19:00 and I start it at 18:10. Then after 10 minutes of watching, the stream will freeze.  I have confirmed this behaviour also occurs in VLC if I request a duration beyond the live TV point.   I have tried this in CoreElec and in Windows latest nightly and the behaviour occurs in both.

In Kodi I am able to start streams in timeshift and am able to rewind past the start.

I have attached a debug log (with personal details removed). [kodi.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/5784219/kodi.log)

Thank you for your help and for all the work on this addon.  It really is a huge step forward for IPTV viewing. Please let me know if you require further info.

**Comment by phunkyfish** [comment]
I would need a test stream to try this out on. Can you provide me one on gitter.im?

**Comment by phunkyfish** [comment]
Also, did you configure the stream similar to the #433?. Do you have timeshifted catchup that is opened with ffmpegdirect?

**Comment by ceekdp** [comment]
I have added the Kodiprops as in #433. From my reading of the debug log I can see ffmpegdirect trying to open the stream again once the EOF is reached but then the stream stalls. 
I will try and contact you on gitter.im with a stream.

**Comment by phunkyfish** [comment]
Closing as they now works.
