### ISSUE TITLE
Error "Make" pvr.iptvsimple with kodi 19.0b2-Matrix

### ISSUE THREAD

**Issue by Gugur** [kodi-pvr/pvr.iptvsimple#464]
Basically, make stuck on: [  5%] Building CXX object CMakeFiles/pvr.iptvsimple.dir/src/PVRIptvData.cpp.o
https://pastebin.com/jLQZbPvu

I am using Debian testing

Any solution? Thanks you.

**Comment by phunkyfish** [comment]
You need the latest version of kodi master so it won’t work with Beta2 tar ball I’m afraid.

There was a late API change that could not be avoided.

**Comment by basilgello** [comment]
Hi @Gugur !

Kodi from Debian does track tagged releases only, not master trunk. That means. I do import, say, 19.0 Beta 2 or RC1 or 19.0 final AND all add-ons for it at once to be sure everything builds as expected.

You are using Debian testing. That means you must either:

* Build Kodi master trunk yourself and all add-ons you need (I don't recommend it, though, as you take all responsibility for updating your trunk builds)
* Build the packaged versions of Debian add-ons that i uploaded to Debian Salsa repo (https://salsa.debian.org/multimedia-team/kodi-media-center) that are guaranteed to work with 19.0 beta 2 packaged
* Wait for 19.0 RC1 to get uploaded to Debian - I am doing my best to get iptvsimple and all other 50+ binary addons to testing right now, or
* Ask me to build the unofficial repository for Debian testing just like I do for buster here: https://basilgello.github.io/kodi-nightly-debian-repo

The easiest for you and me right now is to build the packages that not yet entered Debian in my unofficial repo and let you test it. This will ensure smooth migration to official Debian add-on builds when they get ready.

What do you think?

**Comment by Gugur** [comment]
Thanks you to both, I will wait.

I want a clear system by now.

**Comment by phunkyfish** [comment]
As this is now in Debian I will close this.
