### ISSUE TITLE
IPTV Simple Client cannot be installed from KODI official repository.

### ISSUE THREAD

**Issue by Murianwind** [kodi-pvr/pvr.iptvsimple#465]
I can't see IPTV Simple Client in KODI 19 Beta 2. When I search and try to install it, the message 'The dependency on kodi.binary.instance.pvr' is displayed and the installation fails. Of course, even if I download the file from github and try to install it, the installation does not work. It was certainly possible to install it until a few days ago. What is it?

**Comment by phunkyfish** [comment]
Please install the latest kodi nightly build. There was an API change so the latest version is required to install it.

**Comment by hacker1024** [comment]
This is also the case for Kodi 20 "Nexus" Alpha 3; using a nightly build fixes this issue.
