### ISSUE TITLE
ABR stream not changing to better quality

### ISSUE THREAD

**Issue by wd69** [kodi-pvr/pvr.iptvsimple#470]
Hi. 

I have inputstream.adaptive addon installed.
I have enabled "use inputstream.adaptive for HLS streams"  (and the streams are indeed HLS).

but the video is staying at the lowest bitrate and not changing up.

On Leia version, ABR worked fine. My streams start at lowest quality then should move up to higher bitrate.

An ideas please?

**Comment by phunkyfish** [comment]
Maybe @matthuisman can help

**Comment by wd69** [comment]
Sorry guys it is not an issue, seems OK now.  Seems I can't delete this. Thanks.

**Comment by phunkyfish** [comment]
> Sorry guys it is not an issue, seems OK now. Seems I can't delete this. Thanks.

No worries. Thanks for letting us know.
