### ISSUE TITLE
IPTV Simple 7.4.0 Matrix broken EPG

### ISSUE THREAD

**Issue by rkuftyrev** [kodi-pvr/pvr.iptvsimple#473]
I used IPTV Simple 7.3.0 Matrix with edem.tv provider. All was fine. Yesterday addon was updated to 7.4.0 version and EPG doesn't work correctly now. It shows now one channel logo and one TV broadcast for all channels. I use remote path for EPG and playlist in settings.
EPG cache reloaded.
Kodi 19 RC1, Windows x64.

**Comment by phunkyfish** [comment]
Ah, ok. There were two things in that release. One change for epg load speed and another for filtering channel groups. Let’s try and figure out which caused the problem.

Could you provide a screenshot of the General tab in the add-on settings while in at least advanced settings mode?

**Comment by phunkyfish** [comment]
Also a full debug log would be helpful. Thanks!

**Comment by rkuftyrev** [comment]
Thanks for answer. Scrrenshots and log in debug mode in attach.






![Screenshot_1](https://user-images.githubusercontent.com/78682956/107146276-21339800-6958-11eb-9d49-21285041de93.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/78682956/107146277-2264c500-6958-11eb-8585-a62b02ed893a.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/78682956/107146278-2264c500-6958-11eb-9317-c80195c9cb88.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/78682956/107146279-22fd5b80-6958-11eb-9595-1f4c4a446a4c.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/78682956/107146280-22fd5b80-6958-11eb-9ee3-89c720c350dd.jpg)
[kodi.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/5938961/kodi.log)

**Comment by phunkyfish** [comment]
I might need to test this locally. Could you provide the M3U and EPG links privately on gitter.im?

**Comment by rkuftyrev** [comment]
Yes, i send You links on gitter.im

**Comment by phunkyfish** [comment]
Thanks
