### ISSUE TITLE
macos compilation

### ISSUE THREAD

**Issue by maxlapshin** [kodi-pvr/pvr.iptvsimple#478]
I have to change xbmc compile options from:

```
./configure --host=x86_64-apple-darwin
```

```
./configure --with-platform=macos
```

for it to compile. Without this option, it refuses to compile, claiming on "no platform specified"

**Comment by phunkyfish** [comment]
Do you mean that README needs to be updated or something else needs to be changed too?

**Comment by phunkyfish** [comment]
Fixed in https://github.com/kodi-pvr/pvr.iptvsimple/pull/480
