### ISSUE TITLE
LibreELEC crashes after PVR update

### ISSUE THREAD

**Issue by Grandma-Betty** [kodi-pvr/pvr.iptvsimple#479]
Yesterday I made an update of the PVR simple client and since then, after login with my personal profile, a few seconds later, LibreELEC crashes (black screen for a few seconds and then goes back to login screen (without rebooting the HTPC completely)).
I only have two add-ons installed:

- pvr.iptvsimple
- pvr.teleboy [https://github.com/rbuehlma/pvr.teleboy](url)

After a few tries I fortunately was quick enough to get into the add-on menu and disable the pvr.iptvsimple add-on before it crashed. Since then it does not crash anymore.
This happens on every other profile too which has the pvr.iptvsimple enabled.
I did not test if this happens too without having pvr.teleboy installed.

I'm on LibreELEC 9.2 (Kodi 18.9), latest release.

**Comment by phunkyfish** [comment]
Can you enable debug mode. Disable teleboy and enabled iptvsimple and then restart.

If you can provide the full debug log and crash log I take a look.

**Comment by matthuisman** [comment]
@NeverEatYellowSwissSnow 
I wonder if same issue some users of mine were having with 3.10.0
There is now a 3.10.1 which includes this fix: https://github.com/kodi-pvr/pvr.iptvsimple/pull/484

Its not in libreelec yet, but I have just done a pull request to get it bumped:
https://github.com/LibreELEC/LibreELEC.tv/pull/5176

so hopefully it shows up soon :)

**Comment by Grandma-Betty** [comment]
Issue resolved since 3.10.1, thank you.

**Comment by matthuisman** [comment]
oh, thats great!
I was wondering if your issue as the same as the one I was having (https://github.com/kodi-pvr/pvr.iptvsimple/pull/460#issuecomment-782929759)
