### ISSUE TITLE
Settings resetting 

### ISSUE THREAD

**Issue by shaunsss** [kodi-pvr/pvr.iptvsimple#481]
Hi,  I make changes in channel manager by hiding some channels and in group manager I rename groups and hide some groups. All settings save no issues and everything is setup the way I like it. Give it 5plus hours all settings revert back to default.   Is this a known issue? I have latest update of Kodi on my nvidia shield,  I have reinstalled Kodi, updated the app to the latest, formatted my nvidia and still can’t fix this.   Any ideas?  Thanks

**Comment by phunkyfish** [comment]
![Screenshot 2021-02-20 at 09 49 32](https://user-images.githubusercontent.com/4601187/108591499-fc302380-7360-11eb-9a46-ee306bbe39e3.png)

Make sure you uncheck synchronise channels with backend, channel order from backend etc. Otherwise it will update your custom order.

**Comment by shaunsss** [comment]
Thank you so much!   I have made the changes. 👍

**Comment by shaunsss** [comment]
Hello

After trying what you suggested it seems the 5 groups that were from back end have gone and now created one group with all channels.

The groups from back end is fine. I just want to hide some groups from the kids abd also hide some channels.  That’s the only issue and once I do hide channels abd groups that’s when the next day the groups will re appear along with the hide. Channels.  I hope that makes more sense of the issue?

Thanks.
Regards
Shaun


On 20 Feb 2021, at 10:42 pm, phunkyfish <notifications@github.com> wrote:

﻿

Closed #481<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkodi-pvr%2Fpvr.iptvsimple%2Fissues%2F481&data=04%7C01%7C%7C0df1e3105f9841aef0ba08d8d5948b12%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637494181249983542%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UC6Shu2nAPJWQSu%2FkBCLkd8iK3vzrvaphgswrtVHDv4%3D&reserved=0>.

**Comment by phunkyfish** [comment]
Can you show a screenshot of the PVR settings?

If you want to hide the groups from the backend you can you just add the groups you want to see in the addon settings and only show those. If you want to hide channels then you have to do it all custom and not use the backend groups at all.

The all channels groups is an automatic group giving you quick access to everyone. I’m not sure if it can be edited.
