### ISSUE TITLE
I can’t see my channels

### ISSUE THREAD

**Issue by AS27-pro** [kodi-pvr/pvr.iptvsimple#483]
I have the latest updates and I tried everything but I don't know why I still can't see my channels. Can someone please help me solve this problem.

**Comment by phunkyfish** [comment]
GitHub is for bugs with the add-on. If you need help with using the add-on please visit the forum.

https://forum.kodi.tv/forumdisplay.php?fid=215

**Comment by AS27-pro** [comment]
Ok thank you
