### ISSUE TITLE
CoreElec/Win Kodi 19 long switching channels

### ISSUE THREAD

**Issue by otava5** [kodi-pvr/pvr.iptvsimple#486]
Hello. On Kodi 19, it takes a long time to switch channels up to 25 s. Can you advise what to do with it? I'm adding a kodi log + debug. It goes bad under Win10 and under CoreElec. On Kodi 18.x, everything worked right away. Thank you
https://paste.kodi.tv/itunuvisif.kodi

**Comment by phunkyfish** [comment]
You have a banned addon installed. In your log it’s highlighted in orange. Can you remove it and create a new log?

**Comment by otava5** [comment]
https://paste.kodi.tv/ujalidagub.kodi

**Comment by phunkyfish** [comment]
What format is the video data in?

Also, is it just switching channels or is it also when you open a channel?

**Comment by otava5** [comment]
TS format ,switching and open channels.....

**Comment by phunkyfish** [comment]
What happens if you set a default mime type of `video/mp2t` in the addon settings?

**Comment by otava5** [comment]
It's okay now ... Thank you very much
