### ISSUE TITLE
LibreELEC on MX2/G18 box with Kodi Krypton 17.3

### ISSUE THREAD

**Issue by pepev82** [kodi-pvr/pvr.iptvsimple#487]
Dear all,

I tried to install from .zip file which was downloaded from here, but Kodi given an error message "Failed to install from zip file" and that's all. :(

Device: G Box MX2 / G18REF board
LibreELEC 8.0.2
Kodi Krypton 17.3
file name: pvr.iptvsimple-Krypton.zip
file size: 246 767 bytes

Any advice more than appreciated!

(newer version of Libreelec and Kodi causes remote control issues/problems on this box :(((  )

Kind regards,
Pepev82

**Comment by lrusak** [comment]
You can't install a binary add-on from github. it has to be compiled. pvr.iptvsimple is available in the LibreELEC add-on repo.

**Comment by pepev82** [comment]
Thank you for your answer.
When i try to open the LibreELEC Add-ons to install simple iptv client, i got an error message: Could not connect to repository. :(

**Comment by pepev82** [comment]
nevermind, solved!

Thank you once again for your help!
