### ISSUE TITLE
No sound when timeshifting

### ISSUE THREAD

**Issue by BreizhReloaded** [kodi-pvr/pvr.iptvsimple#490]
Hello,

I'm working on [this plugin](https://github.com/BreizhReloaded/plugin.video.orange.fr), redirecting web TV streams to Kodi via IPTV Simple and it works great on most use cases, but I noticed a strange behaviour. 

Steps to reproduce:
- Select channel and play stream
- Pause stream, starting timeshift
- Fast-forward 2x or 4x for a couple of seconds
- Then back to regular playback

When I perform those actions, video is ok, but I don't have any more audio. The only way to get it back is to press stop, and go back to live, losing the content in between. I can share the logs, but I don't see any error. It may come from my implementation, but I don't see where I'm wrong.

Here is a sample of my .m3u8 file:
```
## TF1
#EXTINF:-1 tvg-name="TF1" tvg-id="192" tvg-logo="https://proxymedia.woopic.com/553/p/logos/v2/logos/livetv_tf1/20180417_164011/webTVSquare/logo_150x150.png" tvg-chno="1" group-title="Orange TV France",TF1
plugin://plugin.video.orange.fr/channel/192
```

And the code called when selecting a channel:
```python
stream = Provider().get_stream_info(channel_id)
if not stream:
    dialog('This channel is not part of your current registration.')
    return

is_helper = inputstreamhelper.Helper(stream['manifest_type'], drm=stream['drm'])
if not is_helper.check_inputstream():
    dialog('Cannot load InputStream.')
    return

listitem = xbmcgui.ListItem(path=stream['path'])
listitem.setMimeType(stream['mime_type'])
listitem.setProperty('inputstream', 'inputstream.adaptive')
listitem.setProperty('inputstream.adaptive.manifest_type', stream['manifest_type'])
listitem.setProperty('inputstream.adaptive.license_type', stream['license_type'])
listitem.setProperty('inputstream.adaptive.license_key', stream['license_key'])
xbmcplugin.setResolvedUrl(plugin.handle, True, listitem=listitem)
```

Is a known limitation of InputStream Adaptive used with IPTV Simple?

Thanks!

**Comment by phunkyfish** [comment]
You need to raise this issue against inputstream.adaptive here: https://github.com/xbmc/inputstream.adaptive/issues

**Comment by BreizhReloaded** [comment]
Hmm... Time shifting capabilities don't come from IPTV Simple? I'm still a newbie around here, just for me to understand: what makes you sure this issue comes from them?

**Comment by BreizhReloaded** [comment]
Posted here: [#612](https://github.com/xbmc/inputstream.adaptive/issues/612)

**Comment by phunkyfish** [comment]
Timeshifting is tied to the inputstream.

The default one in iptvsimple uses inputstream.ffmpegdirect and uses a local buffer. The timeshifting you use will be different as comes from inputstream.adaptive that does not use a buffer.

If you want to see the difference play any live TS stream directly in iptvsimple and it will default to ffmpegdirect once Timeshift is enabled.

**Comment by BreizhReloaded** [comment]
Ah, ok. Interesting. Thank you for the explanation!
