### ISSUE TITLE
some epg error

### ISSUE THREAD

**Issue by qwerttvv** [kodi-pvr/pvr.iptvsimple#492]
2021-03-11 17:24:44.962 T:14029   ERROR <general>: UpdateFromScraper: No EPG scraper defined for table ''
    2021-03-11 17:24:44.962 T:14029   ERROR <general>: Update: Failed to update table ''

full log https://github.com/xbmc/xbmc/files/6124047/kodi.zip and https://github.com/xbmc/xbmc/files/6091632/kodi.zip

some info https://github.com/xbmc/xbmc/issues/19338

：）

**Comment by phunkyfish** [comment]
It means that an epg update failed for some reason. It’s not important and can be ignored. 

You probably have a channel with no name.

**Comment by qwerttvv** [comment]
> It means that an epg update failed for some reason. It’s not important and can be ignored.
> 
> You probably have a channel with no name.

Thank you for reply
All channels have names
But there are some channels that don't have matching names in the epg file
For example
#EXTINF:-1 tvg-name="nothing123",ABCD
There is no nothing123 in the epg file
Is it because of this?

There is the m3u8
https://github.com/qwerttvv/Beijing-IPTV/blob/master/IPTV-Unicom.m3u

**Comment by phunkyfish** [comment]
Maybe, I’m not sure. But I don’t think the error is a problem. I see it on my system too sometimes and I don’t have any issues.

**Comment by qwerttvv** [comment]
> Maybe, I’m not sure. But I don’t think the error is a problem. I see it on my system too sometimes and I don’t have any issues.

Ok, I will do some test about "nothing123" : )

**Comment by phunkyfish** [comment]
This issue is fixed in Kodi 19.1 once it is released. So will close the issue.

**Comment by D4anielCB** [comment]
It still keeps flooding the system log with those error even using the latest version, over 45k entries -.-

**Comment by phunkyfish** [comment]
> It still keeps flooding the system log with those error even using the latest version, over 45k entries -.-

Exactly the same error or is each one slightly different?
