### ISSUE TITLE
Need Help Using Custom Header

### ISSUE THREAD

**Issue by HeIp** [kodi-pvr/pvr.iptvsimple#497]
Website: https://www.americateve.com/contenidos/vivo.html or https://ssh101.com/detail.php?id=ACVTV
Link in question : https://tna5.bozztv.com/ACVTV/index.m3u8

Tried getting this m3u8 stream to work with the following : 
https://tna5.bozztv.com/ACVTV/index.m3u8|if-modified-since=Thu, 18 Mar 2021 00:44:42 GMT&if-none-match="1a1-5bdc4e7b48da1-gzip"&!Sec-Fetch-Dest=empty&!Sec-Fetch-Mode=cors&!Sec-Fetch-Site=cross-site&!sec-ch-ua-mobile=?0&dnt=1&!Host=tna5.bozztv.com&!sec-ch-ua="Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"&origin=https=//ssh101.com&referer=https=//ssh101.com/&User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

I tried using custom headers and the user-agent header but did not load in kodi can anyone help ?

**Comment by phunkyfish** [comment]
GitHub issues or not for support. It’s for bugs with the addon. Please use the kodi forum here: https://forum.kodi.tv/forumdisplay.php?fid=215
