### ISSUE TITLE
Using Catchup on unsupported channels causes kodi to crash/hang

### ISSUE THREAD

**Issue by arthur-liberman** [kodi-pvr/pvr.iptvsimple#499]
Tested on Windows and on CoreELEC, latest stable Matrix release, v7.5.0 of pvr.iptvsimple.
My M3U file only includes a `tvg-rec` tag, which indicates the length of catchup in days. The provider uses the Shift catchup method.
```
#EXTM3U
#EXTINF:0 tvg-rec="3",Chan1
#EXTGRP:Общие
http://my.iptv.net/iptv/mykey/2402/index.m3u8
#EXTINF:0 tvg-rec="0",Chan2
#EXTGRP:Общие
http://my.iptv.net/iptv/mykey/204/index.m3u8
```
`tvg-rec="0"` indicates that there is no catchup on that channel. The only way I can see to make catchup work at all is by forcing it on all channels. But it also marks channels that do not have catchup as supported. If I seek back from live, or select any past program, Kodi freezes. On Windows I am able to click on stop, but then kodi crashes and drops me back to the desktop. On CE it hard-locks.

**Comment by phunkyfish** [comment]
I think you added that tag right? At the time I don't remember any logic around `="0"`.

So it's that you want it to enable catchup of type shift for any entry where `tvg-rec > 0`?

**Comment by phunkyfish** [comment]
Try this: https://github.com/kodi-pvr/pvr.iptvsimple/pull/500

BTW, you should never use catchup on unsupported channels!!!

**Comment by arthur-liberman** [comment]
Yes I added the tag, but looks like I misread the code back then and made a mistake.

Thanks, your fix has worked, but there are still several issues remaining (testing on CE right now, as I've got a build env setup)
* I had to revert the `pugixml` fix, because Kodi kept restarting when it tried to load the EPG (xml.gz file)
* Something I don't quite get is, the number of days set in the Catchup settings takes precedence over what is defined in `tvg-rec`. So the addon now correctly identifies catchup channels, but the number of days you can actually seek back to goes by what is set in the settings. In my case it should be 3 days. I tried the default 5 and 2 days in the addon settings, and it used that figure instead of what is specified in tvg-rec.
* Now, this is more a problem of my iptv provider than the code in the add-on, but the problem remains. In a few cases, a channel is marked as catchup capable in the m3u file, while it is in fact not capable. So it looks like the main problem of the stream getting stuck, and kodi freezing/crashing remains in this case.
I have never paid too much attention to this, as on Leia, in my archive implementation, when I tried to seek on such channels, it would just cut the stream and drop me back to the last Kodi screen I was on (channels/home/epg/whatever)
But here it's a major issue.

**Comment by phunkyfish** [comment]
I think you will that the hard locking goes away after this PR is merged: https://github.com/xbmc/inputstream.ffmpegdirect/pull/92

I also dropped the pugixml fix. It failed due to a cmake bug on ubuntu bionic.

Let me look at the override.

**Comment by phunkyfish** [comment]
> * Something I don't quite get is, the number of days set in the Catchup settings takes precedence over what is defined in `tvg-rec`. So the addon now correctly identifies catchup channels, but the number of days you can actually seek back to goes by what is set in the settings. In my case it should be 3 days. I tried the default 5 and 2 days in the addon settings, and it used that figure instead of what is specified in tvg-rec.

This should not be the case. The value from settings should only be used if no other value is set.

EDIT: I think you have found a bug here.

**Comment by arthur-liberman** [comment]
Cool, this PR indeed fixes the problem, thanks.

**Comment by phunkyfish** [comment]
Try the latest version in the PR, it should also fix the catchup windows from settings issue.

EDIT: Minor bug when I first pushed it. It should work now.

**Comment by arthur-liberman** [comment]
Great, looks like everything works.
I patched ffmpegdirect with your PR, and now the seek "fails", and playback seems to just continue, so that's resolved.
The rvg-rec fix also works as expected now, only thing is I had to tweak the code a little bit for it to compile successfully.
```diff
@@ -107,7 +107,7 @@ void CatchupController::ProcessEPGTagForTimeshiftedPlayback(const kodi::addon::P
 
     time_t timeNow = time(0);
     time_t programmeOffset = timeNow - m_catchupStartTime;
-    time_t timeshiftBufferDuration = std::max(programmeOffset, Settings::GetInstance().GetCatchupDaysInSeconds());
+    time_t timeshiftBufferDuration = std::max(programmeOffset, static_cast<time_t>(channel.GetCatchupDaysInSeconds()));
     m_timeshiftBufferStartTime = timeNow - timeshiftBufferDuration;
     m_catchupStartTime = m_timeshiftBufferStartTime;
     m_catchupEndTime = timeNow;
```
Or maybe it's better to cast `programmeOffset` to `int`, not sure.

**Comment by phunkyfish** [comment]
Yes, I made the same change! Matches your exactly.

**Comment by arthur-liberman** [comment]
Awesome, in that case everything should work properly once the PRs are merged and the packages are bumped.
Thanks for the quick turnaround for a solution.
