### ISSUE TITLE
log filling with info when postponing

### ISSUE THREAD

**Issue by rafhtl** [kodi-pvr/pvr.iptvsimple#504]
INFO <general>: [service.iptv.manager] [resources.lib.modules.iptvsimple] Postponing restart of Simple IPTV since it is currently in use

Hi thank you for the wonderful work on the addon
Ive noticed streaming for a long time that pvr is correctly postponing epg, but it is filling log with the message
can you help me?
thank you

**Comment by phunkyfish** [comment]
The issue with service.iptv.manager and not pvr.iptvsimple 

@michaelarnauts can you help?
