### ISSUE TITLE
Feature Request: Force use of Local Channel Logos

### ISSUE THREAD

**Issue by berkhornet** [kodi-pvr/pvr.iptvsimple#505]
Hi. Would it be possible to include an option to force the use of locally stored channel logos, ignoring any logos in both the M3U and XMLTV files. Many thanks.

**Comment by phunkyfish** [comment]
That should already be the case if local path is used for logos.

You may need to clear the thumbnail cache

**Comment by phunkyfish** [comment]
You need to do something like this to clear the cache: https://github.com/kodi-pvr/pvr.vuplus/issues/252

**Comment by berkhornet** [comment]
Many thanks for you reply. I've tried you suggestion but still have an issue. I'm using XEEV Editor to maintain my m3u files. This has an option to remove picons (logos) from the generated m3u files. However, when XEEV syncs with the provider the providers logos reappear in the generated m3u file, and are displayed in the PVR EPG instead of my local logos.

I also use the XEEV m3u files on apps other than Kodi and need the providers logos there.

I hope that explains my situation more clearly. Many thanks for your time.

On another point, I've tried the new functionality in v 7.6.0 regarding XEEV format catch up. This works a great - many thanks. I did notice that I needed to set the "Use XC2 API Protocol" flag in the XEEV editor which you may want to add to the read me file. Thanks again.

**Comment by phunkyfish** [comment]
Sorry, I misunderstood your question. If there is a logo in the M3U that will be used first so that makes sense, M3U trumps local path. I don't really know anything about the XEEV editor, it was just a request I implemented.

Why not just have 2 playlists in XEEV one for Kodi without the icons and another for everything with them? The local channel logo path in kodi is supposed to be a fallback for when none are given in the M3U file.

**Comment by berkhornet** [comment]
Thanks again for your reply. Unfortunately having two playlists isn’t the answer, because every time the playlist without icons syncs with the iptv provider, the icons are updated into the playlist. it is then necessary to manually go into the editor and clear the icons.

Regards Mick

________________________________

**Comment by phunkyfish** [comment]
Ah, ok. Sounds like more of a bug XEEV but let me look and see what is possible.

**Comment by phunkyfish** [comment]
PR: https://github.com/kodi-pvr/pvr.iptvsimple/pull/506
Testbuilds: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-506/1/artifacts

Under channel logos in the addon settings there is a new advanced setting (it will only show if you have a local path selected). Please test it.

**Comment by berkhornet** [comment]
Hi. That test build works very well. I downloaded an m3u file that included channels logos, but my locally stored logos were displayed. Thank you.

Is it possible to extend that setting to remote m3u files?

UPDATE:
I've noticed that the new setting "for local path ignore logos from m3u" persists even if a remote path is set. So I tested using a remote file that included logos and found that my locally stored logos were displayed.

Thanks again for your help.

**Comment by phunkyfish** [comment]
The path is the logos path not the M3U path which is probably why it still works.

**Comment by berkhornet** [comment]
Ok, I understand, Many thanks for your help with this.

**Comment by phunkyfish** [comment]
Released 7.6.1, closing issue.
