### ISSUE TITLE
Weird looping/dropping

### ISSUE THREAD

**Issue by mohrezaei** [kodi-pvr/pvr.iptvsimple#508]
I've noticed some weird looping/dropped content in some streams. The following stream is an extreme example of this:

https://reuters-reuters-1-eu.rakuten.wurl.com/manifest/playlist.m3u8
(choose 1280x720, which points to beb82be259b22da46051545f5ab288e7.m3u8 at the time of writing)

The stream plays fine in my browser on the same network as the kodi box in a simple player:
https://www.hlsplayer.net/#type=m3u8&src=https%3A%2F%2Freuters-reuters-1-eu.rakuten.wurl.com%2Fmanifest%2Fplaylist.m3u8

ffmpeg (4.3.1) can also put the stream together, but complains with " Invalid DTS: 99867 PTS: 99800 in output stream 0:0, replacing by guess", etc.

`ffmpeg -reconnect 1 -reconnect_streamed 1  -reconnect_delay_max 4000 -i "https://reuters-reuters-1-eu.rakuten.wurl.com/manifest/beb82be259b22da46051545f5ab288e7.m3u8" -c copy  -f segment  -segment_time 900 -segment_atclocktime 1 -strftime 1 "reuters-%Y-%m-%d_%H-%M-%S.mkv"`

Plugin version 7.6.0.1, Kodi 19 (coreelec)

**Comment by phunkyfish** [comment]
Can you try on a laptop computer using a vanilla kodi build?

Can you supply a full debug log?

Are you using ffmpegdirect? If so what version?

**Comment by mohrezaei** [comment]
That would take some effort on my part. Does the stream work for you?

I'm not sure if the plugin is configured for ffmpegdirect (there is nothing in the settings that says that, but it does appear in the dependencies as version 1.20.0.1).

**Comment by phunkyfish** [comment]
Supplying a debug log would be effort for you? 

It works for me.

**Comment by phunkyfish** [comment]
Did you try switching off timeshifting?

**Comment by phunkyfish** [comment]
After leaving it run a longer I think I get the same skipping.

**Comment by phunkyfish** [comment]
If it still happens with timeshifting off it means it's an issue in kodi and that would be the right place to raise the issue.

**Comment by mohrezaei** [comment]
Phew... thanks for trying it.
It's an ancient problem. I had it in Kodi 18 but didn't want to report it because the code for 19 was nearly live and totally different. 

This can't be a problem in the m3u8 parsing and giving the segments in the wrong order to the kodi player, right? this stream seems to have unusually long stream segment urls with funky characters.

**Comment by phunkyfish** [comment]
I’m afraid I have no idea. All the addon does is pass the m3u8 file to Kodi.

**Comment by mohrezaei** [comment]
thanks for the help. Issue raised with kodi: https://github.com/xbmc/xbmc/issues/19584
