### ISSUE TITLE
Zapping to a URI of type plugin://

### ISSUE THREAD

**Issue by gdomenici** [kodi-pvr/pvr.iptvsimple#51]
Hi,

My M3U playlist contains media entries starting with `plugin://`, like so:

    #EXTINF: ...
    plugin://plugin.video.zattoobox/?ext=PvrSync&cid=itv-1-london&mode=watch&id=itv-1-london

What I was thinking would happen is that IPTV Simple PVR would invoke the video plugin `plugin.video.zattoobox` (which is present in my installation) and pass it the query-string parameters (which is what happens when the Kodi core itself encounters a URI like that).

What happens instead is that I get this error in the log:

    XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.zattoobox/?ext=PvrSync&cid=itv-1-london&mode=watch&id=itv-1-london

**Would it be possible for IPTV Simple PVR to handle `plugin://` type of URIs?**

For some background discussion on why this is needed, see this thread on the ZattooBox pull request thread: https://github.com/nancpasc/ZattooBox/pull/17#issuecomment-166122020.

Thanks for your help.

Best regards,

Guido

**Comment by afedchin** [comment]
It's not possible.
