### ISSUE TITLE
m3u playlist dont work with the last update pvr iptv simple client 7.6.2 kodi19

### ISSUE THREAD

**Issue by burimek** [kodi-pvr/pvr.iptvsimple#514]
m3u playlist dont work with the last update 7.6.2 kodi19. if i downgrade kodi with the last addon pvriptv it work immediatly
maybe fix it this bug in next review 7.6.3 ???
i try to downgrade to 7.6.1 but no way have error instalation, maybe have you how to???
thanks in advance

ps: sorry for my bad english i am french!!!

**Comment by phunkyfish** [comment]
Can you supply a full debug log? Otherwise I have no idea what error you are getting.

**Comment by burimek** [comment]
i ty to find it in my pc???i lokk how to have this log but i have this probleme in two android tv and the same in my wondows pc

**Comment by burimek** [comment]
[kodi.old.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/6439891/kodi.old.log)

**Comment by phunkyfish** [comment]
Is the issue that the M3U file does not load or that you cannot play the channels?

Can you supply the M3U file so I can test it?

you can send it to me privately on gitter.im

**Comment by burimek** [comment]
hi i can not play the channel with the lastet update from kodi
if i played with vlc its work and if i downgrade to kodi 18.9 with latest pvriptv for leia its work no probleme
i have tested with other m3u file and works just my private m3u dont work with this update???what wrong?

**Comment by phunkyfish** [comment]
Can you send me the private M3U on https://gitter.im so I can test and figure out what is wrong?

BTW gitter.im is a private chat client where you can use your GitHub account to chat with other GitHub users.

**Comment by burimek** [comment]
ok
i try it

**Comment by phunkyfish** [comment]
> [kodi.old.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/6439891/kodi.old.log)

Nowhere in this log do you attempt to play a channels so there is no error. Also it needs Kodi needs to be in debug mode. Instructions here: https://kodi.wiki/view/Log_file/Easy

**Comment by burimek** [comment]
Problem solved without doing anything suddenly it works, incomprehensible that my own m3u file no longer worked while another taken on the net worked and by magic it restarts on my 4 machines so good weird but happy that it works. Thank you to those who have come up with an idea and long live for kodi user and dev !!! 
special thx to phunkyfish
best regard
