### ISSUE TITLE
Plugin endpoint for EPG/Channels URL

### ISSUE THREAD

**Issue by ratcashdev** [kodi-pvr/pvr.iptvsimple#518]
Is it possible to call a plugin endpoint from IPTV PVR to get the channel list or EPG?
Something like this:
```
plugin://plugins.video.mytv/?action=channel_list&format=m3u
plugin://plugins.video.mytv/?action=epg_guide&format=xml
```
if yes, how should the plugin return the data? Is there a short tutorial somewhere?

**Comment by phunkyfish** [comment]
I don’t know. Try returning a string.

**Comment by ratcashdev** [comment]
Well, tried that, but results in KODI closing (crashing?).
```python
def epg():
    # returning a str containing the XMLTV data.
    return "<?xml ...?> ..."

if __name__ == "__main__":
    params = dict(parse_qsl(sys.argv[2].replace("?", "")))
    action = params.get("action")

    if action == "epg"
        return epg()
```

**Comment by phunkyfish** [comment]
@matthuisman should this work?

**Comment by matthuisman** [comment]
I don't think IPTV simple allows using a plugin path as Playlist or epg source... Only urls or local files. Plugins can't return data like that anyway. Plugins create directories and files.

User will need to just add support for IPTV Manager to their addon or create an http server to return the data
