### ISSUE TITLE
Error while building app

### ISSUE THREAD

**Issue by San4ito** [kodi-pvr/pvr.iptvsimple#522]
Hi!
I tried to install using instructions and when i use "make" it fails. Error message is:
![Screenshot from 2021-06-07 20-46-43](https://user-images.githubusercontent.com/24568377/121065258-3cf95e80-c7d1-11eb-9067-9cf26e16851f.png)
In filemanager there is no folder "pkgconfig":
![Screenshot from 2021-06-07 20-48-53](https://user-images.githubusercontent.com/24568377/121065438-6f0ac080-c7d1-11eb-8f43-81e186ee342c.png)
How to solve this problem?

**Comment by phunkyfish** [comment]
What platform are you building on and using what guide?

**Comment by San4ito** [comment]
> What platform are you building on and using what guide?

I use Arch. First of all i tried install from AUR (Arch User Repository) but received the same problem - missing file/directory "pkgconfig".
Then i used this guide: https://github.com/kodi-pvr/pvr.iptvsimple#build-instructions

**Comment by phunkyfish** [comment]
Those build instructions are for Ubuntu. I’m not sure of the instructions for arch.

maybe try to build kodi first and then try to build the addon.

**Comment by San4ito** [comment]
I just reinstall kodi and it works!😂
