### ISSUE TITLE
TVOS, no PVR Simple IPTV Client?

### ISSUE THREAD

**Issue by AntiBigmac** [kodi-pvr/pvr.iptvsimple#525]
I have installed 19.1 TVOS on to my new Apple TV 4K 2021. But there is no PVR addons.

Any idea, why it is missing?

**Comment by Evandro1975** [comment]
> I have installed 19.1 TVOS on to my new Apple TV 4K 2021. But there is no PVR addons.
> 
> Any idea, why it is missing?

TVOS is not Kodi

**Comment by phunkyfish** [comment]
> I have installed 19.1 TVOS on to my new Apple TV 4K 2021. But there is no PVR addons.
> 
> Any idea, why it is missing?

Weird, it should be there. Did you use the actual Kodi build for this? 

FYI: @kambala-decapitator @fuzzard @sy6sys2

**Comment by AntiBigmac** [comment]
> > I have installed 19.1 TVOS on to my new Apple TV 4K 2021. But there is no PVR addons.
> 
> > 
> 
> > Any idea, why it is missing?
> 
> 
> 
> Weird, it should be there. Did you use the actual Kodi build for this? 
> 
> 
> 
> FYI: @kambala-decapitator @fuzzard @sy6sys2

Yes. I did. Very weird. 🤔

**Comment by AntiBigmac** [comment]
> > I have installed 19.1 TVOS on to my new Apple TV 4K 2021. But there is no PVR addons.
> 
> > 
> 
> > Any idea, why it is missing?
> 
> 
> 
> TVOS is not Kodi

Sorry for confuse. I meant Kodi 19.1 on the TVOS.

**Comment by kambala-decapitator** [comment]
I installed 19.1 release a few days ago and I have PVR clients.

@AntiBigmac where are you checking exactly?

**Comment by AntiBigmac** [comment]
> I installed 19.1 release a few days ago and I have PVR clients.
> 
> 
> 
> @AntiBigmac where are you checking exactly?

Install from repository
Kodi Add-on repository

But no PVR Client

I have both Shield TV Pro and Apple TV 4K 2021. My Shield TV Pro has PVR Client but not with Apple TV 4k 2021.

My Apple TV 4k 2021 has TVOS 14.5 version as OS.

**Comment by phunkyfish** [comment]
Could the issue be with the newer Apple TV 4K 2021?

**Comment by AntiBigmac** [comment]
> Could the issue be with the newer Apple TV 4K 2021?

Maybe. But not sure. Also try to install from "pvr.iptvsimple-Matrix.zip", but failed to install.

**Comment by lrusak** [comment]
Kodi for TVOS includes binary addons, you need to enable the addons that are already included as they aren't in a repository.
