### ISSUE TITLE
Freezing problem

### ISSUE THREAD

**Issue by Ricrdsson1** [kodi-pvr/pvr.iptvsimple#544]
I have a problem with the client freezing every time I switch the program in Kodi 19. In kodi version 18.9 it still works well. Tested on Windows and also on the box with CoreElec same problems.

I'm sending a debug log
.......
I think there are some bugs with FFMPEG

**Comment by phunkyfish** [comment]
Can you try two things. First try turning off timeshift in the addon settings.

Second, please test on another platform. I.e. not CoreElec. Like windows, Mac etc. If it also does not work there it’s likely an FFMpeg issue.

**Comment by Ricrdsson1** [comment]
time shift off. But the problem is still the same on Windows. Couldn't it be a problem with the shape of the url? http://ip:6289/login/password/1 some playlists downloaded from the internet play well. but those from my iptv provider only on Kodi 18.9. On Kodi 19, I can wait 20 seconds before the channel starts

**Comment by phunkyfish** [comment]
Do you have a sample M3U entry?

Please obfuscate any login info.

**Comment by Ricrdsson1** [comment]
I'm sending a sample m3u
I can easily send you the original so you can try it out.
[iptv.m3u](https://home.richardpodzemsky.cz/local/iptv.m3u)

**Comment by Ricrdsson1** [comment]
so I found out that the problem probably won't be in the supplement. When I test it on the phone, I have the problem I described on my internet network. But when I turn on the data network, the problem disappears. Maybe a problem with DNS? But why does it work great on 18.9 then ?.

**Comment by phunkyfish** [comment]
Very strange. Can you try it on a different network? So not your home network, maybe a friends?

**Comment by rene250382** [comment]
I join the author. Addon not installed on Windows (10) or AndroidTV (9) in Kodi 19+. When trying to install the Kodi closes. 18.9 works well

**Comment by phunkyfish** [comment]
Also, do you know if it’s using inputstream adaptive for the streams. If they are HLS streams you could try switching on adaptive in settings. I think it’s under advanced.

**Comment by Ricrdsson1** [comment]
So the mime type solved the problem
![FB_IMG_1640365210303](https://user-images.githubusercontent.com/89133235/147365927-8c1d5180-357c-49c6-8612-cd2d52ad8feb.jpg)
