### ISSUE TITLE
Certain channels are not playing from url.

### ISSUE THREAD

**Issue by Niyasmkkv** [kodi-pvr/pvr.iptvsimple#546]
http://cdn.asianetmobiletvplus.com/channels/rosebowl_7eb4dc1f3240c8eb776d41b95bd1d197/chunks.m3u8

The above channel is not playing on Kodi, but works fine with vlc.

**Comment by phunkyfish** [comment]
For me access is forbidden to this file.

**Comment by Niyasmkkv** [comment]
[kodi.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/7020310/kodi.log)
Here is the log file.

**Comment by phunkyfish** [comment]
It is failing because this URL cannot be found:

`AddOnLog: PVR IPTV Simple Client: Unable to load playlist file 'http://streamiptv.xyz:4300/siptv/user17:uz0ux9:playlist.m3u':  file is missing or empty.`

**Comment by phunkyfish** [comment]
Can you try to install kodi from scratch? I.e. a completely clean install? I see lots of settings in old format errors in the log. Not sure what is happening there.

**Comment by Niyasmkkv** [comment]
That link work fine now. Made few changes to the playlist and it's fine now.
