### ISSUE TITLE
Logs spammed with EPG data errors and slowness on a firestick

### ISSUE THREAD

**Issue by micahg** [kodi-pvr/pvr.iptvsimple#550]
Hello,

I'm adding IPTV Manager support to my CBC addon: https://github.com/micahg/plugin.video.cbc/tree/feature/iptv_manager.

Its working but I'm noticing that when I enable IPTV Manager, I get this repeating ad nauseum:

```
ERROR <general>: UpdateFromScraper: No EPG scraper defined for table ''
ERROR <general>: Update: Failed to update table ''
```

Here is a sample: https://paste.kodi.tv/wikomurubi

I can't quite tell if this is an issue with my addon (having no guide data), IPTV manager OR iptv simple, but I'm happy to investigate. I'm running on kodi 19.1.

If I leave things on, my firestick will eventually slow to a crawl and become unusable.  My laptop is never running long enough to elicit the performance issue (or is just better equipped to deal).

Looking for some advice or a starting point on how I can help resolve this problem.  Would it be beneficial to turn up the debugging and resubmit a log?

Thanks in advance,

**Comment by phunkyfish** [comment]
I think this is a message logged by kodi (not this addon) when a channel can’t be update with EPG data. I.e. it has no EPG data.

**Comment by ksooo** [comment]
Could also be a corrupted EPG database.

**Comment by phunkyfish** [comment]
If a channel is created by the PVR Client it should have a scraper name of `client`. If the channel is created/updated without an EPG ID and one is never set then the scraper name is left as an empty string and would log that error (`UpdateFromScraper: No EPG scraper defined for table`).

So if the first ERROR message is logged the second is also logged when called in the context of an EPG update.

@ksooo I wonder in this case should those log messages be DEBUG level. 

So we either have a corrupt DB as @ksooo has stated, or no EPG is created for the channel and hence it cannot be updated.

**Comment by micahg** [comment]
Clearing data through Kodi PVR settings (as documented -- sorry) seems to resolve the issue.  Closing.

**Comment by micahg** [comment]
@phunkyfish  tyvm for your help :)
