### ISSUE TITLE
Issue with new tag comparing <date> with start time

### ISSUE THREAD

**Issue by matthuisman** [kodi-pvr/pvr.iptvsimple#553]
![image](https://user-images.githubusercontent.com/6225961/132902339-580ddc73-430c-4b5d-830d-f362c1366784.png)

```
<programme start="20210910180000 +0000" stop="20210910190000 +0000">
<date>20210910</date>
```

when simple is comparing the start time with the <date - the start has been converted to local time.
https://github.com/kodi-pvr/pvr.iptvsimple/blob/Matrix/src/iptvsimple/data/EpgEntry.cpp#L230

So, in the above and my timezone, it's now 2021-09-11

However, date is timezone unaware. so often the match won't work.

Simple should be comparing the "raw" start yyyy-mm-dd with the date instead.
That way they are both treated in the same timezone

So, grab the yyyy-mm-dd from 20210910180000 +0000
and then compare that with the yyyy-mm-dd from date

**Comment by phunkyfish** [comment]
So each EPG entry should also store a raw date string for comparison purposes.

**Comment by matthuisman** [comment]
I think we can grab it again in the same function it's needed. So probably no need to store it?

However, can start times be in different formats?

If not, then it's as easy as checking if start string startswith the date string. As long as the date string is 8 characters. Don't want to put new if just th year matches. That would also stop 01/01 wrongly matching if date is only a year 2021 as currently it would match incorrectly on that

Eg.
if date.length() == 8 and start.string().startswith(date.string()):
  New = True

**Comment by phunkyfish** [comment]
It’s a struct format. I’ll send up a PR shortly if you can test.

**Comment by matthuisman** [comment]
fixed with pr: https://github.com/kodi-pvr/pvr.iptvsimple/pull/557
