### ISSUE TITLE
[Feature Request] Record TV (DVR feature) save video stream to local disk

### ISSUE THREAD

**Issue by Hedda** [kodi-pvr/pvr.iptvsimple#56]
I like to make a feature suggestion, and that is the add a recording functionality into this PVR client addon.

The ability to "record to disk" from a user experince. In function be able act a DVR (Digital Video Recorder), to save individual video streams to local disk directory/folder. Preferably even save as video files in MPEG-TS (.TS) format just like real DVRs. 

This ability to record can also add more features which have dependency on recording, like the ability to "Pause" and "rewind" Live TV if could add the possibility to continusly record to a series of temporary files in a look, again just like a read DVR.

All such a function is normally located and dependent in the PVR backend instead of the PVR client addon, but this PVR client addon is somewhat unique in that it connects to the content streams directly, streaming directly from, so it does not go through a third-party PVR backend which can bring such recording functionality. And in addition it would be very nice to have the ability for the video files to be saved locally directlly on an Android device instead of on the PVR backend.

**Comment by afedchin** [comment]
Sorry, but no backend - no recordings. PVR client shouldn't do recording. This is principal of PVR clients. You can use tvheadend or mediaportal (for Windows) backend to make this possible.

**Comment by Hedda** [comment]
@afedchin sorry to see you closing this without first researching the issue at hand

It is just not possible to say that this is a PVR backend issue on a PVR client that does not actually have a PVR backend, which the IPTV Simple Client addon for Kodi indeed does not. The IPTV Simple Client addon connect direct to the content, so you do not instead a matching third-party PVR backend software at home to use it. For all intended purposes from a end-user experience the client addon is stand-alone and works without a PVR backend installed in your home, which means that you can not initiate record from the IPTV Simple Client addon.

Again, the IPTV Simple Client addon (and a few other PVR client addons) are in a somewhat unique situation that it is stand-alone and does not have or need a matching PVR backend software installed at home, and instead it direct connect to the content streams on the internet.

As such  the IPTV Simple Client addon for Kodi does not fit within the classic client <=> backend concept that other PVR addons for Kodi relies on.

**Comment by MartijnKaijser** [comment]
/me start c/p the same reply everywhere else

**Comment by Jalle19** [comment]
@Hedda if this addon supported recording it woulnd't be "simple" anymore as the name implies. If you want recording functionality there is a multitude of backends to choose from.

**Comment by Hedda** [comment]
Here is a fork which features a simple recording feature which adds timeshifting functionality:

https://github.com/simphax/pvr.iptvsimple

@Jalle19 would you reject a pull request for such features to this addons?

Point is for this addons to have this capability nativly without the need to use a backend.

**Comment by Jalle19** [comment]
For this addon, maybe if the code is good. For all addons that don't support it right now, probably not.

**Comment by MartijnKaijser** [comment]
@Jalle19 doing something like this was already refused in core as well so i would very much object doing this. Certainly in this pvr addon

**Comment by Hedda** [comment]
I only mean for addons that do not make use of backends. Stalker and the native HDHomeRun addons are two others. These don't use backends so the recording functionality has to be implemented directly into the client side.

**Comment by Hedda** [comment]
@MartijnKaijser but the code is not for the core, it is for the (binary addon) PVR client only.

This implemenation means that the Kodi core is not touched.

**Comment by MartijnKaijser** [comment]
This addon is abused by the piracy infested community and i will certainly not allow it to add recording of piracy streams to it. 
@FernetMenta ping as you were involved to the PR for doing something similar in core for doing internet stream recoring

**Comment by RacerXx** [comment]
lol sounds like somebody dont like the being "out coded". You call it piracy I call it functionality. Thats like saying we shouldn't have airplanes because they might get hijacked or cars because they can crash. Sorry but im not walking!

**Comment by Jalle19** [comment]
Sounds like someone necromanced an old issue just to complain. Feel free to code up support for this.

**Comment by afedchin** [comment]
> lol sounds like somebody dont like the being "out coded". You call it piracy I call it functionality. Thats like saying we shouldn't have airplanes because they might get hijacked or cars because they can crash. Sorry but im not walking!

sounds like a princess cry which wants a sweetie
Any PVR client add-on shouldn't do a job which PVR server must do. IPTV simple client add-on has no PVR backend i.e. has no recordings and no timeshift. Any questions?

**Comment by RacerXx** [comment]
yeah i have a question. Why doesn't it have a backend? Whats the holdup? Oh thats right "piracy" right? Fix it!

**Comment by MartijnKaijser** [comment]
You code it you smart ass

**Comment by Jalle19** [comment]
If you want to record TV, use a backend and addon that supports it. This one doesn't. It's really as simple as that.
