### ISSUE TITLE
Version 19.0.0 is incompatible

### ISSUE THREAD

**Issue by Durlyn** [kodi-pvr/pvr.iptvsimple#568]
Hi!
after updating Kodi from git the addon stopped working. writes that the version is not compatible with Kodi
ADDON: pvr.iptvsimple version 19.0.0 is incompatible.

pvr.iptvsimple from latest git too

**Comment by phunkyfish** [comment]
The version of iptvsimple should start with 20 if you are running Kodi nexus. Did you check out the Nexus branch of iptvsimple?

**Comment by Durlyn** [comment]
from Master branch

**Comment by Durlyn** [comment]
Thanks. switched to the nexus branch, it all worked.

**Comment by phunkyfish** [comment]
Cool!
