### ISSUE TITLE
Nexus: Media Artwork

### ISSUE THREAD

**Issue by berkhornet** [kodi-pvr/pvr.iptvsimple#576]
Hi. I've successfully run some tests and have some VOD streams available under PVR Recordings. Thanks for adding this feature.
I have one question. Is there any way of adding artwork like Movie posters (say from the m3u file) to the recording data?

Thanks again.

**Comment by phunkyfish** [comment]
It’s possible, but would be a new feature. Where exactly is the artwork source?

**Comment by berkhornet** [comment]
Hi

With my provider, artwork for media is in the tvg-logo entry as in this example:

#EXTINF:-1 media="true" tvg-chno="4" tvg-id="1865" tvg-name="1865" tvg-logo="https://image.tmdb.org/t/p/w185/keGfSvCmYj7CvdRx36OdVrAEibE.jpg" group-title="Boxset: Pirates Of The Caribbean",Pirates of the Caribbean: On Stranger Tides

Regards

**Comment by phunkyfish** [comment]
That makes sense. But I think this is already implemented. It should take the tvglogo as the image path for the recording. If there is an icon for the EPG entry this will override it.

**Comment by berkhornet** [comment]
Yep, got it working. I had a setting enabled that ignored the m3u logos!
