### ISSUE TITLE
Further Suggestion - Nexus Recordings

### ISSUE THREAD

**Issue by berkhornet** [kodi-pvr/pvr.iptvsimple#577]
My provider can supply additional information related to their VOD. For Movies, the plot, genre, actors, IMDB rating and Release Year can be provided. Would it be possible to import this information via Simple Client?

As an alternative, I investigated scanning the recordings into the Kodi Library. The items scanned correctly but would not play. I think this is because the http: link in the m3u file is converted to a pvr link when the item is scanned. Getting this to work would be an alternative.

Many thanks.

**Comment by phunkyfish** [comment]
If they are available in the xmltv file they should work. If not please let me know.

You may not get all those fields. Only those supported by PVR Recordings can be supported.

https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/pvr/pvr_recordings.h

For instance imdb rating and actors would not be supported. However the others would be.

**Comment by berkhornet** [comment]
Unfortunately there are no entries for plot etc for VOD/media in the xmltv file. They are only available as an option in the m3u file.

Mick
________________________________

**Comment by phunkyfish** [comment]
They would have to be in the xmltv file I’m afraid. Reason being there is no de facto standard for that information in the M3U file.

**Comment by berkhornet** [comment]
Ok. Thank you.
