### ISSUE TITLE
Request: 2nd client or multi-source client

### ISSUE THREAD

**Issue by Rvhalewyn** [kodi-pvr/pvr.iptvsimple#580]
IPTV channels often come from different sources. Simple Client is 'simply' the best and most versatile. Such a pity one can only install one source, local or web.
If it's too complicated to add multiple sources, a slightly altered second version that could be used together with SC as a second client would be extremely useful. This was possible using Simple Archive as a second client before kodi 19.

**Comment by ksooo** [comment]
Please use the forum for feature requests. Github is for issues only.
