### ISSUE TITLE
Channel icons not refreshing - broken URL because of an empty group-title tag

### ISSUE THREAD

**Issue by Foksadure** [kodi-pvr/pvr.iptvsimple#586]
Hello there,

Since a few days, channel icons are not refreshing in IPTV Simple client.
I'm using a m3u playlist that happens to have groups, but that did not cause any trouble until now.

`2021-12-16 20:54:01.263 T:13995    INFO <general>: CAddonMgr::FindAddons: pvr.iptvsimple v19.0.2 installed`

Did a fresh install on another device, Android, Windows, no more luck.
I had a look at the favourites.xml file in the userdata folder, and it seems **the `thumb` tag is now missing a closing double quote to be separated from the `group-title` tag**.

`<favourite name="Channel name" thumb="https://picon-13398.kxcdn.com/channel_logo.jpg group-title=">PlayMedia...`

I had a look in the logs, it's 404 galore:

`2021-12-16 20:54:37.750 T:14026   ERROR <general>: CCurlFile::Open failed with code 404 for https://picon-13398.kxcdn.com/animalplanet.jpg group-title=: `
`2021-12-16 20:54:37.750 T:14026   ERROR <general>: CFileCache::Open - <https://picon-13398.kxcdn.com/animalplanet.jpg group-title=> failed to open`

The ressource is OK: https://picon-13398.kxcdn.com/animalplanet.jpg

Thank you for your help.

**Comment by phunkyfish** [comment]
Did you not already post this on forum?

Did you try adding the closing quote to the favourites file?

Note that this is nothing to do with the addon. If the favourites file is being generated incorrectly the problem is in kodi and will need to create an issue in the xbmc GitHub.

**Comment by Foksadure** [comment]
Thank you for your reply.
My bad, it's the m3u that has issues indeed.
I'm closing this.
Thanks again.
