### ISSUE TITLE
Video issues on a new TV. Worked fine on the old one and on other TVs in my house.

### ISSUE THREAD

**Issue by invisiblek** [kodi-pvr/pvr.iptvsimple#600]
Been running this on a Raspberry Pi4 for awhile, and it runs perfectly fine in 2 other rooms in the house, but for whatever reason when I start an iptv channel on this TV, the video is just slow but the audio is fine. Eventually tossing buffer/stream stalled errors.

log: https://gist.github.com/invisiblek/17d90084d4e2c7e54d1eccdfff67204a

Any ideas where to look here? Local media plays great, possibly even better than it did before. Maybe a better framerate this TV is somehow using is causing the stream to not be able to keep up?

**Comment by phunkyfish** [comment]
Please don’t embed logs in issues, use a paste site and provide a full debug log. Do the other rooms also have pi4’s?

have you tried the devices From the working rooms with the problematic TV. Likely it is not the device but the tv that is causing the problem. Some thing to do with HDMI or a bad network cable. Try switching to a physical cable instead of Wi-Fi if that is your current setup.

**Comment by invisiblek** [comment]
I'll get a better debug log tonight. All the other rooms have identical Pi4 setups. I can try some of your suggestions and report back. Thanks!

**Comment by invisiblek** [comment]
Devices from working room confirmed broken on this TV. It should be noted this is not the first TV I have tried with this. I had some issues with the Vizio (unrelated issue) that I had and ended up returning it for this Samsung. Both had this issue.

Tried an HDMI cable from another room, that made no difference.

No Wi-Fi here, just a pi4 using the PoE hat (all of my rooms use this exact hardware setup including the device I tried here from the bedroom which also exhibited the issue). Additionally, this worked fine on my old (shitty) plasma TV that I had here, so I'd be leery of pointing at the PoE causing a problem here.

Log with debugging enabled: https://gist.github.com/invisiblek/d512e5805eb64706aaf4f28eb2acba3a

**Comment by invisiblek** [comment]
K, so I forced 1080p @ 60hz in kodi's settings and this is working perfectly now. Interesting...

I would prefer to have 4k for some of my local media on this 4k tv

**Comment by invisiblek** [comment]
Closing. I don't believe this to be an issue with this plugin. I apologize for the static.

My discoveries so far (for future reference to someone maybe)...
On the bedroom TV (Sharp LC-50Q7030U) Kodi gives an option for 3840x2160@60hz. That is what is selected and everything I use works perfectly.
The new TV in the Living Room (Samsung QN70Q60AAVXZA) does not give an option for 3840x2160@60hz. Only an option of 30hz at that resolution. If I drop it to 1920x1080, it gives and option for 60hz and everything works as expected (iptv is fine, local media is wonderful).
The TV downstairs (Sharp LC-60Q7370U) acts exactly the same as the Samsung QN70Q60AAVXZA in the Living Room. We really never use IPTV on this TV, so I never checked. Local media was always fine so a problem was never noticed.

I suspect if I manage to get these working in 4k@60hz on these other two TVs, this problem will go away. I suppose I'll come back here and EDIT this comment, for posterity, if I manage to solve this.

Again - sorry for the static and thank you for this awesome plugin.

**Comment by phunkyfish** [comment]
No problem. Glad to hear you’re edging closer to some answe.
