### ISSUE TITLE
EPG offset

### ISSUE THREAD

**Issue by nnm-github** [kodi-pvr/pvr.iptvsimple#601]
Cannot set EPG offset to -1 hour, only -0.9 or -1.1 hour

**Comment by phunkyfish** [comment]
Easiest way to fix this is to modify the settings file in the addon manually back to an allowed value. Really this should only increment in 0.5 hours increments. What version of kodi/addon are you using?

The file is here: `userdata/addon_data/pvr.iptvsimple/settings.xml`

**Comment by nnm-github** [comment]
INFO <general>: Starting Kodi (19.3 (19.3.0) Git:20211024-49a04cd6a7). Platform: Windows NT x86 64-bit
INFO <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: pvr.iptvsimple v19.1.0 installed

**Comment by phunkyfish** [comment]
Or an alternative is to set the addon settings back to default and then then reconfigure your settings.

**Comment by EvilCaptKirk** [comment]
How long does the EPG offset setting take to reflect in the program guide? I set an offset value, ticked "apply to all channels", saved, then disabled/reenabled IPTV simple client - no change. I also tried restarting Kodi - no change. What makes the offset go into effect immediately?

**Comment by phunkyfish** [comment]
Probably not until there are new EPG updates. You can clear all PVR data from the PVR settings in Kodi.

**Comment by EvilCaptKirk** [comment]
Thanks, that makes sense. It updated itself before I had a chance to try that. :)
