### ISSUE TITLE
PVR IPTV simple client dont work

### ISSUE THREAD

**Issue by Vipskywalker27** [kodi-pvr/pvr.iptvsimple#602]
Hi , and thanks for all this fantastic work , I have a question my PVR IPTV simple client work great but yesterday dont load nothing , my playlist is only 50 chanels and unistall and reinstall the pvr and i cant fix it ,  could help me with that ? thanks !

https://paste.kodi.tv/egulomixep.kodi

![imagen](https://user-images.githubusercontent.com/99347827/153263839-db3fdad4-465b-4943-aa60-db75b6ada685.png)
![imagen](https://user-images.githubusercontent.com/99347827/153264006-84b65b0f-67c0-40bf-81a4-6a4bcc3f8daa.png)

**Comment by phunkyfish** [comment]
That’s a regular log and not a debug log. Also please remove all the banned add-ons (the things in orange in your log) before adding the debug log if it’s still not working.

**Comment by phunkyfish** [comment]
It’s not working because iptv-org.github.com is subject to a DMCA takedown notice. 

Also note that GitHub is for bugs. For user issues please use the kodi forum.

**Comment by Vipskywalker27** [comment]
https://paste.kodi.tv/jarasusiji.kodi

sorry is my first time in kodi , maybe you could told me where are the good playlist working?

**Comment by phunkyfish** [comment]
Sorry, no. Find a decent provider and pay them for a service legally is my advice.

**Comment by Vipskywalker27** [comment]
oh , good to know , and what provider is good ?

**Comment by phunkyfish** [comment]
I’m afraid I don’t know. I just maintain the add-on for users. I don’t use it myself.

**Comment by Vipskywalker27** [comment]
ok thanks for the time and your answers.
