### ISSUE TITLE
Not compatible with KODI 19.3?

### ISSUE THREAD

**Issue by vawaver** [kodi-pvr/pvr.iptvsimple#603]
I am on Manjaro with KODI 19.3.
I used your building instruction and create the addon.
When I tried to activate the addon there was an error message. 
This addon is not compatible with this version of KODI.
What to do?

**Comment by phunkyfish** [comment]
Which branch of the addon did you build? If you are on Matrix you need to checkout the Matrix branch.

**Comment by vawaver** [comment]
Can you please instruct me where can I find it? 
Thank you.

**Comment by phunkyfish** [comment]
You just checkout the repo from git and then switch the branch to `Matrix`.

**Comment by vawaver** [comment]
Thank you for your answer.
But I am a new user of GITHUB and I am learning how to use it. Can you please be more specific about what exactly should I do?
Thank you for your goodwill.

**Comment by phunkyfish** [comment]
Sure once you clone the repo enter the directory and then run a checkout command like this:

- `git clone https://github.com/kodi-pvr/pvr.iptvsimple`
- `cd pvr.iptvsimple`
- `git checkout Matrix`

Then build as normal.

**Comment by vawaver** [comment]
aaaa.... thank you very much for all.
Now it is clear.
