### ISSUE TITLE
iptvsimple error

### ISSUE THREAD

**Issue by sasha197541** [kodi-pvr/pvr.iptvsimple#604]
can anyone tell me why i get this error

root@raspberrypi:/home/lorn1975/kodi/src/pvr.iptvsimple# make
[  4%] Building CXX object CMakeFiles/pvr.iptvsimple.dir/src/PVRIptvData.cpp.o
In file included from /home/lorn1975/kodi/src/pvr.iptvsimple/src/iptvsimple/Providers.h:11,
                 from /home/lorn1975/kodi/src/pvr.iptvsimple/src/PVRIptvData.h:13,
                 from /home/lorn1975/kodi/src/pvr.iptvsimple/src/PVRIptvData.cpp:8:
/home/lorn1975/kodi/src/pvr.iptvsimple/src/iptvsimple/data/Provider.h:14:10: fatal error: kodi/addon-instance/pvr/Providers.h: No such file or directory
   14 | #include <kodi/addon-instance/pvr/Providers.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pvr.iptvsimple.dir/build.make:82: CMakeFiles/pvr.iptvsimple.dir/src/PVRIptvData.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/pvr.iptvsimple.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

**Comment by phunkyfish** [comment]
What repos/branches are you trying to build?

You have given very little information m, not even your OS.

**Comment by sasha197541** [comment]
lorn1975@raspberrypi:~/kodi/src $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by sasha197541** [comment]
Build Matrix 19.4 on raspberry pi 4

**Comment by phunkyfish** [comment]
You are trying to build the Nexus version of the addon on Kodi Matrix.

**Comment by sasha197541** [comment]
Hi thanks for response can You point me to the right repository address for the correct version of add on for my system?

**Comment by phunkyfish** [comment]
Just check out the Matrix branch of pvr.iptvsimple

**Comment by sasha197541** [comment]
K will do

**Comment by sasha197541** [comment]
The only one I find is for Nexus

**Comment by sasha197541** [comment]
https://github.com/kodi-pvr/pvr.iptvsimple

**Comment by phunkyfish** [comment]
That is the default branch. Check it out using git and specify the branch.

`git checkout -b Matrix https://github.com/kodi-pvr/pvr.iptvsimple`

**Comment by sasha197541** [comment]
Thx that worked.
