### ISSUE TITLE
EPG Empty

### ISSUE THREAD

**Issue by TrillaG** [kodi-pvr/pvr.iptvsimple#605]
https://paste.kodi.tv/ofinecijik.kodi

EPG shows up empty. IPTV still plays streams, but there is no program information. Started happening tonight. Another user had reported the issue to reddit. Was working fine last night.

**Comment by phunkyfish** [comment]
If you would like support please remove all banned add-ons first and the supply a fresh log.

**Comment by TrillaG** [comment]
No thanks lol thanks for literally nothing though.

**Comment by phunkyfish** [comment]
As your log was not a debug log there was literally nothing I could tell you anyway.
