### ISSUE TITLE
Channel logos from tvg-logo tag not visible

### ISSUE THREAD

**Issue by osscombat** [kodi-pvr/pvr.iptvsimple#622]
Hi!
If the channel logos are all written in the remote M3U playlist, and all of those png are on remote server, (i.e. HTTPS link to the png logo), then they are not always loaded in the channel list. Only part of the logos are visible and cached, and Kodi doesn't attempt to re-fetch the other missing logos on restart.
 Tried any other IPTV clients with the same M3U playlist, and everything is fine, so this is not a logo files access issue.

**Comment by phunkyfish** [comment]
What version of kodi/add-on are you using?

**Comment by osscombat** [comment]
Kodi 19.3 or 19.4, plugin v19.1.1, Android ARM and PC x86 builds.

**Comment by phunkyfish** [comment]
Can you try a kodi nexus nightly build and report whether the behaviour is better there or not.

**Comment by osscombat** [comment]
where can I get this build?

**Comment by phunkyfish** [comment]
https://kodi.tv/article/kodi-nexus-alpha-2/

**Comment by osscombat** [comment]
the nexus alpha loads much more logos, but still not 100% of them, I have only 30 channels in the playlist. Even after I deleted the thumbnails cache. The IPTV Pro app for android, for instance, shows 100% of those logos every startup.

**Comment by phunkyfish** [comment]
What skin are you using?

Did you try disabling http2?

https://github.com/kodi-pvr/pvr.iptvsimple/issues/294

**Comment by osscombat** [comment]
I've found the problem - it's a space in the filename of the logo file, strange this is not the problem for other iptv clients.

**Comment by phunkyfish** [comment]
Can you give a concrete example?

**Comment by osscombat** [comment]
Yes, the download fails if your tag is 

`tvg-logo="https://user:pass@hostname/picons/Channel One.png"` or contain non-latin symbols.

**Comment by phunkyfish** [comment]
Yes, because that is not an encoded URL. It might be possible to make that a bit more resilient.

**Comment by phunkyfish** [comment]
Can you supply more examples here? The issue is that the URL provided is invalid in the first place, I would rather not encode every URL but instead just encode the parts that are invalid. For instance, in your example is it always in the channel name part where the problem occurs?

I.e. The `Channel One.png`, but the rest of the URL is OK?

**Comment by phunkyfish** [comment]
@osscombat can you test this PR: https://github.com/kodi-pvr/pvr.iptvsimple/pull/626?

**Comment by osscombat** [comment]
> Can you supply more examples here? The issue is that the URL provided is invalid in the first place, I would rather not encode every URL but instead just encode the parts that are invalid. For instance, in your example is it always in the channel name part where the problem occurs?
> 
> I.e. The `Channel One.png`, but the rest of the URL is OK?

actually I've simply renamed all the png logo files with space in the name to be accessible. The channel name with space itself is not affected, it just misses the logo.

**Comment by osscombat** [comment]
> @osscombat can you test this PR: #626?

sure, I can test it, how to enable the beta channel for this addon?

**Comment by phunkyfish** [comment]
There is no beta channel. You just download the correct package from the testbuilds linked in the PR and install from Zip.

**Comment by phunkyfish** [comment]
> > Can you supply more examples here? The issue is that the URL provided is invalid in the first place, I would rather not encode every URL but instead just encode the parts that are invalid. For instance, in your example is it always in the channel name part where the problem occurs?
> > I.e. The `Channel One.png`, but the rest of the URL is OK?
> 
> actually I've simply renamed all the png logo files with space in the name to be accessible. The channel name with space itself is not affected, it just misses the logo.

It’s only with the logo path that the last part gets encoded. So only assessing the problem that you had.

**Comment by osscombat** [comment]
> @osscombat can you test this PR: #626 

tested it, the issue is resolved in 19.2.0, thanks!

**Comment by phunkyfish** [comment]
Excellent, thanks!
