### ISSUE TITLE
Kodi crashes on EPG fast-scrolling

### ISSUE THREAD

**Issue by krzysztofwinnik** [kodi-pvr/pvr.iptvsimple#623]
**Current Behavior**

This bug happens for a longer time. If I open EPG view and long press up or down to scroll through / iterate the list sooner or later kodi will crash (it takes 5 to 30 seconds usually).
The log says
_ERROR <general>: GetItem: EPG tag (XXX,YYY) not found!
_ERROR <general>: GetGridItemPtr: Got no EPG tag (XXX, YYY)__
where XXX and YYY are different numbers each time this bug occures.

**Expected Behavior**

fast-scrolling in EPG shouldn't crash Kodi

**Steps To Reproduce**

go to EPG
long-press up and down and hold it
see epg list scrolling
wait for a crash - it should happen sooner or later

**Comment by phunkyfish** [comment]
Is the bug on Kodi Matrix or Nexus?

**Comment by krzysztofwinnik** [comment]
> Is the bug on Kodi Matrix or Nexus?

Matrix - Tested on both Coreelec 19.5rc2 and MacOs stable matrix kodi version

**Comment by phunkyfish** [comment]
Can you try kodi Nexus on Mac and report back? There were a lot of EPG fixes made there.

**Comment by krzysztofwinnik** [comment]
@phunkyfish I've done some more tests on Matrix and Nexus and it turnes out it must be a skin or skin engine specific bug. 
On Estuary fast-scrolling works just fine. However on Arctic Horizon 2 (and Arctic Horizon 1 as well) kodi crashes when iterating epg entries... I will reach out the skin dev for help.
Any hint from you what could be causing this bug?

**Comment by phunkyfish** [comment]
No idea I’m afraid. We only test on Estuary. Plus, I’m not really a skin/Python guy so wouldn’t really know where to start 😉

**Comment by krzysztofwinnik** [comment]
Many thanks anyway. You guys are doing amazing job - thank you for that too!
