### ISSUE TITLE
Feature Request: Channel start timeout

### ISSUE THREAD

**Issue by osscombat** [kodi-pvr/pvr.iptvsimple#625]
Hi!
Probably there is such an option already but I can't find in the docs, is it possible to increase the timeout for starting the channel? This is useful if you have your own streams transcoded with ffmpeg, but they need more than 40 seconds to start.

**Comment by phunkyfish** [comment]
This has nothing to do with the add-on. I believe this feature would need to be made for kodi and/or any inputstream addons in use.

**Comment by osscombat** [comment]
got it, thanks
