### ISSUE TITLE
Latest update breaks some images

### ISSUE THREAD

**Issue by matthuisman** [kodi-pvr/pvr.iptvsimple#629]
`#EXTINF:-1 channel-id="500" group-title="Kayo Sports" tvg-chno="500" tvg-id="53217" tvg-logo="https://vmndims.kayosports.com.au/api/v2/img/5bcefccee4b0a8faf3c14aef-1658195201775?location=carousel-item&imwidth=415",Fox Sports News`

https://vmndims.kayosports.com.au/api/v2/img/5bcefccee4b0a8faf3c14aef-1658195201775?location=carousel-item&imwidth=415
is now showing as this image:
https://vmndims.kayosports.com.au/api/v2/img/5bcefccee4b0a8faf3c14aef-1658195201775

Seems the query is getting lost

**Comment by phunkyfish** [comment]
Can you try this patch: https://patch-diff.githubusercontent.com/raw/kodi-pvr/pvr.iptvsimple/pull/630.patch

**Comment by matthuisman** [comment]
@phunkyfish recently switched PCs and dont have my build env setup yet.
I can def try a windows build though to confirm fix.

I see you have a PR here: https://github.com/kodi-pvr/pvr.iptvsimple/pull/630
but the windows builds failed :(

**Comment by phunkyfish** [comment]
Whoops, fixed now.

**Comment by matthuisman** [comment]
@phunkyfish - have tested build with the above PR and it fixes the issue :)

**Comment by phunkyfish** [comment]
Matrix PR: https://github.com/kodi-pvr/pvr.iptvsimple/pull/631

Excellent. Matrix and Nexus both released. Thanks for testing.

**Comment by matthuisman** [comment]
Thanks for quick fix :)
