### ISSUE TITLE
Favorite list

### ISSUE THREAD

**Issue by djmaj0** [kodi-pvr/pvr.iptvsimple#63]
Hi is there possible to implement function which will be able to use any external playlist with TV channels and to create customized favorite list of channels which have changed token? At the moment we can create our own group of channels but after restart of kodi this group disappears. Thats why my suggestion is to use just keywords from the link to remember the items in the list and just update this list with new links which have changed its tokens.

**Comment by Jalle19** [comment]
With the new default skin in Kodi Krypton you will see your recently viewed channels on your home screen. Perhaps that's good enough?

**Comment by phunkyfish** [comment]
Closing as issue is related to older version of kodi.
