### ISSUE TITLE
[Arch Linux] Kodi 19.4: Addon crashes, freezes and exits.

### ISSUE THREAD

**Issue by Davetheraveuk** [kodi-pvr/pvr.iptvsimple#634]
Below has been copied/pasted from: (https://aur.archlinux.org/packages/kodi-addon-pvr-iptvsimple)
OS: Arch Linux
*******************
Kodi Version: 19.4

I would like to confirm what @d4rkgh0m and @DaveOne have stated. After "kodi-addon-pvr-iptvsimple 19.2.2-1" is compiled and installed kodi freezes; crashes and exits.
*******************
Thanks, David.

**Comment by phunkyfish** [comment]
Do you have a debug log and crash log?

**Comment by phunkyfish** [comment]
Does a version before this one work ok? What is the last working version?

**Comment by Davetheraveuk** [comment]
@phunkyfish 

> Do you have a debug log and crash log?
Yes, I have attached it at the bottom of this message.

> Does a version before this one work ok? What is the last working version?
I do not know. I am fairly new to Kodi. Sorry.

I do hope you can resolve this issue, not just for me but for others as well. 
Thanks, David.

[kodi_crashlog-20220827_154019.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/9438159/kodi_crashlog-20220827_154019.log)

**Comment by ilikenwf** [comment]
I'm thinking this may be related to #507 - many Arch users have -Wp,-D_GLIBCXX_ASSERTIONS enabled globally in makepkg.conf.

I modified the PKGBUILD locally to fix this and will be notifying the maintainer about it. A temp fix is to remove this from the CFLAGS, CPPFLAGS, and CXXFLAGS in /etc/makepkg.conf

**Comment by ilikenwf** [comment]
Looking into it if it has anything to do with strings again, this is how the STR() macro is defined...


#include <string.h>

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

**Comment by pandvan** [comment]
This issue was solved "upstream" adding needed compilation flags in the PKGBUILD
Link: https://aur.archlinux.org/cgit/aur.git/commit/?h=kodi-addon-pvr-iptvsimple&id=221688349f8f784b6bb78ccad1689958e3eedd96

**Comment by razzeee** [comment]
Building like that also helped to fix this crash in the flatpak.
