### ISSUE TITLE
Automatically update channels list .m3u & EPG .gz files

### ISSUE THREAD

**Issue by mYnDstrEAm** [kodi-pvr/pvr.iptvsimple#640]
If issues were detected with the TV streams or the EPG, IPTVSimple should check for an update to the configured files. Instead of pointing to local files one could point to an URL (which could redirect to wherever is the latest file).

Additionally, it could run regular checks and update the files if changes to the current file were detected in the latest file (and the latest file is not empty or very small and meets some conditions - it could even run tests if the streams actually work).

To prevent an update with malicious or dysfunctional files, the url pointers could be maintained by some third party or require some verifications/confirmations in some way (how could be discussed here). This could work similar to software repositories (like addons in the Kodi repositories or software in Debian repositories).

This way you'd only have to configure the TV streaming once which would make it far more convenient and easy to setup. Moreover, if you haven't used the streaming for a long time, it's not broken (such as very slow starts of streams and missing EPGs) in the rare time that it's used and once you already forgot how exactly it was set up (such as which m3u file was used in specific or [where to find the IPTV Simple options](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1019190)).

Edit: I think issues with adding URLs include that updating once a day is too often and the URLs can change. Also I don't know if the EPG is refreshed right away when adding an URL. Instead of having to paste an url it would be better if one could just select from https://github.com/iptv-org/epg or at least if there was a link to it in the options. Is there a repo for channels m3u files?

---

[Here](https://www.kodi-tipps.de/kodi-iptv-einrichten-live-tv-mit-kodi-anschauen/) is a German-language tutorial for adding files. One issue I have with some of the latest files is that EPG info is missing for some channels, why is that and what can be done about it – is there already an issue about this somewhere? (It probably varies per EPG source.) If adding multiple EPGs can solve this why isn't this possible in the options of IPTVSimple v 19.1.0 (in Debian backports)?

**Comment by phunkyfish** [comment]
Sorry is this a feature request?

The addon already supports automatically updating from the files on a repeated basis. Updating when a stream does not play is not feasible, the add-on never knows when a stream stops. That is handled by the video player via an inputstream.

**Comment by mYnDstrEAm** [comment]
Yes it is, but I wrote it before I got a newer version from Debian backports - I think in the version I had the option was missing. Please see the things I wrote after Edit:

In specific, could it update less frequently than once a day and does it do a refresh when you entered an url or does it wait until the configured hour to update? Could you enable users to select from a dropdown of options where "paste url" is one option and the other options eg items of https://github.com/iptv-org/epg or at least include a link to such a page where you can find an up-to-date file/url? The EPG info is missing for some channels: why is that and what can be done about it – is there already an issue about this somewhere? Sorry it's not a very specified feature request, that's because I don't know much of the internals, it could still be moved to a separate issue later.

Could you please quickly take a look at [this issue](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1019190) and comment if that problem always occurs for the addon instead of being specific to version 19.1.0 or Debian?

**Comment by phunkyfish** [comment]
As I stated in my response it is not possible to take an action in an addon if a stream does not play or stops playing.

So what you are requesting is not possible.

**Comment by mYnDstrEAm** [comment]
Already acknowledged. That is not relevant to all the other things I asked about and which I repeated in my comment above such as the missing EPG info.

**Comment by basilgello** [comment]
@mYnDstrEAm If I understand this issue correctly, you have issues with incorrect EPG and unplayable streams you got from some playlist. Is that correct?

**Comment by mYnDstrEAm** [comment]
No. Please forget the unplayable streams thing* - I listed the remaining issues [here](https://github.com/kodi-pvr/pvr.iptvsimple/issues/640#issuecomment-1237080949).

*actually the problem I had was that streams did play but it took very long for them to start so I first had to figure out that I need to update the m3u file (and the EPG info was missing entirely and now is still partially missing: for some channels only)

**Comment by phunkyfish** [comment]
Ok, so for the channels that are missing EPG information, do they have valid entries in the EPG xml file?

If so, can you show an example of a  channel entry from the M3U (please obfuscate the URLs) and their corresponding EPG entries from the XML file?

**Comment by mYnDstrEAm** [comment]
If I knew if the EPG info updated immediately after pressing okay it would be easier to debug.

One of the over 3 EPGs I tried it with is https://iptv-org.github.io/epg/guides/de/horizon.tv.epg.xml.gz I don't think posting the m3u file I use makes any sense:

The display name for the affected channels seem to be the same in at least some cases but the tvg-id differs. This is the case for about half of the channels and I'm using a well-known m3u file so I don't think this is an uncommon, unknown problem.

There are probably multiple ways this could be solved such as a repo with standardized names (basically like localization for m3u and epg channel names) or internal code that checks for channel synonyms or by merging EPGs via allowing the user to enter multiple EPGs in the options (asked about the latter).

I now tried it by downloading the files and adding them as files. Another thing that would be very useful, which I also asked about, is giving the user a feedback that the channels list and EPG have successfully refreshed, especially when you have only entered an URL with daily update enabled. It would also be useful if somebody clarified whether the latest version of the addon is supposed to show under addons (I'd think so) as otherwise it being hidden there is an issue with the specific versions in Debian's repos/Debian. Lastly, I think the setup, including finding the most appropriate m3u and epg files, should be made more easily for the user beyond solving the issues above.

**Comment by phunkyfish** [comment]
So only a single channels M3U and EPG xml file is supported. So you can’t just add them channel by channel and hope to retain the EPG information.

Multiple EPG files will never be supported directly in the addon. But addons like IPTVMerge can be used to get this functionality.

Sorry, I don’t know how addons display on Debian. But I’d imagine they are under PVR clients in the Ui.

**Comment by mYnDstrEAm** [comment]
I know. I don't know why you think that I thought that and why you didn't address any of the things I wrote. Moreover, this is mostly a feature request.

**Comment by phunkyfish** [comment]
If this is feature request please state succinctly what the feature is that you require. I’m happy to let you know what is possible and what is not.

**Comment by mYnDstrEAm** [comment]
Because I don't know all things about the software's internals I have a few questions before and within the feature request/s. Other than that I already succinctly stated all of this...and sorry I don't want to seem offensive but thankful for this great open source software. Feature request here:

> The display name for the affected channels seem to be the same in at least some cases but the tvg-id differs. This is the case for about half of the channels and I'm using a well-known m3u file so I don't think this is an uncommon, unknown problem.
> 
> There are probably multiple ways this could be solved such as a repo with standardized names (basically like localization for m3u and epg channel names) or internal code that checks for channel synonyms or by merging EPGs via allowing the user to enter multiple EPGs in the options (asked about the latter).

Questions (already repeated these so I didn't phrase them as question again like I did in the original post of this issue where there's more details; depending on the answer - which hasn't been given so far - these are most likely additional feature requests that are related to a working version of auto-updating):

>Another thing that would be very useful, which I also asked about, is giving the user a feedback that the channels list and EPG have successfully refreshed, especially when you have only entered an URL with daily update enabled. It would also be useful if somebody clarified whether the latest version of the addon is supposed to show under addons (I'd think so) as otherwise it being hidden there is an issue with the specific versions in Debian's repos/Debian. Lastly, I think the setup, including finding the most appropriate m3u and epg files, should be made more easily for the user beyond solving the issues above.

**Comment by phunkyfish** [comment]
> Because I don't know all things about the software's internals I have a few questions before and within the feature request/s. Other than that I already succinctly stated all of this...and sorry I don't want to seem offensive but thankful for this great open source software. Feature request here:
> 
> > The display name for the affected channels seem to be the same in at least some cases but the tvg-id differs. This is the case for about half of the channels and I'm using a well-known m3u file so I don't think this is an uncommon, unknown problem.

The addon only uses information in the M3U and XML file for matching. It will try to match on tvg-id  first and then try to find a matching display name. It will try to match against any display name for the given channel in the XML file. But the display name would need to match the channel name from the M3U file.

> > There are probably multiple ways this could be solved such as a repo with standardized names (basically like localization for m3u and epg channel names) or internal code that checks for channel synonyms or by merging EPGs via allowing the user to enter multiple EPGs in the options (asked about the latter).
> 

Trying to use a remote lookup for channel names is not feature I think is worth the effort. Once things veer from valid specifications it becomes a snowflake and almost impossible to maintain. This should be manageable within the confines of the M3U and XMLTV formats.

Channel synonyms are already supported via the `display-name` Element in the XMLTV specification (see above)

> Questions (already repeated these so I didn't phrase them as question again like I did in the original post of this issue where there's more details; depending on the answer - which hasn't been given so far - these are most likely additional feature requests that are related to a working version of auto-updating):
> 
> > Another thing that would be very useful, which I also asked about, is giving the user a feedback that the channels list and EPG have successfully refreshed, especially when you have only entered an URL with daily update enabled. It would also be useful if somebody clarified whether the latest version of the addon is supposed to show under addons (I'd think so) as otherwise it being hidden there is an issue with the specific versions in Debian's repos/Debian. Lastly, I think the setup, including finding the most appropriate m3u and epg files, should be made more easily for the user beyond solving the issues above.

This one should be a request for kodi, although I’m pretty sure this is the case already. The addon itself does not managed these notifications. But it will add a log entry.

Regarding where the addon appear @basilgello should be able to help on the correct behaviour for Debian.

**Comment by basilgello** [comment]
Debian package for iptvsimple is near vanilla. So everything should look and feel just like in any other Linux distro.

**Comment by mYnDstrEAm** [comment]
Thanks for clarifying you two, I'll now create more succinct new issues.

While there imo are issues with the auto-updating, it does at least work with the latest version which currently is in the Debian backports repo. After the Debian upgrade it'll be the default, until then people running Debian simply have to know that they should install from backports rather than from the main repo. The two most important issues left here are the following (and maybe I'll create separate issues for the other things at a later point):

The issue for EPG info missing for half of the channels: #642

The issue for the addon not showing in the Addons tab: #641
