### ISSUE TITLE
Addon v20.6.0 for Nexus is not compiled for Win32 and Win64

### ISSUE THREAD

**Issue by rainman74** [kodi-pvr/pvr.iptvsimple#650]
The binary plugins for Android and OSX are compiled, but unfortunately not for Win32 and Win64.

**Comment by haso2007** [comment]
Hello where can I  find the correct add_on for the android system. All I need to comply with  the release source code?

**Comment by wsnipex** [comment]
we had intermitten jenkins issues with our windows builders, it's on mirrors now, so you should be able to update from with kodi

**Comment by rainman74** [comment]
> we had intermitten jenkins issues with our windows builders, it's on mirrors now, so you should be able to update from with kodi

Thanks for the update, but unfortunately the v20.6.0 for Windows can not be installed yet, because the dependency inputstream.ffmpegdirect can not be found!

Could you please check there also what is the problem here? Thanks!

**Comment by fuzzard** [comment]
inputstream.ffmpegdirect 20.5.0 has been rerun and is now available on mirrors for the 2 windows platforms that initially failed.

**Comment by rainman74** [comment]
> inputstream.ffmpegdirect 20.5.0 has been rerun and is now available on mirrors for the 2 windows platforms that initially failed.

Thank you, it is working now!
