### ISSUE TITLE
pvr.iptvsimple.so: undefined symbol: IsTimeshifting

### ISSUE THREAD

**Issue by lsnk** [kodi-pvr/pvr.iptvsimple#66]
Hello, I've getting this error while starting kodi on arch linux. Is this some kind of source code problem or are there some missing build options?

```
15:31:15 T:140338486023936  NOTICE: PVRManager - starting up
15:31:15 T:140338364643072   ERROR: Unable to load /usr/lib/kodi/addons/pvr.iptvsimple/pvr.iptvsimple.so, reason: /usr/lib/kodi/addons/pvr.iptvsimple/pvr.iptvsimple.so: undefined symbol: IsTimeshifting
15:31:15 T:140338364643072 WARNING: UpdateAndInitialiseClients - failed to create add-on PVR IPTV Simple Client, status = 6
15:31:15 T:140338364643072 WARNING: UpdateAndInitialiseClients - failed to load the dll for add-on PVR IPTV Simple Client, disabling it
```

the AUR source:
https://aur.archlinux.org/packages/kodi-addon-pvr-iptvsimple-git

**Comment by sbentin** [comment]
I Have similar problem...

Unable to resolve: /pvr.iptvsimple.so.2.4.3 ADDON_Announce, reason: /usr/share/kodi/addons/pvr.iptvsimple/pvr.iptvsimple.so.2.4.3: undefined symbol: ADDON_Announce

same question

**Comment by Jalle19** [comment]
You're using an incompatible version of the addon.
