### ISSUE TITLE
Backend Connection

### ISSUE THREAD

**Issue by mgoproud** [kodi-pvr/pvr.iptvsimple#667]
Hello all,
I apologize if i'm in the wrong place to ask but i am am please need guidance from anyone could help me.
I'm trying to setup IPTV simple client on Kodi without a tv tuner, where can i find documentation or guidance to do it.

Thank you all in advance
Mgo

**Comment by lrusak** [comment]
Please use the forum for support. https://forum.kodi.tv/

**Comment by mgoproud** [comment]
Thank you for your response
I already tried that but couldn't find any help my only question here is
that can i use kodi to watch iptv channels package as in smart tv or
android devices but without a tv tuner just as in a smart player app.

**Comment by phunkyfish** [comment]
That might be the case but this is the GitHub for the addon and is for bugs only. There is no user support here.

**Comment by mgoproud** [comment]
I got what ur saying.
Thanks
