### ISSUE TITLE
Stream freezes after a few minutes

### ISSUE THREAD

**Issue by Andrei-Iosifescu123** [kodi-pvr/pvr.iptvsimple#668]
Whenever I play any channel, it works for 1-2 minutes then stops with error `Cvideoplayeraudio::process - stream stalled`. For it to work in ffmpeg, I need to add the `-http_persistent 0` parameter, otherwise it will freeze. Is there any way to set custom ffmpeg parameters?

**Comment by phunkyfish** [comment]
Can you provide the full ffmpeg command you use to successfully play the video?

I can then look at what is possible via the API

**Comment by Andrei-Iosifescu123** [comment]
ffmpeg -headers "Referer: https://canale.live" -http_persistent 0 -i
https://webdi.openhd.lol/cdn/23/tracks-v1a1/mono.m3u8

lun., 5 dec. 2022, 14:08 phunkyfish ***@***.***> a scris:

**Comment by phunkyfish** [comment]
Have you tried passing the parameter after the URL by appending `|http_persistent=0`?

**Comment by Andrei-Iosifescu123** [comment]
I'll try it tomorrow.

lun., 5 dec. 2022, 23:11 phunkyfish ***@***.***> a scris:

**Comment by Andrei-Iosifescu123** [comment]
Thank you, this solved my issue.
