### ISSUE TITLE
Change default action to "play program"

### ISSUE THREAD

**Issue by hagaygo** [kodi-pvr/pvr.iptvsimple#669]
Hi

Just managed to setup catchup on my iptv provider using this addon , Great Work!

Maybe i am missing something , but at least for my use case i would prefer that "play program" would be the default action for watching tv.
At least on my setup , i can not seek back for live tv stream only when using catchup=vod.
So if clicking on tv channel would use "play program" behavior (for current epg show) instead of "switch" it would be much better.

Any way to change that ? even switching between "Switch" and "play program" buttons order would be better.

Thanks in advance for any help.

**Comment by phunkyfish** [comment]
That’s correct. Catchup being set to VOD means you can’t seek back to a previous programme or forward forward to the next one.

At least that’s what I think you mean by your description above.

**Comment by hagaygo** [comment]
Thanks for you answer.

I understand the limits of vod catchup.

My question was regarding the UI of the addon.

Is there an option to make "play program" the default action ?

**Comment by phunkyfish** [comment]
Ah, I see. That’s not the addon though, that’s Kodi. I’d probably ask on the forum. I’m sure someone else has wanted to do this previously.

**Comment by hagaygo** [comment]
Hi , I have found an option in KODI called "smart select" under PVR -> guide settings.

![image](https://user-images.githubusercontent.com/5015856/206889699-3797547b-9b03-4c75-89d1-eeee162929df.png)

It does kinda what i have asked for , if anyone needs also this behavior.
