### ISSUE TITLE
parsing multiple items in x-tvg-url

### ISSUE THREAD

**Issue by dbojan** [kodi-pvr/pvr.iptvsimple#674]
PVR iptv simple plugin currently does not support multiple urls, in x-tvg-url, separated by coma, like those in iptv-org.

If  multiple urls are specified in x-tvg-url, right now, downloading of the epg data fails.
I suggest if it fails, to try parsing urls, separted by comma, and to load epg from the first url only.

Reason for this, is to be able to use same m3u list kodi and for other players too.
Most notable lists from iptv-org
Those who support it would use all epg urls, those who do not would use at least the first item.

Currently, I know only one iptv player that supports multiple epg entries, entered separately, and that is ProgTV, but that may change.

Thanks.

**Comment by phunkyfish** [comment]
Can you try these testbuilds please and let me know if it works for the first URL: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-677/2/artifacts

**Comment by khimaros** [comment]
it looks like current PR will only use the first URL. how much additional trouble would it be to use all of them?

**Comment by phunkyfish** [comment]
Correct. No, it’s not possible to use multiple. If you require that functionality you should use something like iptvmerge.

But please test the PR and let me know if it works for the first URL.

**Comment by dbojan** [comment]
Excellent, working as intended, It uses the first url.
Tested it with prerelease Kodi 20 version. (Installed plugin from downloaded 64bit zip version, on Windows.)

Thank you.

**Comment by phunkyfish** [comment]
👍
