### ISSUE TITLE
Incorrect handling of spaces in m3u playlist tag #EXTGRP

### ISSUE THREAD

**Issue by egorenar** [kodi-pvr/pvr.iptvsimple#675]
Hi,

spaces within group names in `#EXTGRP` are handled incorrectly as a separator.

README.md says:
`#EXTGRP: A semi-colon separted list of channel groups that this channel belongs to.`
Other players handle them correctly.

Example:
```
...
#EXTGRP:My group
...
```

**Comment by phunkyfish** [comment]
What exactly is the problem you having?

If I test the above example I get a single group called `My Group`

**Comment by egorenar** [comment]
I'm using the Nexus version of the plugin with Kodi Nexus and i get only the first part of the group as the group name.
If i'm not mistaken then `ReadMarkerValue()` uses the space char as a separator https://github.com/kodi-pvr/pvr.iptvsimple/blob/b50a9dab7b899fa8330b415d6e9133fcb5dad803/src/iptvsimple/PlaylistLoader.cpp#L168
And this is why i get only the "My" as the group name.

**Comment by egorenar** [comment]
Is this still correct ?
https://github.com/kodi-pvr/pvr.iptvsimple/blob/b50a9dab7b899fa8330b415d6e9133fcb5dad803/README.md?plain=1#L515

**Comment by egorenar** [comment]
Sorry, correction, i'm using the Nexus branch.

**Comment by phunkyfish** [comment]
If you surround your group string with quotes what happens?

**Comment by egorenar** [comment]
Then it works.
But this has its own issues.
1. The playlist comes not from me.
2. Other players handle spaces correctly.
3. How do multiple groups work ?

Is this correct for multiple groups ?
```
#EXTGRP:"my group1; my group2"
```

**Comment by egorenar** [comment]
Suggestion.
Why not just use ';' as a separator ?

Example:

```
#EXTGRP:My group1;My group2
```

No need to handle spaces in that case, they will be automatically part of a group name.

**Comment by phunkyfish** [comment]
The `EXT` tags have special meaning and are all read as space delimited lists, if we switch to semi colon everything else will break. I think we’ll need a special handler just for groups.

**Comment by phunkyfish** [comment]
Can you test this build: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-677/1/artifacts

It should fix the issue.

**Comment by egorenar** [comment]
yes, works as expected for my use case. thanks.

**Comment by phunkyfish** [comment]
👍

**Comment by matthuisman** [comment]
@phunkyfish did this fix go into Nexus?

**Comment by phunkyfish** [comment]
Yes: https://github.com/kodi-pvr/pvr.iptvsimple/pull/677
