### ISSUE TITLE
Kodi startup - Starting iptv client stuck 

### ISSUE THREAD

**Issue by donalduck101** [kodi-pvr/pvr.iptvsimple#679]
hello, i have pretty weird bug
im running android 7, kodi 19.5 with iptv simple client

the bug happens when the streamer was running for about 1 week. when i start kodi the iptv client starts to run but stuck at 0%
because it happens randomly i cant catch the bug

*also, after i reboot the streamer, the bug seems to pass and iptv client runs perfectly fine
( if i force close the process, it doesnt seems to help)

slim logs (removed alot of addons  and repos from kodi to make it slim and readable.):
https://raw.githubusercontent.com/donalduck101/kodi_log/main/kodi.log

**Comment by phunkyfish** [comment]
What do you mean by the streamer was running for a week?

**Comment by donalduck101** [comment]
I mean that if i reboot the streamer the addon is working fine

**Comment by phunkyfish** [comment]
What is the streamer?

**Comment by donalduck101** [comment]
slim logs (removed alot of addons  and repos from kodi to make it slim and readable.):
https://raw.githubusercontent.com/donalduck101/kodi_log/main/kodi.log

(sorry paste.kodi.tv couldn't handle the 13mb file)
edit:
removed alot of addons and repos from kodi to make it slim and readable

**Comment by donalduck101** [comment]
thanks to emveepee in kodi forums
https://forum.kodi.tv/showthread.php?tid=371140&pid=3131188#pid3131188

will test the solution and if it will reproduce i will open it again
