### ISSUE TITLE
.zip for iOS and OpenElec?

### ISSUE THREAD

**Issue by sei4eto** [kodi-pvr/pvr.iptvsimple#68]
Hello!
I tried to follow building instructions on main page for building zip file. Following instructions I managed to build zip. But then I managed to install it only on kodi on OSX. When I try to install it on iOS or Android I get " cannot install .zip from //path wher the zip is located" error.
Is there any differences in building zip for different platforms? What should I do to build zip for iOS, raspberry PI 2 (openElec)?
Thanks.

**Comment by hudokkow** [comment]
You need to build for every platform you want. Binaries aren't compatible across platforms.
As for the install problem, provide a debug log, please.

**Comment by PonyOny** [comment]
@sei4eto could you finnaly build latest version for raspberry Pi? I also need the compiled zip to install on my Raspberry, i have version 1.15 of iptv....
