### ISSUE TITLE
Problem whit 1080p

### ISSUE THREAD

**Issue by superGrzes** [kodi-pvr/pvr.iptvsimple#682]
Hello,

I have a problem because I bought a new Mecool KM7 box and I have a Samsung 85q70b TV and after installing Kodi and pvr Simple, when I add the plusx list, the channels in 4k work beautifully and the rest of the channels in 1080p jam so much that it freezes after a while. The old Chinese box works great. I don't know what could be the cause. I have no idea anymore, so I am writing to you. Do you have any idea?

**Comment by phunkyfish** [comment]
This question is regarding kodi and not the addon. Please ask in the kodi forum. This GitHub project is for bugs.

**Comment by superGrzes** [comment]
Thx for your time
