### ISSUE TITLE
Kodi v20

### ISSUE THREAD

**Issue by RhAbder** [kodi-pvr/pvr.iptvsimple#688]
This addon's dependencies are still not compatible with  kodi v20

**Comment by phunkyfish** [comment]
Sorry, but that description gives very little to go on. Please give (a lot) more details.

**Comment by SiNaPsEr0x** [comment]
It works for me without problems
![image](https://user-images.githubusercontent.com/5438823/216788514-41057d8b-c56d-4797-98ef-16e81f00f3e8.jpeg)

**Comment by RhAbder** [comment]
My bad, i had to update all the dependencies, as the auto update option was disabled.
Its working great now.
