### ISSUE TITLE
black screens

### ISSUE THREAD

**Issue by sucrov** [kodi-pvr/pvr.iptvsimple#70]
I use philips 50 android tv to stream.
only when I use live tv on kodi with the PVR IPTV SIMPLE 
I get black screens once every 1 or 2 mins.
when I open the live tv trough add-ons with PVR IPTV SIMPLE off
I have no black screens and no issues but it is less comftable using.

**Comment by afedchin** [comment]
This is not the right place for this discussion, you can ask on the Kodi forums. Also keep in mind that addon doesn't play or read or anything else except provide a url to the Kodi's player.
