### ISSUE TITLE
More PVR details

### ISSUE THREAD

**Issue by Radoorech** [kodi-pvr/pvr.iptvsimple#711]
Hello guys, I´d like to ask you if there is any way how to add more details to PVR. My epg.xml contains information about country, origin title and more then one rating. I added to DialogPVRInfo.xml ListItemCountry, but no change, I don´t see any country in pvr detail. So don´t know if this is skin Estuary issue, or kodi. (country works great with videos)

$INFO[ListItem.Country,[COLOR grey]$LOCALIZE[574]:[/COLOR] ,[CR]]
$INFO[ListItem.Country,[COLOR grey]$LOCALIZE[21875]:[/COLOR] ,[CR]]

If is it possible, can you please add ListItemCountry and Original Title to PVR Section?

When I open a look at github source (https://github.com/kodi-pvr/pvr.iptvsimple/blob/Nexus/src/iptvsimple/data/EpgEntry.cpp) I think, the problem is, that there isn´t any SetCountry and SetOriginalTitle like in VideoInfoTag.

Hope you understand what I mean, and sorry for my english.

Regards

https://imgur.com/nnnXQQV

**Comment by phunkyfish** [comment]
VideoInfoTag is used for recordings, not epg entries.

Kodi PVR supports original title but not country for EPG entries. But we don’t support original title is this addon.

**Comment by Radoorech** [comment]
Hello phunkyfish, thanks for your answer. I know that VideoInfoTag is used for recordings, it was just an example that kodi support original title and country in regoordings, but not in the this addon. So there isn´t any way how to show country and original title in PVR  details?

**Comment by phunkyfish** [comment]
There is no support for original title in the xmltv spec. So we can’t support it in the add-on.

Country is in the spec, but not in Kodi PVR EpgInfoTag so no route they’re either.

Recordings are very different to programmes.

**Comment by Radoorech** [comment]
Ok, understand, it´s not possible for now. Thanks for your time and help. I close this issue.
