### ISSUE TITLE
problema sul pvr simple client

### ISSUE THREAD

**Issue by francescomarzullo** [kodi-pvr/pvr.iptvsimple#713]
the git reop master has a problem installing the massive kodi-pvr/pvr.iptvsimple on endavr os and the files to mount it are missing to compile the pvr on arch so if you can solve it I can use the pvr on kodi 20

**Comment by phunkyfish** [comment]
I’m sorry but your message doesn’t really make sense.

**Comment by francescomarzullo** [comment]
I think it makes sense since I can't install the pvr from the git repo for my arch linux

**Comment by francescomarzullo** [comment]
and I followed the addon guide to the letter but it gives me an error on compilation I have kodi 20 installed

**Comment by francescomarzullo** [comment]
if you don't believe me then try the github guide on kodi 20 on arch and see if it gives errors by giving the commands of the github guide on the main page and if it doesn't work on the latest version of kodi solve the git bug on the pvr project

**Comment by phunkyfish** [comment]
Are you using the Arch build package or trying to build from the repo directly?

**Comment by francescomarzullo** [comment]
I am using the package directly from the repository


Il gio 2 mar 2023, 16:06 phunkyfish ***@***.***> ha scritto:

**Comment by lrusak** [comment]
You need to post the build log with the actual error.

**Comment by francescomarzullo** [comment]
gives me this error

bash: cmake: command not found

and I used command 3 of the guide which would be this

cmake -DADDONS_TO_BUILD=pvr.iptvsimple -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons

**Comment by francescomarzullo** [comment]
and it also gives me this error

makefile found

**Comment by phunkyfish** [comment]
You should post on the arch forums somewhere. Special build scripts need to be used for Arch and we don’t supply them I’m afraid.

**Comment by francescomarzullo** [comment]
vabe so i have to contact aur to install the addon component ?

**Comment by phunkyfish** [comment]
Have a look at this issue: https://github.com/kodi-pvr/pvr.iptvsimple/issues/300

it says to use the package from AUR

**Comment by francescomarzullo** [comment]
I read your forum but let's say that then is a problem of distro I know

Il gio 2 mar 2023, 18:32 phunkyfish ***@***.***> ha scritto:
