### ISSUE TITLE
Why to not used URL encode paths using resource:// or special:// protocols in v20.9.1?

### ISSUE THREAD

**Issue by alfonsu** [kodi-pvr/pvr.iptvsimple#730]
Why and what changed in v20.9.1 to disallow using special:// as a path, which previously worked perfectly. This is very inconvenient for Windows users where the profile name is different but they want to make a backup and transfer it to another computer.

**Comment by phunkyfish** [comment]
URL encoding was removed as some look and feel add-ons did not support it. The intent was only to have this happen for logo paths however.

Can you give some examples of paths you use that require it? Maybe we can come up with a better solution.

Please clearly describe your use case.

**Comment by alfonsu** [comment]
If this only affects the logo paths, then no problem.
My paths are working for now, but I was wondering if I should change the path strategy to my playlists or if I can leave them like that for the future.
special://userdata/playlists/tv.m3u
special://userdata/playlists/epg.xml.gz

**Comment by phunkyfish** [comment]
These will be fine. It will only affect paths within the playlist file. Not the path to the playlist itself.
