### ISSUE TITLE
🖐️Thank you for your work on the deferred and Catch-up

### ISSUE THREAD

**Issue by victore447** [kodi-pvr/pvr.iptvsimple#735]
![143](https://user-images.githubusercontent.com/48101775/230619124-b038133c-eed2-40a6-acaa-b827763fc74a.gif)Hi everyone.
☝️The Deferred and Catch Up via Pvr Settings Iptv simple kodi Nexus
client works perfectly
with Iptv m3u (Files) sources that work without cuts with channel Replays👌.

The playback of Replays or rewind of the live recorded are fluid as a
simple video file
and faster than the Tivimate,Iptv Smarters pro etc. apps. 👍✔️![22645-applause01](https://user-images.githubusercontent.com/48101775/230619059-e9a2934e-aad9-4013-b3ac-5ad8d0cc649d.gif)

**Comment by phunkyfish** [comment]
You’re very welcome!
