### ISSUE TITLE
Inputstream Dash and IPTV Simple Client

### ISSUE THREAD

**Issue by joejoeroo** [kodi-pvr/pvr.iptvsimple#74]
When InputStream MPEG DASH is activated some streams cant be opened.

My playlist contains the following stream

> #EXTINF:-1 tvg-id="ZDF.de" tvg-logo="zdf.png",ZDF HD (IP)
> http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/master.m3u8

kodi.log

> 23:55:35 4144.965332 T:1962205184  NOTICE: VideoPlayer: Opening: pvr://channels/tv/Alle Kanäle/pvr.iptvsimple_540930921.pvr
> 23:55:35 4144.965820 T:1343218592  NOTICE: Creating InputStream
> 23:55:35 4145.204590 T:1343218592   ERROR: AddOnLog: InputStream MPEG DASH: Could not open / parse mpdURL (http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/master.m3u8)
> 23:55:35 4145.205078 T:1343218592   ERROR: CDVDInputStreamPVRManager::Open - error opening [http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/master.m3u8]
> 23:55:35 4145.205078 T:1343218592   ERROR: CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/Alle Kanäle/pvr.iptvsimple_540930921.pvr]
> 23:55:35 4145.205566 T:1343218592  NOTICE: CVideoPlayer::OnExit()
> 23:55:35 4145.369629 T:1962205184  NOTICE: CVideoPlayer::CloseFile()
> 23:55:35 4145.369629 T:1962205184  NOTICE: VideoPlayer: waiting for threads to exit
> 23:55:35 4145.369629 T:1962205184  NOTICE: VideoPlayer: finished waiting
> 

when i deactivate the addon for inputstream mpeg dash everything works fine.

i use libreelec milhouse build for kodi 17 "krypton" Apr 17 2016

**Comment by afedchin** [comment]
> When InputStream MPEG DASH is activated some streams cant be opened.

The issue is not related to pvr.iptvsimple. Please use forum for reports.
