### ISSUE TITLE
Media: Custom Groups & Some Groups not respected

### ISSUE THREAD

**Issue by berkhornet** [kodi-pvr/pvr.iptvsimple#745]
When using the m3u group-title as path of the media path, the Custom Groups and Some Groups parameters are not respected; all pf the groups in the local file or remote m3u are included as recordings. I have tested both scenarios.

**Comment by phunkyfish** [comment]
If you don't use the group-title as part of the media path are they respected?

**Comment by berkhornet** [comment]
Hi. Just tested with "use m3u group name in path" set to "never". all entries in the file were listed in recordings. thanks.

**Comment by phunkyfish** [comment]
Can you try these testbuilds: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-736/7/artifacts

Hopefully the custom groups are respected. Let me know.

**Comment by berkhornet** [comment]
@phunkyfish - I can confirm that the custom groups are now respected. Many thanks

**Comment by phunkyfish** [comment]
Closed by: https://github.com/kodi-pvr/pvr.iptvsimple/pull/736 and https://github.com/kodi-pvr/pvr.iptvsimple/pull/739
