### ISSUE TITLE
Media groups appear in EPG

### ISSUE THREAD

**Issue by berkhornet** [kodi-pvr/pvr.iptvsimple#753]
I have now run a test on Omega with Simple Client 21.3.0. I noticed that groups with only media appear in the EPG. This doesn't happen on the Nexus version (20.10.0).
![screenshot00000](https://user-images.githubusercontent.com/67786207/235342902-51eb6026-28b4-4a22-8d23-3bdf95f3c0fd.png)
![screenshot00001](https://user-images.githubusercontent.com/67786207/235342927-836cd574-7aa0-4fc8-a400-14065da80a40.png)

**Comment by phunkyfish** [comment]
Can you explain in more detail? What media settings do you have set up?

**Comment by phunkyfish** [comment]
Hold on, I see what you mean. So you don’t want these groups to appear at all in the EPG.

Hmmm, that’s trickier to do than it sounds. It should be the same on Nexus though.

There are literally zero code differences between Nexus and Omega right now.

**Comment by berkhornet** [comment]
My thinking was that displaying groups that are all media in the EPG is a bit redundant.

Let me run another test in Nexus - I will then migrate that install to Omega and let you know the outcome.

**Comment by phunkyfish** [comment]
I agree that it’s redundant, but that code is all to do with channels and I co-opted it into working for media. It may not be so easy to fix/change this. Will take a look though.

**Comment by berkhornet** [comment]
I've run another controlled test. First my live setup on Nexus 20.1. EPG doesn't show the groups that are all media.
![Nexus EPG](https://user-images.githubusercontent.com/67786207/235344881-8e73a581-5c20-4834-90ac-898badd34075.png)

I then installed the latest Omega nightly, which updated a few addons including IPTV Simple Client (to 21.3.0). Then the EPG showed the groups that are all media.


![omega epg](https://user-images.githubusercontent.com/67786207/235344955-8d363ed8-61ac-40b4-b45b-d2aa7536257e.png)

On the Omega setup I then hid the "all media" groups. This hid them from the EPG whilst the various stream entries remained in Recordings. All good I thought, but the hidden groups did not survive a Kodi restart.

Very strange the difference in behaviour between Nexus and Omega!

**Comment by phunkyfish** [comment]
Can you try these testbuilds on Omega?

https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-754/1/artifacts

It might be that empty groups are shown differently depending on Nexus/Omega. @ksooo FYI, I know you have been dabbling in this area recently.

**Comment by berkhornet** [comment]
@phunkyfish - just tested on Omega.  The empty groups no longer display in the epg. Thank you

**Comment by phunkyfish** [comment]
Fixed by: https://github.com/kodi-pvr/pvr.iptvsimple/pull/754
