### ISSUE TITLE
View channels of other stream types other than http/rtmp

### ISSUE THREAD

**Issue by JoseFSilva** [kodi-pvr/pvr.iptvsimple#76]
I really like this addon and its ui but since some channels are only available via sopcast or other and I find myself having http/rtmp streams in iptvsimple (where they should all belong) and the others live in my favorites folder like a bunch of outsiders :(
What I'm looking for is a way for this plugin to work for both so we can have different types of streams:

> #EXTINF:0, Unreachable TV FHD
> rtmp://0.0.0.0:1234

> #EXTINF:0, PLUXOS TV SUFHD
> plugin://plugin.video.player/?channel=9

Is this achievable? Could someone give me some guidelines?
Cheers.

**Comment by afedchin** [comment]
it's not possible to use `plugin://` urls in m3u.

**Comment by JoseFSilva** [comment]
Does Kodi forbid it? I saw someone achieved this, I'll post the YouTube link soon.

I thought this would be something easy to achieve, like it would just need minor tweaking in the m3u file parsing code. No?

**Comment by afedchin** [comment]
It's not working as you expect. the iptvsimple just provide urls from m3u to PVRManager. The addon doesn't parse them, the addon doesn't open them, the addon can't execute another plugin. that's all.

**Comment by JoseFSilva** [comment]
Thank you for your quick replies.
I still think there should be a workaround to this as the guy in that video was able to do so, he just didn't share the code or fully implemented it. I'll send the link when I find it.

**Comment by JoseFSilva** [comment]
Meanwhile, assuming it is in fact impossible. How would I go about having a addon that looks exactly like iptvsimple's gui (specially the wall view, I love it really) but has such behaviour. Something that isn't tied to the PVRManager (if that is the culprit), or my own version of PVRManager that allows iptvsimple to have such behaviour?

What is the easiest route in your opinion?
Cheers.
