### ISSUE TITLE
IPTV simple client now shows connection lost

### ISSUE THREAD

**Issue by ranjeets9** [kodi-pvr/pvr.iptvsimple#761]
I have tried kodi with different version pc and android but IPTV simple client shows connection lost and I cannot play any jio channels. It was all working before few days and we normally dont do anything with the player apart from installing jio tv plugin to watch indian live channels please check and help

**Comment by phunkyfish** [comment]
What version of the plug-in are you using? Do you have a full debug log?

**Comment by ranjeets9** [comment]
I downloaded Kodi v20.1 (Nexus) 64 bit version for PC and I see IPTV simple client is runnning on version 20.10.1. FYI I have also tried pre releases omega which had different version but same issue
![Capture](https://github.com/kodi-pvr/pvr.iptvsimple/assets/123510532/76528193-0dd7-4ab4-b3da-90ab5044ca0e)

**Comment by ranjeets9** [comment]
![Capture](https://github.com/kodi-pvr/pvr.iptvsimple/assets/123510532/ff0fe0fd-7a9a-418b-8d73-5f67d0bcff4e)
[kodi.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/11432573/kodi.log)
[kodi.old.log](https://github.com/kodi-pvr/pvr.iptvsimple/files/11432574/kodi.old.log)

Hi Again,

I have enabled full debugging log and reproduced the issue by uninstalling IPTV and reinstalling it back with the same connection lost error let me know if that helps or you need more info to debug?

**Comment by phunkyfish** [comment]
Can you try to delete any files matching this name `instance-settings*.xml` in `userdata/addon_data/pvr.iptvsimple`. Then restart kodi.

**Comment by ranjeets9** [comment]
![2](https://github.com/kodi-pvr/pvr.iptvsimple/assets/123510532/63c3fb27-5913-4cc7-8863-5265207d3cf1)
![Capture](https://github.com/kodi-pvr/pvr.iptvsimple/assets/123510532/f7048984-48c8-48cb-80b5-c23fdf4c9fb6)

Deleted the file emptied trash and started kodi and immediately I see the same connection lost pop up error

**Comment by phunkyfish** [comment]
You have not configured a playlist in the addons setting: 

`pvr.iptvsimple - iptvsimple::PlaylistLoader::LoadPlayList - Playlist file path is not configured. Channels not loaded.`

**Comment by ranjeets9** [comment]
Hi, Last when i checked I was not able to play any channels and noticed simple client connection lost thinking that was the main issue. I started checking only fixing the simple client issue but after I installed kodi, added botallen repository and added the latest plugin from krreet although we see the error simple client connection lost I am able to see view all channels without issues my bad. Would there be a way to suppress that message without affecting the current setup which is all good?

**Comment by phunkyfish** [comment]
I don’t know about the repo or the other add-ons you have installed I’m afraid. Those errors in the log indicate that nothing is loaded by iptvsimple. Are you sure you even need iptvsimple installed?

**Comment by ranjeets9** [comment]
I think iptvsimple is the main client to generate playlist and allows to watch live tv channel. I am not sure it is indeed needed just following the old style which was followed in earlier versions 

This is repo https://kodi.botallen.com/

this the plugin https://github.com/krreet/plugin.video.jiotv/releases

Anyway we can check that?

**Comment by phunkyfish** [comment]
You’ll need to talk to the repo/plug-in author. I don’t know how they configure IPTVSimple.

**Comment by ranjeets9** [comment]
I will give that a try but am good for now thanks a lot for your help in checking this 👍

**Comment by xMSNx** [comment]
Good day! Disable the preset settings, and create your own. That's how it worked for me.
