### ISSUE TITLE
Can't install IPTV Simple

### ISSUE THREAD

**Issue by emirelease** [kodi-pvr/pvr.iptvsimple#763]
The official instructions tell me to install from repository, but I couldn't find it in the repository, so I got the zip, but that didn't work either. I tried building it myslef, and while I successfully built it, I either have not figured out how to add the add-on properly, or that build also doesn't install.
I don't know how to get the log file either.

**Comment by emirelease** [comment]
Conclusion: I gave up and uninstalled Kodi. But do please add solutions just in case I need Kodi later.

**Comment by phunkyfish** [comment]
You don’t even mention what platform you tried to install. Getting the log files is easy: 

https://kodi.wiki/view/Log_file/Easy

**Comment by lrusak** [comment]
If on Linux you need to install the binary add-on from your Linux package manager (apt, dnf, yum, pacman, etc).
