### ISSUE TITLE
👋Failed Installations (Inpustream...)

### ISSUE THREAD

**Issue by victore447** [kodi-pvr/pvr.iptvsimple#772]
![155](https://github.com/xbmc/xbmc/assets/48101775/128e6d55-2882-4532-b909-9dbfc94ed509)  **Hello,**
 It has been several months (with Kodi Nexus) that it is impossible to install Pvr Iptv simple client on another device (Android Box TV) when backing up via Backup & EzMaintenance+ addons. Even manually via Zip files.☝️This  does not work until several days later (+ 3 days).
![Pvr 20230623_190151](https://github.com/xbmc/xbmc/assets/48101775/9f61d97d-302f-422b-96ec-b7c8b8ec527e)

 ☝️**Once it worked when I changed my IP address via Vpn etc...And even now it doesn't change anything.**
![Pvr 20230623_190257](https://github.com/xbmc/xbmc/assets/48101775/82d9807d-3a8b-4da1-b824-e0d0de49564a)

 👆**The same is true for the Inputream Adaptive, Inputream.ffmpegdirect, Rtmp inputream etc. add-ons.**
![Inputream 20230623_180913](https://github.com/xbmc/xbmc/assets/48101775/f92b43d4-70d8-43c9-a425-3e80c167a327)

![46](https://user-images.githubusercontent.com/48101775/236531040-06b24a9a-6ac3-467d-b561-b1928058f1f2.gif)
👉 [kodi.log](https://github.com/xbmc/xbmc/files/11850974/kodi.log)

☝️About twenty Skins are configured there with video plugins like youtube, Dailymotion,🎞️ etc..
**Android Tv storage space shows Kodi is 5GB used** 

 **Thank you for your answer** ✔️

**Comment by phunkyfish** [comment]
This is clearly an issue with the addons you are using for backup etc. Please contact the authors of those addons for support.
