### ISSUE TITLE
Fix it showing expired url for Widevine video

### ISSUE THREAD

**Issue by aicynide** [kodi-pvr/pvr.iptvsimple#774]
Inputstream adaptive can play widevine channel videos just fine

**Comment by lrusak** [comment]
Can you describe the problem in more detail?

**Comment by phunkyfish** [comment]
Are you using adaptive to play the video in iptvsimple? Please provide a full debug log.

**Comment by aicynide** [comment]
> Can you describe the problem in more detail?

I can play from .strm file but iptv simple client doesn't refresh token
