### ISSUE TITLE
 Kodi crashes on start of MPEGTS playback

### ISSUE THREAD

**Issue by PlintuZz** [kodi-pvr/pvr.iptvsimple#78]
good afternoon. kodi restarted in the playlist if there is mpegts feed
eg:
# EXTINF:-1 group-title="HD Kanalai",BBC Earth HD

http://xxxxxxxxxx.eu/BBCEarth_HD/mpegts
# EXTINF:-1 group-title="HD Kanalai",BBC World News HD

http://xxxxxxxxxxxxx.eu/BBCWorld_HD/mpegts

if you disable the network at the start of the run.
then connect the network to make data cleanup in the TV menu, then everything will work until you restart.

**Comment by Jalle19** [comment]
Playback issues should be reported on Kodi's bug tracker, not here.
