### ISSUE TITLE
m3u list for radio stations

### ISSUE THREAD

**Issue by WohnW** [kodi-pvr/pvr.iptvsimple#782]
Hello All,
Can anyone please help me. I am getting crazy with m3u list creation.
Whatever flag and/or list text I create Kodi (Nexus 20.02) always put a content to TV section, not as intended to "Radio".
I have added flag radio="true" - still no luck

My playlist looks like that:

#EXTM3U
#EXTINF:-1 radio="true"
#EXTINF:0,Radio Swiss Jazz
http://stream.srg-ssr.ch/m/rsj/aacp_96
#EXTINF:0,Polskie Radio PR2
http://stream3.polskieradio.pl:8902

**HOW TO DEAL WITH THAT???? PLEASE!**
@phunkyfish  - could you please assist me with this? What am I doing wrong? How to create correct list?

List should appear here in RADIO sectio:
![image](https://github.com/kodi-pvr/pvr.iptvsimple/assets/34268821/d4a30577-a1ad-4663-96e2-4a8de59be486)

however, doesn't matter what I do in playlist it appears here, in TV section:
![image](https://github.com/kodi-pvr/pvr.iptvsimple/assets/34268821/6462027d-7137-46ac-9030-81ebb757f0cb)

**Comment by CrAcK75** [comment]
It's wrong.... 
Try:

#EXTM3U
#EXTINF:-1 radio="true",Radio Swiss Jazz
http://stream.srg-ssr.ch/m/rsj/aacp_96

**Comment by WohnW** [comment]
> It's wrong.... Try:
> 
> #EXTM3U #EXTINF:-1 radio="true",Radio Swiss Jazz http://stream.srg-ssr.ch/m/rsj/aacp_96

**Comment by WohnW** [comment]
> It's wrong.... Try:
> 
> #EXTM3U #EXTINF:-1 radio="true",Radio Swiss Jazz http://stream.srg-ssr.ch/m/rsj/aacp_96

@CrAcK75  Worked!!! Amazing! Thank you very much!!
