### ISSUE TITLE
Alternate/backup stream support

### ISSUE THREAD

**Issue by pope3909** [kodi-pvr/pvr.iptvsimple#793]
I have multiple source streams per channel available to me for IPTV, and I'm hoping that it's possible to add "backup" streams that the manager can redirect to if it determines that the primary stream is down. It is very annoying to have these alternate streams available but no way to use them. 

If this is not a current feature then I think that it might be lucrative to have it become a supported feature. (I'm willing to donate to a gofundme or something to help make it happen.) 

I don't know how IPTV managers work, but could a series of stream links (preceded by a #) follow the initial stream link like this:

```
#EXTINF:-1 tvg-chno="" tvg-chno="" tvg-id="" tvg-name="" tvg-logo="" group-title="",XXX
https://XXXXXXXXXX
#https://XXXXXXXXXX
#https://XXXXXXXXXX
#EXTINF:-1 tvg-chno="" tvg-chno="" tvg-id="" tvg-name="" tvg-logo="" group-title="",XXX
```

The manager would consider all subsequent (# preceded) stream links as backup stream links until it encountered the next EXT tag or stream link that was not preceded with a #. 

At the first sign of problems with a stream link, the manager would connect to a backup and add the stream failure to a log.

I'm not sure if this has not already been done for a reason, but it would be a significant step forward for IPTV managers. This method would (in theory) keep the .m3u file compatible with other managers, so that a user doing this would not lose flexibility and could use the same .m3u file with other addons if they chose to do so. IPTV Simple Client could even use a proprietary EXT tag like this:

```
#EXTINF:-1 tvg-chno="" tvg-chno="" tvg-id="" tvg-name="" tvg-logo="" group-title="",XXX
https://XXXXXXXXXX
#EXT-IPTVSC: https://XXXXXXXXXX
#EXT-IPTVSC: https://XXXXXXXXXX
#EXTINF:-1 tvg-chno="" tvg-chno="" tvg-id="" tvg-name="" tvg-logo="" group-title="",XXX
```

Note: I'm currently using KODI/LibreELEC on a Pi4.

**Comment by phunkyfish** [comment]
It’s not likely this will be implemented. Reason being your provider should give reliable streams to play from. Maybe try a different provide?

**Comment by pope3909** [comment]
This post can be deleted as I have found an addon with this feature.

**Comment by phunkyfish** [comment]
Why not just close the issue?
