### ISSUE TITLE
Issue with playing a stream using Widevine and Kodi 21 Omega Beta 1 through PVR

### ISSUE THREAD

**Issue by ghost** [kodi-pvr/pvr.iptvsimple#800]
I am running the latest Arch Linux Aarch64 on a Raspberry PI 3+. I'm trying to play m3u stream that requires Widevine. I have compiled and installed all requirements (64 bit) that pvr simple iptv needs: glibc-widevine, widevine, inputstream.ffmpegdirect, rtmp, adaptive, and helper.

I have disabled catchup and timeshift. When I select a stream through the EPG, the stream starts playing but it only plays for 15 seconds and then stops and I get a stream stalled. I am able to rewind the length of the current show so say I click on to play and the show is 30 minutes the show plays for 15 seconds and then stops then I can rewind 30 minutes and watch until the point where I started play.  I don't have any issues with streams that don't need widevine.

The logs really don't show anything but stream stalled even in debug mode.

**Comment by phunkyfish** [comment]
Can you put a single stream that requires widevine in an M3U file, and play that while in full debug mode and post the log?

**Comment by ghost** [comment]
I had tried changing the advancedsettings but it did the same either way.

In the log I played the stream until it stalled and then I did a rewind and played until it hit the stall point.

https://privatebin.net/?8fa4e77c6ed9799a#7e1eswXrKsnvndSXF3tB1GuUXGTGHWtYnVdefWHKrddR

**Comment by phunkyfish** [comment]
I don’t see anything obvious. I would try posting this in the inputstream.adaptive GitHub and it’s likely something to do with the stream.

**Comment by ghost** [comment]
Thanks for looking. I figured it could be a variety of addons or Kodi itself causing the issue. Anyhow, I posted on the adaptive github.
