### ISSUE TITLE
problem with pluto live tv

### ISSUE THREAD

**Issue by greatAznur** [kodi-pvr/pvr.iptvsimple#806]
i use iptvsimple for integarte pluto tv in  my  channel 

the flow starts well and works until the first ad page
  I watched the video streams a bit
and the problem is that when pluto integrates an ad the ad freezes and there is only the sound

apparently it's blocked with this tag
#EXT-X-DISCONTINUITY
#EXT-X-PROGRAM-DATE-TIME:2023-11-13T20:22:26.564Z
because by removing what is included in these tags and putting back what should normally have it works, it works when I do it on a static file but on a dynamic file where I am not there but the problem persists

**Comment by phunkyfish** [comment]
Does it work when you put the stream in a `.strm` file and play it as a video?

**Comment by greatAznur** [comment]
I create a .strm file
but when I put the master.m3u8 which will contain the file with an ad it freezes at the ad on the other hand if I go and look for the playlist file of the master and I remove the ad section it works yes I have them in my film section and series for vod content
but I can't change it on the fly in the video stream of the plutotv channels

**Comment by phunkyfish** [comment]
What if you play it with inputstream.adaptive?

You can choose to use that for m3u8 in the addon settings, I think it’s under `Advanced`

**Comment by greatAznur** [comment]
the plugin needs inputstream.adaptive in dependance   but at no time can you choose to activate it or not in the plugin

**Comment by phunkyfish** [comment]
Just install it from the kodi repo

**Comment by greatAznur** [comment]
it is already installed

**Comment by phunkyfish** [comment]
Please describe the error you are getting in a different way.

**Comment by greatAznur** [comment]
when I go to a pluto tv channel video stream  (channel not vod ) the stream works until the ad page... or it freezes and I only get the sound

It did the same thing to me on the vod and I fixed the problem except that a channel does not send the master.m3u8 file in full but by flange so I cannot remove what disrupts the flow sorry  I do not see how to explain better

**Comment by phunkyfish** [comment]
Sorry, what I mean is can you explain when you switch to using inputstream.adaptive to play the stream, what happens?

I know it doesn’t work with ffmpeg, but that would need to be fixed in kodi as well. But it may work with adaptive.

**Comment by greatAznur** [comment]
but I don't have the choice to use one or the other in the iptvsimple plugin interface

**Comment by phunkyfish** [comment]
> What if you play it with inputstream.adaptive?
> 
> You can choose to use that for m3u8 in the addon settings, I think it’s under `Advanced`

You need to go to the addon settings and select it as the default for M3u8 streams.

**Comment by phunkyfish** [comment]
There is also a PVR addon for Pluto tv.

**Comment by greatAznur** [comment]
There is also a PVR addon for Pluto tv.  dont work for anything
this ?
[https://zupimages.net/up/23/46/esu7.jpg](url)

**Comment by phunkyfish** [comment]
https://kodi.wiki/view/Add-on:Pluto.tv_PVR_Client

**Comment by phunkyfish** [comment]
You need to go the settings for pvr.iptvsimple to set adaptive as the default to use.

**Comment by greatAznur** [comment]
I am on iptv simple client in expert and there is no adaptive flow setting or default

**Comment by phunkyfish** [comment]
What version of kodi are you using?

https://github.com/kodi-pvr/pvr.iptvsimple#advanced

it’s called: `Use inputstream.adaptive for m3u8 (HLS) streams`

**Comment by greatAznur** [comment]
kodi 20

**Comment by howie-f** [comment]
i am seeing exactly the same issue with the Pluto.TV PVR-Addon on Kodi 20 and 21.
compiled from https://github.com/kodi-pvr/pvr.plutotv .... i always thought reasoning is due to Pluto API changes.
i was told by the maintainer of the python add-on, Lunatixz...

the PVR add-on depends on inputstream.adaptive and inputstream.helper but i can't see anything to configure regarding inputstreams. and honenstly i've no idea how these add-ons interact :)

fyi @phunkyfish

**Comment by phunkyfish** [comment]
Ok, then until someone updates either the video or pvr addons I don’t think there is a way past this.

@greatAznur can you post a screenshot of the advanced tab of your settings for iptvsimple?

**Comment by greatAznur** [comment]
https://zupimages.net/viewer.php?id=23/46/o573.jpg
this ?

**Comment by ksooo** [comment]
> i am seeing exactly the same issue with the Pluto.TV PVR-Addon on Kodi 20 and 21.

I think this is a problem with inputstream.adaptive, not pvr.iptvsimple or pvr.plutotv. Interestingly, I'm using pvr.plutotv (latest official version) on a daily basis on my NVidia Shield Pro 2019, with latest Nexus nigthly build and latest official inputstream.adaptive and have no problems. I had those problems with the ad breaks with earlier version of inputstream.adpative, but some time ago there was an update that fixed it.

Not seeing any logs here with details about platform and kodi/add-on versions, there could be anything going wrong.

**Comment by phunkyfish** [comment]
> https://zupimages.net/viewer.php?id=23/46/o573.jpg this ?

That is the general tab. At the bottom on the left is the Advanced tab. That is what I want to see.

**Comment by phunkyfish** [comment]
@greatAznur can you post a full debug log please?

You should also make sure your addons are up to date.

@glennguy FYI

**Comment by greatAznur** [comment]
who ? Advanced  is not a tab is juste  parameter view in tab .

**Comment by phunkyfish** [comment]
Scroll down the tabs, from General to Chanels, EPG etc. after the Timeshift tab there are more and the last one is advanced.

**Comment by greatAznur** [comment]
ok great the hidden scroll ...  im actived  use the input stream adapative and ...   it's the same
ok with pluto tv is fonctional now ...  with a fresh install

**Comment by phunkyfish** [comment]
Is it working with the video addon or the PVR addon?

**Comment by greatAznur** [comment]
pvr  plutotv  addon is functional  but with ipsimple not always freeze

**Comment by phunkyfish** [comment]
Once its works with pvr.plutotv I considered that fixed. Iptvsimple does not deal with streaming providers with custom APIs.

I’ll close this issue now.
