### ISSUE TITLE
V21 | Duplicate Groups from Multiple Playlists 

### ISSUE THREAD

**Issue by kontell** [kodi-pvr/pvr.iptvsimple#807]
I've got two playlists which have some groups in common. 

In V20 the groups were merged in the PVR but in V21 there are duplicate groups. So I have two groups of the same name with channels from one playlist in each group.

**Comment by ksooo** [comment]
> In V20 the groups were merged in the PVR but in V21 there are duplicate groups. So I have two groups of the same name with channels from one playlist in each group.

That's a V21 feature, not a bug.

**Comment by phunkyfish** [comment]
I’m curious, how were you merging the groups in V20?

**Comment by kontell** [comment]
With a second add-on configuration, that was introduced with V20. Haven't changed anything with V21.

Edit: I'm meaning a second configuration of the same IPTV simple client addon.

**Comment by ksooo** [comment]
> Edit: I'm meaning a second configuration of the same IPTV simple client addon.

As I said, this is a V21 Kodi PVR core feature. Different clients now can have groups with the same name. The "grouping" was considered a bug by others (including myself), thus fixed.

**Comment by kontell** [comment]
Ok, but I'm struggling to see how multiple groups of the same name makes any sense. If they should be separate, give them separate names.

**Comment by ksooo** [comment]
Whenever something changes for the end user, there will always be this one guy complaining. ;-) But we cannot introduce settings for everything. Somebody needs to maintain all the code. I'm sorry.

>  If they should be separate, give them separate names.

If you want to group them, use Kodis channelgroup manager.

**Comment by kontell** [comment]
Using [IPTV Merge](https://www.matthuisman.nz/2019/02/iptv-merge-kodi-add-on.html) is the easiest way to fix the regression for me.

For reference, pull request changing the behaviour. https://github.com/xbmc/xbmc/pull/23016

**Comment by ksooo** [comment]
Problem solved. 🙃 And I know the PR that introduced the „regression“ very well. Have you seen the author? 🫣

**Comment by kontell** [comment]
Ya, I'm just closing the loop, I also noticed that it referenced no issues. If you're going to change the behaviour of a programme don't be surprised when people ask questions.

**Comment by ksooo** [comment]
All good. Nothing wrong with asking questions.
