### ISSUE TITLE
Restart/Timeshift stream

### ISSUE THREAD

**Issue by Radoorech** [kodi-pvr/pvr.iptvsimple#809]
Hello phunkyfish.
I´d like to ask you if is possible to add another option to IPTV Simple Client to play the currently running programm from the beginning.
My provider use three types of streams, live stream and catchup works great, but need to figure how to play timeshift stream.

The streams looks:
https://xxx/live.m3u8?channel=xxx&token=xxx (live stream, works great)
https://xxx/catchup.m3u8?channel=xxx&start=xxx&end=xxx&token=xxx (catchup stream, works great)
https://xxx/timeshift.m3u8?channel=xxx&start=1651427340&end=1651430040&token=xxx (play from beginning, need to play)

So the question is if is possible to add option "Play from beginning" or "Restart", something like you added with possibility to play catchup streams. (if I want to play catchup, there is button "Play programme" in context menu). So can you add button "Play from beginning" or "Restart" if the current programme is running?

So the playlist would look for example like this:

#EXTINF:0 **_timeshift-source="https://xxx/timeshift.m3u8?channel=xxx&start={utc}&end={utcend}&token=xxx"_** catchup="default" catchup-source="https://xxx/catchup.m3u8?channel=xxx&start={utc}&end={utcend}&token=xxx" catchup-days="3",Channel A
https://xxx/live.m3u8?channel=xxx&token=xxx

Hope you understand what I mean, my englisg is not perfect.

What do you thing, is it posibble?

Many thansk for your work.

**Comment by phunkyfish** [comment]
The catchup and timeshift stream URLs look the same.  What is the difference?

**Comment by Radoorech** [comment]
Hello, they looks different. The first difference is **timeshift.m3u8** and **catchup.m3u8** in stream url.
And also the path to stream is different between timeshift and catchup.
For example:
https://abc.org/timeshift.m3u8?....
https://def.org/catchup.m3u8?....

So I can´t use the option "Catchup only available on finished programmes" in catchup settings of IPTV Simple Client, i try it, but doesn´t work.

**Comment by phunkyfish** [comment]
The parameters for both are the same. Are you sure they are different? Have you tried using the timeshift URL in place of the catchup URL?

I don’t see why you can’t just use catchup for everything.

**Comment by Radoorech** [comment]
The parameters for start={utc}&end={utcend} are the same for timeshift and catchup, but timeshift URL and catchup URL are different. And when the currently running programme finished, then after 5 minutes timeshift URL change to catchup URL, so I can't use it anymore. So I can't use catchup with timeshift URL, it doesn't work this way.
For this reason I ask if is posibble to add new feature to iptv simple client to play currently running programme from beginning.

**Comment by phunkyfish** [comment]
So you mean the timeshift stream is only the currently running programme?

And the catchup stream is every finished programme?

**Comment by Radoorech** [comment]
Yes, exactly. Timeshift stream is only currently running programme.
For example, I'm watching now the programme which starts from 8:45 p.m. and ends 10:45 p.m. If I miss the start of programme and begin to watch at 9:15 p.m. I have the option to watch the currently running programme as a live stream from 9:15 p.m. or the second option is to watch it from beginning, so then the live stream switch to timeshift stream.
When the currently running programme finish, then I have just option to watch it a a catchup stream.
Hope you understand what I mean.

**Comment by phunkyfish** [comment]
I understand what you mean now. But I think what you want is two different channels, one using the timeshift stream and another using the catchup stream.

The issue you have is that your provider does not support true catchup which should cover all cases. In their implementation it does not.

Can you try the two channels as I propose and report back on whether or not it works?

**Comment by Radoorech** [comment]
Ok, I will try, but tomorrow. The problem is that I can't share the url of streams because of personal credentials, then you will be able to see the difference between the streams and you can see how does my providers support the catchup.

**Comment by Radoorech** [comment]
hello phunkyfish, so I tried these playlists.

#EXTINF:0 catchup="default" catchup-source="[https://xxx/catchup.m3u8?channel=xxx&start={utc}&end={utcend}&token=xxx](https://xxx/catchup.m3u8?channel=xxx&start=%7Butc%7D&end=%7Butcend%7D&token=xxx)" catchup-days="3",Channel A
https://xxx/live.m3u8?channel=xxx&token=xxx

#EXTINF:0 catchup="default" catchup-source="[https://xxx/timeshift.m3u8?channel=xxx&start={utc}&end={utcend}&token=xxx](https://xxx/catchup.m3u8?channel=xxx&start=%7Butc%7D&end=%7Butcend%7D&token=xxx)" catchup-days="3",Channel A
https://xxx/live.m3u8?channel=xxx&token=xxx

The first playlist works great, both live stream and catchup.
But with the second playlist works just live stream, catchup doesn´t work as I need, it works just with the last ended programme before currently running programme, if I want to play something else from catchup, then it doesn´t work because of non existing url.

This is how the urls looks, timeshift and catchup are different as you can see.

https://cdn0-vip.4ka.tv/at/hls/master/live.m3u8?channel=3&token=<token>
https://cdn0-vip.4ka.tv/at/hls/master/timeshift.m3u8?channel=3&start={start}&end={end}&token=<token>
https://fs3a-vip.4ka.tv/at/hls/master/catchup.m3u8?channel=3&&start={start}&end={end}&token=<token>

**Comment by phunkyfish** [comment]
Have you ever gotten the timeshift URL to work? For the second channel, on the EPG you should have the option to switch to the live stream or play the programme. Which did you choose?

**Comment by Radoorech** [comment]
Yes, the timeshift url works without problem. On currently running programme (title "Helicops (17)" on picture) there is just option switch to channel, live stream works.

Another programme on the picture with title "Otec Brown VIII. (6)", there is option to switch to the live stream and play the programme, I did choose play programme and it works.

But when I choose the title "Vône sveta (33)", there is also option to switch to the live stream and play the programme, I did choose play programme and it doesn´t work. Kodi log shows this:

error <general>: AddOnLog: inputstream.adaptive: Download failed, HTTP error 404: https://cdn0-vip.4ka.tv/at/hls/master/timeshift.m3u8?channel=3&start=1700638200&end=1700640300&token=xxx
2023-11-22 10:19:33.404 T:11884   error <general>: CVideoPlayer::OpenInputStream - error opening [pvr://guide/0001/2023-11-22 07:30:00.epg]

![epg](https://github.com/kodi-pvr/pvr.iptvsimple/assets/64608415/c1df251a-dc7f-4db5-b9b6-d5a4a450f611)

So what I need, on EPG if I open the programme with title "Helicops (17)" and there will be option to play from beginning or restart video and the kodi will play the stream with url https://cdn0-vip.4ka.tv/at/hls/master/timeshift.m3u8?channel=3&start=1700643300&end=1700647200&token=xxx.

**Comment by phunkyfish** [comment]
Please post a screenshot when you select helicops. 

You might need to disable catchup only for finished programmes for it to work.

**Comment by Radoorech** [comment]
So I disabled catchup only for finished programmes, then there is of course option to play the programme, I choose this option and timeshift works, I can rewind back to the start of currently running programme (title "Všade dobre, doma naj (54)" on the picture, the title Helicops ended at 11 a.m).

But now catchup doesn´t work with title "Helicops (17)", the same error : AddOnLog: inputstream.adaptive: Download failed, HTTP error 404: https://cdn0-vip.4ka.tv/at/hls/master/timeshift.m3u8?channel=3&start=1700643300&end=1700647200&token=xxx
2023-11-22 10:19:33.404 T:11884 error : CVideoPlayer::OpenInputStream - error opening [pvr://guide/0001/2023-11-22 08:55:00.epg]

![epg_2](https://github.com/kodi-pvr/pvr.iptvsimple/assets/64608415/c61827dc-2e82-4fc2-85d4-445e71e8f463)

**Comment by phunkyfish** [comment]
So what you need is a way of disabling catchup only for finished channels, per channel instead of globally. I.e. you need the green dot for helicops on the timeshift stream but not the catchup stream.

**Comment by Radoorech** [comment]
Yes, you're right but don't know if is it possible. And I don't want the same channel twice in the playlist, one for timeshift and second for catchup.
The best solution for mne is to add new option for currently running programme, so there will be new button for example "Restart" and kodi opens the timeshift stream. Something similar when you add new feature catchup to watch past programmes.

If it's not so easy, then I have to find other solution, maybe I'll try to write any script.

**Comment by phunkyfish** [comment]
We need a way to override the only finished programmes behaviour and use the timeshift stream for the current programme or the catchup stream otherwise, correct?

The way the addon works is it passes the catchup URL to the inputstream addon. So if we did this and you played the current programme you won’t be able to skip back to previous programmes on the current channel, but you could switch to an older programme via the EPG.

Would that work? So we simply choose a different catchup URL based on the programme being played. And the catchup window the current programme would only be from that programmes start.

**Comment by Radoorech** [comment]
Yes, correct, agree with your last answer. Honestly, this is very technical question for me. I'm just a simply kodi user and don't know how does it exactly works. I just know that my provider have the option to play currently running programme from beginning if I miss the start of the programme, especially for sports events. I think this option offers so many OTT providers, so it will be a very usefull feature of kodi and iptv simple client. This is just my opinion.

If it's not so easy to add this new feature than understand.

**Comment by phunkyfish** [comment]
I think this might be possible by using two catchup URLs. One for the current unfinished programme and the other for everything else.

But this will only work when you start the stream. I.e. if you start the stream with the current programme it will use what you call the timeshift URL but you can’t automatically switch to the other catchup stream unless you visit the epg and play a finished programme. This is a limitation of how kodi PVR and inputstreams work today, so for technical reasons only.

I’ll create a testbuild for you to try in a week or so. Please note that you’ll need to run a Kodi Omega (v21) to try this out.

**Comment by Radoorech** [comment]
Thanks for your answer and your work. This limitation of kodi PVR is nou problem, i'll go back to epg and play a finished programme.
But question is how kodi will know, that it has to play the timeshift URL and not the catchup URL.
I'll wait for your testbuild and will see.
Don't hurry, if you're busy.

**Comment by phunkyfish** [comment]
Wait until the test build and we can try it. I think it will work well.

**Comment by phunkyfish** [comment]
Ok, as a test can you try the testbuild for your platform: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-815/2/artifacts

Note that you will need to run Kodi Omega (v21) to be able to test this. It should work if you play the latest programme or play a channel.

**Comment by Radoorech** [comment]
Ok, I'll test it today and let you know. How should the playlist looks like? I have to use a catchup URL and timeshift URL?
Is there something that I have to add to playlist or use this one:
#EXTINF:0 catchup="default" catchup-source="https://xxx/catchup.m3u8?channel=xxx&start={utc}&end={utcend}&token=xxx" catchup-days="3",Channel A
https://xxx/live.m3u8?channel=xxx&token=xxx

**Comment by phunkyfish** [comment]
Yes. You need to add another URL called `catchup-latest-source`

So like this:

```
#EXTINF:0 catchup="default"  catchup-latest-source="https://xxx/timeshift.m3u8?channel=xxx&start={utc}&end={utcend}&token=xxx"  catchup-source="https://xxx/catchup.m3u8?channel=xxx&start={utc}&end={utcend}&token=xxx" catchup-days="3",Channel A
https://xxx/live.m3u8?channel=xxx&token=xxx
```

**Comment by Radoorech** [comment]
I´m trying this testbuild, it works, but with some problems. When I use option play programme on currently running programme ("Správy RTVS" on the picture), it opens correct catchup-last-source URL with timeshift, but it´s playing from current time 49:48 (see on the second picture), but don ´t know why the stream closed at 19:50 and not at 19:55 as it shows on EPG timeline. Another question is if there is possibility to open the timeshift stream from the first segment, from time 0:00, especially on sport events it´s very important. Hope you understand what I mean.

And the second problem is that all others channels doesn´t have the green dot as you can see on the first picture, so I can´t play any catchup stream. I just added  catchup-latest-source only to the first channel called Jednotka HD, the others channels lost catchup.

Is there any way how can I contact you to share my playlist to you, if you want and have time to test it.

Anyway, on the first testbuild not bad :-)

![obrázok](https://github.com/kodi-pvr/pvr.iptvsimple/assets/64608415/cb1cb125-0a60-4db3-9b1d-43695cb9a24a)

![obrázok](https://github.com/kodi-pvr/pvr.iptvsimple/assets/64608415/c1ac9ea3-fb15-41ad-8a6f-3c3e16d73d1c)

**Comment by phunkyfish** [comment]
Yes, I hacked the code in so the dots disappearing on the other channels is fine. We can fix that. This just proves the concept.

If you look me up on https://gitter.im/ you can share your playlist there, gitter allows private messaging. Having access to your playlist would makes things easier.

**Comment by Radoorech** [comment]
Not sure how does gitter.im works, I sent you a message, also on kodi forum.

**Comment by phunkyfish** [comment]
> Not sure how does gitter.im works, I sent you a message, also on kodi forum.

That also works!

**Comment by Radoorech** [comment]
Hello phunkyfish, did you receive my message on gitter.im or kodi forum?
No rush, just to let me know if you read the message. Thanks.

**Comment by phunkyfish** [comment]
Yes, I got your message, I needed to wait until the Xmas break to work on it further. The file was only a single stream and no EPG so I could not do much with it. 

What I need to finish this is the following:

1. Several channels in an M3U, some using the new feature and some not.
2. EPG that also works for the channels 
3. Screenshots both with and without the feature so I can see what I need to fix
4. All streams will need to be working. I can’t play the last stream you sent me as I get a 403 error.

**Comment by Radoorech** [comment]
Hi, don´t worry, understand it was Xmas time. I sent you new playlist and link to EPG on kodi forum.
Not sure what you mean with point "3. Screenshots both with and without the feature so I can see what I need to fix".
Let me know if you need anything else.
Many thanks.

**Comment by phunkyfish** [comment]
Thanks.

for point 3 it’s a screenshot of the guide window showing the version before the testbuild and the testbuild itself. I.e. showing the green dots.

**Comment by phunkyfish** [comment]
Here is the latest testbuild: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-815/3/artifacts

The dots appear correctly for me using your test file, and the video starts in in the right place for live and start of programme.

**Comment by Radoorech** [comment]
Hi, I´m trying the testbuild and the green dots appear correctly, catchup works great.
But when I try to play currently running programme (name "Henry Nebezpečný (4)"), I choose play programme in context menu, and it opens a catchup stream URL, not the timeshift URL, and it plays like VOD from startime to time when I start to play the stream, and then the stream close (to understand if I start to watch "Henry Nebezpečný" from 8:10 p.m., then VOD is 20 minutes long and close).

I don´t know what has changed to testbuild [PR-815/2/artifacts](https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-815/2/artifacts), but now it doesn´t open the catchup-latest-source stream, it open the catchup stream.

Hope you understand what I mean, my english is not perfect.

![obrázok](https://github.com/kodi-pvr/pvr.iptvsimple/assets/64608415/45414d77-d874-474e-810d-5dadc9c08e71)

![obrázok](https://github.com/kodi-pvr/pvr.iptvsimple/assets/64608415/8a611928-bf8a-452b-8f26-799f56b3af2b)

![obrázok](https://github.com/kodi-pvr/pvr.iptvsimple/assets/64608415/7ddfcf0b-1d54-4700-b5c0-12c1f4ca4b2f)

**Comment by phunkyfish** [comment]
For me switch to channel uses the timeshift.m3u8 for any programme, because that is the currently live programme, and it plays from now.

For only the currently live show,  play programme uses timeshift.m3u8, and for any other show it uses catchup. 

I believe this is expected behaviour.

**Comment by phunkyfish** [comment]
Can you show your catchup settings? Are you sure you have playback as live enabled? Using play programme for the latest progamme, I see different controls.

<img width="2125" alt="Screenshot 2024-01-02 at 20 25 58" src="https://github.com/kodi-pvr/pvr.iptvsimple/assets/4601187/771c6a01-3d98-4c68-9180-d7d9bd30eb0a">

**Comment by phunkyfish** [comment]
Here are my settings:

<img width="1803" alt="Screenshot 2024-01-02 at 20 28 58" src="https://github.com/kodi-pvr/pvr.iptvsimple/assets/4601187/e4393c60-3ad5-4bef-9f19-53d17dcb109f">

In the latest version that you have `Catchup only available on finished programmes` will be ignored as the `catchup-latest-source` url overrides it.

**Comment by Radoorech** [comment]
That´s weird, I´m using the same settings like you, but if I switch to channel it opens the live stream URL, if I use play programme on currently running programme or anything from catchup, it opens the catchup URL, but not the catchup-latest-source URL.
I install version windows-x86_64 zip, I´m trying it on my book.
I have something wrong, but don´t know what. Are you using the playlist which I sent you on kodi forum?

![obrázok](https://github.com/kodi-pvr/pvr.iptvsimple/assets/64608415/8ea7906c-c73d-4886-bba7-bd467fc959df)

![obrázok](https://github.com/kodi-pvr/pvr.iptvsimple/assets/64608415/16fbd702-79b5-40c3-97eb-f551e348b9f0)

**Comment by phunkyfish** [comment]
It sounds to me like you don’t have the correct version installed. Because what you describe is the previous version. Let me rebuild with a different version number to make it easy for you to check it.

**Comment by phunkyfish** [comment]
This one is version 21.7.1

https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-815/4/artifacts

**Comment by Radoorech** [comment]
You wrote:
> For me switch to channel uses the timeshift.m3u8 for any programme, because that is the currently live programme, and it plays from now.
> 
> For only the currently live show, play programme uses timeshift.m3u8, and for any other show it uses catchup.
> 
> I believe this is expected behaviour.

Hi, I´m trying the latest testbuild 21.7.1 and still the same behaviour. I´m confused why it doesn´t work the same way like to you. It still plays the catchup URL. I tried again the testbuild [PR-815/2/artifacts](https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-815/2/artifacts) and then it opens a timeshift URL, but catchup doesn´t work.

So I´m confused, have no clue why it doesn´t work.

Can you send me a message on kodi forum please URLs from your kodi.log when you play the live stream, currently running programme and something from catchup?

Thanks

**Comment by phunkyfish** [comment]
Can you also post a full debug log via the forum please? I'll need that to figure out. Please use a paste site.

I sent you the URLs you asked for

**Comment by Radoorech** [comment]
Full debug log sent

**Comment by phunkyfish** [comment]
Ok, I see the problem. In order to do this correctly we need to know if the programme is live. But we only know its live when setting the properties for catchup, but not when it's processing the URL so it will default to the other URL.

Let me have a think about this and see if there is way to do this. There might not be I'm afraid.

The reason the URL were different for me as I was looking at the logged property and the not the actual URL that was played.

**Comment by Radoorech** [comment]
Hi,
good to know where the problem might be.
If It's not so easy to find a solution for this issue, don't worry, I have to find another way to play the timeshift stream.
Don't waste your free tíme, I'll try to write some addon or script.
Many thanks that you tried it, sorry for your tíme you spent to find the solution.
Regards Rado.

**Comment by phunkyfish** [comment]
Hi, I have something else I'd like to try. Can you send me an update M3U/xmltv on the kodi forum? I'll look into this tomorrow.

**Comment by Radoorech** [comment]
Hello phunkyfish, upadate M3U/xmltv sent on the kodi forum. Many thanks.

**Comment by phunkyfish** [comment]
Thanks!

**Comment by phunkyfish** [comment]
Ok, I worked on this a bit more and its not actually possible for the simple reason that the ffmpegdirect inputstream has no knowledge of the programme information, maybe it will in the next few version of kodi, but not right now.

But I did come across one possible solution. There is a special format specifier call `{caatchup-id}` that read a value by the same name from the XMLTV. You could test this out with a simple XMLTV file where only the latest programme has a different programme ID. In the case of your M3U settings the `catchup-id` in the M3U to `catchup` for everything, except the current programme where it would be set to `timeshift` in the XMLTV. Now this would be routinely update the XMLTV to jave the right `catchup-id` set, but it should work, and even work when you channel surf (I think).

**Comment by Radoorech** [comment]
Hi phunkyfish, thanks for your time. I'll try the hint with catchup-id and will see. Many thanks that you tried to solve the issue.
