### ISSUE TITLE
Launching streams on Kodi Omega / RPi 5

### ISSUE THREAD

**Issue by schadboy** [kodi-pvr/pvr.iptvsimple#812]
So I have this issue on the latest version for LibreElec 12 / Kodi Omega where certain streams just don't work. I tested the streams both on my Computer and on an older Pi 3 with LibreElec 11 / Kodi Nexus and on both the streams work just fine.

First idea I had was to get version 11 on the Pi 5, but that version has no PVR Clients at all.
Next idea I had was to compile it myself, but  after following the Build instructions (for Linux) I'm not so sure where to go next with it.

(the issue might be due to one of the dependencies required for the PVR Client, but to be honest, I have no idea and thus I'm here.)

**Comment by phunkyfish** [comment]
I don’t even know if Kodi 11 will run on a pi 5. It probably won’t.

but you’ll need to follow up with the LibreElec team on this.
