### ISSUE TITLE
Feature request: Continue playing next programme from guide

### ISSUE THREAD

**Issue by kashaCode** [kodi-pvr/pvr.iptvsimple#820]
### Example:
Let's say the guide for a live channel looks like:

```
10:30 Programme A
11:00 Programme B
12:00 Programme C
```
### Current behavior:
If select Programme A from the pop-up guide, the programme is played in the video player and the player quits after 30 mins as it reached the end of the programme.

### Desired behavior:
After programme A is finished, Programme B should start playing.

This could be implemented as a user setting (eg: a checkbox for "Continue playing next programme when finished" under Catchup settings). But IMO this should be the default behavior. The user will stop watching whenever he wants. But if he doesn't stop watching, it means he wants to keep watching, so the addon should add the next programme to the playlist so the player doesn't close. The sudden stop is undesirable.

### What I've tried
With the following M3U playlist entry
```
#EXTINF:0 catchup="vod" catchup-source="plugin://plugin.video.xyz/?channel_id=123&showtime={H}{M}{S}&srno={Y}{m}{d}&programId={catchup-id}" catchup-days="7",Channel Name
plugin://plugin.video.xyz/?channel_id=123
```

I've tried enabling and disabling the option "Play from EPG as live TV (...)". I've also tried the same after changing the `catchup` parameter to `catchup="default"`. But in all cases it doesn't do what I want. So a separate option would be needed.

**Comment by chewitt** [comment]
Please move feature requests to the relevant section of the forum. This is a bug (only) tracker.

**Comment by kashaCode** [comment]
Moving request to the forum as this is a bug only tracker.
