### ISSUE TITLE
changing time of auto hiding OSD info after chanel switch

### ISSUE THREAD

**Issue by issteve** [kodi-pvr/pvr.iptvsimple#848]
Hi,
it takes some time before a new stream is played after I pressed a number (on my raspberry pi 3b+). 
Depending on the station this takes about 7-12 seconds.
So I would prefer the information/EPG data shown right after pressing the number would stay about 10 seconds instead of only about 4 to 5 right now, which is to short for me to read the given information anyway. 

Is there any way to set the OSD auto hide time anywhere?  

Changing it in the standard (Kodi on Libreelec) skin didn't help and I couldn't find anything related in .kodi/addons/pvr.iptvsimple/resources/settings.xml

Thank you very much for your help and this great plugin.
Best regards,
this issteve

**Comment by phunkyfish** [comment]
There won't be anything in iptvsimple that can change this. Likely any change would need to be made in Kodi itself. It might make sense to post on the kodi forum in the PVR section to see what is possible.

**Comment by ksooo** [comment]
Does changing this setting help?

![image](https://github.com/kodi-pvr/pvr.iptvsimple/assets/3226626/e30cea9e-dc43-42cd-b3e4-001bb09f87bb)

**Comment by issteve** [comment]
> Does changing this setting help?

Wow! Great! I think this would be a great hint, but this option is missing on my LibreElec 11.95.1 12.0 (Kodi 21.0rc1, IPTV Simple Client 21.8.2, Estuary Skin).
From which Version is it?

**Comment by ksooo** [comment]
This setting is there since forever, as far as I remember.

**Comment by ksooo** [comment]
Look at lower left of your settings window. Mine is saying "Expert". Most probably you need to change the settings level to see this setting?

**Comment by issteve** [comment]
Yes! That's it changing it to Expert did give me the option I was looking for! Thank you very much and have a nice weekend! 🤗
