### ISSUE TITLE
M3U's "tvg-chno" tag is ignored

### ISSUE THREAD

**Issue by ferrum** [kodi-pvr/pvr.iptvsimple#859]
I loaded a m3u playlist (specifically [this one](https://raw.githubusercontent.com/Tundrak/IPTV-Italia/main/iptvitaplus.m3u)) but the tag "tvg-chno" is ignored, meaning that the number of the channel is only given by the order it is found in.

Here an example of what happens:
![iptvsimpleclient](https://github.com/kodi-pvr/pvr.iptvsimple/assets/49845537/a9fdad1f-e5f6-4147-ab21-4d009a602cc1)

"RTL 102.5", according to the playlist I provided, should be on channel 36, not 26. Thank you for your work.

Edit: The option "Only number by channel order in M3U" is disabled.

**Comment by phunkyfish** [comment]
Ok, so you need that option enabled. Do you have multiple PVR clients or just iptvsimple?

**Comment by ferrum** [comment]
Hi, thank you so much for your quick reply.
The option states "Ignore any tvg-chno tags [...]", so why should it be enabled? Am I missing anything? However, I tried to enable it but the result is identical. Seems like IPTVSIMPLE always orders channels by the order it is found in the file, at least in this case.

The problem happens both on Windows and on Android.

No, I do not have other PVR clients, nor other add-ons whatsoever (except the ones iptvsimple depends on).

**Comment by phunkyfish** [comment]
Make sure you clear the PVR data after changing the setting and post a full debug log using a paste site and I’ll take a look

**Comment by ferrum** [comment]
Thank you again. It's the first time interacting with the Kodi/iptvsimple community. I hope this [debug log](https://paste.kodi.tv/dakuvofivo.kodi) is what you expected.

By the way, if you wish to try yourself, the M3U link I provided is legal, having the publicly available Italian live TV.

**Comment by phunkyfish** [comment]
> By the way, if you wish to try yourself, the M3U link I provided is legal, having the publicly available Italian live TV.

Great, can you provide the M3U and XMLTV links?

**Comment by phunkyfish** [comment]
Your log appears to be missing the debug statements for iptvsimple. Do you have debug mode enabled? Then restart kodi and send that log file.

**Comment by ferrum** [comment]
This is the M3U playlist and the link I inserted in the XMLTV: https://raw.githubusercontent.com/Tundrak/IPTV-Italia/main/iptvitaplus.m3u

I'll do as requested as soon as possible :-)

**Comment by ferrum** [comment]
Hey, I found the issue: I had to enable a switch in the global PVR settings, not in the Iptvsimple settings. Thanks for your help though.
