### ISSUE TITLE
m3u tvg-logo not working with full url

### ISSUE THREAD

**Issue by PonyOny** [kodi-pvr/pvr.iptvsimple#86]
If the m3u file has the tvg-logo property with a full url this is not working as in the configuration you have to specify if logos come from a local folder or remote url, in case it's a remote you have to specify base folder of the logos, in this case as it's a full url it has the base url in it, the client should let you leave the base address blank and then use the full url provided by the m3u file and not concat the m3u file tvg-logo and the base adres you input.

**Comment by catbaxter** [comment]
tvg-logo="http://***.com/icons/rbc.png", works perfectly for me

**Comment by PonyOny** [comment]
I'm using the raspberry version, and looking through the repo version I can see you are now on V2 and raspberry is V1 mmm this could be the problem then, do you know where I can get the latest compiled version for raspberry?

**Comment by PonyOny** [comment]
I close the issue because i have just seen that this was fixed on, if anyone could tell me where i can download compiled version for raspberry please.
v2.1.1
- Fix: Don't ignore channels logo if base logo path setting is empty.
- Fix: Don't apply base logo path to channels logo if tvg-logo has a full NET path.
