### ISSUE TITLE
No EPG content for flemish television

### ISSUE THREAD

**Issue by stemy2** [kodi-pvr/pvr.iptvsimple#861]
Hello,

I reconfigured iptv simple from zero. The strange thing is that EPG works for french language belgian TV (RTBF and RTL groups), but not for the flemish ones (EEN, Ketnet, Canvas). Where did the datas go ?

Thanks

**Comment by phunkyfish** [comment]
Is all the EPG content in a single file or does each have its own file?

can you explain step by step how you set it up?

**Comment by stemy2** [comment]
I followed this [howto](https://catch-up-tv-and-more.github.io/live_tv_installation/).

Everything is in one file named epg.xml.

**Comment by phunkyfish** [comment]
I’d suggest asking the cat up tv and more or the iptv manager authors for help. The files are fully managed by the those addons
