### ISSUE TITLE
build error I cannot resolve

### ISSUE THREAD

**Issue by de-vel-op-r** [kodi-pvr/pvr.iptvsimple#867]
pvr.iptvsimple Provider.h:14:10: fatal error: kodi/addon-instance/pvr/Providers.h: No such file or directory

OS: Ububtu 22.04

Code section that produces error:

-- Build files have been written to: /home/stream77/pvr.iptvsimple/build/pvr.iptvsimple-prefix/src/pvr.iptvsimple-build
[ 90%] Performing forcebuild step for 'pvr.iptvsimple'
Force build of pvr.iptvsimple
[ 93%] Performing build step for 'pvr.iptvsimple'
[  3%] Building CXX object CMakeFiles/pvr.iptvsimple.dir/src/addon.cpp.o
In file included from /home/stream77/pvr.iptvsimple/src/iptvsimple/Providers.h:11,
                 from /home/stream77/pvr.iptvsimple/src/IptvSimple.h:14,
                 from /home/stream77/pvr.iptvsimple/src/addon.cpp:9:
/home/stream77/pvr.iptvsimple/src/iptvsimple/data/Provider.h:14:10: fatal error: kodi/addon-instance/pvr/Providers.h: No such file or directory
   14 | #include <kodi/addon-instance/pvr/Providers.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by phunkyfish** [comment]
Are you building against the correct kodi source?

**Comment by de-vel-op-r** [comment]
I modify the code. Thanks anyway.

**Comment by de-vel-op-r** [comment]
Closed
