### ISSUE TITLE
Latest version for ARM Openelec & Raspberry Pi

### ISSUE THREAD

**Issue by PonyOny** [kodi-pvr/pvr.iptvsimple#87]
Where can I find the latest version to install on a Raspberry Pi with open elec? I have tried to compile / install the latest & it says dependencies missing, I suppose this is because it's not building for ARM, can any one share or explain how to compile project to use on a Raspberry pi?

Thanks.

**Comment by Jalle19** [comment]
Try the forums, you'll most likely have better luck there. You can also try to inform the OpenELEC maintainers of the issue so they update the addon.
