### ISSUE TITLE
Adding a header for use in the properties of the inputstream adaptive addon (ISA)

### ISSUE THREAD

**Issue by werimail** [kodi-pvr/pvr.iptvsimple#871]
In order to play streams correctly, it is necessary to add the following headersto ISA properties:: 

inputstream.adaptive.manifest_headers
inputstream.adaptive.stream_headers

as shown here:
```
#EXTINF:0, stream test
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.stream_headers=User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0
#KODIPROP:inputstream.adaptive.manifest_headers=User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0
http://88.212.7.11/live/test_ctsport_25p/playlist.m3u8|User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0
```
Maybe could also be an idea to have a PVR setting that allows to set or enable/disable user agents.

Thanks and greetings Weri

**Comment by phunkyfish** [comment]
There is a setting for iptvsimple to set a user agent for all streams. 

The props you are setting are ISA specific so no built in support for those in iptvsimple.

**Comment by CastagnaIT** [comment]
now i have no idea how the PVR code works but
yes there is a advanced PVR setting for user-agent this is a good thing,
the thing to check is if that setting value is propagated to ISA props, maybe from here(?):

https://github.com/kodi-pvr/pvr.iptvsimple/blob/847750a3d3dae26218adafe2dcd18fdac2dfd358/src/iptvsimple/utilities/StreamUtils.cpp#L86-L102

a good pratice is also set user agent to `inputstream.adaptive.manifest_headers` that is currently missing form code above it
needless to say, without it will make some providers unusable

**Comment by CastagnaIT** [comment]
@werimail can you test fixes and give a feedback?
builds for k22: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-882/2/artifacts

**Comment by werimail** [comment]
Thanks @CastagnaIT  for the implementation, unfortunately I currently don't have a Kodi 22 environment available for testing. Would it perhaps be possible to provide a backport for Kodi 21 for testing?

Greetings Weri

**Comment by CastagnaIT** [comment]
here k21 https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-883/1/artifacts

**Comment by werimail** [comment]
Thank you @CastagnaIT! I have one question: How can I set these advanced PVR settings? In the settings for the PVR addon I can currently only find "User Agent", "Inputstream name" and "MIME type" under "Advanced". What is the correct position or syntax?

Thanks and greetings Weri

**Comment by CastagnaIT** [comment]
use "User Agent" setting
and should be automatically applyed to all streams that dont already include mentioned ISA props

**Comment by werimail** [comment]
Ok @CastagnaIT  I have entered the following under "User-Agent": `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0` as well as the `#KODIDROP` lines in the .m3u as well the extension at the streaming address is removed. However, the stream cannot be started. Have I forgotten anything else?

Greetings Weri

**Comment by CastagnaIT** [comment]
string is ok
from your example on first comment
must be changed as
```
#EXTINF:0, stream test
http://88.212.7.10/live/test_ctsport_25p/playlist.m3u8
```
you need to enable also
![immagine](https://github.com/user-attachments/assets/54d2af3e-9fbc-41a5-b517-9a63c6d832e6)

and will works

i realized that there are needs an additional improvement because
if you force set inputstreamadaptive by using kodi props `#KODIPROP:inputstream=inputstream.adaptive` will be not evaluated by the PVR and behaviour fails then dont works nothing

sidenote now i never used this pvr addon but its a bit weird that you can enable ISA from PVR setting only for HLS specific format
where ISA support also dash/smoothstreaming

**Comment by werimail** [comment]
Sorry @CastagnaIT , but I made exactly the settings as you described, but the stream still doesn't start. Attached is a log file with the error that occurred.

By the way, I have adjusted the IP address of the test stream so that it has changed in the meantime (see first post)

[kodi_debug_pvr.log](https://github.com/user-attachments/files/16708924/kodi_debug_pvr.log)

Greetings, Weri

**Comment by CastagnaIT** [comment]
as you can see from log now user agent is set correctly on both props
```
2024-08-22 11:59:31.179 T:31605   debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.manifest_headers" value: user-agent=Mozilla%2f5.0%20%28Windows%20NT%2010.0%3b%20Win64%3b%20x64%3b%20rv%3a127.0%29%20Gecko%2f20100101%20Firefox%2f127.0
2024-08-22 11:59:31.179 T:31605   debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.stream_headers" value: user-agent=Mozilla%2f5.0%20%28Windows%20NT%2010.0%3b%20Win64%3b%20x64%3b%20rv%3a127.0%29%20Gecko%2f20100101%20Firefox%2f127.0
```
but your m3u8 link is broken `Failed: Timeout was reached(28)`

**Comment by werimail** [comment]
This is strange @CastagnaIT ??? If I remove the "User Agent" in the PVR settings and use the following structure in the .m3u8:

```
#EXTINF:-1 tvg-id="CTSport.cz" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/%C4%8CT_sport_logo.png/512px-%C4%8CT_sport_logo.png",CT Sport HD (Test)
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.stream_headers=User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0 
#KODIPROP:inputstream.adaptive.manifest_headers=User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0 
http://88.212.7.11/live/test_ctsport_25p/playlist.m3u8|User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0
```

the streams are working again, even with the test version of the PVR addon......

[kodi_debug_pvr_working.log](https://github.com/user-attachments/files/16709415/kodi_debug_pvr_working.log)

**Comment by CastagnaIT** [comment]
idk it could be that server you are using take in account of camelcase of "User-Agent" header name?

**Comment by werimail** [comment]
> idk it could be that server you are using take in account of camelcase of "User-Agent" header name?

Unfortunately I can't say??? But it may well be that capital letters at the beginning are necessary.

**Comment by CastagnaIT** [comment]
> Unfortunately I can't say???

so why not test as:
```
#EXTINF:-1 tvg-id="CTSport.cz" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/%C4%8CT_sport_logo.png/512px-%C4%8CT_sport_logo.png",CT Sport HD (Test)
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.stream_headers=user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0 
#KODIPROP:inputstream.adaptive.manifest_headers=user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0 
http://88.212.7.11/live/test_ctsport_25p/playlist.m3u8|user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0
```

**Comment by werimail** [comment]
Unfortunately not @CastagnaIT , the server can also handle this structure... However, I discovered something else in the log files: The error (`Failed: Timeout was reached(28)`) occurs in both. Where the stream is played (working), only the following string is transferred for the download:

```
2024-08-22 12:47:37.477 T:1918    debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.manifest_headers" value: User-Agent=Mozilla/5.0
2024-08-22 12:47:37.477 T:1918    debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.stream_headers" value: User-Agent=Mozilla/5.0
```

Using the new complete proberty fails:

```
2024-08-22 11:59:31.179 T:31605   debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.manifest_headers" value: user-agent=Mozilla%2f5.0%20%28Windows%20NT%2010.0%3b%20Win64%3b%20x64%3b%20rv%3a127.0%29%20Gecko%2f20100101%20Firefox%2f127.0
2024-08-22 11:59:31.179 T:31605   debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.stream_headers" value: user-agent=Mozilla%2f5.0%20%28Windows%20NT%2010.0%3b%20Win64%3b%20x64%3b%20rv%3a127.0%29%20Gecko%2f20100101%20Firefox%2f127.0
```

That's why I just added `Mozilla/5.0` as "User-Agent" in the PVR settings and now it works!!!

**Comment by CastagnaIT** [comment]
good i will finish PR soon
