### ISSUE TITLE
Simple client kodi 22

### ISSUE THREAD

**Issue by Greg0580** [kodi-pvr/pvr.iptvsimple#878]
I just updated kodi to kodi 22 (32bit) dated 3 August.  

After I open it. It disabled  Simple client.  And  when I try to enable it I get a Message reading  that FFmpeg Direct,  Dependency can't be Satisfied.  

The only  FF mpeg Direct available is 21.3.5  but it wants 22.0.0 Minimum 

And I see RTSMP Input  want 22.0.0 but the only version is 21.1.0

Input steam Adapter is OK  as the Minimum it wants  is 22.0.0 but 22.1.1 is Installed.  

Hopefully you are able to fix this soon  Please 

Thank you

**Comment by phunkyfish** [comment]
Binary addons are in the process of being updated for kodi 22. Expect this to take several days.

**Comment by Greg0580** [comment]
Allgood.
Thank you  for the Quick Reply.
Thank you
Have a Good day.



Sent from my Galaxy



-------- Original message --------
From: phunkyfish ***@***.***>
Date: 4/08/24 05:42 (GMT+12:00)
To: "kodi-pvr/pvr.iptvsimple" ***@***.***>
Cc: Greg0580 ***@***.***>, Author ***@***.***>
Subject: Re: [kodi-pvr/pvr.iptvsimple] Simple client kodi 22 (Issue #878)


Binary addons are in the process of being updated for kodi 22. Expect this to take several days.

**Comment by woodside007** [comment]
Any updated status on this? Thanks.

**Comment by Greg0580** [comment]
Not yet .  Hopefully it will be  fixed soon.  Waiting for FFmpeg direct  and RTMP Input  to be both updated.

**Comment by woodside007** [comment]
Anybody know anything about when this might be fixed yet? It's been a while.

**Comment by Greg0580** [comment]
RTMP , And  Input Streamer have been Updated in the last week.  But still waiting for FFmpeg Direct  to Updated to 22.0.0 or higher.  
As of 6.30pm eastern usa time Monday 12/8/2024. It still not been Updated.  Hopefully it Might be Updated this Week.   I believe there's 3 or 4 Developers  working on these Updates .

**Comment by phunkyfish** [comment]
The Piers branch for ffmpegdirect fails to build for Android due to an SDK change on the Android platform.

There is no ETA to fix this currently.

**Comment by Greg0580** [comment]
Hello
Thank you .  I just got the Update For FFmpeg Direct.  And Simple Client is Now fully Dated and as all Dependencies.  And is Working with No problem.  14/8/2024, 6.15 pm Eastern USA Time. 
Have A Good Day 👍.

**Comment by phunkyfish** [comment]
Yes. I figured out the android issue yesterday so it had been released for all platforms. You’re welcome.
