### ISSUE TITLE
cavs decoder support

### ISSUE THREAD

**Issue by bike3097** [kodi-pvr/pvr.iptvsimple#885]
I hope to add a CAVS decoder. Currently, the live stream source that plays CAVS decoding has a black screen and sound.

**Comment by phunkyfish** [comment]
Support for CAVS would need to be added to kodi or an inputstream addon. Then it could be used in iptvsimple.

**Comment by bike3097** [comment]
Hello, I tested it and a black screen appeared when playing cavs. Could you please test it? Thank you.

**Comment by phunkyfish** [comment]
I don’t know what CAVS is or how to test it. The response I left was to indicate to you that this was the wrong place for your request.

**Comment by bike3097** [comment]
I understand.
