### ISSUE TITLE
bug: seek for a non standard header in EPG xml files

### ISSUE THREAD

**Issue by t2pierre** [kodi-pvr/pvr.iptvsimple#896]
error parsing xmltv file when <?xml version="1.0" encoding="UTF-8" ?> is not in first line (which is not standard now

error <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadEPG - Unable parse EPG XML: Start-end tags mismatch, offset: 0:

**Comment by phunkyfish** [comment]
Huh?

If the XML file is not valid there is no way to parse it? This error is from the parser.

Can you provide the XML file? There is most definitely a standard for XML files.

**Comment by t2pierre** [comment]
Hello

Here is the xmltv file. There are other EPG sources available on internet providing such files
The parser is rejecting it.
If you add up <?xml version="1.0" encoding="UTF-8" ?> as the first line in the file, the parser works well

Best regards
PCH 
￼

**Comment by phunkyfish** [comment]
Ok, but those files are broken. I’m sorry but I don’t see this as a bug.

**Comment by t2pierre** [comment]
Why do you say it is broken?It works perfectly in Plex or other iOS iptv app. PchLe 24 sept. 2024 à 21:23, phunkyfish ***@***.***> a écrit :﻿
Ok, but those files are broken. I’m sorry but I don’t see this as a bug.

**Comment by phunkyfish** [comment]
Because they are invalid files. I didn’t see an XML file attached to the issue, so I can’t look at it myself.

**Comment by t2pierre** [comment]
I send it again as attachment, gzip in case oft was too big

￼

**Comment by phunkyfish** [comment]
You might need to upload the file, it’s might not work via email response.

**Comment by t2pierre** [comment]
[es.xml.gz](https://github.com/user-attachments/files/17121096/es.xml.gz)

**Comment by t2pierre** [comment]
Done!PchLe 24 sept. 2024 à 22:40, phunkyfish ***@***.***> a écrit :﻿
You might need to upload the file, it’s might not work via email response.

**Comment by phunkyfish** [comment]
> [es.xml.gz](https://github.com/user-attachments/files/17121096/es.xml.gz)

This xmltv file is valid and contains the leading `<?xml version="1.0" encoding="UTF-8"?>` tag. So I don't see what the problem is. Or did you add the tag to the file?

**Comment by t2pierre** [comment]
Yes I did. EPG provider send it without the first Line. PchLe 25 sept. 2024 à 19:01, phunkyfish ***@***.***> a écrit :﻿

es.xml.gz

This xmltv file is valid and contains the leading <?xml version="1.0" encoding="UTF-8"?> tag. So I don't see what the problem is. Or did you add the tag to the file?

**Comment by phunkyfish** [comment]
Is the file generated by an addon?

can you send me the file without any modifications?

**Comment by t2pierre** [comment]
[epg-34-7.xml.zip](https://github.com/user-attachments/files/17270563/epg-34-7.xml.zip)

this file is generated by Xteve (IPTV plugin). working fine in Plex or Emby.

**Comment by phunkyfish** [comment]
Thanks for the file, it helped with testing. This had nothing to do with the parser at all. It would in fact accept a file without the leading `xml` tag.

There was a check for tarred archives prior to parsing that looks for the `xml` tag. I've now changed this to the `xml` tag or starting wit `<` and ending with `>`.

Please test:
- Piers: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-902/2/artifacts
- Omega: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-903/1/artifacts

**Comment by Uukrull** [comment]
After this update I get no epg at all. Before launching Kodi I deleted Epg19.db to be sure to start fresh and these are the logs for 22.2.0 (working) and 22.2.1 (no EPG at all):

[kodi_22.2.0.log](https://github.com/user-attachments/files/17294505/kodi_22.2.0.log)

[kodi_22.2.1.log](https://github.com/user-attachments/files/17294508/kodi_22.2.1.log)

This happens with the external epg I used for this test (https://www.tdtchannels.com/epg/TV.xml) and my own customized xml.

From the 22.2.1 log:

```
2024-10-08 16:03:10.657 T:17704   error <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - iptvsimple::Epg::LoadEPG - Unable parse EPG XML: Start-end tags mismatch, offset: 17: 
                                                   [ 
                                                   	</programme>
                                                   </ 
                                                   ]
```

**Comment by phunkyfish** [comment]
> After this update I get no epg at all. Before launching Kodi I deleted Epg19.db to be sure to start fresh and these are the logs for 22.2.0 (working) and 22.2.1 (no EPG at all):
> 
> [kodi_22.2.0.log](https://github.com/user-attachments/files/17294505/kodi_22.2.0.log)
> 
> [kodi_22.2.1.log](https://github.com/user-attachments/files/17294508/kodi_22.2.1.log)
> 
> This happens with the external epg I used for this test (https://www.tdtchannels.com/epg/TV.xml) and my own customized xml.
> 
> From the 22.2.1 log:
> 
> ```
> 2024-10-08 16:03:10.657 T:17704   error <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - iptvsimple::Epg::LoadEPG - Unable parse EPG XML: Start-end tags mismatch, offset: 17: 
>                                                    [ 
>                                                    	</programme>
>                                                    </ 
>                                                    ]
> ```

ok, I’ll test using that xml file later on. Do you have some sample M3U entries I can use to test it works correctly? The URLs can be obfuscated, I don’t need anything to play, just load in the UI.

**Comment by Uukrull** [comment]
This is what I'm using for the test:

```
#EXTM3U

#EXTINF:-1 tvg-id="24Horas.TV" tvg-logo="https://pbs.twimg.com/profile_images/1144547866393882626/2R0Khn5n_200x200.png" group-title="Informativos" tvg-name="24h",24h
https://ztnr.rtve.es/ztnr/1694255.m3u8

```

**Comment by phunkyfish** [comment]
@Uukrull 

Your test M3U and XML file work for me on a mac. The previously supplied XML file from @t2pierre also worked for me.

Let me create you a testbuild with some logging for you to run and post the debug log.

**Comment by phunkyfish** [comment]
Oh, I think I found the problem. Can try this testbuild?

https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-904/1/artifacts

**Comment by Uukrull** [comment]
Working now:

```
2024-10-08 21:54:11.767 T:12992   debug <general>: CCurlFile::XFILE::CCurlFile::Open - <https://www.tdtchannels.com/epg/TV.xml> Effective URL is https://www.tdtchannels.com/epg/TV.xml.gz
2024-10-08 21:54:11.819 T:12992   debug <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - iptvsimple::Epg::LoadChannelEpgs - Loaded channel EPG with id '24Horas.TV' with display names: '24Horas.TV'
2024-10-08 21:54:11.819 T:12992    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - iptvsimple::Epg::LoadChannelEpgs - Loaded '1' EPG channels.
2024-10-08 21:54:11.820 T:12992    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - iptvsimple::Epg::LoadEpgEntries - Loaded '37' EPG entries.
2024-10-08 21:54:11.822 T:12992    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - iptvsimple::Epg::LoadEPG - EPG Loaded - 302 (ms)
```

Many thanks.

**Comment by phunkyfish** [comment]
Great, I've released that now.
