### ISSUE TITLE
keymap on tvOS different from Android system.

### ISSUE THREAD

**Issue by jazsm** [kodi-pvr/pvr.iptvsimple#901]
Sir, Why the keymap of pvr iptv simple on Android different from tvOS system ? we like the keymap on Android system, Could you
change the keymap on tvOS system just like Android, thanks a million

**Comment by phunkyfish** [comment]
This is nothing to do with iptvsimple. The keymap is supplied from kodi core. I suggest raising this on the xbmc GitHub.

there is nothing stopping you from using the android keymap for tvos. Note that the keymap for tvos is modelled on the Apple Remote.
