### ISSUE TITLE
Kodi 21.1 not shipping with pvr.iptvsimple / version 21.9.2 seems problematic showing EPG info

### ISSUE THREAD

**Issue by enerdude** [kodi-pvr/pvr.iptvsimple#906]
Hi there

I created an issue with an addon creator [here](https://github.com/matthuisman/slyguy.addons/issues/894#issuecomment-2400993223)

You can read everything I did to recreate the problem.
First of all my Kodi Omega 21.1's Kodi repo does not come with pvr.iptvsimple and when I installed pvr.iptvsimple 21.8.3 the issue went away.  I could also see that Kodi repo wanted to update to 21.9.2 but I set auto update off to avoid not having EPG info again.

**Comment by phunkyfish** [comment]
21.9.3 fixes this issue. It should be available on addon repos now to install.

**Comment by phunkyfish** [comment]
I just checked the binary addon repo: https://mirrors.kodi.tv/addons/omega/

And I can see that 21.9.3 is available for all platform except Windows x64 which has 22.2.2.zip instead. Not quite sure his this happened.

You can manaully update from here in the meantime as we figure out how to fix this: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-905/1/artifacts

**Comment by matthuisman** [comment]
do you think there could be similar issue on Kodi 22?
https://github.com/matthuisman/slyguy.addons/issues/895

**Comment by phunkyfish** [comment]
> do you think there could be similar issue on Kodi 22? [matthuisman/slyguy.addons#895](https://github.com/matthuisman/slyguy.addons/issues/895)

Yes, 22.2.2 fixes it.

**Comment by matthuisman** [comment]
Perfect, thank you @phunkyfish  :)

**Comment by enerdude** [comment]
> 21.9.3 fixes this issue. It should be available on addon repos now to install.

Thanks tested 21.9.3 on android arm7 so far - works fine.
Will manually install for my windows x64 and let you know

**Comment by enerdude** [comment]
Tested 21.9.3 on windows x64 - also working.

Thanks for your help.

**Comment by phunkyfish** [comment]
Great, I’ll leave this issue open until the correct binary is available in the binary addon repository.

**Comment by goldengate2121** [comment]
I just compiled the latest git. In previous versions of Simple IPTV, it would try to match the tvg-id tag and if this was blank then it would match the tvg-name. If it saw a tvg-name, then it would match and display. The latest version doesn't do this. As a test I manually changed my m3u and my xml to have matching tvg-id tags and it is displaying with matching tvg-name tags no matching thus not displaying.

**Comment by phunkyfish** [comment]
> I just compiled the latest git. In previous versions of Simple IPTV, it would try to match the tvg-id tag and if this was blank then it would match the tvg-name. If it saw a tvg-name, then it would match and display. The latest version doesn't do this. As a test I manually changed my m3u and my xml to have matching tvg-id tags and it is displaying with matching tvg-name tags no matching thus not displaying.

please open a separate issue for this. What version of the addon are you using? Do you have a full debug log?

**Comment by goldengate2121** [comment]
I am using version 22.2.2. I will open up a separate ticket with a debug log file.

**Comment by phunkyfish** [comment]
> I am using version 22.2.2. I will open up a separate ticket with a debug log file.

Thanks, please also include the version number of the older addon where this worked for you.

**Comment by phunkyfish** [comment]
Binary addon repo fixed now. Closing
