### ISSUE TITLE
Failed to install add-on from zip file

### ISSUE THREAD

**Issue by MuzeLake** [kodi-pvr/pvr.iptvsimple#907]
Failed to install add-on from zip file10/10/2024 9:47:27 PM
Installing the add-on from zip file located at D:\kodi\pvr.iptvsimple-22.2.2-Piers.zip failed due to an invalid structure.
![PixPin_2024-10-10_21-54-00](https://github.com/user-attachments/assets/f84bea99-13e8-4f6d-bf14-f9af28215472)

system: Windows 10 22H2

**and I found that addons is also unavailable in official Kodi addon repository**
![image](https://github.com/user-attachments/assets/7360babd-45dc-401c-be94-d38c0da55e3e)
windows x86 64 downloading on website is not found
![image](https://github.com/user-attachments/assets/34610333-db7a-4393-bc08-8f405927038a)

i am confused... is anything happened on this project...?

**Comment by phunkyfish** [comment]
There was an automation problem with the binary addon server. Should be fixed in the next few days. Please manually refer to 21.9.1 in the meantime.

https://mirrors.kodi.tv/addons/omega/pvr.iptvsimple+windows-x86_64/pvr.iptvsimple-21.9.1.zip

**Comment by phunkyfish** [comment]
Binary addon repo fixed now. Closing
