### ISSUE TITLE
Unable to update.

### ISSUE THREAD

**Issue by Anth70** [kodi-pvr/pvr.iptvsimple#910]
Hello, I have a PC(LibreELEC-Generic-legacy.x86_64-12.0.1) with IPTV Simple Client v21.9.1.1 and want to update to v21.9.3.1. But the system just crashes every time I try to update, can't update to v21.9.2.1 either. Hoping for help with this, best regards Thore

**Comment by phunkyfish** [comment]
Have you posted this on the LibreElec forum? 

We just support vanilla kodi here.

**Comment by Anth70** [comment]
> Have you posted this on the LibreElec forum?
> 
> We just support vanilla kodi here.

Ahaa. Sorry. Should i delete this issue?

**Comment by phunkyfish** [comment]
That’s ok, I can close it.
