### ISSUE TITLE
EPG-Coreelec-UgoosAM6B+

### ISSUE THREAD

**Issue by slappy6212** [kodi-pvr/pvr.iptvsimple#911]
Hi,
Coreelec is not showing up my epg. Both options in the EPG settings (Web or Local) i dont know what to enter. I am using a m3u iptv server url address wich is normally working fine using other boxes like Formuler or Ugoos AM6B+ with Tivimate App as exemples. I tried adding my m3u url in the epg path with no success.

Here is the log requesting me to configure the path.
LOG: 2024-10-14 16:02:26.753 T:4162     info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadEPG - EPG file path is not configured. EPG not loaded.

Note: I am also unable to update to the latest vesrsion [22.2.2]. when using update from ZIP.

**Comment by slappy6212** [comment]
Ok I found it. 
My provider should also provided the EPG address separately.
For those looking for the solution, you must edit your m3u url address replacing the following url
http://xxxxxx.bz:8080/get.php?username=xxxxxx&password=xxxxxx with this one:
http://xxxxxx.bx:8080/xmltv.php?username=xxxxxx&password=xxxxxx

Replace the get.php? by xmltv.php? et voilà ! :-)

I am still unable to update to the latest version via ZIP method .... look like i need to wait for the repo to be updated first....

**Comment by phunkyfish** [comment]
Yes, and you need to report the update issue with CoreElec. The PVR addons are binary addons, you can’t just install from zip from this repo. That’s just the source code. It doesn’t work like Python addons.
