### ISSUE TITLE
Question regarding VOD entries 

### ISSUE THREAD

**Issue by lavish440** [kodi-pvr/pvr.iptvsimple#915]
Hi I have a m3u playlist with around 1100 channels and some VODs. 
When I use those VODs as Live Channels, they work perfectly but they have some issues regarding seeking forward and backward. 

When I use them as VOD using `media="true"` they fail to play. 
My VODs require some `KODIPROPS` because they are DRM protected by my provider and when using the VODs as media entries, SIPTV ignores those `KODIPROPS`. 

Is that the intended behaviour or a bug?
Also, I don't understand what's the use of the `realtime` option.

**Comment by phunkyfish** [comment]
Realtime means a live stream. So media items can never be realtime.

Kodiprops should work for media items. Do you have an example entry for a media item and I can check it? The URL can be obfuscated as well as any other private values.

**Comment by lavish440** [comment]
> Realtime means a live stream. So media items can never be realtime.


Okay what would happen if I do `realtime=false` for a live stream?

> Kodiprops should work for media items. Do you have an example entry for a media item and I can check it? The URL can be obfuscated as well as any other private values.

I can't as they are geo restricted and need tokens etc. 

The manifest type is DASH. It's a "static" type manifest so it's very large like 5-6 MBs. 
The `content-type` header is wrong though. 
It says `octet-stream` instead of `xml+dash`. 
I can override that using ISA. 
Maybe that's causing the issue?

**Comment by lavish440** [comment]
Looks like the `KODIPROPS` are not working. 
I specified `User-Agent` using `manifest_headers` in ISA but it is still using the default Kodi UA. 
I have tried to use a proxy to modify the `content-type` tag but still it is not working. 

Please note that all of the testing was done with "Show Media as Recordings" to On.

**Comment by phunkyfish** [comment]
What version of the addon are you running?

I’m pretty sure I fixed props for media entries a couple of weeks ago.

**Comment by lavish440** [comment]
> What version of the addon are you running?
> 
> I’m pretty sure I fixed props for media entries a couple of weeks ago.

22.1.2 built from Git. 
I think only the space char issue was fixed by Stefano. 

Edit: My bad. You have fixed that in your commits. 
I will try to rebuild it.

**Comment by lavish440** [comment]
@phunkyfish I can confirm that it works now. 
Also, is it possible to "skip" a live stream like a VOD by using something like `realtime=false`?

**Comment by phunkyfish** [comment]
Not sure, maybe just try it and see what happens.

**Comment by lavish440** [comment]
> Not sure, maybe just try it and see what happens.

I can with arrow keys but the progress bar doesn't update and if I try to seek with the progress bar, the stream restarts from 0. 

Can this be added please?

**Comment by phunkyfish** [comment]
This is ISA and not iptvsimple I’m afraid.

They likely need to implement the itimes interface.

**Comment by lavish440** [comment]
> This is ISA and not iptvsimple I’m afraid.
> 
> They likely need to implement the itimes interface.

Thanks for your assistance. 
I will open a feature request on ISA.

**Comment by lavish440** [comment]
Also, offtopic but each Instance is shown as a provider in the Providers tab along with the specified providers. 
Is that supposed to happen?

**Comment by phunkyfish** [comment]
Yes, that’s intended. Some users have only iptvsimple instances, and sometimes 10 or more. So the instance is the provider.

**Comment by lavish440** [comment]
Anyway to disable it?

**Comment by phunkyfish** [comment]
No, not currently, but this is a kodi feature and not iptvsimple.
