### ISSUE TITLE
No longer playing Pluto TV channels

### ISSUE THREAD

**Issue by MajinLugia** [kodi-pvr/pvr.iptvsimple#917]
Hello, whenever I link an m3u that contains Pluto TV channels, it can't play anything at all. This wasn't a problem in the past and I've done a fresh install as well and they work if I use iptv merge. I'm using Kodi 21.1 on Android TV 10.

**Comment by phunkyfish** [comment]
It could be that Pluto is blocking the kodi user agent. Hard to tell unless you supply a full debug log.

**Comment by MajinLugia** [comment]
Here is a log. If Pluto is blocking kodi user agent then that's a big loss.
https://paste.kodi.tv/mesikejufu.kodi

**Comment by MajinLugia** [comment]
Okay so I have set user-agent to OKHTTP as @matthuisman helped me out and it works now!
