### ISSUE TITLE
Not correctly downloading playlists and EPGs with M3U4U / Dropbox

### ISSUE THREAD

**Issue by rkershenbaum** [kodi-pvr/pvr.iptvsimple#920]
I'm using the M3U4U site to manage and edit my playlists and EPGs.  This has worked well -- until this week.  Because of unacceptable download loads, they have made a change to their systems.  Playlists and EPGs are now pushed to the user's Dropbox account, and the actual downloads are done from Dropbox.  

The links provided by M3U4U redirect to a Dropbox download link.  When the IPTV Simple addon uses that link, it downloads the HTML code for the Dropbox download page, instead of the actual playlist or EPG file.  So I see lots of "Unknown Channel" entries, and no usable channels. 

The Dropbox links to which M3U4U redirects do contain the "&dl=1" tag at the end, which should prevent this behavior.  I've also tried to enter the direct Dropbox url (containing that tag) into the addon, but the same thing happens.  

Is the addon stripping that tag?  Or is something causing it to be ignored?

(For now, I've worked around this by installing the Dropbox app on a home server, sharing the local Dropbox directory, and having the IPTV Simple addon obtain the files from there.)

Thanks for taking a look at this!

**Comment by phunkyfish** [comment]
The addon should not strip any tags, but take look at your debug log and see if the correct URL is being used.

Dropbox should let you generate a direct download link.

**Comment by phunkyfish** [comment]
Hmmm, it appears that `&dl=1` is the correct way to get a direct link.

**Comment by rkershenbaum** [comment]
When I use the direct Dropbox link, the &dl=1 tag is there in the URL shown in the debug log.  But it's being ignored for some reason.

**Comment by rkershenbaum** [comment]
I could PM the URLs to you if that would help.  (Obviously, don't post them anywhere.)

**Comment by phunkyfish** [comment]
Yes, that would work. I can at leat try them and see why it's not working.

**Comment by phunkyfish** [comment]
Not sure there is PM on github though. Maybe put them in a private gist and share it with just me.

**Comment by rkershenbaum** [comment]
Never done this before....I created a secret gist, but I'm not seeing how to share it just with you.  

From what I'm reading, anyone with the link would be able to see the contents.

**Comment by phunkyfish** [comment]
Ok, then that’s not a good idea.

**Comment by phunkyfish** [comment]
Maybe try gitter.im

**Comment by phunkyfish** [comment]
https://gitter.im/

**Comment by rkershenbaum** [comment]
https://matrix.to/#/@rkershenbaum:gitter.im

**Comment by rkershenbaum** [comment]
What's your gitter username?

**Comment by phunkyfish** [comment]
phunkyfish, same as GitHub

**Comment by rkershenbaum** [comment]
The following users may not exist
Unable to find profiles for the Matrix IDs listed below - would you like to start a DM anyway?

@phunkyfish:gitter.im: Profile was not found

Can you try the invite link I posted?

**Comment by phunkyfish** [comment]
Link worked. Just sent you a message.

**Comment by rkershenbaum** [comment]
Thanks to great help from phunkyfish and the M3U4U folks on Discord, we were able to determine the cause of the glitch. The file security in Dropbox needs to be set to "anyone with the link". Otherwise, Kodi / IPTV Simple / IPTV Merge will pick up html code requesting access, rather than the actual playlist or epg file.

So we can close this ticket. Thanks again for the help!!

**Comment by phunkyfish** [comment]
You’re very welcome
