### ISSUE TITLE
Time shift for a single EPG on m3u file tvg-shift="3"

### ISSUE THREAD

**Issue by DimSumDev** [kodi-pvr/pvr.iptvsimple#932]
Not sure if this is the right place or if this is a Kodi 20.5 issue (default skin)

I have an m3u with all my streams..
I have created an XMLTV epg and everything work fine except a few channels that use different time zones..

Example would be `AdultSwimWest.us` and `AdultSwimEast.us`. Same program, but just a shift in time..

I am trying to shift a a few streams (NOT all),  so the TV Guide on Kodi shows correctly.

Below is an example of entry, `tvg-shift="3" does not seem to work. I reset and cleared everything several times.
```
#EXTINF:-1 tvg-id="AdultSwimWest.us" tvg-shift=3 group-title="TV",Adult SWIM (East)

#EXTINF:-1 tvg-id="AdultSwimWest.us"  group-title="TV",Adult SWIM (West)
```
My question is, will this work or am i using the `tvg-shift` improperly? 

FYI: All my channels on Guide show up properly. And you might ask why I just don't download all the timezone? I'm trying to avoid that because there are other issues for doing that.

**Comment by DimSumDev** [comment]
Missed the toggle that was on. Should have been off.. resolved

**Comment by phunkyfish** [comment]
The value for `tvg-shift` must be in quotes for it to work.

Like this: `tvg-shift=“3”`

**Comment by phunkyfish** [comment]
Ok, cool you figured it out.

**Comment by DimSumDev** [comment]
> Ok, cool you figured it out.

Spent 6 hours trying to get it to work and oddly it was just the toggle setting. That I never set or used.
