### ISSUE TITLE
Sound BUG!

### ISSUE THREAD

**Issue by mackib** [kodi-pvr/pvr.iptvsimple#94]
When using the addon going from stereo to dd5.1 channels everything works. But when doing the opposite from dd5.1 to stereo there are no sound on the stereo channels. You have to reset box to get stereo sound again. passtrough is enabled when this happens. Switching passtrough of, you have sound on all channels without problem but only stereo wich doesnt come in handy when you want to switch and watch movies inside kodi instead. Somehow addon does not switch audio streams properly. This is going from dd5.1 source to stereo source. Minix U1

**Comment by afedchin** [comment]
The addon doesn't open/play any content

**Comment by mackib** [comment]
Wy did you close this issue?

**Comment by afedchin** [comment]
why you don't read my message? In other words: the issue isn't related to the addon.

**Comment by mackib** [comment]
Yes it is! When watching tv over simpleclient with m3u playlist it does not do correct audio switching when changing channels since you have different audio formats with different channels . Read my above statement. There are no sound issues outside the iptv simpleclient

**Comment by afedchin** [comment]
**The addon doesn't open/play any content**
